### ISSUE TITLE
[Bug] 被删好友通知bug

### ISSUE THREAD

**Issue by 56662017** [cinit/QAuxiliary#100]
### Steps to reproduce/复现步骤

没有开启被删好友通知，但是每次都通知我
![Screenshot_2022-06-28-00-19-10-467_com tencent mobileqq](https://user-images.githubusercontent.com/44309366/176092570-af098b54-002d-46b6-8c6d-cbd897f4144c.jpg)
![Screenshot_2022-06-28-10-41-24-764_com android browser](https://user-images.githubusercontent.com/44309366/176092581-e989722c-cc56-4e5c-9a95-97b267b7c56e.jpg)
![Screenshot_2022-06-28-10-41-07-410_com tencent mobileqq](https://user-images.githubusercontent.com/44309366/176092585-14b7e766-ce11-4187-bf29-75c174d4e08d.jpg)

### Expected behaviour/预期行为

没有通知

### Actual behaviour/实际行为

通知了我

### XPosed Framework you used/你使用的XP框架

1.8.3zygisk

### QQ(TIM)版本/QQ(TIM) Version

8.8.95

### Module Version/模块版本

1.2.7.r681.d 1acc68

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

- [ ]

**Comment by Q56662017** [comment]
日志我不知道怎么上传。。。。

**Comment by cinit** [comment]
fixed in 3f52ae30d83994ab422f32005d643b8d6a48c6f5
