### ISSUE TITLE
[功能请求] 屏蔽新版频道

### ISSUE THREAD

**Issue by METEOR137** [cinit/QAuxiliary#1000]
### QQ(TIM)版本/QQ(TIM) Version

9.0.56

### 为什么你认为需要此功能

新版频道不是给人用的

### 具体功能需要/Specific features require

屏蔽QQ新版频道使用旧版频道

**Comment by klxiaoniu** [comment]
https://github.com/cinit/QAuxiliary/issues/794#issuecomment-1925580655
另，现在已经意义不大，旧版未必能正常使用
