### ISSUE TITLE
[Bug] 1.5的qa里，对于QQ9.0.56.16830的“强制使用默认字体功能失效”

### ISSUE THREAD

**Issue by DEEP-PEMN** [cinit/QAuxiliary#1002]
### Steps to reproduce/复现步骤

安装QQ9.0.56.16830
安装QA1.5
导入了备份的QA设置记录（版本好像来源于1.4.7还是更低来着）
然后聊天时发现字体五花八门
进入QA设置，发现这个开关开着，但是并未生效
手动关闭重开显示以下错误
![Screenshot_2024-06-01-21-45-52-425_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/135584322/1c2ee651-aeb1-44b8-a741-b45ab7aa7f7f)

### Expected behaviour/预期行为

字体全部统一为默认字体

### Actual behaviour/实际行为

字体并未统一，报以下错
![Screenshot_2024-06-01-21-45-52-425_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/135584322/21d06e95-9da5-4da3-89b2-88c252f4118c)

### Xposed Framework you used/你使用的Xposed框架

lsposed1.9.2

### Your Android version/你使用的安卓系统版本

Android Q

### QQ(TIM)版本/QQ(TIM) Version

9.0.56.16830

### Module Version/模块版本

1.5.0

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.5.0.r2001.597cbf1
QQ9.0.56(6372)
PID: 22215, UID: 10203
cc.ioctl.hook.chat.DefaultFont
isInitialized: false
isInitializationSuccessful: false
isEnabled: false
isAvailable: true
isPreparationRequired: true
errors: 0
![Screenshot_2024-06-01-22-05-02-864_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/135584322/21f1f320-3f18-4b5f-bb31-562ff5bbbd3c)
![Screenshot_2024-06-01-22-05-11-032_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/135584322/70754b0c-f2b0-41ec-87ce-50eee15d7422)

**Comment by klxiaoniu** [comment]
![image](https://github.com/cinit/QAuxiliary/assets/48382562/8eab4cf2-bcce-4e37-a2af-8264549f39f1)
