### ISSUE TITLE
QQ9.0.60以图片方式打开闪照功能失效

### ISSUE THREAD

**Issue by shugeguangtou** [cinit/QAuxiliary#1003]
### Steps to reproduce/复现步骤

安装最新QA，打开以图片方式打开闪照功能，9.0.56版QQ正常使用，更新为9.0.60版本QQ后失效

### Expected behaviour/预期行为

QQ9.0.60版本能支持以图片方式打开闪照

### Actual behaviour/实际行为

![Screenshot_2024-06-03-18-56-56-045_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/171567457/3a31b104-b698-40b0-b471-3a0edb9ad0f6)
![Screenshot_2024-06-03-19-01-28-468_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/171567457/4a5898d8-247d-4274-a56a-9dc4ae99c0f7)

### Xposed Framework you used/你使用的Xposed框架

1.9.2（7058）-Zygisk

### Your Android version/你使用的安卓系统版本

13

### QQ(TIM)版本/QQ(TIM) Version

9.0.60

### Module Version/模块版本

1.5.1.r2099.e624c23(2099)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.5.1.r2099.e624c23
QQ9.0.60(6478)
PID: 21273, UID: 10342
cc.ioctl.hook.msg.FlashPicHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by HdShare** [comment]
尝试最新CI版

**Comment by shugeguangtou** [comment]
功能可以用了，感谢
