### ISSUE TITLE
[Bug] “精简联系人页面”导致联系人页面闪退

### ISSUE THREAD

**Issue by noname258** [cinit/QAuxiliary#1008]
### Steps to reproduce/复现步骤

使用“精简联系人页面”功能，勾选了“通讯录”和“订阅号”。

### Expected behaviour/预期行为

使用“精简联系人”功能后能够正常进入好友列表页面。

### Actual behaviour/实际行为

切换到好友列表qq就会立刻闪退。

### Xposed Framework you used/你使用的Xposed框架

Magisk 27.0

### Your Android version/你使用的安卓系统版本

Android 14，HyperOS 1.0.8.0

### QQ(TIM)版本/QQ(TIM) Version

v9.0.60.17095

### Module Version/模块版本

1.5.1.r2104.bc94122(2104)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.5.1.r2104.bc94122
QQ9.0.60(6478)
PID: 29927, UID: 10276
xyz.nextalone.hook.SimplifyContactTabs
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by HdShare** [comment]
尝试使用 异常跟踪(AppErrorsTracking) 模块 查看闪退异常堆栈
