### ISSUE TITLE
[Bug] QQ所有版本以及qa版本都存在这个问题

### ISSUE THREAD

**Issue by YiChen2025** [cinit/QAuxiliary#1011]
### Steps to reproduce/复现步骤

反馈一个，就是防撤回这个功能的，能否优化下
1.即使阻止到了，这个提示"没收到"，就删除了，保留正确的阻止提示
2.有时候即使qq在前台聊天，切其他群聊看消息，忽然看到某些较近消息出现未防到撤回，一直提示没收到，但是对方消息确实是发送过然后撤回的。然后还有一种就是跟假离线状态一样，仿佛进入离线状态部分被对方撤回的消息，也没法防到撤回，qq长时间挂后台，杀后台或者没被杀后台，时间长了再去看下消息，也是提示"没收到"
![Screenshot_2024-06-06-10-13-01-715_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/80463727/e71dde2b-1fa0-4036-9393-ffdea912e2ad)

![Screenshot_2024-06-06-10-11-32-890_com tencent mobileqq-edit](https://github.com/cinit/QAuxiliary/assets/80463727/5d0a5752-a434-4ae6-a7d5-d7e76344eed7)

### Expected behaviour/预期行为

尽量全面一点获取/拦截到撤回的消息

### Actual behaviour/实际行为

![Screenshot_2024-06-06-10-11-32-890_com tencent mobileqq-edit](https://github.com/cinit/QAuxiliary/assets/80463727/38de3e39-ae19-493a-9fd3-b7b4cee4c9ac)
![Screenshot_2024-06-06-10-13-01-715_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/80463727/8aff4e80-be9f-45d2-bf9d-3f9183a0b5af)

### Xposed Framework you used/你使用的Xposed框架

LSPosed-192.7024

### Your Android version/你使用的安卓系统版本

13

### QQ(TIM)版本/QQ(TIM) Version

QQ9.0.0

### Module Version/模块版本

1.5.1.r2109.606a873(2109)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

因未报错，无日志

**Comment by klxiaoniu** [comment]
重复的issue，跟QQ后台消息拉取机制有关

**Comment by LionYu66** [comment]
测试8.9.28版本的qq还是在后台全部拉取的，QAu有办法可以更改拉取机制吗

**Comment by cinit** [comment]
> 测试8.9.28版本的qq还是在后台全部拉取的，QAu有办法可以更改拉取机制吗

@LionYu66 这些消息内容和撤回信息的数据包（如 OlPushMsg 等）都是服务器直接下发给客户端的，有能力的话你可以去研究一下协议。

**Comment by LionYu66** [comment]
那想问下现在解决方法是就只有停留在旧版本吗

**Comment by cinit** [comment]
> 那想问下现在解决方法是就只有停留在旧版本吗

@LionYu66 是的，另外可能和群消息通知模式也有关，比如群助手等。

**Comment by m8417** [comment]
> > 那想问下现在解决方法是就只有停留在旧版本吗
> 
> @LionYu66 是的，另外可能和群消息通知模式也有关，比如群助手等。

@cinit 旧版不让登录有办法解决吗

**Comment by cinit** [comment]
> > > 那想问下现在解决方法是就只有停留在旧版本吗
> > 
> > @LionYu66 是的，另外可能和群消息通知模式也有关，比如群助手等。
> 
> @cinit 旧版不让登录有办法解决吗

无，这个和每个账号的风控情况有关。

**Comment by LionYu66** [comment]
我用的nt架构前一个版本可以，应该是8.9.63前
