### ISSUE TITLE
[功能请求]阻止QQ每日广告弹窗

### ISSUE THREAD

**Issue by CSaq** [cinit/QAuxiliary#1012]
### QQ(TIM)版本/QQ(TIM) Version

9.0.17

### 为什么你认为需要此功能

有时候每天进入QQ，就会弹出全屏广告，影响用户查看QQ消息

### 具体功能需要/Specific features require

阻止QQ每日开屏广告

**Comment by HdShare** [comment]
尝试最新CI版
