### ISSUE TITLE
[Bug] 9.0.60常见闪退问题

### ISSUE THREAD

**Issue by lxy071130** [cinit/QAuxiliary#1013]
### Steps to reproduce/复现步骤

1.打开QQ
2.随便打开一个群
3.上下快速滑动聊天记录1-2s
4.闪退

### Expected behaviour/预期行为

正常浏览聊天记录

### Actual behaviour/实际行为

闪退，下附调试信息红字

### Xposed Framework you used/你使用的Xposed框架

ONpatch

### Your Android version/你使用的安卓系统版本

13

### QQ(TIM)版本/QQ(TIM) Version

9.0.60

### Module Version/模块版本

v1.5.1.r2096

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

 调试信息红字：
[11]ArkAppItemBubbleBuilder
com.tencent.mobileqq.activity.aio.item.ArkAppItemBubbleBuilder
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
 
[23]GuildArkHelper
com.tencent.mobileqq.guild.chatpie.helper.GuildArkHelper
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  
[24]GuildHelperProvider
com.tencent.mobileqq.guild.chatpie.GuildHelperProvider
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  
[27]ItemBuilderFactory
com.tencent.mobileqq.activity.aio.item.ItemBuilderFactory
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  
[36]ReplyMsgSender
com.tencent.mobileqq.replymsg.ReplyMsgSender
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [37]ReplyMsgUtils
com.tencent.mobileqq.activity.aio.reply.ReplyMsgUtils
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  
[58]BaseChatPie
com.tencent.mobileqq.activity.BaseChatPie
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  
[59]BaseChatPie
com.tencent.mobileqq.activity.BaseChatPie
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  
[60]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V

**Comment by klxiaoniu** [comment]
@lxy071130 发crash log，或者自己排查哪个功能的问题

**Comment by 6DDUU6** [comment]
把**_文本消息自由复制_**关了试试

**Comment by lxy071130** [comment]
> 把**_文本消息自由复制_**关了试试

谢谢，解决了
