### ISSUE TITLE
[功能请求] 尝试在9.0.35以下版本支持半屏图片选择器

### ISSUE THREAD

**Issue by XingLiAl** [cinit/QAuxiliary#1015]
### QQ(TIM)版本/QQ(TIM) Version

9.0.20

### 为什么你认为需要此功能

应该在9.0.35以下版本半屏图片选择器也没有被删除吧

### 具体功能需要/Specific features require

在9.0.35以下版本支持半屏图片选择器

**Comment by HdShare** [comment]
更新最新CI r2127版
