### ISSUE TITLE
[功能请求] 给表情面板功能增加一个关闭最近发送按钮

### ISSUE THREAD

**Issue by Noko9** [cinit/QAuxiliary#1016]
### QQ(TIM)版本/QQ(TIM) Version

9.0.60（6478）

### 为什么你认为需要此功能

冷启动时总会默认打开最近发送，但是最近发送并没法记忆固定位置的表情，所以申请增加关闭最近发送功能，更好的发送表情。

### 具体功能需要/Specific features require

在表情面板的设置中增加一个选项用来移除最近发送这个按钮。或者冷启动qq时可以选择默认打开的图集。

**Comment by Noko9** [comment]
有人看一眼吗？

**Comment by keta1** [comment]
@Noko9 我听不懂你的描述，能带点图吗

**Comment by Noko9** [comment]
> @Noko9 我听不懂你的描述，能带点图吗

是这个功能
![Screenshot_2024-06-16-13-30-55-75_9d26c6446fd7bb8e41d99b6262b17def](https://github.com/cinit/QAuxiliary/assets/89293483/b528a27e-655c-430f-bc2f-86e01e03441a)
![IMG_20240616_133123](https://github.com/cinit/QAuxiliary/assets/89293483/746e5306-f0df-4e86-a32e-7fdfe6b83100)

**Comment by Noko9** [comment]
这个功能默认第一个只能是最近使用，希望添加一个关闭最近使用

**Comment by Noko9** [comment]
@keta1

**Comment by HdShare** [comment]
冷启动QQ时, 默认打开上次选择图集的位置, 你觉得怎么样

**Comment by Noko9** [comment]
@HdShare 可以，主要就是冷启动会恢复成最近使用的问题。如果能记住再好不过。
