### ISSUE TITLE
[Bug] 收藏表情包排序无效

### ISSUE THREAD

**Issue by tksmly** [cinit/QAuxiliary#1020]
### Steps to reproduce/复现步骤

更新qq

### Expected behaviour/预期行为

按使用顺序排序

### Actual behaviour/实际行为

收藏表情包排序无效

### Xposed Framework you used/你使用的Xposed框架

LSPatch

### Your Android version/你使用的安卓系统版本

14

### QQ(TIM)版本/QQ(TIM) Version

9.0.60.17095

### Module Version/模块版本

1.5.1.r2136.d0f097f(2136)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.5.1.r2136.d0f097f
QQ9.0.60(6478)
PID: 23919, UID: 10331
cc.microblock.hook.FavEmoticonSortBy
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by HdShare** [comment]
使用最新CI-r2137版
