### ISSUE TITLE
[Bug] QQ9.0.60 “精简联系人”崩溃

### ISSUE THREAD

**Issue by Arce0416** [cinit/QAuxiliary#1023]
### Steps to reproduce/复现步骤

1.在使用“精简联系人”发生了崩溃
2.多次复现排查确认是此功能问题(此问题从正式版1.5.1版本就存在)
3.获取日志(由于崩溃无日志显示，所以使用logfox获取日志）
4.反馈bug

### Expected behaviour/预期行为

在正常情况下，应该不崩溃，而是正常使用。

### Actual behaviour/实际行为

使用此功能时，从主员打开“联系人”界面，会发崩溃。

### Xposed Framework you used/你使用的Xposed框架

NPatch_0.6

### Your Android version/你使用的安卓系统版本

Android13(ColorOS13)

### QQ(TIM)版本/QQ(TIM) Version

QQ9.0.60

### Module Version/模块版本

1.5.1.r2144.4679866(2144)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

[crash.log](https://github.com/user-attachments/files/15839232/crash.log)

**Comment by HdShare** [comment]
尝试CI-r2145及以上版本，看看问题是否仍然存在

**Comment by HdShare** [comment]
尝试使用CI-r2164版本
