### ISSUE TITLE
[Bug] 禁用群文件预览疑似失效

### ISSUE THREAD

**Issue by mcyangky1** [cinit/QAuxiliary#1024]
### Steps to reproduce/复现步骤

开启禁用文档预览以后，打开QQ群文档时，不显示预览窗口

### Expected behaviour/预期行为

出现文档下载功能窗口

### Actual behaviour/实际行为

直接进入文档预览功能   且无保存文档按钮

![image](https://github.com/cinit/QAuxiliary/assets/143930138/d8012f2e-4d24-4881-81a0-5877958a604d)
![image](https://github.com/cinit/QAuxiliary/assets/143930138/a73f3694-3574-4d5d-bb93-22f6e2c27509)
![image](https://github.com/cinit/QAuxiliary/assets/143930138/e0da9e6f-9f10-4d29-8d28-7da921342cda)

### Xposed Framework you used/你使用的Xposed框架

1.8.6（6886）-  Zygisk 

### Your Android version/你使用的安卓系统版本

12

### QQ(TIM)版本/QQ(TIM) Version

9.0.17.15185(5712)

### Module Version/模块版本

1.5.1.r2096.9d589b7(2096)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.5.1.r2096.9d589b7
QQ9.0.17(5712)
PID: 15466, UID: 10426
com.xiaoniu.hook.DisableDocOnlinePreview
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

![2E59B2ABE0ED1650490AC7E42B782457](https://github.com/cinit/QAuxiliary/assets/143930138/7f15bafb-7140-47a4-88c4-9c695a870ffe)
![77ECF80E78CF325DFF9F1C992F8253A4](https://github.com/cinit/QAuxiliary/assets/143930138/88fc04d8-57cf-4a16-a5b3-51fd902ee51b)

**Comment by klxiaoniu** [comment]
QQ设置里提供了群文件在线预览开关了，你看下
