### ISSUE TITLE
[功能请求] 希望能在不获取真实位置的情况下加入位置共享，或可以自定义位置

### ISSUE THREAD

**Issue by VEHMaw** [cinit/QAuxiliary#103]
### QQ(TIM)版本/QQ(TIM) Version

都可以的

### 为什么你认为需要此功能

保护隐私

### 具体功能需要/Specific features require

希望能在不获取真实位置的情况下加入位置共享，或可以自定义位置
环境是太极阴，绝大多数虚拟定位软件不能正常工作，故请求在qa里实现
感谢作者的付出

**Comment by cinit** [comment]
@VEHMaw 你快去 PR 把复读机的抄过来
