### ISSUE TITLE
[功能请求] 在一些特殊消息中添加撤回或其保留普通消息长按菜单中的功能

### ISSUE THREAD

**Issue by ztb1126** [cinit/QAuxiliary#1030]
### QQ(TIM)版本/QQ(TIM) Version

9.0.35

### 为什么你认为需要此功能

一些特殊消息长按中不能直接撤回，需要撤回很不方便

### 具体功能需要/Specific features require

在一些特殊消息，例如红包的长按菜单中添加撤回

**Comment by EatHatsuneShallots** [comment]
经实测，戳一戳（不是双击头像）、表情弹射、可以用 QQ 手表版和协议库撤回 ~~（红包没试过，没钱）~~
所以理论可以实现

**Comment by ztb1126** [comment]
> 经实测，戳一戳（不是双击头像）、表情弹射可以用 QQ 手表版和协议库撤回 ~（红包没试过，没钱）~ 所以理论可以实现

这个功能有在做吗

**Comment by HdShare** [comment]
除了红包，其他有无必要?

**Comment by EatHatsuneShallots** [comment]
> 除了红包，其他有无必要?

有的，也包括多选消息时，不能选中相关消息的限制

**Comment by HdShare** [comment]
> 有的，也包括多选消息时，不能选中相关消息的限制

多选估计要分析别的地方，目前只对红包的菜单栏增加了撤回消息
如需要其他消息请举例子一并添加到菜单栏

**Comment by HdShare** [comment]
7152afd4f08fb2b59a475d4a970e13d86f588e02 支持表情泡泡, 戳一戳, 红包转账
