### ISSUE TITLE
[Bug] 图片摘要不对单张图片生效

### ISSUE THREAD

**Issue by EatHatsuneShallots** [cinit/QAuxiliary#1038]
### Steps to reproduce/复现步骤

1. 使用半屏或全屏图片选择器
2. 选择一张或多张图片
3. 然后发送（不要带有文字，这样会导致功能生效）

### Expected behaviour/预期行为

图片摘要生效

### Actual behaviour/实际行为

显示为 “[图片]”

### Xposed Framework you used/你使用的Xposed框架

NPatch 0.6.1

### Your Android version/你使用的安卓系统版本

12S

### QQ(TIM)版本/QQ(TIM) Version

9.0.0

### Module Version/模块版本

1.5.1.r2169.78deae7

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

```
1.5.1.r2169.78deae7
QQ9.0.0(5282)
PID: 21438, UID: 10452
cc.microblock.hook.ImageCustomSummary
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0
```

**Comment by HdShare** [comment]
使用CI-r2173版
