### ISSUE TITLE
[Bug] 防撤回与以图片方式打开闪照不可用

### ISSUE THREAD

**Issue by tianshaguxing-233** [cinit/QAuxiliary#1040]
### Steps to reproduce/复现步骤

1.启动功能
2.开启功能防撤回提示异常，以图片方式打开闪照无异常
3.防撤回与以图片方式打开闪照无法使用

### Expected behaviour/预期行为

功能正常运行

### Actual behaviour/实际行为

无

### Xposed Framework you used/你使用的Xposed框架

opatch

### Your Android version/你使用的安卓系统版本

14

### QQ(TIM)版本/QQ(TIM) Version

V 9.0.65.17370

### Module Version/模块版本

1.5.1.r2096.9d58967

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

[以图片方式打开闪照.txt](https://github.com/user-attachments/files/15903453/default.txt)
[防撤回.txt](https://github.com/user-attachments/files/15903455/default.txt)

**Comment by LegendEast** [comment]
我也是，已经降级回9060了

**Comment by klxiaoniu** [comment]
你使用的是最新CI？
