### ISSUE TITLE
[功能请求] 复制代码对 Markdown 消息生效

### ISSUE THREAD

**Issue by EatHatsuneShallots** [cinit/QAuxiliary#1044]
### QQ(TIM)版本/QQ(TIM) Version

9.0.0.14110

### 为什么你认为需要此功能

Markdown 消息没有 **复制代码** 菜单，且直接复制不会得到原来的数据

### 联系到哪些已经存在的bug或者功能

复制代码

### 具体功能需要/Specific features require

为 Markdown 消息支持复制代码，复制的内容为 **原始 Markdown 数据**

**Comment by HdShare** [comment]
原始 Markdown 数据? 与MarkdownElement的content区别在哪里?

**Comment by EatHatsuneShallots** [comment]
> 原始 Markdown 数据? 与MarkdownElement的content区别在哪里?

可能是我描述有误，原始 Markdown 数据就是指 Markdown 文本

**Comment by HdShare** [comment]
尝试CI-r2181版
