### ISSUE TITLE
[Bug] 复制 Markdown 消息无法使用

### ISSUE THREAD

**Issue by EatHatsuneShallots** [cinit/QAuxiliary#1048]
### Steps to reproduce/复现步骤

长按机器人发送的 Markdown 消息

### Expected behaviour/预期行为

显示相关菜单

### Actual behaviour/实际行为

未显示相关菜单

### Xposed Framework you used/你使用的Xposed框架

NPatch 0.6.1

### Your Android version/你使用的安卓系统版本

12S

### QQ(TIM)版本/QQ(TIM) Version

9.0.0

### Module Version/模块版本

1.5.1.r2183.f2c4a4d

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

```
1.5.1.r2183.f2c4a4d
QQ9.0.0(5282)
PID: 19041, UID: 10452
me.hd.hook.CopyMarkdown
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0
```

**Comment by HdShare** [comment]
尝试CI-r2184版

**Comment by EatHatsuneShallots** [comment]
> 尝试CI-r2184版

仍无法使用，点击菜单后直接闪退
功能异常列表显示无异常

~~不方便抓取日志~~

**Comment by HdShare** [comment]
> 仍无法使用，点击菜单后直接闪退
> 功能异常列表显示无异常
> 
> ~~不方便抓取日志~~

那等过几天我再看看，目前没电脑测试

**Comment by EatHatsuneShallots** [comment]
<details>
<summary>Logcat</summary>
<pre><blockcode>
06-22 20:39:53.159 13422 13422 D AndroidRuntime: Shutting down VM
06-22 20:39:53.161 13422 13422 I LSPosed-Bridge: Crash unexpectedly: java.util.NoSuchElementException: Array contains no element matching the predicate.
06-22 20:39:53.161 13422 13422 I LSPosed-Bridge: at me.hd.hook.CopyMarkdown.onGetMenuNt$lambda$2(CopyMarkdown.kt:1138)
06-22 20:39:53.161 13422 13422 I LSPosed-Bridge: at me.hd.hook.CopyMarkdown.$r8$lambda$Hc6pXUOfasd78CI11lZoIIggzgs(CopyMarkdown.kt:0)
06-22 20:39:53.161 13422 13422 I LSPosed-Bridge: at me.hd.hook.CopyMarkdown$$ExternalSyntheticLambda0.invoke(R8$$SyntheticClass:0)
06-22 20:39:53.161 13422 13422 I LSPosed-Bridge: at io.github.qauxv.util.CustomMenu.createItemIconNt$lambda$6(CustomMenu.kt:136)
06-22 20:39:53.161 13422 13422 I LSPosed-Bridge: at io.github.qauxv.util.CustomMenu.$r8$lambda$1kqu94Xuy5lxsl4ShV8M0-kdyA8(CustomMenu.kt:0)
06-22 20:39:53.161 13422 13422 I LSPosed-Bridge: at io.github.qauxv.util.CustomMenu$$ExternalSyntheticLambda3.call(R8$$SyntheticClass:0)
06-22 20:39:53.161 13422 13422 I LSPosed-Bridge: at com.tencent.qqnt.aio.menu.ui.c$ByteBuddy$GJ4RB7j9.f(Unknown Source:3)
06-22 20:39:53.161 13422 13422 I LSPosed-Bridge: at com.tencent.qqnt.aio.menu.ui.QQCustomMenuExpandableLayout$c.onClick(P:3)
06-22 20:39:53.161 13422 13422 I LSPosed-Bridge: at android.view.View.performClick(View.java:7512)
06-22 20:39:53.161 13422 13422 I LSPosed-Bridge: at android.view.View.performClickInternal(View.java:7489)
06-22 20:39:53.161 13422 13422 I LSPosed-Bridge: at android.view.View.access$3700(View.java:857)
06-22 20:39:53.161 13422 13422 I LSPosed-Bridge: at android.view.View$PerformClick.run(View.java:29016)
06-22 20:39:53.161 13422 13422 I LSPosed-Bridge: at android.os.Handler.handleCallback(Handler.java:938)
06-22 20:39:53.161 13422 13422 I LSPosed-Bridge: at android.os.Handler.dispatchMessage(Handler.java:99)
06-22 20:39:53.161 13422 13422 I LSPosed-Bridge: at android.os.Looper.loopOnce(Looper.java:233)
06-22 20:39:53.161 13422 13422 I LSPosed-Bridge: at android.os.Looper.loop(Looper.java:334)
06-22 20:39:53.161 13422 13422 I LSPosed-Bridge: at android.app.ActivityThread.main(ActivityThread.java:8397)
06-22 20:39:53.161 13422 13422 I LSPosed-Bridge: at java.lang.reflect.Method.invoke(Native Method)
06-22 20:39:53.161 13422 13422 I LSPosed-Bridge: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
06-22 20:39:53.161 13422 13422 I LSPosed-Bridge: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065)
--------- beginning of crash
06-22 20:39:53.163 13422 13422 E AndroidRuntime: FATAL EXCEPTION: main
06-22 20:39:53.163 13422 13422 E AndroidRuntime: Process: com.tencent.mobileqq, PID: 13422
06-22 20:39:53.163 13422 13422 E AndroidRuntime: java.util.NoSuchElementException: Array contains no element matching the predicate.
06-22 20:39:53.163 13422 13422 E AndroidRuntime: at me.hd.hook.CopyMarkdown.onGetMenuNt$lambda$2(CopyMarkdown.kt:1138)
06-22 20:39:53.163 13422 13422 E AndroidRuntime: at me.hd.hook.CopyMarkdown.$r8$lambda$Hc6pXUOfasd78CI11lZoIIggzgs(CopyMarkdown.kt:0)
06-22 20:39:53.163 13422 13422 E AndroidRuntime: at me.hd.hook.CopyMarkdown$$ExternalSyntheticLambda0.invoke(R8$$SyntheticClass:0)
06-22 20:39:53.163 13422 13422 E AndroidRuntime: at io.github.qauxv.util.CustomMenu.createItemIconNt$lambda$6(CustomMenu.kt:136)
06-22 20:39:53.163 13422 13422 E AndroidRuntime: at io.github.qauxv.util.CustomMenu.$r8$lambda$1kqu94Xuy5lxsl4ShV8M0-kdyA8(CustomMenu.kt:0)
06-22 20:39:53.163 13422 13422 E AndroidRuntime: at io.github.qauxv.util.CustomMenu$$ExternalSyntheticLambda3.call(R8$$SyntheticClass:0)
06-22 20:39:53.163 13422 13422 E AndroidRuntime: at com.tencent.qqnt.aio.menu.ui.c$ByteBuddy$GJ4RB7j9.f(Unknown Source:3)
06-22 20:39:53.163 13422 13422 E AndroidRuntime: at com.tencent.qqnt.aio.menu.ui.QQCustomMenuExpandableLayout$c.onClick(P:3)
06-22 20:39:53.163 13422 13422 E AndroidRuntime: at android.view.View.performClick(View.java:7512)
06-22 20:39:53.163 13422 13422 E AndroidRuntime: at android.view.View.performClickInternal(View.java:7489)
06-22 20:39:53.163 13422 13422 E AndroidRuntime: at android.view.View.access$3700(View.java:857)
06-22 20:39:53.163 13422 13422 E AndroidRuntime: at android.view.View$PerformClick.run(View.java:29016)
06-22 20:39:53.163 13422 13422 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:938)
06-22 20:39:53.163 13422 13422 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:99)
06-22 20:39:53.163 13422 13422 E AndroidRuntime: at android.os.Looper.loopOnce(Looper.java:233)
06-22 20:39:53.163 13422 13422 E AndroidRuntime: at android.os.Looper.loop(Looper.java:334)
06-22 20:39:53.163 13422 13422 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:8397)
06-22 20:39:53.163 13422 13422 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
06-22 20:39:53.163 13422 13422 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
06-22 20:39:53.163 13422 13422 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065)
</blockcode></pre>
</details>

**Comment by EatHatsuneShallots** [comment]
@HdShare 仍然无法使用
```
06-25 12:45:18.553  9900  9900 E AndroidRuntime: FATAL EXCEPTION: main
06-25 12:45:18.553  9900  9900 E AndroidRuntime: Process: com.tencent.mobileqq, PID: 9900
06-25 12:45:18.553  9900  9900 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.tencent.qqnt.kernel.nativeinterface.MarkdownElement.getContent()' on a null object reference
06-25 12:45:18.553  9900  9900 E AndroidRuntime: 	at me.hd.hook.CopyMarkdown.onGetMenuNt$lambda$0(CopyMarkdown.kt:62)
06-25 12:45:18.553  9900  9900 E AndroidRuntime: 	at me.hd.hook.CopyMarkdown.$r8$lambda$79jpiDNFily4OTt4akYGBNFPEdc(CopyMarkdown.kt:0)
06-25 12:45:18.553  9900  9900 E AndroidRuntime: 	at me.hd.hook.CopyMarkdown$$ExternalSyntheticLambda0.invoke(R8$$SyntheticClass:0)
06-25 12:45:18.553  9900  9900 E AndroidRuntime: 	at io.github.qauxv.util.CustomMenu.createItemIconNt$lambda$6(CustomMenu.kt:136)
06-25 12:45:18.553  9900  9900 E AndroidRuntime: 	at io.github.qauxv.util.CustomMenu.$r8$lambda$1kqu94Xuy5lxsl4ShV8M0-kdyA8(CustomMenu.kt:0)
06-25 12:45:18.553  9900  9900 E AndroidRuntime: 	at io.github.qauxv.util.CustomMenu$$ExternalSyntheticLambda3.call(R8$$SyntheticClass:0)
06-25 12:45:18.553  9900  9900 E AndroidRuntime: 	at com.tencent.qqnt.aio.menu.ui.c$ByteBuddy$NHfBEOtV.f(Unknown Source:3)
06-25 12:45:18.553  9900  9900 E AndroidRuntime: 	at com.tencent.qqnt.aio.menu.ui.QQCustomMenuExpandableLayout$c.onClick(P:3)
06-25 12:45:18.553  9900  9900 E AndroidRuntime: 	at android.view.View.performClick(View.java:7512)
06-25 12:45:18.553  9900  9900 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7489)
06-25 12:45:18.553  9900  9900 E AndroidRuntime: 	at android.view.View.access$3700(View.java:857)
06-25 12:45:18.553  9900  9900 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:29016)
06-25 12:45:18.553  9900  9900 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
06-25 12:45:18.553  9900  9900 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-25 12:45:18.553  9900  9900 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:233)
06-25 12:45:18.553  9900  9900 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:334)
06-25 12:45:18.553  9900  9900 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8397)
06-25 12:45:18.553  9900  9900 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-25 12:45:18.553  9900  9900 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
06-25 12:45:18.553  9900  9900 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065)
```

**Comment by HdShare** [comment]
Content内容空指针，估计是Markdown消息问题
群号发一下，我去排查一下Md消息

**Comment by EatHatsuneShallots** [comment]
> Content内容空指针，估计是Markdown消息问题
确实是，有的消息可以，有的不行

> 群号发一下，我去排查一下Md消息
好像与群聊无关，只与消息有关
~~你是要加入我的群吗（）~~

**Comment by HdShare** [comment]
> 好像与群聊无关，只与消息有关
> ~~你是要加入我的群吗（）~~

我加的群没几个在发md消息
估计要加你那 有发md消息的群
然后排查具体的md消息

**Comment by EatHatsuneShallots** [comment]
> 然后排查具体的md消息

https://qun.qq.com/qunpro/robot/qunshare?robot_uin=3889001741
添加这个机器人

**Comment by HdShare** [comment]
fix CI-r2191
