### ISSUE TITLE
[Bug] 禁用轻互动功能失效

### ISSUE THREAD

**Issue by SYSTEMAI** [cinit/QAuxiliary#1056]
### Steps to reproduce/复现步骤

打开QA的禁用轻互动，没有任何效果

### Expected behaviour/预期行为

轻互动不会出现

### Actual behaviour/实际行为

照样在消息列表出现。在目前最新推荐的CI版本(1.5.1.r2096.9d589b7)会直接让QQ闪退，后台都不留的那种

### Xposed Framework you used/你使用的Xposed框架

LSPatch 0.6(398) ,即LSPosed 1.9.2(7024)

### Your Android version/你使用的安卓系统版本

13

### QQ(TIM)版本/QQ(TIM) Version

8.9.93

### Module Version/模块版本

1.5.1.r2192.d8b8389

### Version and Other Requirements/版本和其他要求

- [x] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.5.1.r2192.d8b8389
QQ8.9.93(5028)
PID: 8955, UID: 10349
cc.ioctl.hook.chat.DisableLightInteraction
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by HdShare** [comment]
尝试最新CI-r2508版本
