### ISSUE TITLE
[功能请求] 语音转发能够一次转发给多个用户

### ISSUE THREAD

**Issue by 0XPYEX0** [cinit/QAuxiliary#106]
### QQ(TIM)版本/QQ(TIM) Version

8.8.90(2828)

### 为什么你认为需要此功能

群发语音当海王(不是
群发语音当搞笑人

### 具体功能需要/Specific features require

当转发语音时，点击右上角“多选”按钮选择后，转发无效
希望能够生效

**Comment by keta1** [comment]
@0XPYEX0 @NextAIone 海王快去写这个功能

**Comment by NextAlone** [comment]
> @NextAlone 海王快去写这个功能

怪事？
