### ISSUE TITLE
[Bug] 9.0.70+ 点击表情面板里的图片表情会直接闪退

### ISSUE THREAD

**Issue by 2334534714** [cinit/QAuxiliary#1061]
### Steps to reproduce/复现步骤

在聊天界面，打开QQNT表情面板，发送图片表情

### Expected behaviour/预期行为

正常发送图片表情

### Actual behaviour/实际行为

点击图片表情，QQ卡顿一秒后直接闪退，无任何提示

### Xposed Framework you used/你使用的Xposed框架

LSPatch

### Your Android version/你使用的安卓系统版本

安卓14

### QQ(TIM)版本/QQ(TIM) Version

9.70和9.73（测试版）

### Module Version/模块版本

1.5.1.r2197.7a04437(2197)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

表情面板这个功能在故障排查里没有报错，只能贴正常的运行日志了（其他功能倒是报错不少）
1.5.1.r2197.7a04437
QQ9.0.73(6722)
PID: 29788, UID: 10590
cc.hicore.hook.stickerPanel.Hooker.StickerPanelEntryHooker
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by HdShare** [comment]
已在Ci-r2202修复
