### ISSUE TITLE
[功能请求] 隐藏语音播放时的“请调大手机音量后播放”

### ISSUE THREAD

**Issue by EatHatsuneShallots** [cinit/QAuxiliary#1063]
### QQ(TIM)版本/QQ(TIM) Version

9.0.0.14110

### 为什么你认为需要此功能

~~碍眼（~~

### 具体功能需要/Specific features require

隐藏语音播放时的“请调大手机音量后播放”

**Comment by HdShare** [comment]
更新CI-r2203

**Comment by HdShare** [comment]
更新CI-r2203
