### ISSUE TITLE
[Bug] QQ9.0.71(6702)防撤回失效

### ISSUE THREAD

**Issue by Arce0416** [cinit/QAuxiliary#1070]
### Steps to reproduce/复现步骤

**1.**关闭所有功能，仅启动消息防撤回功能
**2.**多次测试，消息防撤回无法拦截消息
**3.**上述测试均在qq官网发布的正式版本并且使用最新的QAuxiliary_cl版本上测得

### Expected behaviour/预期行为

正常情况应该拦截消息，并返回一段灰字“名称+尝试撤回一条消息”

### Actual behaviour/实际行为

未成功拦截，未返回灰字

### Xposed Framework you used/你使用的Xposed框架

ONPatch0.6.1

### Your Android version/你使用的安卓系统版本

Android 13

### QQ(TIM)版本/QQ(TIM) Version

QQ9.0.71(6702)

### Module Version/模块版本

1.5.1.r2228.8b21d1e(2228)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Logs/日志

[RevokeMsgHook-1720669443267.txt](https://github.com/user-attachments/files/16171364/RevokeMsgHook-1720669443267.txt)

**Comment by HdShare** [comment]
#1058 重复
