### ISSUE TITLE
[Bug] 显示具体消息数量对QQ9.0.8之前版本左上角返回按钮失效

### ISSUE THREAD

**Issue by EatHatsuneShallots** [cinit/QAuxiliary#1075]
### QQ(TIM)版本/QQ(TIM) Version

9.0.0.14110

### 为什么你认为需要此功能

提交 https://github.com/cinit/QAuxiliary/commit/618b4d9b507de1b6df0a163658e3ecdc7305dc03 新增了对底下的消息数量的支持

### 联系到哪些已经存在的bug或者功能

显示具体消息数量

### 具体功能需要/Specific features require

显示具体消息数量功能对左上角返回按钮旁边的消息数量生效

**Comment by HdShare** [comment]
QQ9.0.8及之后版本正常显示，泪目，又得重新分析
