### ISSUE TITLE
[Bug] 复读+1闪退

### ISSUE THREAD

**Issue by chuxinMind** [cinit/QAuxiliary#1076]
### Steps to reproduce/复现步骤

无复现步骤，最近更新后产生的bug。
bug功能设置：
“消息 +1 Plus”
勾选“双击复读”
其他默认

### Expected behaviour/预期行为

聊天界面双击“+1”后复读信息

### Actual behaviour/实际行为

双击“+1”后QQ闪退

### Xposed Framework you used/你使用的Xposed框架

LSPosed（1.9.2-7024）

### Your Android version/你使用的安卓系统版本

安卓13 （MIUI 1.0.3.0）

### QQ(TIM)版本/QQ(TIM) Version

9.0.71.17655(6702)

### Module Version/模块版本

1.5.1.r2096.9d589b7(2096)

### Version and Other Requirements/版本和其他要求

- [ ] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Logs/日志

异常列表中显示“消息 +1 Plus”无异常，如下：
1.5.1.r2096.9d589b7
QQ9.0.71(6702)
PID: 15736, UID: 10271
cc.hicore.hook.RepeaterPlus
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0
故提供LSPosed中的日志（文件上次）：
[verbose_2024-07-13T16_58_37.016484.log](https://github.com/user-attachments/files/16201533/verbose_2024-07-13T16_58_37.016484.log)

### 补充说明（可选）

![Screenshot_2024-07-13-17-25-55-779_com tencent mobileqq](https://github.com/user-attachments/assets/2b0f4bb3-cdf0-400b-a067-3d3f1abdcc35)
请问下以上功能考虑恢复吗（例如防撤回）
如果已经通知过可不回复该补充说明

**Comment by klxiaoniu** [comment]
@chuxinMind 你更新到最新CI试试呢？https://t.me/QAuxiliary_CI
