### ISSUE TITLE
[Bug] 屏蔽消息功能无法使用

### ISSUE THREAD

**Issue by mogocheal** [cinit/QAuxiliary#1081]
### Steps to reproduce/复现步骤

通知设置-静默指定类型消息-@全体消息

### Expected behaviour/预期行为

屏蔽@全体成员消息无效

### Actual behaviour/实际行为

屏蔽@全体成员消息有效

### Xposed Framework you used/你使用的Xposed框架

lspatch0.6  xposed1.9.2

### Your Android version/你使用的安卓系统版本

12

### QQ(TIM)版本/QQ(TIM) Version

9.0.65

### Module Version/模块版本

1.5.1.r2231

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Logs/日志

暂无

### 补充说明（可选）

无

**Comment by HdShare** [comment]
@mogocheal 重复 #870 , 坏好久了
