### ISSUE TITLE
[Bug] 历史好友有时会误报机器人被删除

### ISSUE THREAD

**Issue by EatHatsuneShallots** [cinit/QAuxiliary#1088]
### Steps to reproduce/复现步骤

不明，要求加了官方机器人好友，且没有主动删除它（或者被删除）
时间显示的是登录后的一段时间

### Expected behaviour/预期行为

不会误报

### Actual behaviour/实际行为

可能误报

### Xposed Framework you used/你使用的Xposed框架

NPatch 0.6.1

### Your Android version/你使用的安卓系统版本

12S

### QQ(TIM)版本/QQ(TIM) Version

9.0.60

### Module Version/模块版本

be83b0be4e7e1046fd886c154d893d2dc4bc7aae

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Logs/日志

```
1.5.1.r2253.be83b0b
QQ9.0.60(6478)
PID: 20453, UID: 10452
cc.ioctl.hook.friend.FriendDeletionNotification
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

```

**Comment by HdShare** [comment]
@EatHatsuneShallots 自行查看是否开启XA，加好友活跃

**Comment by EatHatsuneShallots** [comment]
> @EatHatsuneShallots 自行查看是否开启XA，加好友活跃

并没有开启相关功能

**Comment by cinit** [comment]
@EatHatsuneShallots 机器人的QQ号是多少

**Comment by EatHatsuneShallots** [comment]
> @EatHatsuneShallots 机器人的QQ号是多少

2854207033

**Comment by HdShare** [comment]
已更新机器人白名单列表，尝试最新CI版
