### ISSUE TITLE
[Bug] 9.0.80beta版本精简侧边栏失效

### ISSUE THREAD

**Issue by CuSO4with5H2O** [cinit/QAuxiliary#1093]
### Steps to reproduce/复现步骤

1.打开侧边栏精简功能

### Expected behaviour/预期行为

功能正常

### Actual behaviour/实际行为

功能异常，如图
![Screenshot_2024-07-21-16-54-26-095_com tencent mobileqq](https://github.com/user-attachments/assets/19487b5a-4b2b-44d8-8154-39e7af0851d2)

### Xposed Framework you used/你使用的Xposed框架

lsposed1.9.2 7024

### Your Android version/你使用的安卓系统版本

14

### QQ(TIM)版本/QQ(TIM) Version

9.0.80 (6896)

### Module Version/模块版本

1.5.1.r2262.ba72136 (2262)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Logs/日志

1.5.1.r2262.ba72136
QQ9.0.80(6896)
PID: 15556, UID: 10342
cc.ioctl.hook.sideswipe.SimplifyQQSettingMe
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

[LSPosed_2024-07-21T16_59_14.497190.zip](https://github.com/user-attachments/files/16323598/LSPosed_2024-07-21T16_59_14.497190.zip)

**Comment by CuSO4with5H2O** [comment]
功能异常列表下无本功能，所以无法提供qa内的日志

**Comment by CuSO4with5H2O** [comment]
1.5.1.r2262.ba72136
QQ9.0.80(6896)
PID: 15556, UID: 10342
cc.ioctl.hook.sideswipe.SimplifyQQSettingMe
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by Ptilopsis01** [comment]
同

**Comment by HdShare** [comment]
尝试最新CI版本

**Comment by CuSO4with5H2O** [comment]
1.5.2.r2272.bdabefa 版本已修复
