### ISSUE TITLE
[功能请求] 消息 +1 Plus 复读按钮可以同时显示在消息旁和长按菜单

### ISSUE THREAD

**Issue by EatHatsuneShallots** [cinit/QAuxiliary#1101]
### QQ(TIM)版本/QQ(TIM) Version

9.0.60

### 为什么你认为需要此功能

在开启了显示在长按菜单后，复读按钮不会显示在消息旁

### 联系到哪些已经存在的bug或者功能

消息 +1 Plus

### 具体功能需要/Specific features require

消息 +1 Plus 复读按钮可以同时显示在消息旁和长按菜单

**Comment by klxiaoniu** [comment]
这个需求过于小众了，不打算支持。
