### ISSUE TITLE
[Bug] 打开转发消息超过9人限制后无法选择转发对象

### ISSUE THREAD

**Issue by charleszhao999** [cinit/QAuxiliary#1103]
### Steps to reproduce/复现步骤

1.打开去除转发9名联系人限制
2.转发消息 选择多选
3.点击任意联系人

### Expected behaviour/预期行为

上方的列表中正常出现点击的联系人，且右上角的“发送”按钮变为高亮可点击

### Actual behaviour/实际行为

上方的列表中未出现点击的联系人，且右上角的“发送”按钮为灰色不可点击状态

### Xposed Framework you used/你使用的Xposed框架

Lsposed集成模式

### Your Android version/你使用的安卓系统版本

14

### QQ(TIM)版本/QQ(TIM) Version

9.0.17

### Module Version/模块版本

QAuxv-v1.5.2.r2263.c3d9cc2-arm64

### Version and Other Requirements/版本和其他要求

- [ ] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Logs/日志

1.5.2.r2263.c3d9cc2
QQ9.0.17(5714)
PID: 14367, UID: 10349
io.github.memory2314.hook.RemoveShareLimit
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by HdShare** [comment]
已复现，待修复
