### ISSUE TITLE
[功能请求] 一种解除回复消息限制的思路

### ISSUE THREAD

**Issue by MoonLeeeaf** [cinit/QAuxiliary#1104]
### QQ(TIM)版本/QQ(TIM) Version

TIM 3.0.0

### 为什么你认为需要此功能

我经常需要对自己的消息回复以进行解释说明

### 具体功能需要/Specific features require

方法签名： Lcom/tencent/mobileqq/activity/aio/BaseBubbleBuilder;->a(Lcom/tencent/mobileqq/data/ChatMessage;Lcom/tencent/mobileqq/utils/dialogutils/QQCustomMenu;)V

关键代码:
```java
protected void a(ChatMessage chatMessage, QQCustomMenu qQCustomMenu) {
    // 这是判断是否能回复的语句，这非常关键，或者直接重写整个方法，这样不仅能任意回复消息，还能解决不能回复自己消息的问题
    // 暂时没有办法测试代码，所以就不PR了（摊
    if (chatMessage != null && this.wD.yM == mwm && !chatMessage.senderuin.equals(this.app.getCurrentUin()) && chatMessage.isSupportReply()) {
        qQCustomMenu.F(2131238756, this.mContext.getString(2131631067), 2131165801);
        MessageForReplyText.reportReplyMsg(this.app, "Msg_menu", "exp_replyMsg", chatMessage.frienduin, chatMessage);
    }
}
```

关联的Resource资源ID： 2131631067 即 7f0e1bdb

成功标志：
![Screenshot_20240729-103356_TIM](https://github.com/user-attachments/assets/bd722941-c41c-48fb-9e55-481c905d93de)

注意：TIM 3.5.1 以下版本必须使用较老的号，否则无法登录进行测试，建议对照反出来的代码直接进行编写，我可以通过CI来获取更新进行测试

关联Issue： #221

**Comment by HdShare** [comment]
尝试最新Ci版本

**Comment by MoonLeeeaf** [comment]
功能正常运作，感谢❤️
