### ISSUE TITLE
[功能请求] 请解除QQ收藏点图片提示该收藏暂不支持预览

### ISSUE THREAD

**Issue by shty0008** [cinit/QAuxiliary#1106]
### QQ(TIM)版本/QQ(TIM) Version

8.9.85.12820(4766)

### 为什么你认为需要此功能

![IMG_20240729_121537](https://github.com/user-attachments/assets/ed0c1014-9e6c-48e8-859d-b8f6bebb7ace)
求求您救救我的涩图吧，太严格了，肤色露多点的都是打不开的，不涩的图都可以正常的点开。
qq日常作恶，和谐和到收藏里，qq老版本收藏图都可以正常点开，升到8.9版就不行了

### 具体功能需要/Specific features require

QQ收藏中点图片点不开，并提示该收藏暂不支持预览，麻烦去除提示并让图片可以正常点开，保存或转发，求求您救救我的涩图吧。

**Comment by HdShare** [comment]
先切图片栏，再打开图片，是否也有弹窗
![image](https://github.com/user-attachments/assets/da98c634-51d2-4400-b679-17c94e3442b5)

**Comment by HdShare** [comment]
尝试最新CI版本
