### ISSUE TITLE
[Bug] “隐藏底栏”功能会导致原底栏位置出现模糊遮罩，并且阻挡点击

### ISSUE THREAD

**Issue by CosVersin** [cinit/QAuxiliary#1110]
### Steps to reproduce/复现步骤

1.启用“侧滑栏”内的“禁止新样式侧滑栏”, 启用“娱乐功能”内的“隐藏底栏”功能
2.启用“通用”内的普通模式
3.重启qq
![sp20240730_165555_611](https://github.com/user-attachments/assets/f508cbc4-1c25-4db1-973d-1232ae5e7f2d)

### Expected behaviour/预期行为

qq主页原底栏不再存在，并且不遮挡消息，同时也可以点击处于原位置的消息

### Actual behaviour/实际行为

qq主页原底栏位置出现模糊遮罩，并且不可点击背后的消息
![sp20240730_165600_444](https://github.com/user-attachments/assets/abb663a8-1633-49ec-821e-98104631cf90)

### Xposed Framework you used/你使用的Xposed框架

LSPatch集成模式

### Your Android version/你使用的安卓系统版本

14

### QQ(TIM)版本/QQ(TIM) Version

9.0.65

### Module Version/模块版本

1.5.2.r2324.cd347d3(2324)

### Version and Other Requirements/版本和其他要求

- [ ] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [x] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Logs/日志

1.5.2.r2324.cd347d3
QQ9.0.65(6588)
PID: 11410, UID: 10443
me.ketal.hook.HideTab
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

### 补充说明（可选）

复现步骤中第一步启用的“禁止新样式侧滑栏”，是由于“隐藏底栏”功能无法在新版侧滑栏中生效。

复现步骤中第二步的启用“通用”内的普通模式，是由于普通模式下此bug必定出现，简洁模式偶尔出现

底栏被成功移至侧滑栏，这是这个功能没失效的一个地方

日志中提到“隐藏底栏”功能“未见明显异常”

**Comment by HdShare** [comment]
尝试最新Ci-2329版，阻挡点击应该修好了
