### ISSUE TITLE
[Bug] 新版侧边栏精简出现了一堆”我的相册“

### ISSUE THREAD

**Issue by tianlongJ** [cinit/QAuxiliary#1116]
### Steps to reproduce/复现步骤

侧边栏精简勾选任意

### Expected behaviour/预期行为

只显示未勾选的

### Actual behaviour/实际行为

出现了一堆”我的相册“
![75fdf4908f436f805073b9c2fca2336](https://github.com/user-attachments/assets/3a5131e7-6c91-4f5f-bcb7-0b5375df5568)

### Xposed Framework you used/你使用的Xposed框架

onpatch06.1

### Your Android version/你使用的安卓系统版本

14

### QQ(TIM)版本/QQ(TIM) Version

9.0.81

### Module Version/模块版本

1.5.2

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Logs/日志

侧边栏精简
未见明显异常
1.5.2.r2263.c3d9cc2
QQ9.0.81(6922)
PID: 25278, UID: 10897
cc.ioctl.hook.sideswipe.SimplifyQQSettingMe
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by HdShare** [comment]
@tianlongJ 更新到最新CI-r2352版本
而非正式版

**Comment by tianlongJ** [comment]
> @tianlongJ 更新到最新CI-r2352版本 而非正式版

不好意思，看刚才没看到ci发布频道，只在主频道里看到了正式版，已经更新，问题解决了
