### ISSUE TITLE
[Invalid][求教] 如何在宿主应用中直接读写 Prefernences

### ISSUE THREAD

**Issue by MoonLeeeaf** [cinit/QAuxiliary#1117]
### QQ(TIM)版本/QQ(TIM) Version

None

### 为什么你认为需要此功能

本人正在想办法给自己的模块适配免 root 框架，但目前为止均未取得成效，想到此项目，故想求方

### 具体功能需要/Specific features require

在宿主应用中启动模块的配置页面，但是配置文件是储存在宿主应用中的
例如有一 PreferencesActivity，在模块中定义，然后模块还有一个页面，这个页面引导用户启动宿主应用，启动的页面是模块定义的 PreferencesActivity
在这个 PreferencesActivity 修改的任何设置都是在宿主应用中保存的

可能没有说太清楚，如何有不理解的可回问，本人目前一直寻求未果

谢谢🌚

若我找到了解决方法 或 您有好的解决办法 亦或者 协作者回复思路 等，由我 或 协作者 Close as completed

如何确实有扰乱了一些规则，Close as not planned

**Comment by cinit** [comment]
你 startActivity 的时候 extra bundle 塞个 binder 过去 AIDL IPC 不就行了，如此情况下，你的 PreferencesActivity 在模块进程，配置存储在宿主私有目录，唯一的问题就是你的 PreferencesActivity 必须从宿主侧 startActivity.

**Comment by MoonLeeeaf** [comment]
> 你 startActivity 的时候 extra bundle 塞个 binder 过去 AIDL IPC 不就行了，如此情况下，你的 PreferencesActivity 在模块进程，配置存储在宿主私有目录，唯一的问题就是你的 PreferencesActivity 必须从宿主侧 startActivity.

也就是模块分主页和配置页面，从主页打开配置页面时是通过 Hook 宿主的一个 Activity 然后获取 extra bundle 是否有指定的传参，再传入一个 Binder 到 bundle 然后启动配置页面，由此达成模块的 PreferencesActivity 直接读写存储在宿主私有目录的配置文件？
我回去研究下（

**Comment by cinit** [comment]
@MoonLeeeaf 传 binder 是目的，而 startActivity 是手段

**Comment by MoonLeeeaf** [comment]
也就是说，通过用 startActivity 启动宿主的 Activity 再传宿主进程的 Binder 给模块进程？

**Comment by cinit** [comment]
@MoonLeeeaf binder 是作为 startActivity bundle 参数传递副

**Comment by MoonLeeeaf** [comment]
恕鄙人修炼不足，尚有许多未能理解（）
阁下意思是”宿主进程 -> startActivity(模块_Activity) 带 宿主_Binder -> IPC“么

**Comment by cinit** [comment]
@MoonLeeeaf 我指 ”宿主进程 -> startActivity(模块_Activity) 带 宿主_Binder“，而 IPC 是 startActivity 后你读写配置时的事情了

**Comment by cinit** [comment]
@MoonLeeeaf 你直接私聊我吧，在 issue 上讨论这个太费劲了。
