### ISSUE TITLE
[功能请求] 在体验模式(极简模式)下显示聊天框上方的快捷按钮

### ISSUE THREAD

**Issue by Maybe0019** [cinit/QAuxiliary#112]
### QQ(TIM)版本/QQ(TIM) Version

8.8.95

### 为什么你认为需要此功能

体验模式(极简模式)的皮肤挺好看的，然后普通模式下的聊天框的那一排快捷方式我又挺喜欢……两难全，寄希望于模块看能不能满足一下我鱼和熊掌兼得的愿望

### 具体功能需要/Specific features require

“体验模式(简洁模式)显示聊天框上方快捷按钮”

**Comment by HdShare** [comment]
尝试更新QQ版本
实测QQ8.9.88体验模式聊天框上方自带快捷按钮(公告/文件/相册...)
