### ISSUE TITLE
[功能请求] 屏蔽qq表情中的超级表情（也叫大号emoji）

### ISSUE THREAD

**Issue by CosVersin** [cinit/QAuxiliary#1128]
### QQ(TIM)版本/QQ(TIM) Version

9.0.65

### 为什么你认为需要此功能

部分表情又大又唐，而且还在动，看着很烦
另外由于体积很大，很容易遮挡群聊对话，造成不流畅
![image](https://github.com/user-attachments/assets/1be4770f-02db-4aba-8df5-81f553748469)

### 联系到哪些已经存在的bug或者功能

目前已经有功能“关闭大号Emoji”，但仅限于自己发送的情况下生效，别人发送的超级表情还是会变成大号的。

### 具体功能需要/Specific features require

这类表情在单独发送时会变大，如果表情在发送时携带其他文本或者图片或者表情时，将不会触发变大。
希望：屏蔽超级表情（也叫大号emoji）。可以屏蔽隐藏单独发送该表情的消息，又或者是使得表情不再变大
![image](https://github.com/user-attachments/assets/54d7d83b-2a09-43b0-b852-adb784a7f553)
![image](https://github.com/user-attachments/assets/51dfd2e9-38e8-49fe-b816-d36ef522dde4)

**Comment by HdShare** [comment]
尝试最新CI-r2373版
