### ISSUE TITLE
 [Bug] 长按快捷方式的...显示Bug?

### ISSUE THREAD

**Issue by AEDELSTAN** [cinit/QAuxiliary#1132]
### Steps to reproduce/复现步骤

桌面长按qq图标弹出快捷方式

### Expected behaviour/预期行为

不显示/只显示几个 联系人

### Actual behaviour/实际行为

![Uploading IMG_20240816_132653.jpg…]()
![Uploading Screenshot_2024-08-16-13-55-35-268_com.miui.home-edit.jpg…]()

### Xposed Framework you used/你使用的Xposed框架

lsposed 1.9.2(7024)

### Your Android version/你使用的安卓系统版本

14

### QQ(TIM)版本/QQ(TIM) Version

QQ 9.0.85

### Module Version/模块版本

1.5.2.r2375.5c0b933(2375)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Logs/日志

我认为是messagestyle导致的，但是相关日志没有报错

1.5.2.r2375.5c0b933
QQ9.0.85(7068)
PID: 2949, UID: 10281
moe.zapic.hook.MessagingStyleNotification
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

### 补充说明（可选）

我偶然发现了这个问题。以前版本是只显示几个联系人还好点。现在显示太多，会被挡住

**Comment by AEDELSTAN** [comment]
图片没有成功上传，这里尝试补一下

![IMG_20240816_132653.jpg](https://github.com/user-attachments/assets/7948561c-f421-4873-ab3f-7e8724d36b32)

![Screenshot_2024-08-16-13-55-35-268_com.miui.home-edit.jpg](https://github.com/user-attachments/assets/d4fabfae-5d30-42e7-b5c1-774fef2a59ff)

**Comment by keta1** [comment]
应该是通知进化导致的

**Comment by AEDELSTAN** [comment]
> 应该是通知进化导致的

以前好像见过，是另一个软件吗？我现在qq只有QA进行修改

**Comment by keta1** [comment]
> > 应该是通知进化导致的
> 
> 以前好像见过，是另一个软件吗？我现在qq只有QA进行修改

就是 那个让消息通知有联系人分组的功能

**Comment by klxiaoniu** [comment]
故障排查中可以清除shortcuts

**Comment by klxiaoniu** [comment]
至于桌面显示数目过多，可能是你使用了某些模块解除所谓限制导致的

**Comment by AEDELSTAN** [comment]
> 至于桌面显示数目过多，可能是你使用了某些模块解除所谓限制导致的

是的抱歉，刚刚发现是hyperceiler的接触限制功能导致的
不过我关掉之后好像又出现了新的问题，就是联系人把默认的四个快捷方式覆盖了
![IMG_20240817_134208](https://github.com/user-attachments/assets/33241f49-b1d0-4385-938d-51d0bd66d23c)

**Comment by klxiaoniu** [comment]
清除SHortcuts后重启QQ可恢复，如不想再出现可以关闭MessagingStyle通知功能

**Comment by AEDELSTAN** [comment]
好的感谢

快乐小牛 ***@***.***> 于 2024年8月17日周六 下午1:47写道：
