### ISSUE TITLE
[功能请求] 点击机器人消息时不发送消息

### ISSUE THREAD

**Issue by EatHatsuneShallots** [cinit/QAuxiliary#1134]
### QQ(TIM)版本/QQ(TIM) Version

9.0.60

### 为什么你认为需要此功能

~~防止窥屏时不小心点到而被发现~~
用于确认将会发送什么消息

### 具体功能需要/Specific features require

点击机器人消息时不发送消息

**Comment by HdShare** [comment]
指这种点击按钮自动发送的消息?
![image](https://github.com/user-attachments/assets/5ae5bc10-7011-4798-ae34-25e15e4c9e54)

**Comment by EatHatsuneShallots** [comment]
> 指这种点击按钮自动发送的消息?
> 

是的，也包括 Markdown 消息里面的（吗）
