### ISSUE TITLE
[功能请求] 屏蔽动态的游戏中心冒的红点

### ISSUE THREAD

**Issue by 233YUZI** [cinit/QAuxiliary#1139]
### QQ(TIM) 版本 / QQ(TIM) Version

9.0.85

### 为什么你认为需要此功能

具体请看这个链接，我只能说巨TM烦人https://support.qq.com/embed/phone/61107/post/170858299561571916/?clientInfo=23049RAD8C&os=android&clientVersion=9.0.85.18570&netType=WiFi&_wv=1&from_new_gamecenter=1

### 联系到哪些已经存在的 bug 或者功能

模块中有一个“隐藏小红点”的选项，但是没说明具体生效位置，不清楚是否对游戏中心有效

### 具体功能需要 / Detailed features requirements

若能只屏蔽游戏中心导致的红点就好了，若无法实现，会影响到动态正常消息的红点的话，给个一刀切选项也行

**Comment by tianlongJ** [comment]
+1，而且屏蔽红点功能对动态的红点不生效，游戏中心只要有红点，动态就出现红点，而且开启了屏蔽红点后动态红点还是在，不点进游戏中心就不消失，完全没用
