### ISSUE TITLE
[Bug] 屏蔽更新功能导致 QQ 闪退问题

### ISSUE THREAD

**Issue by Guan096** [cinit/QAuxiliary#1143]
### 复现步骤 / Steps to reproduce

1.激活模块开启需要的功能
2.杀死QQ进程
3.打开QQ闪退

### 预期行为 / Expected behaviour

进入QQ主页面

### 实际行为 / Actual behaviour/

进入主页面后闪退后续打开依旧闪退

### 你使用的Xposed框架 / Xposed Framework you used

LSPosed 1.9.2.7058

### 你使用的安卓系统版本 / Your Android version

Android14

### QQ(TIM) 版本 / QQ(TIM) Version

QQ9.0.85

### 模块版本 / Module Version

1.5.2.r2392.4f7a3a9

### Version and Other Requirements/版本和其他要求

- [X] 我正在使用最新 CI 调试版本且启用详细日志 / I am using latest debug CI version of QAuxiliary and enable verbose log
- [X] 我使用的 QQ 是官方发布的正式版本，而非修改版或测试版 / The QQ I am using is an official release version, not a modified or beta version
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 日志 / Logs

[LSPosed_2024-08-20T19_33_11.574208.zip](https://github.com/user-attachments/files/16675164/LSPosed_2024-08-20T19_33_11.574208.zip)

### 补充说明（可选） / Additional information (optional)

清除QQ数据和QA数据后依旧有这个问题  并且在另一个设备中也存在闪退问题

**Comment by klxiaoniu** [comment]
确定是模块问题吗？排查一下哪个功能导致的

**Comment by cinit** [comment]
@Guan096 请尝试关闭模块的“屏蔽更新”功能

**Comment by Guan096** [comment]
抱歉我的回复可能有些晚 关闭模块和使用故障排查里的安全模式后就不会再崩溃了  功能异常列表里没有报红的功能  我会尝试关闭屏蔽更新功能的

**Comment by Guan096** [comment]
我尝试了关闭屏蔽更新功能 关闭后杀死QQ后再打开的三次中没有出现应用崩溃现象  再次打开屏蔽更新后杀死QQ再打开的三次中出现了两次崩溃现象

**Comment by HdShare** [comment]
尝试v1.5.3-r2480版本

**Comment by Guan096** [comment]
> 尝试v1.5.3-r2480版本

已正常
