### ISSUE TITLE
[功能请求] 防撤回灰字提示

### ISSUE THREAD

**Issue by xvkong233** [cinit/QAuxiliary#115]
### QQ(TIM)版本/QQ(TIM) Version

8.9.0

### 为什么你认为需要此功能

聊天过程中，不知道哪些信息被撤回，哪些信息没被撤回。

### 具体功能需要/Specific features require

在对话撤回后，有灰色小字的提示。
qn模块中有实现。

**Comment by cinit** [comment]
@xvkong233 CI 刚修
