### ISSUE TITLE
[Bug] 启用自定义外显内容后，复读的商城表情也会应用外显

### ISSUE THREAD

**Issue by EatHatsuneShallots** [cinit/QAuxiliary#1154]
### 复现步骤 / Steps to reproduce

1. 启用自定义外显内容，确保 “商城表情” 已选中
2. 如果启用了 消息+1 Plus，则确保显示在长按菜单中没有选中（会导致消息旁边的 +1 按钮被隐藏）
3. 点击 **商城表情** 消息旁边的 +1 按钮（不是点击消息菜单中的 +1 按钮）

### 预期行为 / Expected behaviour

不更改外显

### 实际行为 / Actual behaviour/

更改了外显

### 你使用的Xposed框架 / Xposed Framework you used

ONPatch 0.0.7

### 你使用的安卓系统版本 / Your Android version

10

### QQ(TIM) 版本 / QQ(TIM) Version

9.0.60

### 模块版本 / Module Version

f9eaffe6cb32a467e8df116091c937a0b6a55b96

### 版本和其他要求 / Version and Other Requirements

- [X] 我正在使用最新 CI 调试版本且启用详细日志 / I am using latest debug CI version of QAuxiliary and enable verbose log
- [X] 我使用的 QQ 是官方发布的正式版本，而非修改版或测试版 / The QQ I am using is an official release version, not a modified or beta version
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 日志 / Logs

消息 +1 Plus（无关）：
```
1.5.2.r2405.f9eaffe
QQ9.0.60(6478)
PID: 16401, UID: 10225
cc.hicore.hook.RepeaterPlus
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

```
自定义外显内容：
```
1.5.2.r2405.f9eaffe
QQ9.0.60(6478)
PID: 16401, UID: 10225
cc.microblock.hook.ImageCustomSummary
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

```

**Comment by HdShare** [comment]
非bug，复读代码中对复读类型进行了判断
如果是PicElement，StructMsgElement，ArkElement则进行转发
否则就进行发送操作

**Comment by EatHatsuneShallots** [comment]
> 复读代码中对复读类型进行了判断

那可以在复读商城表情时使用转发吗（转发没有问题）
