### ISSUE TITLE
[Bug] 新功能提示不起作用

### ISSUE THREAD

**Issue by Bai-0305** [cinit/QAuxiliary#1157]
### 复现步骤 / Steps to reproduce

1.每次模块更新后，并不会给我新功能提示

### 预期行为 / Expected behaviour

告诉我新功能是什么

### 实际行为 / Actual behaviour/

![Screenshot_20240830_112314_com tencent mobileqq](https://github.com/user-attachments/assets/0c201294-e7b3-46fb-a99a-59ecf1ecca6a)
只有开关开了，但是没有作用

### 你使用的Xposed框架 / Xposed Framework you used

OPatch

### 你使用的安卓系统版本 / Your Android version

HarmonyOS 4.2.0

### QQ(TIM) 版本 / QQ(TIM) Version

9.0.60

### 模块版本 / Module Version

1.5.2.r2409.4f4be22(2409)

### 版本和其他要求 / Version and Other Requirements

- [X] 我正在使用最新 CI 调试版本且启用详细日志 / I am using latest debug CI version of QAuxiliary and enable verbose log
- [X] 我使用的 QQ 是官方发布的正式版本，而非修改版或测试版 / The QQ I am using is an official release version, not a modified or beta version
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 日志 / Logs

1.5.2.r2409.4f4be22
QQ9.0.60(6478)
PID: 15375, UID: 10441
io.github.qauxv.tips.newfeaturehint.NewFeatureManager$NewFeatureTipEnabledAgent

**Comment by cinit** [comment]
@Bai-0305 已确认 bug, 下个 release 修

**Comment by EatHatsuneShallots** [comment]
> 下个 release 修

好像忘修了（

**Comment by cinit** [comment]
@EatHatsuneShallots 它的原理是每次更新存一下，和上次比较，所以要这次更新的下一次才会有

**Comment by EatHatsuneShallots** [comment]
> 它的原理是每次更新存一下，和上次比较，所以要这次更新的下一次才会有

更新是指更新模块本身这个软件吗，LSPatch 内置模式好像没有显示（或者我不知道在哪里显示）
已经启用了 新功能提示

**Comment by cinit** [comment]
> 更新是指更新模块本身这个软件吗

@EatHatsuneShallots  是的，等下一次 qa 更新你应该就能看到新功能提示了。

**Comment by Bai-0305** [comment]
> > 更新是指更新模块本身这个软件吗
> 
> @EatHatsuneShallots  是的，等下一次 qa 更新你应该就能看到新功能提示了。
> 


这个提示是以弹窗还是什么样的方式告诉我的（其实连续几次更新我也一直没看到新功能提示，但这次我觉得可能是我的问题）

**Comment by HdShare** [comment]
> 这个提示是以弹窗还是什么样的方式告诉我的（其实连续几次更新我也一直没看到新功能提示，但这次我觉得可能是我的问题）

标题栏下方
![image](https://github.com/user-attachments/assets/e4e725ac-97e7-47fb-9a87-289996294f28)

**Comment by Bai-0305** [comment]
> > 这个提示是以弹窗还是什么样的方式告诉我的（其实连续几次更新我也一直没看到新功能提示，但这次我觉得可能是我的问题）
> 
> 标题栏下方
> ![image](https://github.com/user-attachments/assets/e4e725ac-97e7-47fb-9a87-289996294f28)
> 
> 
> 

老是说我的设备并没有提示并且没有报错，可能是我开启了李跳跳或者其他个人原因，感谢开发者

**Comment by EatHatsuneShallots** [comment]
> 标题栏下方

未曾见过
