### ISSUE TITLE
[功能请求] 显示具体消息数量对隐藏会话生效

### ISSUE THREAD

**Issue by EatHatsuneShallots** [cinit/QAuxiliary#1159]
### QQ(TIM) 版本 / QQ(TIM) Version

9.0.60

### 为什么你认为需要此功能

~~还是强迫症~~

### 联系到哪些已经存在的 bug 或者功能

显示具体消息数量

### 具体功能需要 / Detailed features requirements

显示具体消息数量对 设置 -> 隐私 -> 隐藏会话 旁边的消息数量生效，这个入口只会在有设置了隐藏会话的群聊或（和）好友时才会显示

**Comment by HdShare** [comment]
隐藏会话 位置? 无法找到
![image](https://github.com/user-attachments/assets/868aae5c-c3b7-4d7f-bc5b-939671fa8e16)

**Comment by EatHatsuneShallots** [comment]
> 隐藏会话 位置? 无法找到
> 

请先将任意一个群隐藏会话

**Comment by HdShare** [comment]
> 
> 请先将任意一个群或好友设置隐藏会话
> 

ok, 已找到，下次新增这功能
