### ISSUE TITLE
长按消息撤回功能异常

### ISSUE THREAD

**Issue by Tylerxz** [cinit/QAuxiliary#116]
### Steps to reproduce/复现步骤

长按消息点击撤回

### Expected behaviour/预期行为

消息已撤回

### Actual behaviour/实际行为

上面一个提示撤回失败

### XPosed Framework you used/你使用的XP框架

太极阴

### QQ(TIM)版本/QQ(TIM) Version

8.8.98

### Module Version/模块版本

1.2.10.r790.4362827(790)

### Version requirement/版本要求

- [x] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.2.10.r790.4362827
QQ8.8.98(3002)
me.ketal.hook.MultiActionHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by lliioollcn** [comment]
请问你撤回的是你自己的还是别人的，还有就是是不是消息发送已经超过两分钟，并且在群里面你不是群管
