### ISSUE TITLE
[Bug]启用qa模块 无法打开QQ钱包，以及无法使用QQ内置的图片编辑器

### ISSUE THREAD

**Issue by zhuixingzhe-baisheng** [cinit/QAuxiliary#117]
### Steps to reproduce/复现步骤

启用qa

### Expected behaviour/预期行为

打开QQ钱包及图片编辑器闪退

### Actual behaviour/实际行为

闪退

### XPosed Framework you used/你使用的XP框架

太极9.12

### QQ(TIM)版本/QQ(TIM) Version

QQ8.8.95

### Module Version/模块版本

1.10

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

功能都正常

**Comment by keta1** [comment]
测试下使用新版模块， 打开 故障排查 中的 安全模式，问题是否存在
