### ISSUE TITLE
[Bug] 人脸识别失败

### ISSUE THREAD

**Issue by wangnimaaaa** [cinit/QAuxiliary#1177]
### 复现步骤 / Steps to reproduce

账号解封需要人脸识别

### 预期行为 / Expected behaviour

识别成功

### 实际行为 / Actual behaviour

人脸识别失败，设备环境异常

### 你使用的Xposed框架 / Xposed Framework you used

LSpatch

### 你使用的安卓系统版本 / Your Android version

13

### QQ(TIM) 版本 / QQ(TIM) Version

9.0.95

### 模块版本 / Module Version

1.5.2.r2263.c3d9cc2(2263)

### 版本和其他要求 / Version and Other Requirements

- [ ] 我正在使用最新 CI 调试版本且启用详细日志 / I am using latest debug CI version of QAuxiliary and enable verbose log
- [X] 我使用的 QQ 是官方发布的正式版本，而非修改版或测试版 / The QQ I am using is an official release version, not a modified or beta version
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 日志 / Logs

没有错误日志

**Comment by klxiaoniu** [comment]
你试过在人脸识别的时候关掉模块吗？

**Comment by EatHatsuneShallots** [comment]
填 Xposed 框架不是模块

**Comment by wangnimaaaa** [comment]
> 你试过在人脸识别的时候关掉模块吗？

大佬，请问怎么关掉模块？

**Comment by EatHatsuneShallots** [comment]
> 大佬，请问怎么关掉模块？

建议：卸载非官方版 QQ 并重新安装 QQ（小心登录时显示非常用设备，建议在另一个设备解封）

**Comment by wangnimaaaa** [comment]
> > 大佬，请问怎么关掉模块？
> 
> 建议：卸载非官方版QQ并重新安装QQ（登录小心时显示非常用设备，建议先在另一个设备解封）

你好大佬，我试过把模块卸载后重新安装最新版qq登录，在原来的手机和旧手机登录也是显示非常用设备，禁止登陆。怎么办才好呢？

**Comment by wangnimaaaa** [comment]
不知道qq在有模块的情况下人脸识别设备环境不安全的bug可不可以修好呢？

**Comment by EatHatsuneShallots** [comment]
> 不知道qq在有模块的情况下人脸识别设备环境不安全的bug可不可以修好呢？

解决不了（Wontfix）

**Comment by wangnimaaaa** [comment]
> > 不知道qq在有模块的情况下人脸识别设备环境不安全的bug可不可以修好呢？
> 
> 解决不了（Wontfix）

啊？难道只能腾讯客服解决吗？这客服打了好多遍都没人工

**Comment by wangnimaaaa** [comment]
> > > 不知道qq在有模块的情况下人脸识别设备环境不安全的bug可不可以修好呢？
> > 
> > 
> > 解决不了（Wontfix）
> 
> 啊？难道只能腾讯客服解决吗？这客服打了好多遍都没人工

不用模块登录，说我非常规设备禁止登陆，用了模块登录就卡在最后的人脸识别，难崩
