### ISSUE TITLE
[功能请求] 拦截机器人点击发送消息也能对智能体生效

### ISSUE THREAD

**Issue by EatHatsuneShallots** [cinit/QAuxiliary#1182]
### QQ(TIM) 版本 / QQ(TIM) Version

9.0.60

### 为什么你认为需要此功能

还是容易误触

### 联系到哪些已经存在的 bug 或者功能

拦截机器人点击发送消息

### 具体功能需要 / Detailed features requirements

拦截机器人点击发送消息也能对智能体的聊天推荐生效
智能体是指：聊天机器人的私信

**Comment by HdShare** [comment]
![image](https://github.com/user-attachments/assets/4ef0fe3b-be88-4eef-87c8-8236e7df3ee9)
是这个吧?

**Comment by EatHatsuneShallots** [comment]
> 是指这个吧?

是的
