### ISSUE TITLE
[Bug] 消息+1无复读图标

### ISSUE THREAD

**Issue by lzx9002** [cinit/QAuxiliary#1183]
### 复现步骤 / Steps to reproduce

聊天和消息->
消息+1 plus和
消息+1

### 预期行为 / Expected behaviour

消息旁出现+1

### 实际行为 / Actual behaviour

什么也没有

### 你使用的Xposed框架 / Xposed Framework you used

1.9.2

### 你使用的安卓系统版本 / Your Android version

10

### QQ(TIM) 版本 / QQ(TIM) Version

9.0.95

### 模块版本 / Module Version

1.5.2.r2263.c3d9cc2

### 版本和其他要求 / Version and Other Requirements

- [ ] 我正在使用最新 CI 调试版本且启用详细日志 / I am using latest debug CI version of QAuxiliary and enable verbose log
- [X] 我使用的 QQ 是官方发布的正式版本，而非修改版或测试版 / The QQ I am using is an official release version, not a modified or beta version
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 日志 / Logs

1.5.2.r2263.c3d9cc2
QQ9.0.95(7368)
PID: 16692, UID: 10217
cc.hicore.hook.RepeaterPlus
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by HdShare** [comment]
在最新的1.5.3.r2434无法复现，尝试更新QA版本

**Comment by lzx9002** [comment]
> 在最新的1.5.3.r2434无法复现，尝试更新QA版本

完全没用

**Comment by lzx9002** [comment]
> 在最新的1.5.3.r2434无法复现，尝试更新QA版本

一样的结果

**Comment by lzx9002** [comment]
> > 在最新的1.5.3.r2434无法复现，尝试更新QA版本
> 
> 一样的结果
![Screenshot_2024-09-14-12-41-24-708_com tencent mo](https://github.com/user-attachments/assets/605ba589-f603-47d6-bfad-b73cce952d89)
![Screenshot_2024-09-14-12-41-45-915_com tencent mo](https://github.com/user-attachments/assets/b2d7d31d-934e-4d92-a225-c86446bf59b2)
![Screenshot_2024-09-14-12-42-02-109_com tencent mo](https://github.com/user-attachments/assets/aa2912cd-eb3d-4730-af86-89ec59daef45)

![Screenshot_2024-09-14-12-44-27-608_com tencent mo](https://github.com/user-attachments/assets/d2523204-ddd1-47f4-8dde-d685ba8560e6)
我已尝试过重启qq，qa，包括手机多次

**Comment by lzx9002** [comment]
我的手机是红米k20，miui12

**Comment by lzx9002** [comment]
新版日志：
1.5.3.r2434.e6297ae
QQ9.0.95(7368)
PID: 7578, UID: 10217
cc.hicore.hook.RepeaterPlus
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0
