### ISSUE TITLE
[Bug] 移除夜间遮罩失效

### ISSUE THREAD

**Issue by kkdyyy** [cinit/QAuxiliary#119]
### Steps to reproduce/复现步骤

打开移除夜间遮罩开关
显示初始化失败

### Expected behaviour/预期行为

初始化成功，重启QQ生效

### Actual behaviour/实际行为

初始化失败，无效

### XPosed Framework you used/你使用的XP框架

lsp

### QQ(TIM)版本/QQ(TIM) Version

8.9.1 64bit

### Module Version/模块版本

1.2.11.r840.5b91f01 arm64

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.2.11.r840.5b91f01
QQ8.9.1(3068)
cc.ioctl.hook.DarkOverlayHook
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by keta1** [comment]
移除夜间遮罩功能已删除
