### ISSUE TITLE
[Bug] 语音转发和保存

### ISSUE THREAD

**Issue by fight-fly** [cinit/QAuxiliary#1198]
### 复现步骤 / Steps to reproduce

语音转发失效了吗？
这边提示发送成功，
那边的没收到。这边也没聊天记录。

### 预期行为 / Expected behaviour

转发正常，或者告知功能匹配版本

### 实际行为 / Actual behaviour

对方没收到转发的语音，这边也没出现聊天记录

### 你使用的Xposed框架 / Xposed Framework you used

opatch_7

### 你使用的安卓系统版本 / Your Android version

10

### QQ(TIM) 版本 / QQ(TIM) Version

9.0.65

### 模块版本 / Module Version

1.5.3.2434

### 版本和其他要求 / Version and Other Requirements

- [X] 我正在使用最新 CI 调试版本且启用详细日志 / I am using latest debug CI version of QAuxiliary and enable verbose log
- [X] 我使用的 QQ 是官方发布的正式版本，而非修改版或测试版 / The QQ I am using is an official release version, not a modified or beta version
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 日志 / Logs

1.5.3.r2434.e6297ae
QQ9.0.65(6588)
PID: 27874, UID: 10460
cc.ioctl.hook.msg.PttForwardHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by HdShare** [comment]
QQ9.0.65(6566)+QA1.5.3.r2439.cf6f615未复现
