### ISSUE TITLE
[功能请求] 禁用群消息被自动屏蔽

### ISSUE THREAD

**Issue by Tai7sy** [cinit/QAuxiliary#120]
### QQ(TIM)版本/QQ(TIM) Version

8.9.1

### 为什么你认为需要此功能

![SmartSelect_20220723-132204_QQ](https://user-images.githubusercontent.com/12840640/180591725-4ab051ef-ca91-44dc-8d37-12646c965473.jpg)

新版本发现的，极为太恶心人

### 具体功能需要/Specific features require

禁用屏蔽消息检测

**Comment by NextAlone** [comment]
@Tai7sy 服务器控制，无法实现

**Comment by Tai7sy** [comment]
发出去短时间内可以看到，过10秒左右才变成这样

**Comment by NextAlone** [comment]
@Tai7sy 恩？唔，

**Comment by Tai7sy** [comment]
比如消息
http://dd.ma/A

发送到群聊中，自己看正常， 别人刚接收到是正常的，过10妙左右自动被屏蔽。

**Comment by NextAlone** [comment]
> 比如消息
> http://dd.ma/A
> 
> 发送到群聊中，自己看正常， 别人刚接收到是正常的，过10妙左右自动被屏蔽。

哦，这样的话可以看一下

**Comment by qwq233** [comment]
服务端控制的吧
