### ISSUE TITLE
[Bug] 在小米14体验增强版beta系统中，无法激活模块

### ISSUE THREAD

**Issue by mrliguo** [cinit/QAuxiliary#1203]
### 复现步骤 / Steps to reproduce

安装小米14体验增强版beta系统后，使用了支持安卓15的lsposed版本，在QA中提示已激活，但是QQ里没有出现QA对应入口，同时模块也没有激活
![Screenshot_2024-09-24-08-12-23-931_io github qauxv](https://github.com/user-attachments/assets/faab7860-771e-4f27-80e2-3b04ddbb4cd8)
![Screenshot_2024-09-24-08-12-20-436_com tencent mobileqq](https://github.com/user-attachments/assets/8352885d-496c-4342-a883-f70b410b1f45)
![Screenshot_2024-09-24-08-12-15-762_com tencent mobileqq](https://github.com/user-attachments/assets/2afdc245-6e9b-4337-9520-d14adca14c65)

### 预期行为 / Expected behaviour

模块在QQ中正常激活

### 实际行为 / Actual behaviour

模块没有激活

### 你使用的Xposed框架 / Xposed Framework you used

lsposed 1.9.3_mod（7295）

### 你使用的安卓系统版本 / Your Android version

Android 15

### QQ(TIM) 版本 / QQ(TIM) Version

9.0.95

### 模块版本 / Module Version

1.5.3.r2448.761c72d

### 版本和其他要求 / Version and Other Requirements

- [X] 我正在使用最新 CI 调试版本且启用详细日志 / I am using latest debug CI version of QAuxiliary and enable verbose log
- [X] 我使用的 QQ 是官方发布的正式版本，而非修改版或测试版 / The QQ I am using is an official release version, not a modified or beta version
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 日志 / Logs

无法进入模块设置界面

**Comment by cinit** [comment]
@mrliguo 去群里说吧

**Comment by mrliguo** [comment]
更新lsp后解决
