### ISSUE TITLE
[dev] 对于 模块功能配置 的若干疑问

### ISSUE THREAD

**Issue by MoonLeeeaf** [cinit/QAuxiliary#1211]
### 描述 / Description

继 #1117 后,我仍没能实现 "宿主应用 → 模块应用的配置页面 with 宿主_Binder → 模块应用 IPC 宿主应用",因此我想再找下“模块功能配置”的灵感(

1. 除了 Binder、ContentProvider、XSharedPreference 以外,还有没有更好的方案?
2. QA 是如何做到把 [SettingsUiFragmentHostActivity.kt](https://github.com/cinit/QAuxiliary/blob/a60bf1da9415d75b781463611ecf97f04e856cf9/app/src/main/java/io/github/qauxv/activity/SettingsUiFragmentHostActivity.kt)⁦ 植入到宿主应用并启动的?
3. QA 对于 免root Xposed Framework 的适配有何技巧或者感想,亦或者文档? 鄙人对此毫无经验😂

对于 Xposed 模块开发,既无统一的文档,又无正规的教程,还有一大片空白,真的很让我头疼🤔

谢谢!🍉

附:如果确实想知道我的模块写成了什么样子,请参见 [FuckMaoNemo](https://github.com/MoonLeeeaf/FuckMaoNemo/tree/main/app/src/main) 当然鄙人的技法甚烂 可能会难以入目()

### 其他要求 / Other Requirements

- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我知晓此 Issue 模板仅限开发者使用，普通用户请使用问题反馈或功能请求模板。 / I know this issue template is for developers only. Regular users should use the bug report or feature request template.

**Comment by Hicores** [comment]
@MoonLeeeaf 模块hook宿主的一个activity，然后模块本体点击配置按钮时启动被hook的activity，hook逻辑中启动模块自身的activity

**Comment by cinit** [comment]
@MoonLeeeaf 1. 没有了，常规方式就这些。
2. 说来话长，私聊。
3. 不要假设用户安装了模块 apk, 仅使用 initZygote 提供的 apk 路径。

**Comment by teble** [comment]
@MoonLeeeaf 2. 涉及四大组件插件化，有兴趣可以谷歌了解一下原理

**Comment by keta1** [comment]
直接 fork qa 改成你的模块）

**Comment by leafmoes** [comment]
> 2. QA 是如何做到把 [SettingsUiFragmentHostActivity.kt](https://github.com/cinit/QAuxiliary/blob/a60bf1da9415d75b781463611ecf97f04e856cf9/app/src/main/java/io/github/qauxv/activity/SettingsUiFragmentHostActivity.kt)⁦ 植入到宿主应用并启动的?

你可以看看这个类 [Parasitics.java](https://github.com/cinit/QAuxiliary/blob/a60bf1da9415d75b781463611ecf97f04e856cf9/app/src/main/java/io/github/qauxv/lifecycle/Parasitics.java)

**Comment by MoonLeeeaf** [comment]
谢谢各位大神
研究中()()()

**Comment by cinit** [comment]
@MoonLeeeaf 你在 qa 用户群吗，我找你

**Comment by MoonLeeeaf** [comment]
> @MoonLeeeaf 你在 qa 用户群吗，我找你私聊

@cinit 我的TG之前炸哩(大悲
(二次验证,另一台登了号的手机废了)
