### ISSUE TITLE
[功能请求] QQ屏蔽聊天快捷栏

### ISSUE THREAD

**Issue by dontknowhy** [cinit/QAuxiliary#1226]
### QQ(TIM) 版本 / QQ(TIM) Version

9.1.10（内测，不确定会不会实装）

### 为什么你认为需要此功能

![Screenshot_20241026_101638](https://github.com/user-attachments/assets/dac544cd-5847-471c-9652-25d0efa5a587)
你不觉得很酷吗，现在你需要每个群点至少三次才能看见超级不起眼的开关。
具体地方为：群聊设置>个性设置>展示聊天快捷栏

### 具体功能需要 / Detailed features requirements

这个开关是每个群单独出来的，所以貌似可以直接默认关掉全部群的这个开关
**警告：我是QQ内测版，如果真的感觉内测没必要接这个活的话麻烦把我晾着（**

**Comment by HdShare** [comment]
未在 群聊设置>个性设置 中找到 展示聊天快捷栏
只在 群聊设置>群应用中心 中找到 在聊天快捷栏展示群应用
