### ISSUE TITLE
[功能请求] QQ添加自动关闭聊天快捷栏

### ISSUE THREAD

**Issue by dontknowhy** [cinit/QAuxiliary#1227]
### QQ(TIM) 版本 / QQ(TIM) Version

9.1.10（内测版）

### 为什么你认为需要此功能

![Screenshot_20241026_101638](https://github.com/user-attachments/assets/dac544cd-5847-471c-9652-25d0efa5a587)
你不觉得很酷吗，现在你需要每个群点至少三次才能看见超级不起眼的开关。
具体地方为：群聊设置>个性设置>展示聊天快捷栏

### 具体功能需要 / Detailed features requirements

这个开关是每个群单独出来的，所以貌似可以直接默认关掉全部群的这个开关
**警告：我是QQ内测版，如果真的感觉内测没必要接这个活的话麻烦把我晾着（**

**Comment by HdShare** [comment]
自动关闭 是指?

**Comment by dontknowhy** [comment]
> 自动关闭 是指?

不需要人工干预就会关闭每个群的功能栏
另外我感觉还是得要把我晾在这毕竟刚才你commit上去的设置项对于内测版这东西没啥用处
或者直接not planned关掉，如果正式版真的默认每个群单独开这个且设置单独存储的话我再打开这个issue

**Comment by HdShare** [comment]
> 不需要人工干预就会关闭每个群的功能栏
> 另外我感觉还是得要把我晾在这毕竟刚才你commit上去的设置项对于内测版这东西没啥用处
> 或者直接not planned关掉，如果正式版真的默认每个群单独开这个且设置单独存储的话我再打开这个issue

刚才commit的 隐藏聊天快捷栏
我用的就是9.1.10内测版测试没问题
你当前是无效果还是报错?

**Comment by dontknowhy** [comment]
> > 不需要人工干预就会关闭每个群的功能栏
> > 另外我感觉还是得要把我晾在这毕竟刚才你commit上去的设置项对于内测版这东西没啥用处
> > 或者直接not planned关掉，如果正式版真的默认每个群单独开这个且设置单独存储的话我再打开这个issue
> 
> 刚才commit的 隐藏聊天快捷栏
> 我用的就是9.1.10内测版测试没问题
> 你当前是无效果还是报错?
> 
> 

没效果，以及你提到的设置位置不一样，是我被选中做灰度测试了还是？
![Screenshot_20241027_194152.jpg](https://github.com/user-attachments/assets/4854a6ca-4dcf-49e1-9d0e-06f2cdea162c)

我这边并没有所谓的 在聊天快捷栏展示群应用
![Screenshot_20241027_194252.jpg](https://github.com/user-attachments/assets/33414a2f-ebbd-4c58-99e1-9f094169c57a)

但是我可以在我提到的群聊设置 >个性设置找到。
奇怪

**Comment by HdShare** [comment]
![image](https://github.com/user-attachments/assets/89b3a2ab-abbb-44f3-b06b-446705d8117c)

经测试，9.1.10.20440(7816)与8.9.88.13035(4852)隐藏聊天快捷栏都正常有效

**Comment by dontknowhy** [comment]
> 经测试，9.1.10.20440(7816)与8.9.88.13035(4852)隐藏聊天快捷栏都正常有效
![Image_39723199310598.jpg](https://github.com/user-attachments/assets/bb6867a6-4a1e-40a3-ae56-e996d434431b)

![Image_39719482372751.jpg](https://github.com/user-attachments/assets/bd5d4098-fab2-4645-ab07-ef4bfef2c03d)

找群友截图了一下，他两个地方都没有（

**Comment by HdShare** [comment]
尝试QA-r2495版本

**Comment by dontknowhy** [comment]
> 尝试QA-r2495版本

烦人的快捷栏已消失，且原来的开关成摆设
