### ISSUE TITLE
[功能请求] 添加取消批量撤回数量限制功能

### ISSUE THREAD

**Issue by xinghe6** [cinit/QAuxiliary#1229]
### QQ(TIM) 版本 / QQ(TIM) Version

9.1.1.0

### 为什么你认为需要此功能

目前版本qq批量撤回限制10条消息，感觉是对批量这个词有什么误解，导致操作的时候还是得点很多次，十分不方便

### 具体功能需要 / Detailed features requirements

添加一个取消数量限制功能。

**Comment by xinghe6** [comment]
> @xinghe6 QA有批量撤回功能

现在官方也支持批量撤回了，我的意思是她有数量限制，只能撤回10条，开启qa的批量撤回也是一样

**Comment by HdShare** [comment]
> 现在官方也支持批量撤回了，我的意思是她有数量限制，只能撤回10条，开启qa的批量撤回也是一样

经测试，以上官方批量撤回上限去除后，
单次撤回仍然是最多10次，多选的不会被撤回

**Comment by xinghe6** [comment]
> > 现在官方也支持批量撤回了，我的意思是她有数量限制，只能撤回10条，开启qa的批量撤回也是一样
> 
> 经测试，以上官方批量撤回上限去除后， 单次撤回仍然是最多10条，多选的不会被撤回

那寄了，可能是服务器限制，还得是QQ

**Comment by HdShare** [comment]
尝试QA-r2493版本的批量撤回，已添加撤回延迟方便撤回更多

**Comment by xinghe6** [comment]
> 尝试QA-r2493版本的批量撤回，已添加撤回延迟方便撤回更多

太感谢了，我去试试

**Comment by AltinaNissan** [comment]
> 尝试QA-r2493版本的批量撤回，已添加撤回延迟方便撤回更多

请问2493什么时候上线
