### ISSUE TITLE
[功能请求] 给TIM整一个链接预览

### ISSUE THREAD

**Issue by molehzy** [cinit/QAuxiliary#1231]
### QQ(TIM) 版本 / QQ(TIM) Version

3.5.x+

### 为什么你认为需要此功能

IOS版QQ有
PC版也有第三方插件实现

### 具体功能需要 / Detailed features requirements

![76CDE390AAC2BDB3A566493FB4A0AF2B](https://github.com/user-attachments/assets/dba3833c-83d3-474d-aa87-957c91ca3b4b)

**Comment by klxiaoniu** [comment]
@molehzy 可以关注下TIM4后续更新
