### ISSUE TITLE
trpc.o3开启后无法拉取人脸资源

### ISSUE THREAD

**Issue by kagg886** [cinit/QAuxiliary#1234]
### 复现步骤 / Steps to reproduce

1. 开启trpc.o3拦截
2. 使用被冻结QQ，进入人脸验证环节
3. 点击开始

### 预期行为 / Expected behaviour

正常进入人脸且识别成功

### 实际行为 / Actual behaviour

qq将一直停在准备中画面，随后loading消失，约三分钟后提示人脸资源拉取失败

### 你使用的Xposed框架 / Xposed Framework you used

LSPosed内测版 1.9.2-it-7237

### 你使用的安卓系统版本 / Your Android version

14

### QQ(TIM) 版本 / QQ(TIM) Version

9.0.90

### 模块版本 / Module Version

1.5.3-r2462-f7b7ecd

### 版本和其他要求 / Version and Other Requirements

- [ ] 我正在使用最新 CI 调试版本且启用详细日志 / I am using latest debug CI version of QAuxiliary and enable verbose log
- [X] 我使用的 QQ 是官方发布的正式版本，而非修改版或测试版 / The QQ I am using is an official release version, not a modified or beta version
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 日志 / Logs

1.5.3.r2462.f7b7ecd
QQ9.0.90(7218)
PID: 14056, UID: 10299
awoo.linwenxuan04.hook.ChannelProxyHook
isInitialized: false
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

### 补充说明（可选） / Additional information (optional)

无

**Comment by Hicores** [comment]
那就关掉就行了

**Comment by kagg886** [comment]
> 那就关掉就行了

关掉后提示设备不安全(｡･ˇ_ˇ･｡:)

**Comment by TaffyStudio** [comment]
> > 那就关掉就行了
> 
> 关掉后提示设备不安全(｡･ˇ_ˇ･｡:)

关开发者模式 lsposed里所有模块不要hook qq 然后重启qq再人脸试试

**Comment by kagg886** [comment]
> > > 那就关掉就行了
> > 
> > 关掉后提示设备不安全(｡･ˇ_ˇ･｡:)
> 
> 关开发者模式 lsposed里所有模块不要hook qq 然后重启qq再人脸试试

这边卸载magisk后等待半天后最终过了人脸....

推测是QQ更新了一波新的检测。。。
