### ISSUE TITLE
[Bug] qa+funbox+android15下，进入qa设置闪退

### ISSUE THREAD

**Issue by Mayuker** [cinit/QAuxiliary#1235]
### 复现步骤 / Steps to reproduce

和funbox一起用 qa进设置闪退

### 预期行为 / Expected behaviour

1

### 实际行为 / Actual behaviour

1

### 你使用的Xposed框架 / Xposed Framework you used

框架版本 1.10.1（7115)

### 你使用的安卓系统版本 / Your Android version

15

### QQ(TIM) 版本 / QQ(TIM) Version

9.0.95

### 模块版本 / Module Version

1.5.4.r2506.deeaa77

### 版本和其他要求 / Version and Other Requirements

- [ ] 我正在使用最新 CI 调试版本且启用详细日志 / I am using latest debug CI version of QAuxiliary and enable verbose log
- [X] 我使用的 QQ 是官方发布的正式版本，而非修改版或测试版 / The QQ I am using is an official release version, not a modified or beta version
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 日志 / Logs

[LSPosed_2024-11-04T17_24_14.063536.zip](https://github.com/user-attachments/files/17616222/LSPosed_2024-11-04T17_24_14.063536.zip)
![Screenshot_2024-11-04-17-40-20-992_com tencent mobileqq](https://github.com/user-attachments/assets/5368111d-1826-4526-ae84-240ef908fa77)

**Comment by klxiaoniu** [comment]
关闭funbox后如何呢？

**Comment by Mayuker** [comment]
> 关闭funbox后如何呢？

**Comment by Mayuker** [comment]
> 关闭funbox后如何呢？

详情请看视频

**Comment by Mayuker** [comment]
详情请看视频

https://github.com/user-attachments/assets/580eb50c-05c4-4348-bad3-adb28dcc9d8e

**Comment by shixiaoxiao233** [comment]
同款问题，但是只是设置界面打不开，功能能正常使用

**Comment by qli5208** [comment]
同样的问题，功能正常，但是在其它界面也有可能造成闪退。https://github.com/user-attachments/assets/1fefc246-24d4-4365-92a7-80fb0fe2cb6f

**Comment by qli5208** [comment]
同样的问题，模块可能正常，但是在进入部分界面的时候也会闪退。
模块日志[LSPosed_2024-11-17T10_11_13.613308.zip](https://github.com/user-attachments/files/17788588/LSPosed_2024-11-17T10_11_13.613308.zip)

Uploading Screenrecorder-2024-11-17-10-10-58-642.mp4…


https://github.com/user-attachments/assets/e112e01d-1bc9-4c08-ab87-d237ccccbb24

**Comment by baiyao105** [comment]
同款遇到了

**Comment by klxiaoniu** [comment]
不要无意义+1，这个问题已经在研究，谢谢

**Comment by klxiaoniu** [comment]
ci 2525已解决
