### ISSUE TITLE
[Bug] QQ9.1.10.20545版本下各种QA功能全部失效

### ISSUE THREAD

**Issue by IzumiChino** [cinit/QAuxiliary#1237]
### 复现步骤 / Steps to reproduce

1.本人先前使用QQ 8.x版本，今天被提示版本过老强制升级到9.0.9，然后再被提示内测版本已经结束，因此被强制升级到QQ V9.1.10.20545，在这个版本下QA无法正常启用，在设置栏中并没有Qauxiliary的选项，但是模块显示已激活

### 预期行为 / Expected behaviour

正常在设置栏中显示QAuxiliary的选项并且各项功能均可正常使用

### 实际行为 / Actual behaviour

所有功能均已失效，设置栏中没有QAuxiliary的选项，哪怕模块显示已激活
![qq_pic_merged_1730751435615](https://github.com/user-attachments/assets/090363a2-ca02-4cdd-9089-651105c2c5a4)
![qq_pic_merged_1730751455612](https://github.com/user-attachments/assets/a8d6b71c-97b4-42be-b133-16f5198e2488)

### 你使用的Xposed框架 / Xposed Framework you used

LSPosed 1.9.3_mod(7244)

### 你使用的安卓系统版本 / Your Android version

Android 14(UP1A.231005.007)

### QQ(TIM) 版本 / QQ(TIM) Version

QQ 9.1.10.20545

### 模块版本 / Module Version

1.5.4.r2483.eecf29b

### 版本和其他要求 / Version and Other Requirements

- [ ] 我正在使用最新 CI 调试版本且启用详细日志 / I am using latest debug CI version of QAuxiliary and enable verbose log
- [X] 我使用的 QQ 是官方发布的正式版本，而非修改版或测试版 / The QQ I am using is an official release version, not a modified or beta version
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 日志 / Logs

完全无法打开功能异常列表，即使已经手动启用安全模式也无法进入故障排查，立即卡退

### 补充说明（可选） / Additional information (optional)

![image](https://github.com/user-attachments/assets/3714aba9-b709-49ae-b8bc-f6cc2d4d10a5)

我在这四个~~不可以提到的字~~后面添加了具体版本号，但是这个bot检测到有这四个字就还是给closed了（有点尴尬

**Comment by HdShare** [comment]
lsp日志

**Comment by cinit** [comment]
@IzumiChino LSPosed 框架问题，请更新你的 LSPosed 到内测版。
