### ISSUE TITLE
[Bug] 字数统计功能无法关闭

### ISSUE THREAD

**Issue by Angel-GP** [cinit/QAuxiliary#1240]
### 复现步骤 / Steps to reproduce

1.打开聊天字数统计
2.个性签名被替换为红色Today Send: Text(0) TextWord(0) Pic(0)
3.字数统计功能无效，且无法关闭，卸载插件后恢复正常

### 预期行为 / Expected behaviour

正常情况下此功能应可以正常开关和使用
![IMG_20241113_224404](https://github.com/user-attachments/assets/35b239b0-32cc-486c-9359-a8531184d544)

### 实际行为 / Actual behaviour

字数统计功能无效，且无法关闭

### 你使用的Xposed框架 / Xposed Framework you used

opatch0.0.6

### 你使用的安卓系统版本 / Your Android version

14

### QQ(TIM) 版本 / QQ(TIM) Version

安卓9.1.10

### 模块版本 / Module Version

QAuxv-v1.5.4.r2483.eecf29b-universal

### 版本和其他要求 / Version and Other Requirements

- [ ] 我正在使用最新 CI 调试版本且启用详细日志 / I am using latest debug CI version of QAuxiliary and enable verbose log
- [X] 我使用的 QQ 是官方发布的正式版本，而非修改版或测试版 / The QQ I am using is an official release version, not a modified or beta version
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 日志 / Logs

1.5.4.r2483.eecf29b
QQ9.1.10(7858)
PID: 23557, UID: 10493
xyz.nextalone.hook.ChatWordsCount
isInitialized: false
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

### 补充说明（可选） / Additional information (optional)

日志无明显异常

**Comment by Angel-GP** [comment]
> 此功能不支持较新的版本, 推荐使用 统计聊天发送消息数量

目前只能通过降低qq版本解决吗，我不想使用这个功能但是他关闭不了，关闭之后仍然会显示

**Comment by HdShare** [comment]
> 目前只能通过降低qq版本解决吗，我不想使用这个功能但是他关闭不了，关闭之后仍然会显示

关闭仍然会显示，我明天修修看

**Comment by HdShare** [comment]
1.[聊天字数统计] 只适配老版本，对新版已无效
2.你的[Today Send: Text(0) TextWord(0) Pic(0)]是[统计聊天发送消息数量]设置的，对新版适配且可以正常关闭
