### ISSUE TITLE
[Bug] QQ底栏频道按钮无法去除

### ISSUE THREAD

**Issue by abcdefqwer1234** [cinit/QAuxiliary#1242]
### 复现步骤 / Steps to reproduce

1.打开:净化设置，杂项，精简底栏
2.勾选频道和一些其他选项
3.退出，重启QQ
4.频道按钮不消失

### 预期行为 / Expected behaviour

频道等底栏按钮都能被精减

### 实际行为 / Actual behaviour

![Screenshot_2024-11-15-18-34-27-122_com tencent mobileqq](https://github.com/user-attachments/assets/456ff2bd-9ea4-4c50-9a0d-4456d7a98057)
![Screenshot_2024-11-15-18-34-34-807_com tencent mobileqq](https://github.com/user-attachments/assets/575e847c-14b2-45c4-b6f7-5398e8340905)

### 你使用的Xposed框架 / Xposed Framework you used

lsposed 1.9.2(7024)zygisk

### 你使用的安卓系统版本 / Your Android version

a14

### QQ(TIM) 版本 / QQ(TIM) Version

qq9.1.0

### 模块版本 / Module Version

1.5.4.r2483.eecf29b(2483)

### 版本和其他要求 / Version and Other Requirements

- [X] 我正在使用最新 CI 调试版本且启用详细日志 / I am using latest debug CI version of QAuxiliary and enable verbose log
- [x] 我使用的 QQ 是官方发布的正式版本，而非修改版或测试版 / The QQ I am using is an official release version, not a modified or beta version
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 日志 / Logs

[SimplifyBottomTab-1731668566108.txt](https://github.com/user-attachments/files/17774493/SimplifyBottomTab-1731668566108.txt)

### 补充说明（可选） / Additional information (optional)

该功能精减其他按钮似乎都是可以的，只有频道不好使

**Comment by klxiaoniu** [comment]
@abcdefqwer1234 QQ自带这个设置
