### ISSUE TITLE
[功能请求] 阻止群文件闪退

### ISSUE THREAD

**Issue by EatHatsuneShallots** [cinit/QAuxiliary#1246]
### QQ(TIM) 版本 / QQ(TIM) Version

9.0.60

### 为什么你认为需要此功能

这个 Bug 十分严重，会影响从 8.9.63 到截止至 2024-11-18 版本的 NTQQ
主要症状：在拉取新聊天记录时，如果有会导致闪退的群文件消息（不清楚原理），则会在解析时闪退（不清楚是 Java 层闪退还是 Native 层闪退）
我目前没遇到这种消息，所以无法提供更详细的信息

### 具体功能需要 / Detailed features requirements

防止在拉取新聊天记录时，解析含有会导致闪退的群文件消息导致闪退
功能最低版本：8.9.63

**Comment by Cryolitia** [comment]
腾讯已经在客户端修了

**Comment by EatHatsuneShallots** [comment]
> 腾讯已经在服务端修了

貌似之前已经拉取到消息的客户端还会崩溃，不过新拉取的不会
原理是热补丁吗

**Comment by Cryolitia** [comment]
> 貌似之前已经拉取到消息的客户端还会崩溃，不过新拉取的不会 原理是热补丁吗

腾讯应该很快会想办法修复客户端的，说不定我们写的还没他们修的快。服务端现在已经屏蔽有问题的json了
