### ISSUE TITLE
[Bug] HyperOS2.0.6.0無法使用内置QAuxiliary的QQ

### ISSUE THREAD

**Issue by 0qxServer** [cinit/QAuxiliary#1249]
### 复现步骤 / Steps to reproduce

小米14更新hyper2之后，已经安装QA的QQ将无法使用
重新打包一个最新版的9.0.15的QQ和1.5.4版本
的QA或者打包一个最新版的9.0.10的QQ和1.5.4版本的QA
依然无法使用
卸载QQ并不安装任何插件的情况下QQ就可以恢复正常

### 预期行为 / Expected behaviour

正常打開

### 实际行为 / Actual behaviour

無法打開QQ，打開QQ閃退，提示當前應用的版本不兼容當前的系統

### 你使用的Xposed框架 / Xposed Framework you used

LSPatch0.6

### 你使用的安卓系统版本 / Your Android version

安卓15（小米hyperOS 2.0.6.0）

### QQ(TIM) 版本 / QQ(TIM) Version

9.0.10-9.0.15

### 模块版本 / Module Version

1.5.4.r2483.eecf29b

### 版本和其他要求 / Version and Other Requirements

- [ ] 我正在使用最新 CI 调试版本且启用详细日志 / I am using latest debug CI version of QAuxiliary and enable verbose log
- [X] 我使用的 QQ 是官方发布的正式版本，而非修改版或测试版 / The QQ I am using is an official release version, not a modified or beta version
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 日志 / Logs

無法導出任何log 因爲軟件無法打開

**Comment by cinit** [comment]
请使用支持 Android 15 的 patch 框架
