### ISSUE TITLE
IQOO手机及华为nova3手机使用太极·阴软件配合QAuxiliary，QA无法启动QQ、TIM，会闪退

### ISSUE THREAD

**Issue by Colyn2022** [cinit/QAuxiliary#125]
### Steps to reproduce/复现步骤

我使用IQOO第一代手机（Android12）和华为nova3（HarmonyOS第二代）安装太极APP，配合QQ和QAuixiary使用，发现初次打开QAuixiary时点击QQ或TIM会发生闪退，然后怎么点都没反应。就算太极取消优化也没作用。
--------
其次咨询一个问题：
QAuixiary官方说目前最新版[QAuxv-v1.2.11.r840.5b91f01]仅对仅指对 QQ v8.9.0 (3060) 和 QQ v8.9.1 (3068) 进行适配，意味着只能使用这两个版本的手机QQ吗？如果是的话官方大佬能分享一下这两个版本的QQ吗？我在网上找了半天没找到。腾讯不维护旧版本QQ，仅提供最新版QQ的下载途径，有哪个大佬能教教我怎么下载官方历史版本的QQ呀？非常感谢！
---------
祝好

### Expected behaviour/预期行为

正常加载QQ软件

### Actual behaviour/实际行为

第一次点击，QQ闪退；后续点击无反应。

### XPosed Framework you used/你使用的XP框架

太极·阴APP（太极129模块），目前最新版

### QQ(TIM)版本/QQ(TIM) Version

8.8.90.7975

### Module Version/模块版本

arm64-v8a

### Version requirement/版本要求

- [ ] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

直接打不开QQ，因此点击故障排除无反应。

**Comment by Colyn2022** [comment]
- 手机：IQOO第一代、华为nova3
- 系统:IQOO(Android12)，华为(HarmonyOS第二代)
- QQ：8.8.90
- QAuixiary：v1.2.11.r840.5b91f01
- 太极APP：承影9.1.2.07052050
- 太极APP内核：太极·阴内核129
- 太极APP适配引擎版本号：8164
- 宿主：QQ(arm64-v8a)、TIM(armeabi-v7a)
- QAuixiary安装包：[QAuxv-v1.2.11.r840.5b91f01-armAll.apk](https://github.com/cinit/QAuxiliary/releases/download/v1.2.11/QAuxv-v1.2.11.r840.5b91f01-armAll.apk)

**Comment by duzhaokun123** [comment]
啊两个手机 那分开提 issue

**Comment by Colyn2022** [comment]
大佬能教我一下怎么提取log吗？我也是第一次接触这个框架和模块。
我分别用了2部手机，安装相同版本的软件，均会发生这种现象

**Comment by duzhaokun123** [comment]
> 大佬能教我一下怎么提取log吗？

1. adb logcat > log.txt
2. 复现崩溃
3. CTRL C

**Comment by Colyn2022** [comment]
大佬请过目：https://bafybeid4sj7iydshe74qu3545ceiypyqgozsvurxh32tazmgfu7w5g34va.ipfs.infura-ipfs.io/log.html

**Comment by Colyn2022** [comment]
等一下，搞错了，这个是以前的报错目录，抱歉！

**Comment by duzhaokun123** [comment]
> 其次咨询一个问题：
QAuixiary官方说目前最新版[QAuxv-v1.2.11.r840.5b91f01]仅对仅指对 QQ v8.9.0 (3060) 和 QQ v8.9.1 (3068) 进行适配，意味着只能使用这两个版本的手机QQ吗？如果是的话官方大佬能分享一下这两个版本的QQ吗？我在网上找了半天没找到。腾讯不维护旧版本QQ，仅提供最新版QQ的下载途径，有哪个大佬能教教我怎么下载官方历史版本的QQ呀？非常感谢！

可以使用其他版本的 QQ 但不保证功能正常

**Comment by duzhaokun123** [comment]
> 有哪个大佬能教教我怎么下载官方历史版本的QQ呀？

可以在 https://m.wandoujia.com/apps/566489/history 和  https://t.me/QQUpdates 找到 QQ 历史版本

**Comment by Colyn2022** [comment]
大佬请过目，久等了！
https://bafybeidabkrgqaygs4vqngubmitxquhkxexif5qmgc7mtgev7ux3qwf3ui.ipfs.infura-ipfs.io/log.txt

**Comment by Colyn2022** [comment]
我大概的操作流程就是，先在太极APP里面添加QQ和QAuixiary，太极APP会先让卸载这两个软件，然后太极APP会自动安装这2个软件；然后我在太极APP的“模块管理”中把QAuixiary勾选，进入QAuixiary就会显示绿色激活，这个时候我点击QAuixiary的模块中的QQ或者TIM，就会闪退，然后怎么点都没反应了，最后我点“故障排查”相关的按钮也没有反应。

**Comment by duzhaokun123** [comment]
@Colyn2022 你在太极里加 qa?
你以前有没有通过太极用过 qa 他是否正常工作

**Comment by Colyn2022** [comment]
还没有试欸，我一会试试看。正常来说不是要在太极里面添加qa才能使用qa吗？我是免root的

**Comment by duzhaokun123** [comment]
@Colyn2022 > 正常来说不是要在太极里面添加qa才能使用qa吗？

正常来说你不应该修改 qa

你之前有通过太极使用其他模块吗? 也是将他们添加到太极里吗? 如果那么做了 他们正常工作吗

**Comment by Colyn2022** [comment]
我试试┗|｀O′|┛ 嗷~~，谢谢大佬啦

**Comment by Colyn2022** [comment]
有了有了呜呜，谢谢大佬，我是笨蛋，原来我操作上有问题，确实不应该在太极里添加QA的，辛苦大佬啦！！！！
这个issues可以彻底关闭了呜呜，感谢大佬，今天学到不少知识！
