### ISSUE TITLE
[问题] 登录状态频繁失效

### ISSUE THREAD

**Issue by ganchengcaiyue** [cinit/QAuxiliary#1252]
### 复现步骤 / Steps to reproduce

安装模块登录QQ等待一段时间（约一小时）会强制下线重新验证登录

### 预期行为 / Expected behaviour

减少登录失效

### 实际行为 / Actual behaviour

![144986F27D18CAC8E5519A7B427D88D5](https://github.com/user-attachments/assets/5a35ce1a-c9eb-4268-ae66-7d20b11e0b37)

### 你使用的Xposed框架 / Xposed Framework you used

OPatch

### 你使用的安卓系统版本 / Your Android version

14

### QQ(TIM) 版本 / QQ(TIM) Version

9.1.16

### 模块版本 / Module Version

1.5.4

### 版本和其他要求 / Version and Other Requirements

- [X] 我正在使用最新 CI 调试版本且启用详细日志 / I am using latest debug CI version of QAuxiliary and enable verbose log
- [X] 我使用的 QQ 是官方发布的正式版本，而非修改版或测试版 / The QQ I am using is an official release version, not a modified or beta version
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 日志 / Logs

功能无问题

**Comment by klxiaoniu** [comment]
@ganchengcaiyue https://t.me/QAuxiliary/316

**Comment by dongguacc** [comment]
我也遇到了这样的问题，但是我没有找到解决方法，你找到了吗？

**Comment by ganchengcaiyue** [comment]
@dongguacc 用没有安装模块的QQ正常使用2星星期及以上之后再用回模块
