### ISSUE TITLE
[Bug] Tim4.0.95的消息显示ID和时间

### ISSUE THREAD

**Issue by yuangqian108** [cinit/QAuxiliary#1254]
### 复现步骤 / Steps to reproduce

tim4.0.95的消息显示id和时间功能已完全失效。但故障排查界面显示该功能正常

### 预期行为 / Expected behaviour

消息显示id和时间功能正常显示。

### 实际行为 / Actual behaviour

 
![IMG_20241124_230940](https://github.com/user-attachments/assets/03cf8e0e-fe6a-4635-bc13-cdd054c82750)
![Screenshot_2024-11-24-23-03-07-611_com tencent tim-edit](https://github.com/user-attachments/assets/50766113-a4dc-4ca9-987a-0aad9a8a9890)

### 你使用的Xposed框架 / Xposed Framework you used

yapatch

### 你使用的安卓系统版本 / Your Android version

14

### QQ(TIM) 版本 / QQ(TIM) Version

tim4.0.95

### 模块版本 / Module Version

1.5.4.r2532.2787164

### 版本和其他要求 / Version and Other Requirements

- [X] 我正在使用最新 CI 调试版本且启用详细日志 / I am using latest debug CI version of QAuxiliary and enable verbose log
- [X] 我使用的 QQ 是官方发布的正式版本，而非修改版或测试版 / The QQ I am using is an official release version, not a modified or beta version
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 日志 / Logs

因功能异常列表显示功能正常，故无日志。
![IMG_20241124_230940](https://github.com/user-attachments/assets/6fc82662-3f9d-437f-aa06-2d41b534bf4d)

### 补充说明（可选） / Additional information (optional)

无

**Comment by Ashestar** [comment]
请问为什么我tim跟你一样版本，安装后没有在设置里看到模块入口

**Comment by SinGo01** [comment]
批量撤回消息也是如此

**Comment by Prurite** [comment]
TIM 4.0.95 显然不符合

> 我使用的 QQ 是官方发布的正式版本，而非修改版或测试版 / The QQ I am using is an official release version, not a modified or beta version

一条吧

**Comment by Narut0123** [comment]
> 请问为什么我tim跟你一样版本，安装后没有在设置里看到模块入口

TIM安卓版v4.0.95目前要这样操作：打开QAuxiliary APP，点击“模块设置”方框里的“TIM”，就能进入模块设置页面了
