### ISSUE TITLE
更新originos5之后，使用npatch安装的模块打开会闪退

### ISSUE THREAD

**Issue by semorai2miku** [cinit/QAuxiliary#1260]
### 复现步骤 / Steps to reproduce

1.使用originos5
2.使用npatch

### 预期行为 / Expected behaviour

正常打开

### 实际行为 / Actual behaviour

闪退

### 你使用的Xposed框架 / Xposed Framework you used

NPatch

### 你使用的安卓系统版本 / Your Android version

OriginOS 5 安卓15

### QQ(TIM) 版本 / QQ(TIM) Version

9.1.20

### 模块版本 / Module Version

1.5.5

### 版本和其他要求 / Version and Other Requirements

- [ ] 我正在使用最新 CI 调试版本且启用详细日志 / I am using latest debug CI version of QAuxiliary and enable verbose log
- [X] 我使用的 QQ 是官方发布的正式版本，而非修改版或测试版 / The QQ I am using is an official release version, not a modified or beta version
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 日志 / Logs

闪退无日志

**Comment by EatHatsuneShallots** [comment]
请提供确切的 Android 版本
如果是 Android 15 (API 35) 及以上的话，的话，可以参考 [这个](https://github.com/cinit/QAuxiliary/issues/1249#issuecomment-2485520372)
