### ISSUE TITLE
[功能请求] 拜托兼容一下澎湃2.0

### ISSUE THREAD

**Issue by SainT194555** [cinit/QAuxiliary#1263]
### QQ(TIM) 版本 / QQ(TIM) Version

9.0

### 为什么你认为需要此功能

小米更新到澎湃2.0系统，用插件会提示未适配当前安卓系统版本，造成闪退。

### 具体功能需要 / Detailed features requirements

不知道是不是兼容问题，可以看一下吗

**Comment by klxiaoniu** [comment]
https://github.com/cinit/QAuxiliary/issues/1249#issuecomment-2485520372

**Comment by klxiaoniu** [comment]
@SainT194555 https://t.me/QToolCI/405
