### ISSUE TITLE
[功能请求] Tim NT 平板登录失效

### ISSUE THREAD

**Issue by LiamWang2002** [cinit/QAuxiliary#1266]
### 复现步骤 / Steps to reproduce

1.实验性功能
2.强制平板模式

### 预期行为 / Expected behaviour

Tim NT 平板登录 

### 实际行为 / Actual behaviour

故障排查-功能异常列表 强制平板模式 提示异常
报错如下：
1.5.5.r2544.405f777
TIM4.0.96(4010)
PID: 19011, UID: 10002
cc.ioctl.hook.experimental.ForcePadMode
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: false
isPreparationRequired: false
errors: 0

### 你使用的Xposed框架 / Xposed Framework you used

Lsposed 1.9.2(7181)

### 你使用的安卓系统版本 / Your Android version

15

### QQ(TIM) 版本 / QQ(TIM) Version

Tim 4.0.96

### 模块版本 / Module Version

1.5.5.r2544.405f777

### 版本和其他要求 / Version and Other Requirements

- [X] 我正在使用最新 CI 调试版本且启用详细日志 / I am using latest debug CI version of QAuxiliary and enable verbose log
- [X] 我使用的 QQ 是官方发布的正式版本，而非修改版或测试版 / The QQ I am using is an official release version, not a modified or beta version
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 日志 / Logs

1.5.5.r2544.405f777
TIM4.0.96(4010)
PID: 19011, UID: 10002
cc.ioctl.hook.experimental.ForcePadMode
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: false
isPreparationRequired: false
errors: 0

**Comment by HdShare** [comment]
预期行为 TIM 与 QQ 同时登录?
