### ISSUE TITLE
[Bug] 9.1.16下打开“以图片方式打开闪照”导致聊天界面卡顿

### ISSUE THREAD

**Issue by KemurihinoGatsu** [cinit/QAuxiliary#1269]
### 复现步骤 / Steps to reproduce

1.打开“以图片方式打开闪照”
2.进入聊天界面
3.加载聊天记录慢，滑动出现卡顿

### 预期行为 / Expected behaviour

正常显示聊天记录，滑动正常

### 实际行为 / Actual behaviour

聊天记录加载慢（长时间“消息接收中”），加载完成后滑动卡顿

### 你使用的Xposed框架 / Xposed Framework you used

lspatch

### 你使用的安卓系统版本 / Your Android version

15

### QQ(TIM) 版本 / QQ(TIM) Version

9.1.16

### 模块版本 / Module Version

1.5.5

### 版本和其他要求 / Version and Other Requirements

- [X] 我正在使用最新 CI 调试版本且启用详细日志 / I am using latest debug CI version of QAuxiliary and enable verbose log
- [X] 我使用的 QQ 是官方发布的正式版本，而非修改版或测试版 / The QQ I am using is an official release version, not a modified or beta version
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 日志 / Logs

[Uploading FlashPicHook-1733984895533.txt…]()

**Comment by EatHatsuneShallots** [comment]
有文件未上传成功，请重新上传

**Comment by KemurihinoGatsu** [comment]
[FlashPicHook-1733984895533.txt](https://github.com/user-attachments/files/18106673/FlashPicHook-1733984895533.txt)

**Comment by HdShare** [comment]
安卓15框架问题，请自行更换
