### ISSUE TITLE
[Bug] 安卓15下不显示消息id和时间

### ISSUE THREAD

**Issue by AVMLOVER** [cinit/QAuxiliary#1270]
### 复现步骤 / Steps to reproduce

打开消息id功能

### 预期行为 / Expected behaviour

显示消息id和撤回消息

### 实际行为 / Actual behaviour

不显示消息id，时间，防撤回可以拦截但是也不显示“尝试撤回消息”

### 你使用的Xposed框架 / Xposed Framework you used

lspatch 0.7

### 你使用的安卓系统版本 / Your Android version

15

### QQ(TIM) 版本 / QQ(TIM) Version

9.1.25

### 模块版本 / Module Version

1.5.5.r2550.dda17e2(2550)

### 版本和其他要求 / Version and Other Requirements

- [X] 我正在使用最新 CI 调试版本且启用详细日志 / I am using latest debug CI version of QAuxiliary and enable verbose log
- [X] 我使用的 QQ 是官方发布的正式版本，而非修改版或测试版 / The QQ I am using is an official release version, not a modified or beta version
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 日志 / Logs

  [0]PicElement
com.tencent.mobileqq.aio.msg.AIOMsgElementType.PicElement
= (void*)0
  [6]AbstractQQCustomMenuItem
com.tencent.qqnt.aio.menu.ui.AbstractQQCustomMenuItem
= Lcom/tencent/qqnt/aio/menu/ui/d;->toString()Ljava/lang/String;
  [8]AIOPictureView
com.tencent.mobileqq.richmediabrowser.view.AIOPictureView
= com.tencent.mobileqq.richmediabrowser.view.AIOPictureView
  [9]AIOUtils
com.tencent.mobileqq.activity.aio.AIOUtils
= (void*)0
  [10]AbstractGalleryScene
com.tencent.common.galleryactivity.AbstractGalleryScene
= (void*)0
  [11]AppConstants
com.tencent.mobileqq.app.AppConstants
= com.tencent.mobileqq.app.AppConstants
  [12]ArkAppItemBubbleBuilder
com.tencent.mobileqq.activity.aio.item.ArkAppItemBubbleBuilder
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [13]AvatarUtil
com.tencent.mobileqq.avatar.utils.AvatarUtil
= (void*)0
  [14]BasePicDownloadProcessor
com.tencent.mobileqq.transfile.BasePicDownloadProcessor
= com.tencent.mobileqq.transfile.BasePicDownloadProcessor
  [15]CustomWidgetUtil
com.tencent.widget.CustomWidgetUtil
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [16]DialogUtil
com.tencent.mobileqq.utils.DialogUtil
= com.tencent.mobileqq.utils.DialogUtil
  [17]ChatActivityFacade
com.tencent.mobileqq.activity.ChatActivityFacade
= com.tencent.mobileqq.activity.ChatActivityFacade
  [18]FaceManager
com.tencent.mobileqq.app.face.FaceManager
= (void*)0
  [19]FavEmoConstant
com.tencent.mobileqq.emosm.favroaming.FavEmoConstant
= com.tencent.mobileqq.emosm.favroaming.FavEmoConstant
  [20]FlashPicHelper
com.tencent.mobileqq.app.FlashPicHelper
= Lcom/tencent/mobileqq/app/av;->e(Lcom/tencent/mobileqq/data/MessageRecord;Z)V
  [21]FrameControllerInjectImpl
com.tencent.mobileqq.activity.framebusiness.controllerinject.FrameControllerInjectImpl
= com.tencent.mobileqq.activity.framebusiness.controllerinject.FrameControllerInjectImpl
  [22]GalleryBaseScene
com.tencent.mobileqq.gallery.view.GalleryBaseScene
= (void*)0
  [23]TroopAppShortcutDrawer
com.tencent.mobileqq.activity.aio.drawer.TroopAppShortcutDrawer
= com.tencent.mobileqq.activity.aio.drawer.TroopAppShortcutDrawer
  [24]GuildArkHelper
com.tencent.mobileqq.guild.chatpie.helper.GuildArkHelper
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [25]GuildHelperProvider
com.tencent.mobileqq.guild.chatpie.GuildHelperProvider
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [26]HttpDownloader
com.tencent.mobileqq.transfile.HttpDownloader
= com.tencent.mobileqq.transfile.HttpDownloader
  [27]IntimateInfoChatDrawer
com.tencent.mobileqq.activity.aio.drawer.IntimateInfoChatDrawer
= (void*)0
  [28]ItemBuilderFactory
com.tencent.mobileqq.activity.aio.item.ItemBuilderFactory
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [29]MessageCache
com.tencent.mobileqq.service.message.MessageCache
= Lcom/tencent/mobileqq/service/h/e;-><clinit>()V
  [30]MessageRecordFactory
com.tencent.mobileqq.service.message.MessageRecordFactory
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [31]MultiMsgManager
com.tencent.mobileqq.multimsg.MultiMsgManager
= com.tencent.mobileqq.multimsg.MultiMsgManager
  [32]OnlinePushPbPushTransMsg
com.tencent.mobileqq.app.handler.receivesuccess.OnlinePushPbPushTransMsg
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [33]PicEmoticonInfo
com.tencent.mobileqq.emoticonview.PicEmoticonInfo
= com.tencent.mobileqq.emoticonview.PicEmoticonInfo
  [34]PngFrameUtil
com.tencent.mobileqq.magicface.drawable.PngFrameUtil
= (void*)0
  [35]PopOutEmoticonUtil
com.tencent.mobileqq.popanim.util.PopOutEmoticonUtil
= (void*)0
  [36]MsgNotification
cooperation.qzone.push.MsgNotification
= cooperation.qzone.push.MsgNotification
  [37]ReplyMsgSender
com.tencent.mobileqq.replymsg.ReplyMsgSender
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [38]ReplyMsgUtils
com.tencent.mobileqq.activity.aio.reply.ReplyMsgUtils
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [39]ScreenShotHelper
com.tencent.mobileqq.screendetect.ScreenShotHelper
= com.tencent.mobileqq.screendetect.ScreenShotHelper
  [40]SimpleUIUtil
com.tencent.mobileqq.theme.SimpleUIUtil
= (void*)0
  [41]SystemMessageProcessor
com.tencent.mobileqq.app.message.SystemMessageProcessor
= Lcom/tencent/mobileqq/app/message/n;->b0(Lcom/tencent/qphone/base/remote/FromServiceMsg;Lcom/tencent/mobileqq/app/FriendsManager;Ljava/util/List;IILcom/tencent/mobileqq/newfriend/api/INewFriendService;Ljava/lang/String;J)V
  [42]TestStructMsg
com.tencent.mobileqq.structmsg.TestStructMsg
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [43]TimeFormatterUtils
com.tencent.mobileqq.utils.TimeFormatterUtils
= (void*)0
  [44]TroopGiftUtil
com.tencent.mobileqq.troop.utils.TroopGiftUtil
= (void*)0
  [45]ZipUtils
com.tencent.biz.common.util.ZipUtils
= com.tencent.biz.common.util.ZipUtils
  [49]DefaultFileModel
com.tencent.mobileqq.filemanager.fileviewer.model.DefaultFileModel
= Lcom/tencent/mobileqq/filemanager/fileviewer/model/g;->x0(ILjava/lang/String;)V
  [52]EmotcationConstants
com.tencent.mobileqq.text.EmotcationConstants
= com.tencent.mobileqq.text.EmotcationConstants
  [53]ForwardSendPicUtil
com.tencent.mobileqq.utils.ForwardSendPicUtil
= com.tencent.mobileqq.utils.ForwardSendPicUtil
  [63]

= (void*)0
  [64]

= Lcom/tencent/mobileqq/aio/input/multiselect/b;->r()V
  [65]toBottomIntent
com.tencent.mobileqq.aio.input.multiselect.c.toBottomIntent
= Lcom/tencent/mobileqq/aio/input/multiselect/c$f;->toString()Ljava/lang/String;
  [76]CustomWidgetUtil
com.tencent.widget.CustomWidgetUtil
= Lcom/tencent/widget/b;->a(Lcom/tencent/mobileqq/quibadge/QUIBadge;IIILjava/lang/String;)V
  [94]

= (void*)0
  [103]

= (void*)0
  [105]EditTroopMemberNickService$EmojiFilter;
Lcom.tencent.mobileqq.activity.editservice.EditTroopMemberNickService$EmojiFilter;
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [107]LoadPropertiesUtils
com.tencent.smtt.utils.LoadPropertiesUtils
= (void*)0
  [108]activity
com.tencent.qqnt.aio.activity
= (void*)0
  [112]

= (void*)0
  [115]

= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [119]

= (void*)0
  [1]sendMsg
com.tencent.mobileqq.aio.input.sendmsg.AIOSendMsgVMDelegate.sendMsg
= Lcom/tencent/mobileqq/aio/input/sendmsg/AIOSendMsgVMDelegate;->l0(Ljava/util/List;Landroid/os/Bundle;Ljava/lang/Long;Ljava/lang/String;)V
  [2]AIOTextElementCtor
com.tencent.mobileqq.aio.msg.AIOMsgElement.AIOTextElementCtor
= (void*)0
  [3]AIOTitleVB
com.tencent.mobileqq.aio.title.AIOTitleVB
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [4]AIO_Create_QQNT
AIO_Create_QQNT
= Lcom/tencent/aio/base/chat/ChatPie;->v(Landroid/os/Bundle;Lcom/tencent/aio/main/fragment/ChatFragment;Lkotlin/jvm/functions/Function1;)V
  [5]

= Lcom/tencent/mobileqq/aio/input/simpleui/AIOInputSimpleUIVBDelegate;->C(Lcom/tencent/mobileqq/aio/input/c/b/a;)V
  [7]BaseListenTogetherPanel
com.tencent.mobileqq.listentogether.ui.BaseListenTogetherPanel
= com.tencent.mobileqq.listentogether.ui.BaseListenTogetherPanel
  [46]ChatPanel_InitPanel_QQNT
ChatPanel_InitPanel_QQNT
= Lcom/tencent/mobileqq/aio/input/simpleui/AIOInputSimpleUIVBDelegate;->A()V
  [47]

= (void*)0
  [48]

= Lcom/tencent/mobileqq/copyprompt/CopyPromptHelper;->f(Ljava/lang/String;)V
  [50]LiteActionBottomBar;
Lcom.tencent.mobileqq.aio.bottombar.c2c.LiteActionBottomBar;
= (void*)0
  [51]

= (void*)0
  [54]NotifyIdManager
com.tencent.util.notification.NotifyIdManager
= (void*)0
  [55]Guild_Emo_Btn_Create_QQNT
Guild_Emo_Btn_Create_QQNT
= Lcom/tencent/guild/aio/component/emoji/b;->onCreateView(Lcom/tencent/q0/a/c/a;)Landroid/view/View;
  [56]PickerBottomBarPart
Lcom.tencent.qqnt.qbasealbum.album.view.PickerBottomBarPart
= Lcom/tencent/qqnt/qbasealbum/album/view/PickerBottomBarPart$b;->a(Ljava/lang/Boolean;)V
  [57]PhotoListPanel
Lcom.tencent.mobileqq.activity.aio.photo.PhotoListPanel
= Lcom/tencent/mobileqq/activity/aio/photo/PhotoListPanel;->T(Z)V
  [58]VasADBannerManager
cooperation.vip.qqbanner.manager.VasADBannerManager
= cooperation.vip.qqbanner.manager.VasADBannerManager
  [59]message
com.tencent.imcore.message
= Lcom/tencent/imcore/message/af$f;->k(Ljava/util/ArrayList;LOnlinePushPack/MsgInfo;)Z
  [60]AIOFileViewer
Lcom.tencent.mobileqq.aio.msglist.holder.component.file.AIOFileViewer
= (void*)0
  [61]TroopShortcutVB;
Lcom.tencent.mobileqq.troop.shortcut.aio.TroopShortcutVB;
= com.tencent.mobileqq.troop.shortcut.aio.TroopShortcutVB
  [62]TroopAppShortcutBarHelper;
Lcom.tencent.mobileqq.activity.aio.helper.TroopAppShortcutBarHelper;
= com.tencent.mobileqq.activity.aio.helper.TroopAppShortcutBarHelper
  [66]AtPanel
com.tencent.mobileqq.troop.quickat.ui.AtPanel
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [67]AtPanel
com.tencent.mobileqq.troop.quickat.ui.AtPanel
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [68]BaseChatPie
com.tencent.mobileqq.activity.BaseChatPie
= (void*)0
  [69]BaseChatPie
com.tencent.mobileqq.activity.BaseChatPie
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [70]BaseChatPie
com.tencent.mobileqq.activity.BaseChatPie
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [71]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= (void*)0
  [72]ChatActivityFacade
com.tencent.mobileqq.activity.ChatActivityFacade
= com.tencent.mobileqq.activity.ChatActivityFacade
  [73]ContactUtils
com.tencent.mobileqq.utils.ContactUtils
= Lcom/tencent/mobileqq/utils/ax;->e(Lmqq/app/AppRuntime;Ljava/lang/String;Z)Ljava/lang/String;
  [74]ContactUtils
com.tencent.mobileqq.utils.ContactUtils
= Lcom/tencent/mobileqq/utils/ax;->l(Lcom/tencent/common/app/business/BaseQQAppInterface;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
  [75]Conversation
com.tencent.mobileqq.activity.home.Conversation
= Lcom/tencent/mobileqq/activity/home/Conversation;->notifyCreate()V
  [77]FriendChatPie
com.tencent.mobileqq.activity.aio.core.FriendChatPie
= (void*)0
  [78]FriendsStatusUtil
com.tencent.mobileqq.app.utils.FriendsStatusUtil
= Lcom/tencent/mobileqq/app/utils/FriendsStatusUtil;->j(Lcom/tencent/mobileqq/app/QQAppInterface;Ljava/lang/String;I)Z
  [79]LeftSwipeReplyHelper
com.tencent.mobileqq.bubble.LeftSwipeReplyHelper
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [80]PadUtil
com.tencent.common.config.PadUtil
= (void*)0
  [81]PhotoListPanel
com.tencent.mobileqq.activity.aio.photo.PhotoListPanel
= Lcom/tencent/mobileqq/activity/aio/photo/PhotoListPanel;->T(Z)V
  [82]ProfileCardUtil
com.tencent.mobileqq.util.ProfileCardUtil
= com.tencent.mobileqq.util.ProfileCardUtil
  [83]QQSettingMe
com.tencent.mobileqq.activity.QQSettingMe
= (void*)0
  [84]QQSettingMe
com.tencent.mobileqq.activity.QQSettingMe
= (void*)0
  [85]

= (void*)0
  [86]Scene
com.tencent.mobileqq.troopAddFrd.Scene
= (void*)0
  [87]TroopAppShortcutBarHelper
com.tencent.mobileqq.activity.aio.helper.TroopAppShortcutBarHelper
= com.tencent.mobileqq.activity.aio.helper.TroopAppShortcutBarHelper
  [88]TroopChatPie
com.tencent.mobileqq.activity.aio.core.TroopChatPie
= (void*)0
  [89]VasProfileTemplateController
com.tencent.mobileqq.profilecard.vas.VasProfileTemplateController
= com.tencent.mobileqq.profilecard.vas.VasProfileTemplateController
  [90]VipUtils
com.tencent.mobileqq.utils.VipUtils
= Lcom/tencent/mobileqq/vip/r;->getPrivilegeFlags(Ljava/lang/String;)I
  [91]VipUtils
com.tencent.mobileqq.utils.VipUtils
= (void*)0
  [92]WebSecurityPluginV2$
com.tencent.mobileqq.webview.WebSecurityPluginV2$
= (void*)0
  [93]PaiYiPaiHandler
com.tencent.mobileqq.paiyipai.PaiYiPaiHandler
= Lcom/tencent/mobileqq/paiyipai/PaiYiPaiHandler;->P2(Ljava/lang/String;)Z
  [95]PushNotificationManager
com.tencent.mobileqq.managers.PushNotificationManager
= com.tencent.mobileqq.managers.PushNotificationManager
  [96]QQValuePagView
com.tencent.mobileqq.vas.qqvaluecard.view.QQValuePagView
= com.tencent.mobileqq.vas.qqvaluecard.view.QQValuePagView
  [97]QZoneFeedxTopEntranceManagerView
com.qzone.reborn.feedx.widget.entrance.QZoneFeedxTopEntranceManagerView
= com.qzone.reborn.feedx.widget.entrance.QZoneFeedxTopEntranceManagerView
  [98]

= (void*)0
  [99]AudioTransitionAnimManager;
Lcom.tencent.mobileqq.activity.aio.audiopanel.AudioTransitionAnimManager;
= com.tencent.mobileqq.activity.aio.audiopanel.AudioTransitionAnimManager
  [100]

= Lcom/tencent/mobileqq/aio/input/reply/c;->p(Lcom/tencent/mobileqq/aio/msg/AIOMsgItem;)V
  [101]

= (void*)0
  [102]TroopGuildChatPie
com.tencent.mobileqq.troop.guild.TroopGuildChatPie
= (void*)0
  [104]

= (void*)0
  [106]p
com.tencent.mobileqq.vas.p
= Lcom/tencent/mobileqq/vas/s;->a(Ljava/util/HashMap;Lcom/tencent/qqnt/kernelpublic/nativeinterface/Contact;I)V
  [109]AIO_Create_QQNT
AIO_Create_QQNT
= Lcom/tencent/aio/base/chat/ChatPie;->w()V
  [110]

= (void*)0
  [111]

= Lcom/tencent/mobileqq/filebrowser/FileBrowserActivity$e;->onItemClick(Lcom/tencent/mobileqq/utils/ShareActionSheetBuilder$ActionSheetItem;Lcom/tencent/mobileqq/widget/share/ShareActionSheet;)V
  [113]GrowHalfLayerHelper
cooperation.vip.ad.GrowHalfLayerHelper
= cooperation.vip.ad.GrowHalfLayerHelper
  [114]

= (void*)0
  [116]

= (void*)0
  [117]

= (void*)0
  [118]

= (void*)0
  [120]AIOAvatarContentComponent
com.tencent.mobileqq.aio.msglist.holder.component.avatar.AIOAvatarContentComponent
= com.tencent.mobileqq.aio.msglist.holder.component.avatar.AIOAvatarContentComponent
  [121]AIOPictureView
com.tencent.mobileqq.activity.aio.photo.AIOPictureView
= (void*)0
  [122]AIOPictureView
com.tencent.mobileqq.activity.aio.photo.AIOPictureView
= (void*)0
  [123]TextItemBuilder
com.tencent.mobileqq.activity.aio.item.TextItemBuilder
= (void*)0
  [124]

= (void*)0
  [125]TextMsgItem
com.tencent.mobileqq.aio.msg.TextMsgItem
= Lcom/tencent/mobileqq/aio/msg/s;->n2()Ljava/lang/CharSequence;
  [40001]ReplyNoAtHook
com/tencent/mobileqq/activity/aio/rebuild/input/d
  [40002]ChatWordsCount
nyn
  [40003]SortAtPanel.sessionInfoTroopUin
f
  [40004]RemovePlayTogether.ClockInEntryHelper
n
  [40005]QQMessageFacade
B2
  [40006]SimplifyQQSettingMe::MidContentName
f0
  [40007]RemovePlayTogether.TogetherControlHelper
q

### 补充说明（可选） / Additional information (optional)

升级安卓15后，重装lspatch+模块后出现问题

**Comment by EatHatsuneShallots** [comment]
https://github.com/cinit/QAuxiliary/issues/1249#issuecomment-2485520372

**Comment by AVMLOVER** [comment]
> [#1249 (comment)](https://github.com/cinit/QAuxiliary/issues/1249#issuecomment-2485520372)

我使用了，要不然根本打不开，就是功能出问题了
