### ISSUE TITLE
[Bug] 不能以图片方式打开闪照

### ISSUE THREAD

**Issue by wuyyyhao** [cinit/QAuxiliary#1272]
### 复现步骤 / Steps to reproduce

1.打开以图片打开闪照
![Screenshot_2024-12-15-16-03-56-20_cb819d8fa60af39fdbc84f6c72b4cf1c](https://github.com/user-attachments/assets/8db8eb7a-5e96-4219-8b3e-3039a9020eaf)
2.打开收到的闪照

### 预期行为 / Expected behaviour

以图片方式打开闪照

### 实际行为 / Actual behaviour

以默认方式打开闪照，查看后被销毁
![Screenshot_2024-12-15-16-05-29-62_cb819d8fa60af39fdbc84f6c72b4cf1c](https://github.com/user-attachments/assets/1e1f30fd-0e18-452e-bbfc-4cbeaad2b987)
![Screenshot_2024-12-15-16-07-38-59_cb819d8fa60af39fdbc84f6c72b4cf1c](https://github.com/user-attachments/assets/c32f32ca-708a-4c84-9308-247ed3216000)

### 你使用的Xposed框架 / Xposed Framework you used

ONPatch

### 你使用的安卓系统版本 / Your Android version

13

### QQ(TIM) 版本 / QQ(TIM) Version

Tim4.0.97(4011)

### 模块版本 / Module Version

1.5.5.r2540.224cfe1(2540)

### 版本和其他要求 / Version and Other Requirements

- [X] 我正在使用最新 CI 调试版本且启用详细日志 / I am using latest debug CI version of QAuxiliary and enable verbose log
- [X] 我使用的 QQ 是官方发布的正式版本，而非修改版或测试版 / The QQ I am using is an official release version, not a modified or beta version
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 日志 / Logs

未见明显错误
1.5.5.r2540.224cfe1
TIM4.0.97(4011)
PID: 28162, UID: 10391
cc.ioctl.hook.msg.FlashPicHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by HdShare** [comment]
r2540 正在使用最新 CI 调试版本?

r2549 已修复，且最新为 r2554 版

**Comment by MonkeyDcm** [comment]
Releases只有r2540，没有看到actions有了新版本
