### ISSUE TITLE
[Bug] 更新小米澎湃OS后qq登录提示appid is invalid

### ISSUE THREAD

**Issue by STGOZ** [cinit/QAuxiliary#1273]
### 复现步骤 / Steps to reproduce

1.打开qq
2.输入账号密码前提示appid is invalid，但仍可以操作
3.点击登录后无限转圈或直接卡死

### 预期行为 / Expected behaviour

正常登录使用

### 实际行为 / Actual behaviour

打开提示appid is invalid无法正常登录

### 你使用的Xposed框架 / Xposed Framework you used

onpatch

### 你使用的安卓系统版本 / Your Android version

安卓15

### QQ(TIM) 版本 / QQ(TIM) Version

9.1.25

### 模块版本 / Module Version

1.5.5.r2540.24cfe1

### 版本和其他要求 / Version and Other Requirements

- [X] 我正在使用最新 CI 调试版本且启用详细日志 / I am using latest debug CI version of QAuxiliary and enable verbose log
- [X] 我使用的 QQ 是官方发布的正式版本，而非修改版或测试版 / The QQ I am using is an official release version, not a modified or beta version
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 日志 / Logs

无，使用的是模块内置功能

**Comment by Hicores** [comment]
你框架问题

**Comment by wlwxj** [comment]
我也是这样，但是我是tim，你解决了吗
