### ISSUE TITLE
[Bug] Zygisk LSPosed 1.9.3（mod）下无法运行

### ISSUE THREAD

**Issue by KannaZeng** [cinit/QAuxiliary#1275]
### 复现步骤 / Steps to reproduce

1.安装狐狸面具。2.安装LSP1.9.3 Zygisk。3.安装模块并正常启用。

### 预期行为 / Expected behaviour

打开QQ后模块正常运行。

### 实际行为 / Actual behaviour

模块没有运行。

### 你使用的Xposed框架 / Xposed Framework you used

Zygisk LSPosed 1.9.3

### 你使用的安卓系统版本 / Your Android version

13，LG V60 40G

### QQ(TIM) 版本 / QQ(TIM) Version

9.0.15

### 模块版本 / Module Version

1.5.5.r2540

### 版本和其他要求 / Version and Other Requirements

- [ ] 我正在使用最新 CI 调试版本且启用详细日志 / I am using latest debug CI version of QAuxiliary and enable verbose log
- [X] 我使用的 QQ 是官方发布的正式版本，而非修改版或测试版 / The QQ I am using is an official release version, not a modified or beta version
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 日志 / Logs

我尝试按照操作步骤进入故障排查，但是无效

**Comment by HdShare** [comment]
框架问题，尝试更换内测版 LSPosed 
或 https://github.com/re-zero001/LSPosed-Irena/

**Comment by KannaZeng** [comment]
谢了，但是7024版本原来运行得好好的突然水灵灵地死了这种事情还是挺离谱的就。

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
