### ISSUE TITLE
[Bug] 聊天界面查看图片使用透明背景 无法使用

### ISSUE THREAD

**Issue by PensiveCar5231** [cinit/QAuxiliary#1279]
### 复现步骤 / Steps to reproduce

聊天界面查看图片使用透明背景 设置无效
![Screenshot_2024-12-22-16-17-17-76_9d26c6446fd7bb8e41d99b6262b17def](https://github.com/user-attachments/assets/2f93bc95-f1aa-4332-99b4-7fb34aae12f4)
![Screenshot_2024-12-22-16-19-03-23_9d26c6446fd7bb8e41d99b6262b17def](https://github.com/user-attachments/assets/70eedea5-81ef-4de9-bf4e-b45931aed351)

### 预期行为 / Expected behaviour

查看图片时，背景按照设置正常模糊

### 实际行为 / Actual behaviour

查看图片时，背景无法模糊

### 你使用的Xposed框架 / Xposed Framework you used

未使用Xposed框架（lspatch）

### 你使用的安卓系统版本 / Your Android version

Android14（coloros14）

### QQ(TIM) 版本 / QQ(TIM) Version

9.1.20

### 模块版本 / Module Version

1.5.5.r2540.224cfe1(2540)

### 版本和其他要求 / Version and Other Requirements

- [ ] 我正在使用最新 CI 调试版本且启用详细日志 / I am using latest debug CI version of QAuxiliary and enable verbose log
- [ ] 我使用的 QQ 是官方发布的正式版本，而非修改版或测试版 / The QQ I am using is an official release version, not a modified or beta version
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 日志 / Logs

[GalleryBgHook-1734854994329.txt](https://github.com/user-attachments/files/18221186/GalleryBgHook-1734854994329.txt)

**Comment by PensiveCar5231** [comment]
系统已允许允许窗口级模糊出力
![Screenshot_2024-12-22-16-24-00-63_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/user-attachments/assets/a5098c22-e016-44a8-8fa5-9ae7976aaa29)
处理

**Comment by duzhaokun123** [comment]
既然 qa 设置界面都没有模糊

说明这大概了是个上游 bug

**Comment by PensiveCar5231** [comment]
不知道为什么，我啥也没干，它现在又好了（但故障排查里还是报错，清除完缓存之后还是报错）
