### ISSUE TITLE
[Bug] 在QQ8.9.x中，发送闪照对方接收到的是普通照片

### ISSUE THREAD

**Issue by emotime** [cinit/QAuxiliary#128]
### Steps to reproduce/复现步骤

开启QA中的“以图片方式打开闪照”后，在聊天栏点击图片，点击要发送的图片，选择闪照并发送。

### Expected behaviour/预期行为

对方接收到闪照

### Actual behaviour/实际行为

对方接收到的是普通照片

### XPosed Framework you used/你使用的XP框架

LSPosed

### QQ(TIM)版本/QQ(TIM) Version

8.9.2

### Module Version/模块版本

1.2.12.r855.75ddd88

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

此功能故障排查无异常

**Comment by cinit** [comment]
fixed in b8f8a35e4fe1a7380a3d45b38a3c70cfc7032b79
