### ISSUE TITLE
[Bug] 该账号涉嫌使用非官方QQ客户端或外挂插件

### ISSUE THREAD

**Issue by qwe5283** [cinit/QAuxiliary#1285]
### 复现步骤 / Steps to reproduce

无复现步骤

### 预期行为 / Expected behaviour

插件不应该被客户端检测出来

### 实际行为 / Actual behaviour

![IMG_20241226_084243](https://github.com/user-attachments/assets/1f24e313-0bb0-4da9-82cf-7565bcc818ed)

### 你使用的Xposed框架 / Xposed Framework you used

LSPatch 0.7

### 你使用的安卓系统版本 / Your Android version

Android 15

### QQ(TIM) 版本 / QQ(TIM) Version

9.1.10.20545(7858)

### 模块版本 / Module Version

1.5.5.r2540.224cfe1(2540)

### 版本和其他要求 / Version and Other Requirements

- [ ] 我正在使用最新 CI 调试版本且启用详细日志 / I am using latest debug CI version of QAuxiliary and enable verbose log
- [ ] 我使用的 QQ 是官方发布的正式版本，而非修改版或测试版 / The QQ I am using is an official release version, not a modified or beta version
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 日志 / Logs

1.5.5.r2540.224cfe1
QQ9.1.10(7858)
PID: 670, UID: 10317
cc.ioctl.hook.msg.RevokeMsgHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by Hicores** [comment]
这边建议你入职腾讯拿到检测方法

**Comment by klxiaoniu** [comment]
重复的issue，前面有人提过了

**Comment by RocketMaDev** [comment]
> 重复的issue，前面有人提过了

请问有没有ref？
