### ISSUE TITLE
群文件转永久

### ISSUE THREAD

**Issue by tatan0000** [cinit/QAuxiliary#1288]
### 复现步骤 / Steps to reproduce

辅助功能文件存储群文件长按转存永久

### 预期行为 / Expected behaviour

群文件转永久正常

### 实际行为 / Actual behaviour

初始化失败

### 你使用的Xposed框架 / Xposed Framework you used

LSPatch

### 你使用的安卓系统版本 / Your Android version

14

### QQ(TIM) 版本 / QQ(TIM) Version

9.1.16

### 模块版本 / Module Version

1.5.5.r2570.91ee21e(2570)

### 版本和其他要求 / Version and Other Requirements

- [ ] 我正在使用最新 CI 调试版本且启用详细日志 / I am using latest debug CI version of QAuxiliary and enable verbose log
- [X] 我使用的 QQ 是官方发布的正式版本，而非修改版或测试版 / The QQ I am using is an official release version, not a modified or beta version
- [X] 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 日志 / Logs

[Uploading TroopFileSaveLasting-1735466550896.txt…]()

**Comment by klxiaoniu** [comment]
@tatan0000 强制停止QQ，重新打开

**Comment by tatan0000** [comment]
强行停止后还是同样的结果



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月29日(周日) 晚上8:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cinit/QAuxiliary] 群文件转永久 (Issue #1288)




 
@tatan0000 强制停止QQ，重新打开

**Comment by tatan0000** [comment]
好了好了，得先打开群文件一次
