### ISSUE TITLE
[功能请求] 

### ISSUE THREAD

**Issue by ZoidbergPi** [cinit/QAuxiliary#134]
### QQ(TIM)版本/QQ(TIM) Version

Any

### 为什么你认为需要此功能

QQ会自动静默升级到最新版，导致提示使用非官方版本QQ被禁用帐号

### 具体功能需要/Specific features require

阻止QQ静默升级

**Comment by Hicores** [comment]
@ZoidbergPi 请关闭你手机应用商店的自动升级
