### ISSUE TITLE
[功能请求] 发送图片时给图片文件二进制添加随机字符串

### ISSUE THREAD

**Issue by HBcao233** [cinit/QAuxiliary#136]
### QQ(TIM)版本/QQ(TIM) Version

QQ v8.8.88.7830

### 为什么你认为需要此功能

当发送特殊图片时，QQ会把图片的md5值和数据库比对进行风控，如果在发送图片时给图片文件二进制添加随机字符串，就可以改变图片的md5值从而绕过QQ风控

### 具体功能需要/Specific features require

发送图片时，以打开追加二进制模式（'ab'模式）打开图片文件，将随机字符串写入文件末尾，然后发送即可。

**Comment by cinit** [comment]
和 "涉密不上网，上网不涉密" 一个道理，有需求请用其他 IM。
