### ISSUE TITLE
[Bug] 修改机型功能失效

### ISSUE THREAD

**Issue by abai233** [cinit/QAuxiliary#137]
### Steps to reproduce/复现步骤

打开修改机型功能，填入型号，保存，重启QQ

### Expected behaviour/预期行为

重启QQ后，设备名称被成功修改

### Actual behaviour/实际行为

设备名称没有任何变化，打开功能异常列表也没有提示错误

### XPosed Framework you used/你使用的XP框架

应用转生

### QQ(TIM)版本/QQ(TIM) Version

8.9.3

### Module Version/模块版本

1.2.13.r894.c0f4975

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.2.13.r894.c0f4975
QQ8.9.3(3118)
com.rymmmmm.hook.CustomDeviceModel
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by keta1** [comment]
duplicate #77
