### ISSUE TITLE
[Bug] 禁用$打开送礼界面失效

### ISSUE THREAD

**Issue by ANan-12345** [cinit/QAuxiliary#138]
### Steps to reproduce/复现步骤

群聊时输入框里输入$

### Expected behaviour/预期行为

不弹出任何界面

### Actual behaviour/实际行为

弹出送礼窗口

### XPosed Framework you used/你使用的XP框架

LSPosed

### QQ(TIM)版本/QQ(TIM) Version

QQ 8.9.3

### Module Version/模块版本

1.2.13.r894.c0f4975

### Version requirement/版本要求

- [x] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.2.13.r894.c0f4975
QQ8.9.3(3118)
cc.ioctl.hook.SendGiftHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by cinit** [comment]
fixed in 7ed81489725d9dcf32c2116587bf7e9e9b479afb
