### ISSUE TITLE
[Bug] 显示具体消息数量失效

### ISSUE THREAD

**Issue by ANan-12345** [cinit/QAuxiliary#139]
### Steps to reproduce/复现步骤

消息数超过99时

### Expected behaviour/预期行为

显示具体消息数

### Actual behaviour/实际行为

显示99+

### XPosed Framework you used/你使用的XP框架

LSPosed

### QQ(TIM)版本/QQ(TIM) Version

QQ 8.9.3

### Module Version/模块版本

1.2.13.r894.c0f4975

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.2.13.r894.c0f4975
QQ8.9.3(3118)
com.rymmmmm.hook.ShowMsgCount
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by cinit** [comment]
9abf2d529dad624d3bb3ad71d16ed716b822a986 修过了, 你去 故障排查 清除一下模块缓存

**Comment by ANan-12345** [comment]
> [9abf2d5](https://github.com/cinit/QAuxiliary/commit/9abf2d529dad624d3bb3ad71d16ed716b822a986) 修过了, 你去 故障排查 清除一下模块缓存

清了，还是没效果

**Comment by cinit** [comment]
@ANan-12345 你更新  CI 版本了没？

**Comment by ANan-12345** [comment]
> @ANan-12345 你更新 CI 版本了没？

QQ8.9.3.8730
模块1.2.13 armALL

**Comment by cinit** [comment]
你去从 https://github.com/cinit/QAuxiliary/actions/runs/2846481041 下载 CI 版本使用。
