### ISSUE TITLE
[功能请求] 发送信息时，根据用户设置自动替换消息内的关键词

### ISSUE THREAD

**Issue by maxesisn** [cinit/QAuxiliary#141]
### QQ(TIM)版本/QQ(TIM) Version

8.8.88

### 为什么你认为需要此功能

1. 使用户可以方便调用常用的短语：例如发送"[很酷]"可自动替换成"不觉得很酷吗？作为一个工科男，我觉得这太酷了，很符合我对未来生活的想象，科技并带着些趣味"，免去手动输入或找地方复制粘贴的苦恼；
2. 规避某些群聊内的屏蔽词检测机器人：例如某些群聊机器人会检测关键词“炼铜”并对发送者进行禁言处理，但如果用户真的是在讨论冶金技术，则会被该规则误伤。如果可以自动把“炼铜”替换为"金属冶炼"等词汇，则可大幅提高用户的使用体验，不用再为屏蔽词机制而担心。

### 具体功能需要/Specific features require

当用户启用该功能时，提供一个列表，使用户可以自定义关键词字典，例如：
![image](https://user-images.githubusercontent.com/20412597/184845433-386f1352-49b3-46b2-b8ef-d82162f71e07.png)

**Comment by keta1** [comment]
@maxesisn 这个活我觉得 丢给你的输入法比较好

**Comment by maxesisn** [comment]
@keta1 其实提这个issue主要是为了需求2，但是光这一条有些太单薄了，想了一下也可以用来实现需求1，就一起写上去了（

**Comment by cinit** [comment]
但是这个需求太怪了，建议交给输入法

**Comment by maxesisn** [comment]
> @maxesisn 防屏蔽建议交给 https://github.com/lz233/unvcode_android

草，确实可以，把处理完的字符串塞到输入法自定义词库里面也能有我想要的效果（指直接发屏蔽词不被机器人抓到）
