### ISSUE TITLE
[功能请求] 防止QQ在主目录拉屎/QQ拉屎重定向

### ISSUE THREAD

**Issue by Zh40Le1ZOOB** [cinit/QAuxiliary#142]
### QQ(TIM)版本/QQ(TIM) Version

8.9.0

### 为什么你认为需要此功能

QQ常年在主目录乱拉屎，导致主目录凌乱不堪，困扰大量用户
人话：看着不舒服

### 具体功能需要/Specific features require

将/storage/emulated/0/Tencent目录(此处还会出现小写的tencent目录)和/storage/emulated/0/DCIM/.tmfs还有QQ默认下载目录(/storage/emulated/0/Android/data/com.tencent.mobileqq/Tencent/QQfile_recv/)里的.tmp和.thumbnails文件夹干掉(干掉这俩是因为使用下载目录重定向时很不爽)

**Comment by keta1** [comment]
@Zh40Le1ZOOB 你可以不给qq存储权限

**Comment by Zh40Le1ZOOB** [comment]
> 

那样QQ会无法读取相册，且下载目录重定向会失效

**Comment by HelloMitsuha** [comment]
这边建议删除想要阻止写入的文件夹，然后创建同名文件(空文件)，只要没有不可写入就重建的逻辑就永远不会乱建(任何软件通杀)
