### ISSUE TITLE
[功能请求] 降低QQ后台CPU占用

### ISSUE THREAD

**Issue by Zh40Le1ZOOB** [cinit/QAuxiliary#143]
### QQ(TIM)版本/QQ(TIM) Version

8.9.0

### 为什么你认为需要此功能

QQ在后台收个消息就常年占用半分之五六十的CPU，有时候还飙上250%，我的电池深受其害

### 具体功能需要/Specific features require

把QQ主进程和MSF进程的代码优化下，让它们像微信那样乖乖的

**Comment by cinit** [comment]
@Zh40Le1ZOOB 我看不懂，但我大受震撼

**Comment by Zh40Le1ZOOB** [comment]
![Screenshot_2022-08-19-11-05-04-680-edit_github tornaco android thanos](https://user-images.githubusercontent.com/97139537/185534024-aeacbd00-73bd-4f6b-9300-8ef2d5cb924f.png)
QQ群都退的差不多了一天都没几条消息，就这CPU占用还高的离谱，微信都常年1%2%

**Comment by cinit** [comment]
@Zh40Le1ZOOB 你应该去给 QQ 提 issue

**Comment by ZoruaFox** [comment]
我看不懂，但我大受震撼
