### ISSUE TITLE
[Bug] TTS语音发不了

### ISSUE THREAD

**Issue by YX-IT** [cinit/QAuxiliary#145]
### Steps to reproduce/复现步骤

每次只能发一次,第二次就会提示错误[需要删除后台重进才能再发一次]
设置里面tts的功能都开了
发送指令：#tts zh-CN
                   语音测试
提示错误,设置了其他的引擎也用不了
![Screenshot_20220819_105709_com tencent mobileqq](https://user-images.githubusercontent.com/81810514/185536099-593d93e4-f073-410a-8168-dbc68f60cf7d.jpg)
![Screenshot_20220819_105202_com tencent mobileqq](https://user-images.githubusercontent.com/81810514/185536102-1bb9a799-ab57-4528-af62-6460106dfb06.jpg)

### Expected behaviour/预期行为

正常发送

### Actual behaviour/实际行为

只能发送一次tts语音 #
![Screenshot_20220819_105709_com tencent mobileqq](https://user-images.githubusercontent.com/81810514/185536014-078725c8-dee3-4e32-ac12-fdc109609232.jpg)
![Screenshot_20220819_105202_com tencent mobileqq](https://user-images.githubusercontent.com/81810514/185536019-e528ef40-d34c-4a71-8c39-3f720d45ab6b.jpg)
![Screenshot_20220819_105202_com tencent mobileqq](https://user-images.githubusercontent.com/81810514/185536021-ec007d8c-bb01-4855-aeee-0c30e01c17a9.jpg)
![Screenshot_20220819_110107_com tencent mobileqq](https://user-images.githubusercontent.com/81810514/185536023-be57cba9-6f9b-4036-8fed-17446bc3b110.jpg)
![Screenshot_20220819_104921_com tencent mobileqq](https://user-images.githubusercontent.com/81810514/185536024-dbb4dfc1-0f77-46c5-b6f1-4c777291c643.jpg)

### XPosed Framework you used/你使用的XP框架

应用转生

### QQ(TIM)版本/QQ(TIM) Version

8.8.68

### Module Version/模块版本

1.2.13.r894.c0f4975

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

无

**Comment by duzhaokun123** [comment]
@YX-IT 你才试了 5 次
为什么不多试试呢

**Comment by duzhaokun123** [comment]
tts 发送大改 894 已过时
