### ISSUE TITLE
[功能请求] 增加显示坦白说对方QQ号，我不想留有遗憾。

### ISSUE THREAD

**Issue by NianBroken** [cinit/QAuxiliary#148]
### QQ(TIM)版本/QQ(TIM) Version

QQ 8.9.5.8845

### 为什么你认为需要此功能

QQ显示09.24有人给我发了很多坦白说，但是今年现在才八月，所以这个坦白是至少是去年别人给我发的，我不想留有遗憾，我想看看对方是谁，真的很想，很想很想。

在发这个建议之前，我已经问了对方是谁，但是对方没有回复。

![Screenshot_2022-08-22-13-33-14-501_com tencent mobileqq](https://user-images.githubusercontent.com/57057288/185846638-af6304d8-6cef-4d90-9717-b5c3bf050f5c.jpg)

### 具体功能需要/Specific features require

显示坦白说对方QQ号

**Comment by cinit** [comment]
坦白说很早就改了，现在服务器已经不下发对方 QQ 号到客户端了，取而代之的是一个 ID，与帐号对应。

**Comment by keta1** [comment]
@NianBroken 入职腾讯（

**Comment by cinit** [comment]
@NianBroken 没有，最多能做的就是拿到 confess id 对比那些会话是不是来自同一个帐号，仅此而已。
