### ISSUE TITLE
[Bug] 开启 聊天界面 - 可选使用系统相册/可选使用系统文件 导致频道私聊发图失败

### ISSUE THREAD

**Issue by ljcbaby** [cinit/QAuxiliary#149]
### Steps to reproduce/复现步骤

1. 开启 聊天界面 - 可选使用系统相册/可选使用系统文件
2. 在频道私聊内采用任一形式发图

### Expected behaviour/预期行为

正常发送图片，如果多图应该合并为一条消息

### Actual behaviour/实际行为

没有动作

### XPosed Framework you used/你使用的XP框架

LSPosed1.8.3(6552)

### QQ(TIM)版本/QQ(TIM) Version

QQ 8.9.5(3176)

### Module Version/模块版本

1.2.14.r921.f309bde

### Version requirement/版本要求

- [ ] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

I am not using latest debug CI version of QAuxiliary and enable verbose log/我并不正在使用最新 CI 调试版本且启用详细日志

**Comment by ljcbaby** [comment]
合理猜测为 QQ频道允许接收多图并合并为一条消息，导致接收图片的结构体发生变化

**Comment by keta1** [comment]
@ljcbaby 没适配频道 应该也没空去适配

**Comment by ljcbaby** [comment]
那是不是应该屏蔽一下相关功能的应用面，避免产生有害干扰

**Comment by keta1** [comment]
fixed in 3096a8286a25

**Comment by keta1** [comment]
@keta1 ^
