### ISSUE TITLE
[功能请求]自动续火

### ISSUE THREAD

**Issue by A1Panda** [cinit/QAuxiliary#150]
### QQ(TIM)版本/QQ(TIM) Version

8.9.5

### 为什么你认为需要此功能

方便实用qn之前存在的功能

### 具体功能需要/Specific features require

可以给你选择的QQ定时发送续火内容

**Comment by cinit** [comment]
@A1Panda 你应该用 XAutoDaily

**Comment by A1Panda** [comment]
> @A1Panda 你应该用 XAutoDaily

感谢🙏
