### ISSUE TITLE
[功能请求] 去除安全风险弹窗

### ISSUE THREAD

**Issue by nekoteai** [cinit/QAuxiliary#151]
### QQ(TIM)版本/QQ(TIM) Version

8.9.1

### 为什么你认为需要此功能

手机号未实名导致安全风险弹窗，无法关闭，影响正常使用

### 具体功能需要/Specific features require

去除弹窗
![image](https://user-images.githubusercontent.com/87892508/186821073-0286454c-9430-4cd9-9dba-a0d3eea5cc20.png)

**Comment by lliioollcn** [comment]
你应该按照国家相关法律进行实名认证，而不是去除它

**Comment by cinit** [comment]
@lliioollcn 建议 上网不实名，实名不上网
