### ISSUE TITLE
[功能请求] 去除分享来源官方应用验证

### ISSUE THREAD

**Issue by CirnoSalt** [cinit/QAuxiliary#152]
### QQ(TIM)版本/QQ(TIM) Version

8.9.3

### 为什么你认为需要此功能

被修改过的APP在向QQ分享时会弹出“非官方应用”的错误而无法发送，如目前因作者弃坑而只能使用修改版本的share微博客户端，猜测可能是QQ客户端会试图验证来源APP的包名或签名所致。
![Screenshot_2022-08-26-17-56-12-798-edit_com tencent mobileqq](https://user-images.githubusercontent.com/23478997/186879516-bf48a398-e151-46e0-895c-bbee8f342224.jpg)

### 具体功能需要/Specific features require

如果确实为本地客户端实现，去除该限制。

**Comment by cinit** [comment]
实现起来十分麻烦，不予考虑，QQ 检测点非常多，绝对不止一个 apk 签名。
