### ISSUE TITLE
[功能请求] 修改 QQ 图标

### ISSUE THREAD

**Issue by entr0pia** [cinit/QAuxiliary#155]
### QQ(TIM)版本/QQ(TIM) Version

QQ 8.8.38

### 为什么你认为需要此功能

为了让 QQ 消息推送更省电而同时使用着标准版 QQ 和手表版 QQ, 但两者图标和应用名都一样, 在不显示包名的界面无法区分. 这个问题无法使用图标包来解决, 直接修改 QQ 图标 (甚至应用名) 后应该可以区分.

### 具体功能需要/Specific features require

自定义 QQ 图标, 也可以提供几个样例

**Comment by keta1** [comment]
@entr0pia 做不到 建议 让你的桌面干这活

**Comment by entr0pia** [comment]
桌面管不到这里

![Screenshot_20220828-164031](https://user-images.githubusercontent.com/30486766/187065497-7b32b860-5c1e-4bd7-b0d5-82d94a5170dd.png)

hook 资源做不到吗? Xperia 有 xp 模块可以修改 volte 图标, 我感觉方法应该是一致的. 如果我说错了, 请忽略

**Comment by duzhaokun123** [comment]
> hook 资源做不到吗? 

hook QQ 的做不到 因为自由是静态的 模块无法干预这个过程

**Comment by rigious** [comment]
@keta1 @duzhaokun123 
应该可以做到
 QQ设置里面有个会员选项，可以更换qq图标。

位置在 
设置-隐私-展示设置-设置APP个性图标
