### ISSUE TITLE
[Bug] 隐藏群聊共同好友提醒失效

### ISSUE THREAD

**Issue by PandaYuuHa** [cinit/QAuxiliary#160]
### Steps to reproduce/复现步骤

1.打开QA隐藏群聊共同好友提醒功能
2.重启QQ

### Expected behaviour/预期行为

群聊内不再出现共同好友提醒

### Actual behaviour/实际行为

仍提示共同好友
![IMG_20220902_092310](https://user-images.githubusercontent.com/63838456/188039505-2ea24cee-56c6-40f4-9876-6b8f24dc7c8a.jpg)

### XPosed Framework you used/你使用的XP框架

太极 青钢影·10.0.5.08232213-8400

### QQ(TIM)版本/QQ(TIM) Version

8.9.2

### Module Version/模块版本

1.3.0.r952.63d229f

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.3.0.r952.63d229f
QQ8.9.2(3072)
PID: 10980, UID: 10735
xyz.nextalone.hook.HideTroopAddTips
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by keta1** [comment]
fixed in 1a1715272da6b49de0c939145d13f2ac43d5dd38
