### ISSUE TITLE
[Bug] 修复安卓13的QQ支持

### ISSUE THREAD

**Issue by Tinnci** [cinit/QAuxiliary#162]
### Steps to reproduce/复现步骤

似乎与小米6ArrowOS的安卓13版本存在兼容性问题，模块无法激活，模块版本1.3.0.r947.c03491d

### Expected behaviour/预期行为

应当跳出模块设置/正常激活模块

### Actual behaviour/实际行为

无任何反馈或选单弹出

### XPosed Framework you used/你使用的XP框架

Lsposed 1.8.3(6552)-Zygisk

### QQ(TIM)版本/QQ(TIM) Version

8.9.8

### Module Version/模块版本

1.3.0.r947.c03491d

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

点击故障排查中的QQ选单仍无任何反馈，无弹窗或选单弹出

**Comment by cinit** [comment]
@Tinnci 你去 LSP 的详细日志里找找有没有 at io.qauxv 之类的错误信息

**Comment by Tinnci** [comment]
> @Tinnci 你去 LSP 的详细日志里找找有没有 at io.qauxv 之类的错误信息

没事了，LSposed里面没有勾选系统框架，勾选后可以正常使用了。
感谢大大。

**Comment by keta1** [comment]
@Tinnci 我们是一个 QQ 模块，不 修改 你的系统，你不需要勾选系统框架

**Comment by cinit** [comment]
@Tinnci QAuxiliary 是一个 QQ 模块，你**不应该**将系统框架添加到它的作用域。
