### ISSUE TITLE
[Bug] 在发生图片时点击编辑QQ会卡死，系统也会重启

### ISSUE THREAD

**Issue by Duck-Deng** [cinit/QAuxiliary#165]
### Steps to reproduce/复现步骤

1. 在QQ中选择一张图片分享
2. 在发送界面点击编辑
3.QQ会崩溃，紧接着系统重启

### Expected behaviour/预期行为

正常情况应该打开编辑页面

### Actual behaviour/实际行为

QQ卡死，系统重启

### XPosed Framework you used/你使用的XP框架

LSPosed1.8.3（6600）-zygisk

### QQ(TIM)版本/QQ(TIM) Version

QQ8.9.5

### Module Version/模块版本

v1.3.0.r947.c03491d-arm64

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.3.0.r960.9306696
QQ8.9.5(3176)
PID: 32377, UID: 10158
cc.ioctl.hook.HideQFSRedPointTips
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: false
isPreparationRequired: false
errors: 0

**Comment by Duck-Deng** [comment]
故障排除内的异常功能只有“屏蔽好友推过”，但我关闭“可使用系统相册”和“可使用系统文件”后正常

**Comment by lliioollcn** [comment]
使用最新ci版本试试呢

**Comment by Duck-Deng** [comment]
> 使用最新ci版本试试呢

没有用，还是会闪退。补充一下，似乎重启后第一次打开编辑是正常的，之后就会闪退并重启
