### ISSUE TITLE
小米QQ分身不能使用该模块

### ISSUE THREAD

**Issue by Mike-Joh** [cinit/QAuxiliary#167]
### QQ(TIM)版本/QQ(TIM) Version

QQ8.9.5.8845

### 为什么你认为需要此功能

作者大大开发的该模块实在是太好用了，我已经爱不释手了，没有这个模块我感觉人生似乎缺少了什么。
不知为何，小米12X手机在应用双开中导入的QQ分身不能使用该模块，在应用列表中寻找分身软件也没有找到，可能是小米应用双开的锅。
希望如果作者大大有空的话，可以稍微投入一点点精力在小米手机分身创造出的QQ不能使用QAuxiliary的问题上。
谢谢大大，祝作者财运滚滚，好运连连！

### 具体功能需要/Specific features require

适配小米12X手机应用双开的QQ

**Comment by teble** [comment]
@Mike-Joh 分身能不能使用插件得看框架是否支持

**Comment by Mike-Joh** [comment]
> 

什么框架？是分身软件框架吗？如果不支持怎么整呢？
（如果太费劲就算了）

**Comment by Hicores** [comment]
@Mike-Joh 需要你的Xposed框架支持

**Comment by SYuanLUV** [comment]
lsposed框架里有个xspace，在那里开

**Comment by Mike-Joh** [comment]
> lsposed框架里有个xspace，在那里开

我去，原来是这么用的，太谢谢你了！
好人一生平安！
