### ISSUE TITLE
[功能请求]拯救一下会员2099的人们吧 

### ISSUE THREAD

**Issue by jituihanbao** [cinit/QAuxiliary#168]
### QQ(TIM)版本/QQ(TIM) Version

8.9.5

### 为什么你认为需要此功能

超级会员或者黄钻达到2099年上限后很多活动无法购买
希望能出个功能修改自己的会员年限 让我们可以改低年限购买活动
希望修改的年限包括会员 超级会员 黄钻 豪华黄钻 大会员

### 具体功能需要/Specific features require

希望修改包括会员 超级会员 黄钻 豪华黄钻 大会员在内的年限 本地生效即可 活动的年限检查在前端 修改年限能绕过活动的前端检查即可

**Comment by teble** [comment]
@jituihanbao 此功能属于浏览器端js代码，非APP实现，请从浏览器/抓包方向自行解决
