### ISSUE TITLE
[Bug] 自编译失败

### ISSUE THREAD

**Issue by 6DDUU6** [cinit/QAuxiliary#171]
### Steps to reproduce/复现步骤

1.glone项目并拉取所有子模块
2.用as打开项目
3.gradle编译失败

### Expected behaviour/预期行为

编译成功

### Actual behaviour/实际行为

编译失败

### XPosed Framework you used/你使用的XP框架

-

### QQ(TIM)版本/QQ(TIM) Version

-

### Module Version/模块版本

-

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

在前两周我还能成功编译并能编译出apk，今天晚上pull拉取了一下新的就不能编译了。尝试过重新clone项目到新的文件夹，重新拉取子模块，什么代码都没动用as打开，还是显示如下错误。
Execution failed for task ':app:compileReleaseAidl'.
具体日志如下：
https://paste.ubuntu.com/p/xvv8mgwsX5/

**Comment by keta1** [comment]
不懂，检查 https://github.com/cinit/QAuxiliary/blob/main/gradle.properties#L24-L25
实在不行 删掉 https://github.com/cinit/QAuxiliary/blob/main/gradle.properties#L23-L25

**Comment by 6DDUU6** [comment]
> 不懂，检查 https://github.com/cinit/QAuxiliary/blob/main/gradle.properties#L24-L25 实在不行 删掉 https://github.com/cinit/QAuxiliary/blob/main/gradle.properties#L23-L25


删掉了还是一样的问题这个task失败QAQ ':app:compileReleaseAidl'.

**Comment by keta1** [comment]
> > 不懂，检查 https://github.com/cinit/QAuxiliary/blob/main/gradle.properties#L24-L25 实在不行 删掉 https://github.com/cinit/QAuxiliary/blob/main/gradle.properties#L23-L25
> 
> 删掉了还是一样的问题这个task失败QAQ ':app:compileReleaseAidl'.

试试 clean 后编译

**Comment by qwq233** [comment]
有没有动过jdk版本和gradle版本
试试手动命令行执行`gradle :app:assemble --debug`

**Comment by 6DDUU6** [comment]
我reset到之前的提交可以重新编译
![image](https://user-images.githubusercontent.com/51308585/189381516-de388703-fde5-4717-92b7-8496b67373ab.png)
到新的新的就不行
![image](https://user-images.githubusercontent.com/51308585/189382087-c3325060-e9c0-4084-a7d7-38dda3c92e9f.png)
clean后编译还是一样的问题。
这是debug后的日志：
https://paste.ubuntu.com/p/JTBVBqkfyp/

**Comment by keta1** [comment]
https://github.com/cinit/QAuxiliary/commit/a9fa36e893fcf1867281136165cfdb85e9cc4937#diff-26c8f7175cdd57b6738e1f888b46139b3f0059558cf40bd6682dfb05051b4c65R12
试试删掉这行

**Comment by keta1** [comment]
> > [a9fa36e#diff-87680529770c9e23f6c5f8c85cf602461940a70282a247d7cdf9c50a384b9272R36](https://github.com/cinit/QAuxiliary/commit/a9fa36e893fcf1867281136165cfdb85e9cc4937#diff-87680529770c9e23f6c5f8c85cf602461940a70282a247d7cdf9c50a384b9272R36) 试试删掉这行
> 
> 离谱可以了，原来是buildtool版本不对，感谢大佬！

我怀疑 windows 上 33 的 buildtool 有问题，不是版本不对，看日志调用的就是 33 的 buildtool
