### ISSUE TITLE
[Bug] 自定义机型功能失效

### ISSUE THREAD

**Issue by giver18** [cinit/QAuxiliary#173]
### Steps to reproduce/复现步骤

1.自定义机型编辑
2.点击确认后退出清理后台或者清除数据
3.重新登录后发现自定义机型不显示

### Expected behaviour/预期行为

在线状态应为用户所编辑的文案

### Actual behaviour/实际行为

实际上在线状态不是自己编辑的文案，是QQ官方给出的文案

### XPosed Framework you used/你使用的XP框架

1.8.3 (6552)

### QQ(TIM)版本/QQ(TIM) Version

8.9.8

### Module Version/模块版本

1.3.1.r974.735d 9ad

### Version requirement/版本要求

- [x] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.3.1.r974.735d9ad
QQ8.9.8(3238)
PID: 26982, UID: 10239
com.rymmmmm.hook.CustomDeviceModel
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by lliioollcn** [comment]
@giver18 试试最新ci版呢

**Comment by giver18** [comment]
> 
最新ci版啥意思

**Comment by lliioollcn** [comment]
@giver18 最新构建版

**Comment by giver18** [comment]
> @giver18 最新构建版

抱歉我是新手，你说的言语我有点难理解，能给个具体步骤或者链接吗，再次感谢！

**Comment by giver18** [comment]
> @giver18 最新构建版

telegram我下载不了，那该怎么下载ci版呢请问

**Comment by Naynna** [comment]
> > @giver18 最新构建版
> 
> telegram我下载不了，那该怎么下载ci版呢请问

@giver18 [Github Actions](https://github.com/cinit/QAuxiliary/actions/workflows/push_ci.yml)

**Comment by giver18** [comment]
> > > @giver18 最新构建版
> > 
> > 
> > telegram我下载不了，那该怎么下载ci版呢请问
> 
> @giver18 [吉特哈布操作](https://github.com/cinit/QAuxiliary/actions/workflows/push_ci.yml)

ci版本试过了依旧失效

**Comment by giver18** [comment]
> > > > @giver18 最新构建版
> > > 
> > > 
> > > telegram我下载不了，那该怎么下载ci版呢请问
> > 
> > 
> > @giver18 [吉特哈布操作](https://github.com/cinit/QAuxiliary/actions/workflows/push_ci.yml)
> 
> ci版本试

> > > > @giver18 最新构建版
> > > 
> > > 
> > > telegram我下载不了，那该怎么下载ci版呢请问
> > 
> > 
> > @giver18 [吉特哈布操作](https://github.com/cinit/QAuxiliary/actions/workflows/push_ci.yml)
> 
> ci版本试过了依旧失效

日志
1.3.1.r978.edf3058
QQ8.9.3(3118)
PID: 5247, UID: 10239
com.rymmmmm.hook.CustomDeviceModel
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0
qa版本号1.3.1.r978.edf3058
lsposed版本1.8.4 (6609)
QQ版本8.9.8

**Comment by lliioollcn** [comment]
不要重复提交已知问题 #174
