### ISSUE TITLE
[Bug] 自定义机型失效

### ISSUE THREAD

**Issue by giver18** [cinit/QAuxiliary#174]
### Steps to reproduce/复现步骤

1.自定义机型编辑
2.点击确认后退出清理后台或者清除数据
3.重新登录后发现自定义机型不显示

### Expected behaviour/预期行为

在线状态应为用户所编辑的文案

### Actual behaviour/实际行为

实际上在线状态不是自己编辑的文案，是QQ官方给出的文案

### XPosed Framework you used/你使用的XP框架

1.8.4（6609）-Zygisk

### QQ(TIM)版本/QQ(TIM) Version

8.9.8

### Module Version/模块版本

qa版本号1.3.1.r978.edf3058

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

日志
1.3.1.r978.edf3058
QQ8.9.3(3118)
PID: 5247, UID: 10239
com.rymmmmm.hook.CustomDeviceModel
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by lliioollcn** [comment]
目前尚且不确定QQ显示机型的逻辑，所以修起来很困难

**Comment by rinscr3003** [comment]
要命。小米11如果设置为其他机型文字，就会被自动替换成“m2011k2c”（关键是还tmd小写的，难看死了）

**Comment by star-picker** [comment]
爱玩机工具箱里头有个换机型的功能，可以试试但是不晓得好不好使

**Comment by Cyanide-zh** [comment]
> 目前尚且不确定QQ显示机型的逻辑，所以修起来很困难

2021年那会手机QQ机型更改只需要先在xposed模块里改好,彻底关闭手机qq然后去删掉/data/data/com.tencent.mobileqq/app_webview_tool/Default/Local Storage/leveldb/这个文件夹,再打开手机qq选在线状态就好了。

**Comment by Cyanide-zh** [comment]
> 目前尚且不确定QQ显示机型的逻辑，所以修起来很困难


2021年那会手机QQ机型更改只需要先在xposed模块里改好,彻底关闭手机qq然后去删掉/data/data/com.tencent.mobileqq/app_webview_tool/Default/Local Storage/leveldb/这个文件夹,再打开手机qq选在线状态就好了。
现在确定,8.9.80版本机型文件在/data/data/com.tencent.mobileqq/files/mmkv/common_mmkv_configurations这个文件里,改完机型删掉这个文件重启手机qq即可。寻找思路如下:

1. 先cd到/data/data/com.tencent.mobileqq,尝试删除所有app开头的文件夹和缓存文件夹,无效。
2. 猜测可能在files文件夹,于是删除整个files文件夹,有效。
3. cd到files文件夹,尝试删除a~o开头的文件夹,有效。
4. 输入命令`grep -rnli "Pixel 3"`,此处Pixel 3为qq中显示的机型,将这些文件逐个排查,最终找到/data/data/com.tencent.mobileqq/files/mmkv/common_mmkv_configurations。
