### ISSUE TITLE
[Bug] 重命名base.apk中

### ISSUE THREAD

**Issue by klxn0-0** [cinit/QAuxiliary#175]
### Steps to reproduce/复现步骤

1.启用重命名base.apk，格式中添加%c
2.QQ中发送apk

### Expected behaviour/预期行为

g-被替换为版本号

### Actual behaviour/实际行为

%c显示为com.tencent.common.app.BaseApplicationImpl@4de8b0c
![Screenshot_2022-09-15-12-27-28-739-edit_com tencent mobileqq](https://user-images.githubusercontent.com/48382562/190316774-e142d3d2-2519-453d-a133-bd4346cb392a.jpg)

### XPosed Framework you used/你使用的XP框架

Lsposed 1.8.3(6552)

### QQ(TIM)版本/QQ(TIM) Version

8.9.8.9000

### Module Version/模块版本

1.3.1.r978.edf3058(978)

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.3.1.r978.edf3058
QQ8.9.8(3238)
PID: 23497, UID: 10235
com.rymmmmm.hook.BaseApk
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by lliioollcn** [comment]
已修复
