### ISSUE TITLE
[Bug] 撤回消息时聊天窗口不显示灰色撤回消息的提示

### ISSUE THREAD

**Issue by 2ulovett** [cinit/QAuxiliary#181]
### Steps to reproduce/复现步骤

开启 在撤回提示灰字中显示被撤回消息的shmsgseq
但是撤回消息后,虽然撤回的消息还在聊天对话窗口里面并没有消息,但是下面没有提示灰字
在上个版本中,还正常显示

### Expected behaviour/预期行为

开启 在撤回提示灰字中显示被撤回消息的shmsgseq 的功能后,会在撤回的消息下面用灰色字体注明该消息为撤回消息

### Actual behaviour/实际行为

开启该功能后,撤回的消息下面并没有出现提示的灰色字体

### XPosed Framework you used/你使用的XP框架

LSPatch 0.3.1 (308) 框架版本 1.8.3 (6563) 嵌入APP方式

### QQ(TIM)版本/QQ(TIM) Version

QQ版本为 8.9.10(3296)

### Module Version/模块版本

QAuxv-v1.3.2.r1014.fb897aa-arm64

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.3.2.r1014.fb897aa
QQ8.9.10(3296)
PID: 12179, UID: 10614
cc.ioctl.hook.RevokeMsgHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by lliioollcn** [comment]
@2ulovett

**Comment by 2ulovett** [comment]
撤回成功,但是下面没有灰字提示,正常打开提示功能,在撤回的消息下面会有一个灰色字体提示这是撤回的消息shmsgseq

**Comment by lliioollcn** [comment]
> 

谢谢，完全没懂你什么意思

**Comment by 2ulovett** [comment]
![QQ图片20220618015422](https://user-images.githubusercontent.com/108536549/191953199-bcdfeecb-ef25-48c9-b1da-e39912800c64.png)
就是这个功能无效! 但是消息防撤回是正常,是不是由于这个防撤回功能里面子功能,所以在故障排查里面的功能异常列表里面显示不出来防撤回有异常?
![已经撤回](https://user-images.githubusercontent.com/108536549/191954286-27a7f5a3-5856-4a82-9ccc-66de34321d4f.png)
![这里并没有显示撤回的灰色字体提示](https://user-images.githubusercontent.com/108536549/191954289-4cade89d-40fd-4444-b53c-15855f9b79c2.png)

并且在子功能中的第三个功能"保留自己撤回的消息"这个子功能也是无效的,开启之后,撤回自己的消息,自己的就没了,并不会保留!

**Comment by lliioollcn** [comment]
你清除数据试试，我正常

**Comment by 2ulovett** [comment]
清除了,还是不行,算了吧,您那边没事,应该就是我个人的问题了...等下个版本再看看吧
感谢您耐心的回复!

**Comment by keta1** [comment]
@2ulovett 我在代码中发现一个相关 的 问题，等我改完之后你试试新版的 qa

**Comment by 2ulovett** [comment]
@keta1 感谢,感谢!
