### ISSUE TITLE
[Bug] 发送xml卡片消息失效(json正常)

### ISSUE THREAD

**Issue by ghost** [cinit/QAuxiliary#182]
### Steps to reproduce/复现步骤

输入xml卡片代码长按发送键

### Expected behaviour/预期行为

发送卡片

### Actual behaviour/实际行为

无效或卡死闪退

### XPosed Framework you used/你使用的XP框架

LSPosed

### QQ(TIM)版本/QQ(TIM) Version

QQ 8.9.10

### Module Version/模块版本

1.3.2

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.3.2.r1017.81b244a
QQ8.9.10(3296)
PID: 30430, UID: 10198
cc.ioctl.hook.CopyCardMsg
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by keta1** [comment]
由于 author 以销号，此 issue 关闭
