### ISSUE TITLE
[功能请求] 禁用CoreService或其他服务

### ISSUE THREAD

**Issue by HelloMitsuha** [cinit/QAuxiliary#184]
### QQ(TIM)版本/QQ(TIM) Version

QQ：8.7.1

### 为什么你认为需要此功能

有一个服务(CoreService)占用了大量内存，导致QQ卡顿占内存，由于没有Root，shell也不能禁用，故此希望模块可以禁用或者强行停止CoreService

其他服务比如Qzone.*也会占用内存，希望也可以禁用

### 具体功能需要/Specific features require

以下是服务的解决方案，可以参考一下
①用定时器停止服务
②禁用服务
③减少占用(固定搭配，比如com.tencent.mobileqq.app.CoreService)
④尝试hookQQ然后禁用组件

提供的开关：
* 禁用服务
    * 子菜单
        * 添加控制(类名:com.xxx.xxx)
        * 全部解禁
        * 全部禁用
        * 全部停止
        * (长按删除)
        * (列表的服务可以点击禁用或解禁)

**Comment by teble** [comment]
你可以使用TSBattery来禁用CoreService

**Comment by HelloMitsuha** [comment]
> 你可以使用TSBattery来禁用CoreService

谢谢

但应用转生好像没有效果(已激活并选择作用域)

**Comment by teble** [comment]
@HelloMitsuha 印象中，TSB好像拒绝在转生加载，你打开APP本体看看
