### ISSUE TITLE
[功能请求] 屏蔽官方机器人消息

### ISSUE THREAD

**Issue by AmasakiKiha** [cinit/QAuxiliary#186]
### QQ(TIM)版本/QQ(TIM) Version

8.9.10-

### 为什么你认为需要此功能

Q群管家点进去就是那个机器人设置页面，现在机器人因为QQ更新之后没法拉黑名单了，群里加一个人我就多一个红点，请问能给机器人的聊天加一个屏蔽选项么

### 联系到哪些已经存在的bug或者功能

Q群管家等官方机器人

### 具体功能需要/Specific features require

出一个按钮，屏蔽所有官方机器人消息，或者更细一点，屏蔽指定机器人消息。

**Comment by lliioollcn** [comment]
已添加，在通知设置->自带已读群机器人消息
重启生效
