### ISSUE TITLE
增加QQ修改图标的功能

### ISSUE THREAD

**Issue by rigious** [cinit/QAuxiliary#189]
### QQ(TIM)版本/QQ(TIM) Version

8.9.10

### 为什么你认为需要此功能

比较酷炫，而且可以在安装多个QQ时根据图标区分。

### 具体功能需要/Specific features require

QQ设置里面有个选项，可以更换qq图标。
Hook修改这个设置就可以实现修改图标的目的。

位置在
设置-隐私-展示设置-设置APP个性图标

**Comment by duzhaokun123** [comment]
已经有了
