### ISSUE TITLE
[Bug] 防撤回不显示撤回提示

### ISSUE THREAD

**Issue by klxn0-0** [cinit/QAuxiliary#194]
### Steps to reproduce/复现步骤

1.打开防撤回功能
2.他人消息被撤回
3.消息仍在，但没有尝试撤回的提示

### Expected behaviour/预期行为

有尝试撤回的提示

### Actual behaviour/实际行为

没有提示

### XPosed Framework you used/你使用的XP框架

lsposed 1.8.4

### QQ(TIM)版本/QQ(TIM) Version

8.9.10(3296)

### Module Version/模块版本

1.3.2.r1061.e1d1ef8(1061)

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.3.2.r1061.e1d1ef8
QQ8.9.10(3296)
PID: 14024, UID: 10234
cc.ioctl.hook.RevokeMsgHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by klxn0-0** [comment]
回退1.3.2.r1014.fb897aa(1014)正常

**Comment by keta1** [comment]
fixed in ddda0cc64f7e6e2421b3b75dd49ae2f2cea0309c
