### ISSUE TITLE
[功能请求] 屏蔽 Q 群管家的 @ 全体成员消息通知

### ISSUE THREAD

**Issue by YidaozhanYa** [cinit/QAuxiliary#201]
### QQ(TIM)版本/QQ(TIM) Version

8.8.85

### 为什么你认为需要此功能

在某些群中，Q 群管家会每天定时发送消息并 @ 全体，这样很烦，又不能屏蔽，希望此模块能加入屏蔽此类通知的功能。

### 具体功能需要/Specific features require

加入取消 Q 群管家 @ 全体成员消息的通知的功能

**Comment by lliioollcn** [comment]
已添加，在通知设置->自带已读群机器人消息
重启生效
