### ISSUE TITLE
[Bug] 点击他人发送的合并转发消息不能显示出发送人和群号

### ISSUE THREAD

**Issue by xiaohuang2004** [cinit/QAuxiliary#202]
### Steps to reproduce/复现步骤

开启转发消息点击头像查看详细信息功能，
点击他人发送给自己的合并消息不会正常弹出对话框。
但是点击自己发送的合并转发消息却可以正常弹出
此外，软件并未检测到异常

### Expected behaviour/预期行为

弹出消息的发送人和群号

### Actual behaviour/实际行为

什么都没有发生

### XPosed Framework you used/你使用的XP框架

太极

### QQ(TIM)版本/QQ(TIM) Version

8.9.13

### Module Version/模块版本

1.3.3.r1094.74b04bf

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.3.3.r1094.74b04bf
QQ8.9.13(3350)
PID: 18991, UID: 10378
cc.ioctl.hook.MultiForwardAvatarHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by rinscr3003** [comment]
QQ8.9.15.9425，QAux1.3.3.r1094，遇到同样问题

**Comment by teble** [comment]
@rinscr3003 新版QQ都坏了，还没修

**Comment by keta1** [comment]
经测试，使用 最新版模块在此版本 QQ 上无此问题
