### ISSUE TITLE
[功能请求] Tim夜间模式

### ISSUE THREAD

**Issue by HelloMitsuha** [cinit/QAuxiliary#206]
### QQ(TIM)版本/QQ(TIM) Version

Tim 3.0.0

### 为什么你认为需要此功能

晚上用Tim会瞎眼睛，即使亮度最小

### 具体功能需要/Specific features require

* 跟随系统夜间模式
* 手动夜间模式
* X5内置浏览器加载夜间模式js代码
* 消息页加号菜单快捷方式

**Comment by cinit** [comment]
QQ夜间模式是通过主题换肤资源包来实现的，抱歉我们没有能力为TIM设计一套暗色主题（QQ/TM主题资源包不兼容）。
