### ISSUE TITLE
[Bug] Tim批量撤回图标错位

### ISSUE THREAD

**Issue by HelloMitsuha** [cinit/QAuxiliary#207]
### Steps to reproduce/复现步骤

1. 打开"批量撤回消息"
2. 重启Tim(可选)
3. 长按任意消息选择多选

### Expected behaviour/预期行为

多选时显示正确的撤回图标并列与其他图标按钮，取消多选后同时消失，没有残留的选项

### Actual behaviour/实际行为

**仅针对Tim**

* (情况1)多选时不出现图标，取消多选后出现图标占用输入框

* (情况2)看到错位的图标，并且撤回按钮占用输入框

![Screenshot_20221029_223815_com tencent tim_edit_1237081343545607](https://user-images.githubusercontent.com/92676720/198837810-ec2feeae-0825-4e10-90ec-20c0278681fc.jpg)
![Screenshot_20221029_223858](https://user-images.githubusercontent.com/92676720/198837815-d6e1ea4b-b64a-4c0f-b4b9-4d32193c88dc.jpg)

### XPosed Framework you used/你使用的XP框架

应用转生 app6.5.9 内核9.0

### QQ(TIM)版本/QQ(TIM) Version

Tim 3.0.0

### Module Version/模块版本

1.2.6.r656.7fba07b(656)

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

没有报错......

1.2.6.r656.7fba07b
TIM3.0.0(1082)
me.ketal.hook.MultiActionHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0
![Screenshot_20221029_225108_com tencent tim](https://user-images.githubusercontent.com/92676720/198838121-f17aa6a2-bbcd-40ca-9117-b2e7015c47f4.jpg)

**Comment by keta1** [comment]
Tim 3.0.0 已经无法登陆

**Comment by MoonLeeeaf** [comment]
使用旧的账号能登（大概21年底之前的都行），但是这个Issue有点久远🤔
