### ISSUE TITLE
卡片消息能发，但是只有自己能看得到，相当于没发

### ISSUE THREAD

**Issue by Qfxaile** [cinit/QAuxiliary#208]
### Steps to reproduce/复现步骤

输入
{"app":"com.tencent.qqpay.qqmp.groupmsg","desc":"","view":"groupPushView","ver":"1.0.0.3","prompt":"[QQ红包]","appID":"","sourceName":"","actionData":"","actionData_A":"","sourceUrl":"","meta":{"groupPushData":{"time":"","cancel_url":"http:\/\/shouhuwl.com\/","fromIcon":"","report_url":"","bannerLink":"","fromName":"name","summaryTxt":"","bannerImg":"http:\/\/gchat.qpic.cn\/gchatpic_new\/3141944282\/1028840661-3191512097-2B75EB17586726652D1190C1C7DDE9EB\/0?term=2","bannerTxt":"？","item1Img":""}},"config":{"forward":0,"showSender":1},"text":"","sourceAd":"","extra":""}
后长按发送键，发送成功，但是换个号查看，没有这个消息

### Expected behaviour/预期行为

换号查看，应该能看到，小号都看不到，别人也肯定看不到

### Actual behaviour/实际行为

换小号，看不到卡片消息，相当于没发

### XPosed Framework you used/你使用的XP框架

lsposed

### QQ(TIM)版本/QQ(TIM) Version

8.8.98

### Module Version/模块版本

1.3.4.r1122.caef72e

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.3.4.r1122.caef72e
QQ8.8.98(3002)
PID: 463, UID: 10265
cc.ioctl.hook.CardMsgSender
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by Hicores** [comment]
@Qfxaile 这个建议你去问问tx为什么不给别人看到
