### ISSUE TITLE
[Bug] 好友分组列表下方不显示“历史好友”入口

### ISSUE THREAD

**Issue by Bcake123** [cinit/QAuxiliary#209]
### Steps to reproduce/复现步骤

打开“好友分组列表下显示历史好友入口”选项开关以后，好友分组列表下依然不会显示“历史好友”入口（QQ已重启）

### Expected behaviour/预期行为

打开开关后，好友分组列表下应该显示“历史好友”入口

### Actual behaviour/实际行为

![Screenshot_20221030_105418_com tencent mobileqq](https://user-images.githubusercontent.com/98083630/198860442-78aa4860-f678-4673-bc78-7aca38065109.jpg)

![Screenshot_20221030_103123_com tencent mobileqq_edit_110488457083579](https://user-images.githubusercontent.com/98083630/198860207-d47a7362-f101-45e1-8602-6fd34facebd4.jpg)
如图，开关打开后重启QQ并没有显示“历史好友”入口

### XPosed Framework you used/你使用的XP框架

太极

### QQ(TIM)版本/QQ(TIM) Version

8.9.13(3350)

### Module Version/模块版本

1.3.4.r1122.caef72e(1122)

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.3.4.r1122.caef72e
QQ8.9.13(3350)
PID: 17668, UID: 10288
cc.ioctl.hook.ShowDeletedFriendListEntry

**Comment by keta1** [comment]
在 此版本 qq 上使用 最新版 模块测试无此问题
