### ISSUE TITLE
[功能请求] 屏蔽QQ界面长按进入多标签页聊天界面

### ISSUE THREAD

**Issue by xiaohuang2004** [cinit/QAuxiliary#215]
### QQ(TIM)版本/QQ(TIM) Version

8.9.15

### 为什么你认为需要此功能

有时单手操作非常容易误触进入，很麻烦

### 具体功能需要/Specific features require

屏蔽QQ界面长按进入多标签页聊天界面
在QQ主页面长按不会进入多标签页的聊天页面

**Comment by Lagrio** [comment]
@xiaohuang2004 有没有可能 QQ 设置里就可以关
