### ISSUE TITLE
[功能请求] 屏蔽左侧栏中的好友点赞通知（名片赞）

### ISSUE THREAD

**Issue by Bcake123** [cinit/QAuxiliary#219]
### QQ(TIM)版本/QQ(TIM) Version

8.9.13(3350)

### 为什么你认为需要此功能

很多人点赞就会收到很多通知 其实没有必要，看着烦 QQ本身也没提供关闭点赞通知的功能 所以想通过模块实现。

### 具体功能需要/Specific features require

屏蔽掉左侧滑动栏好友点赞的通知消息

**Comment by keta1** [comment]
![Screenshot_2022-11-11-12-57-12-604_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/41381927/201266608-b4b6ef5e-62c9-49a4-b254-86712c4df183.jpg)


已经有了
