### ISSUE TITLE
[功能请求] QQ设置里QA入口改为圆角

### ISSUE THREAD

**Issue by ObcbO** [cinit/QAuxiliary#22]
### QQ(TIM)版本/QQ(TIM) Version

QQ V8.8.80.7400

### 为什么你认为需要此功能

设置里的QA的入口是方角，而其它QQ的设置选项是圆角，看起来不协调

![Screenshot_20220313-230339_QQ](https://user-images.githubusercontent.com/49872497/158066176-34bd176a-b625-4458-bead-9d115634216d.png)
![IMG_20220313_230757](https://user-images.githubusercontent.com/49872497/158066180-45deaddd-9b3e-4816-9ec9-db87f6522b3a.jpg)

### 具体功能需要/Specific features require

改设置里的QA选项为圆角

**Comment by cinit** [comment]
fixed in e75f03d33b166e86d5e96adf492f6b208934fb69
