### ISSUE TITLE
[功能请求] 屏蔽一起听歌

### ISSUE THREAD

**Issue by block13566** [cinit/QAuxiliary#220]
### QQ(TIM)版本/QQ(TIM) Version

8.9.13

### 为什么你认为需要此功能

有时候想要点左上角三条杠会误触到一起听歌，而且并不是每个人都会用一起听歌的，有时候一起听歌在上面一直挡着挺烦的

### 具体功能需要/Specific features require

屏蔽群聊界面一起听歌

**Comment by cinit** [comment]
d8d6500da97967f698ed98e8dbe28c436a037e5c
