### ISSUE TITLE
[功能请求] Tim(旧版)强制回复消息

### ISSUE THREAD

**Issue by HelloMitsuha** [cinit/QAuxiliary#221]
### QQ(TIM)版本/QQ(TIM) Version

Tim 3.0.0

### 为什么你认为需要此功能

因为新版太垃圾，QQ太臃肿，故此使用旧版
但是旧版不支持回复自己的消息和私聊回复，非常烦人，影响交流
![IMG20221113122358](https://user-images.githubusercontent.com/92676720/201505625-e921813c-1b17-477b-aa95-a2fd59997b04.jpg)
![IMG20221113122321](https://user-images.githubusercontent.com/92676720/201505624-8130ed53-412b-4fe6-b601-fc9b6866eb4d.jpg)
![IMG20221113122202](https://user-images.githubusercontent.com/92676720/201505627-f0c97360-7bd1-4281-9455-13ff979bcb0c.jpg)
![IMG20221113122120](https://user-images.githubusercontent.com/92676720/201505626-84be4a2c-ce2c-472c-be5b-0fbba5c27247.jpg)

### 具体功能需要/Specific features require

* 长按消息框的菜单添加"Reply"选项，点击后像点击回复一样进入回复输入(旧版Tim在自己发送、私聊中任何消息都不会有"回复"按钮)

* 新增滑动消息框(3.0.0不支持的功能)回复消息

* 在所有消息框中始终显示"回复"选项

建议使用第一个方案解决

**Comment by keta1** [comment]
@HelloMitsuha 这个版本有右滑回复吗

**Comment by HelloMitsuha** [comment]
> @HelloMitsuha 这个版本有右滑回复吗

没有
强制右滑可以不弄

**Comment by HdShare** [comment]
尝试最新Ci版本
