### ISSUE TITLE
[Bug] 无法自动发送原图

### ISSUE THREAD

**Issue by CoreyLu1104** [cinit/QAuxiliary#224]
### Steps to reproduce/复现步骤

无法自动发送原图。
只有选择“QQ 相册”时，才会自动发送原图。
选择“系统相册”“系统文档”或从其他APP分享图片到QQ时，不会自动发送原图。

### Expected behaviour/预期行为

自动发送原图

### Actual behaviour/实际行为

无法自动发送原图。
8.9.15+1.3.4/8.9.19+1.3.5/8.9.20+1.3.5/8.9.20+QAuxv-v1.3.5.r1161.57877b4-arm64均尝试过，都只能“QQ 相册”发送原图。
手机是小米12 Pro，8Gen1，MIUI 13.0.41。
打包方式是用Windows LSPatch 0.5.1+（java -jar lspatch.jar bl.apk -m ro.apk -l 2）命令完成，使用安卓LSPatch也同样有问题。

### XPosed Framework you used/你使用的XP框架

LSPatch 0.5.1

### QQ(TIM)版本/QQ(TIM) Version

8.9.20(8.9.15 8.9.19也试过)

### Module Version/模块版本

1.3.4和1.3.5都试过

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.3.5.r1161.57877b4
QQ8.9.20(3524)
PID: 27699, UID: 10279
xyz.nextalone.hook.AutoSendOriginalPhoto
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by keta1** [comment]
@CoreyLu1104 关掉平板模式

**Comment by CoreyLu1104** [comment]
没有开启平板模式...
[0]AIOPictureView
com.tencent.mobileqq.richmediabrowser.view.AIOPictureView
= com.tencent.mobileqq.richmediabrowser.view.AIOPictureView
  [1]AIOUtils
com.tencent.mobileqq.activity.aio.AIOUtils
= Lcom/tencent/mobileqq/activity/aio/o;->J(Lcom/tencent/mobileqq/app/QQAppInterface;Lcom/tencent/mobileqq/app/BaseActivity;Landroid/content/Intent;)I
  [2]AbstractGalleryScene
com.tencent.common.galleryactivity.AbstractGalleryScene
= (void*)0
  [3]AppConstants
com.tencent.mobileqq.app.AppConstants
= com.tencent.mobileqq.app.AppConstants
  [4]ArkAppItemBubbleBuilder
com.tencent.mobileqq.activity.aio.item.ArkAppItemBubbleBuilder
= com.tencent.mobileqq.activity.aio.item.ArkAppItemBubbleBuilder
  [5]AvatarUtil
com.tencent.mobileqq.avatar.utils.AvatarUtil
= Lcom/tencent/mobileqq/j/e/c;->h(Ljava/lang/String;)Ljava/lang/String;
  [6]BasePicDownloadProcessor
com.tencent.mobileqq.transfile.BasePicDownloadProcessor
= com.tencent.mobileqq.transfile.BasePicDownloadProcessor
  [7]DialogUtil
com.tencent.mobileqq.utils.DialogUtil
= com.tencent.mobileqq.utils.DialogUtil
  [8]ChatActivityFacade
com.tencent.mobileqq.activity.ChatActivityFacade
= com.tencent.mobileqq.activity.ChatActivityFacade
  [9]FaceManager
com.tencent.mobileqq.app.face.FaceManager
= (void*)0
  [10]FavEmoConstant
com.tencent.mobileqq.emosm.favroaming.FavEmoConstant
= com.tencent.mobileqq.emosm.favroaming.FavEmoConstant
  [11]FlashPicHelper
com.tencent.mobileqq.app.FlashPicHelper
= Lcom/tencent/mobileqq/app/ap;->e(Lcom/tencent/mobileqq/data/MessageRecord;Z)V
  [12]GalleryBaseScene
com.tencent.mobileqq.gallery.view.GalleryBaseScene
= (void*)0
  [13]TroopAppShortcutDrawer
com.tencent.mobileqq.activity.aio.drawer.TroopAppShortcutDrawer
= Lcom/tencent/mobileqq/activity/aio/c/e;->e()V
  [14]GuildArkHelper
com.tencent.mobileqq.guild.chatpie.helper.GuildArkHelper
= (void*)0
  [15]GuildHelperProvider
com.tencent.mobileqq.guild.chatpie.GuildHelperProvider
= (void*)0
  [16]HttpDownloader
com.tencent.mobileqq.transfile.HttpDownloader
= com.tencent.mobileqq.transfile.HttpDownloader
  [17]IntimateInfoChatDrawer
com.tencent.mobileqq.activity.aio.drawer.IntimateInfoChatDrawer
= (void*)0
  [18]ItemBuilderFactory
com.tencent.mobileqq.activity.aio.item.ItemBuilderFactory
= Lcom/tencent/mobileqq/activity/aio/core/msglist/a/a;->b(Lcom/tencent/mobileqq/data/ChatMessage;Landroid/widget/BaseAdapter;)Lcom/tencent/mobileqq/activity/aio/aa;
  [19]MessageCache
com.tencent.mobileqq.service.message.MessageCache
= Lcom/tencent/mobileqq/service/h/e;-><clinit>()V
  [20]MessageRecordFactory
com.tencent.mobileqq.service.message.MessageRecordFactory
= Lcom/tencent/mobileqq/service/h/r;->J(Lcom/tencent/common/app/AppInterface;Lcom/tencent/mobileqq/data/MessageRecord;Ljava/lang/String;Ljava/lang/String;I)V
  [21]MultiMsgManager
com.tencent.mobileqq.multimsg.MultiMsgManager
= com.tencent.mobileqq.multimsg.MultiMsgManager
  [22]OnlinePushPbPushTransMsg
com.tencent.mobileqq.app.handler.receivesuccess.OnlinePushPbPushTransMsg
= (void*)0
  [23]PicEmoticonInfo
com.tencent.mobileqq.emoticonview.PicEmoticonInfo
= com.tencent.mobileqq.emoticonview.PicEmoticonInfo
  [24]PngFrameUtil
com.tencent.mobileqq.magicface.drawable.PngFrameUtil
= Lcom/tencent/mobileqq/magicface/drawable/d;->a(Ljava/lang/String;)Z
  [25]PopOutEmoticonUtil
com.tencent.mobileqq.popanim.util.PopOutEmoticonUtil
= Lcom/tencent/mobileqq/popanim/a/a;->h(ILcom/tencent/mobileqq/emoticonview/EmoticonInfo;I)Z
  [26]MsgNotification
cooperation.qzone.push.MsgNotification
= cooperation.qzone.push.MsgNotification
  [27]ReplyMsgSender
com.tencent.mobileqq.replymsg.ReplyMsgSender
= (void*)0
  [28]ReplyMsgUtils
com.tencent.mobileqq.activity.aio.reply.ReplyMsgUtils
= (void*)0
  [29]ScreenShotHelper
com.tencent.mobileqq.screendetect.ScreenShotHelper
= com.tencent.mobileqq.screendetect.ScreenShotHelper
  [30]SimpleUIUtil
com.tencent.mobileqq.theme.SimpleUIUtil
= (void*)0
  [31]SystemMessageProcessor
com.tencent.mobileqq.app.message.SystemMessageProcessor
= (void*)0
  [32]TestStructMsg
com.tencent.mobileqq.structmsg.TestStructMsg
= Lcom/tencent/mobileqq/structmsg/w;->a(Ljava/lang/String;)Lcom/tencent/mobileqq/structmsg/AbsStructMsg;
  [33]TimeFormatterUtils
com.tencent.mobileqq.utils.TimeFormatterUtils
= Lcom/tencent/mobileqq/utils/dj;->s(Landroid/content/Context;JLjava/lang/StringBuilder;Ljava/text/SimpleDateFormat;IZ)Ljava/lang/CharSequence;
[34]TroopGiftUtil
com.tencent.mobileqq.troop.utils.TroopGiftUtil
= Lcom/tencent/mobileqq/troop/utils/t;->n(Ljava/io/File;)Z
  [35]ZipUtils
com.tencent.biz.common.util.ZipUtils
= com.tencent.biz.common.util.ZipUtils
  [36]AtPanel
com.tencent.mobileqq.troop.quickat.ui.AtPanel
= Lcom/tencent/mobileqq/troop/quickat/ui/a;->c(Lcom/tencent/mobileqq/troop/quickat/ui/i$a;)V
  [37]AtPanel
com.tencent.mobileqq.troop.quickat.ui.AtPanel
= Lcom/tencent/mobileqq/troop/quickat/ui/a;->q(Landroid/view/View;Ljava/lang/String;Z)V
  [38]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= com.tencent.mobileqq.activity.aio.core.BaseChatPie
  [39]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= Lcom/tencent/mobileqq/activity/aio/helper/ap;->u(Lcom/tencent/mobileqq/data/ChatMessage;)V
  [40]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= Lcom/tencent/mobileqq/activity/aio/core/BaseChatPie;->z0()V
  [41]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= com.tencent.mobileqq.activity.aio.core.BaseChatPie
  [42]ChatActivityFacade
com.tencent.mobileqq.activity.ChatActivityFacade
= Lcom/tencent/mobileqq/activity/ChatActivityFacade;->z1(Lcom/tencent/mobileqq/app/QQAppInterface;Landroid/content/Context;Lcom/tencent/mobileqq/activity/aio/t;Ljava/lang/String;Ljava/util/ArrayList;Lcom/tencent/mobileqq/activity/ChatActivityFacade$d;)[J
  [43]ContactUtils
com.tencent.mobileqq.utils.ContactUtils
= Lcom/tencent/mobileqq/utils/ah;->e(Lmqq/app/AppRuntime;Ljava/lang/String;Z)Ljava/lang/String;
  [44]ContactUtils
com.tencent.mobileqq.utils.ContactUtils
= Lcom/tencent/mobileqq/utils/ah;->l(Lcom/tencent/common/app/business/BaseQQAppInterface;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
  [45]Conversation
com.tencent.mobileqq.activity.home.Conversation
= com.tencent.mobileqq.activity.home.Conversation
  [46]CustomWidgetUtil
com.tencent.widget.CustomWidgetUtil
= Lcom/tencent/widget/e;->b(Landroid/widget/TextView;IIIILjava/lang/String;)V
  [47]FriendChatPie
com.tencent.mobileqq.activity.aio.core.FriendChatPie
= Lcom/tencent/mobileqq/activity/aio/core/FriendChatPie;->b5()V
  [48]FriendsStatusUtil
com.tencent.mobileqq.app.utils.FriendsStatusUtil
= com.tencent.mobileqq.app.utils.FriendsStatusUtil
  [49]LeftSwipeReplyHelper
com.tencent.mobileqq.bubble.LeftSwipeReplyHelper
= Lcom/tencent/mobileqq/bubble/i;->R()V
  [50]PadUtil
com.tencent.common.config.PadUtil
= (void*)0
  [51]PhotoListPanel
com.tencent.mobileqq.activity.aio.photo.PhotoListPanel
= com.tencent.mobileqq.activity.aio.photo.PhotoListPanel
  [52]ProfileCardUtil
com.tencent.mobileqq.util.ProfileCardUtil
= Lcom/tencent/mobileqq/util/ProfileCardUtil;->H(Lmqq/app/AppRuntime;Ljava/lang/String;)Lcom/tencent/mobileqq/data/Card;
  [53]QQSettingMe
com.tencent.mobileqq.activity.QQSettingMe
= Lcom/tencent/mobileqq/activity/QQSettingMe;->d0()V
  [54]QQSettingMe
com.tencent.mobileqq.activity.QQSettingMe
= Lcom/tencent/mobileqq/activity/QQSettingMe;->K0(Lcom/tencent/mobileqq/activity/qqsettingme/a/m;)V
  [55]Scene
com.tencent.mobileqq.troopAddFrd.Scene
= (void*)0
  [56]TroopAppShortcutBarHelper
com.tencent.mobileqq.activity.aio.helper.TroopAppShortcutBarHelper
= (void*)0
  [57]TroopChatPie
com.tencent.mobileqq.activity.aio.core.TroopChatPie
= Lcom/tencent/mobileqq/activity/aio/core/TroopChatPie;->L6()V
  [58]VasProfileTemplateController
com.tencent.mobileqq.profilecard.vas.VasProfileTemplateController
= Lcom/tencent/mobileqq/profilecard/vas/VasProfileTemplateController;->onCardUpdate(Lcom/tencent/mobileqq/profilecard/base/framework/IComponentCenter;Lcom/tencent/mobileqq/profilecard/data/ProfileCardInfo;)Z
  [59]VipUtils
com.tencent.mobileqq.utils.VipUtils
= com.tencent.mobileqq.utils.VipUtils
  [60]VipUtils
com.tencent.mobileqq.utils.VipUtils
= Lcom/tencent/mobileqq/utils/VipUtils;->t(Lcom/tencent/mobileqq/app/QQAppInterface;Ljava/lang/String;Z)I
  [61]WebSecurityPluginV2$
com.tencent.mobileqq.webview.WebSecurityPluginV2$
= Lcom/tencent/mobileqq/webview/h$a;->callback(Landroid/os/Bundle;)V
  [40001]ReplyNoAtHook
com/tencent/mobileqq/activity/aio/rebuild/input/d
  [40002]ChatWordsCount
nnl
  [40003]SortAtPanel.sessionInfoTroopUin
f
  [40004]RemovePlayTogether.ClockInEntryHelper
n
  [40005]QQMessageFacade
B2
  [40006]SimplifyQQSettingMe::MidContentName
h0
  [40007]RemovePlayTogether.TogetherControlHelper
q

**Comment by CoreyLu1104** [comment]
下午又试了一下。
把QQ卸载，然后用8.9.15+1.3.4可以正常发送原图，然后到晚上又不行了，可能是QQ的问题，不是模块的问题。

**Comment by CoreyLu1104** [comment]
今天又测试了，刚安装上的时候没问题，过一会（或者说几个小时），发送原图就不好用了。

**Comment by keta1** [comment]
Add in 88a3ea2f998c19178a8a3262c7c506d9479d3db9
