### ISSUE TITLE
[Bug] q群文件撤回 页面卡在撤回中

### ISSUE THREAD

**Issue by KeyOfSky** [cinit/QAuxiliary#225]
### Steps to reproduce/复现步骤

发送文件后撤回一条文件消息

### Expected behaviour/预期行为

文件撤回成功，消息不显示。

### Actual behaviour/实际行为

q群文件已不存在，但是卡在撤回中界面，并且消息没有删除。
图片[https://imgse.com/i/zuc8hj](url)

### XPosed Framework you used/你使用的XP框架

Lsposed

### QQ(TIM)版本/QQ(TIM) Version

QQ 8.9.19.9580

### Module Version/模块版本

1.3.5.r1153.c2ed23e

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

故障排除列表中未有。。。批量撤回文件消息功能正常。

**Comment by keta1** [comment]
你试试 关了模块，再撤回看看
感觉是 qq 的 bug

**Comment by KeyOfSky** [comment]
好像是的，十分抱歉，打扰了。o(╥﹏╥)o
