### ISSUE TITLE
[功能请求] 隐藏桌面图标

### ISSUE THREAD

**Issue by ExcitedEven** [cinit/QAuxiliary#23]
### QQ(TIM)版本/QQ(TIM) Version

8.8.80

### 为什么你认为需要此功能

桌面图标并不需要

### 具体功能需要/Specific features require

应用信息界面可以直接从Xposed管理器中打开. 桌面图标不需要, 建议直接隐藏桌面图标, 或者添加隐藏桌面图标的开关

**Comment by keta1** [comment]
![image](https://user-images.githubusercontent.com/41381927/158290062-16511d93-8a7b-4920-b281-5fee78328e33.png)
早就有了

**Comment by ExcitedEven** [comment]
不好意思我眼瞎没看到

**Comment by NextAlone** [comment]
@ExcitedEven _No response_
