### ISSUE TITLE
[Bug] 非会员贴表情（根本没有办法吧表情拖出来

### ISSUE THREAD

**Issue by A1Panda** [cinit/QAuxiliary#231]
### Steps to reproduce/复现步骤

目前不知道是什么功能导致的 
开启或关闭非会员贴标签功能 都无法贴表情
表情根本没有办法拖出来

### Expected behaviour/预期行为

正常拖出表情到聊天框 

### Actual behaviour/实际行为

无法拖出表情到聊天框

### XPosed Framework you used/你使用的XP框架

太极 10.1.0

### QQ(TIM)版本/QQ(TIM) Version

8.9.18.9570

### Module Version/模块版本

1.3.5.r1153.c2ed23e

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.3.5.r1153.c2ed23e
QQ8.9.18(3466)
PID: 7420, UID: 10279
cc.ioctl.hook.chat.FakeVipHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by keta1** [comment]
@A1Panda 那就不是 模块的问题，可能是 qq 关了这个功能
按理说就算没会员也能拖出来的

**Comment by A1Panda** [comment]
@keta1 并不是 我尝试在太极中禁用Qa 重启qq后 可以正常粘贴表情

**Comment by keta1** [comment]
> @keta1 并不是 我尝试在太极中禁用Qa 重启qq后 可以正常粘贴表情

经过大量测试，这真是 qq 的 bug, 禁用 qa 模块 重启qq后， 第一次可以正常的贴表情，然后再次尝试的时候就失败 了

**Comment by keta1** [comment]
@keta1 咕咕华 你快给 qq 修 bug
