### ISSUE TITLE
底栏精简里频道精简失效

### ISSUE THREAD

**Issue by Bitwise294874** [cinit/QAuxiliary#234]
### Steps to reproduce/复现步骤

净化设置，杂项，精简底栏

### Expected behaviour/预期行为

底栏中应该没有频道图标

### Actual behaviour/实际行为

还有频道图标

### XPosed Framework you used/你使用的XP框架

LSPosed1.8.5(6652)-zygisk

### QQ(TIM)版本/QQ(TIM) Version

8.9.20

### Module Version/模块版本

1.3.5.r1163.ecec4d2

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

故障排查未见明显异常

**Comment by lliioollcn** [comment]
QQ本身就可以隐藏

请在QQ中将  设置->辅助功能->主页底部导航栏设置->频道  选项关闭即可
