### ISSUE TITLE
[功能请求] 希望为新版本QQ加入砍掉的加号菜单里的群投票功能（现在只有tim有）

### ISSUE THREAD

**Issue by Huaxidesu** [cinit/QAuxiliary#239]
### QQ(TIM)版本/QQ(TIM) Version

8.9.19

### 为什么你认为需要此功能

几乎没人愿意用小程序里面的那个群投票，发了也没人看。所以希望能为新版本版本QQ加回这个功能。

### 具体功能需要/Specific features require

在加号菜单里重新加入群投票功能

**Comment by Hakuin123** [comment]
TIM内群投票入口已被云控关闭，实际点开后服务器502，也就是说这个功能在服务器那边砍掉了…这个issue估计可以close了（）
