### ISSUE TITLE
给 QQ 添加小白条/状态栏适配

### ISSUE THREAD

**Issue by Clearpole** [cinit/QAuxiliary#243]
### QQ(TIM)版本/QQ(TIM) Version

8.9.23

### 为什么你认为需要此功能

小白条黑色实在是太丑了

### 具体功能需要/Specific features require

QQ 的界面小白条搞上沉浸/着色

**Comment by cinit** [comment]
建议去 系统设置-系统导航方式-隐藏手势指示条 把小白条关掉。

**Comment by Clearpole** [comment]
谢谢你，平凡而伟大的陌生人，我的灵魂仿佛得到了神圣的洗涤，虔诚的信徒为您高歌，即使宇宙覆灭，我也不会忘记您今天对我的教诲，如果不是你，我一辈子都被蒙在鼓里。

**Comment by duzhaokun123** [comment]
@cinit 这是坏的 不应该因为厂商委屈自己

**Comment by sclznb** [comment]
> 建议去 系统设置-系统导航方式-隐藏手势指示条 把小白条关掉。

容易累死
