### ISSUE TITLE
[功能请求] 自动跳过小程序广告

### ISSUE THREAD

**Issue by zhuixingzhe-baisheng** [cinit/QAuxiliary#244]
### QQ(TIM)版本/QQ(TIM) Version

8.9.8(3238)

### 为什么你认为需要此功能

玩小程序时方便，不需要看烦人广告

### 具体功能需要/Specific features require

点击广告时，自动关闭，并且获得奖励

**Comment by keta1** [comment]
开发者都不用小程序，不在计划中，欢迎 pr
