### ISSUE TITLE
[功能请求] 防止被傻逼疯子社卡屏

### ISSUE THREAD

**Issue by OnlyNaya** [cinit/QAuxiliary#246]
### QQ(TIM)版本/QQ(TIM) Version

QQ 8.7.0

### 为什么你认为需要此功能

新版本已经和谐了卡屏
但由于个人需求，不更新

但是却又被群里人发卡屏
![Screenshot_20221209_220102_com tencent mobileqq_edit_147156536412439](https://user-images.githubusercontent.com/119770909/206735290-75d64cf9-ee0f-4cb2-9693-1e37da3af817.jpg)
虽然其他模块脚本可以删，但是未能生效

样本:
```
<?xml version='1.0' encoding='UTF-8' standalone='yes' ?><msg serviceID="35" templateID="1" action="viewMultiMsg" brief="【疯子社卡屏】临江牛逼" sourceMsgId="0" url="" flag="3" adverSign="0" multiMsgFlag="0"><item layout="1" advertiser_id="0" aid="0"><title size="26" color="#777777" maxLines="2" lineSpace="12">疯子社</title><summary size="1">疯子社牛逼</summary></item><source name="聊天记录" icon="" action="" appid="-1" /></msg>
```
![Screenshot_20221209_233457](https://user-images.githubusercontent.com/119770909/206737602-af7e851e-4e68-4e4e-966e-3aef855bb8c5.jpg)

[问题关联#183](https://github.com/cinit/QAuxiliary/issues/183)

### 具体功能需要/Specific features require

将这类消息检测出来(比如获取xml文本)，然后删除或者替换
如:
```java
if(String(xml).contains("疯子社")){
    //执行
}
```

附加项(选做):自定义匹配消息并删除

**Comment by StudentYee** [comment]
建议使用 Qtool

**Comment by OnlyNaya** [comment]
> 建议使用 Qtool

已使用，但貌似没有此功能
脚本试过，不行，杀后台就不能用了

**Comment by lliioollcn** [comment]
> > 建议使用 Qtool
> 
> 已使用，但貌似没有此功能 脚本试过，不行，杀后台就不能用了

你可以使用 “卡片消息文本化” 功能来解决这个问题
