### ISSUE TITLE
[功能请求] 添加在粘贴图片时不经确认直接发送的选项

### ISSUE THREAD

**Issue by univeous** [cinit/QAuxiliary#247]
### QQ(TIM)版本/QQ(TIM) Version

QQ V8.8.98.8410

### 为什么你认为需要此功能

使用Gboard、[EweSticker](https://github.com/FredHappyface/Android.EweSticker)等输入法时可以更加便捷地发送表情包。

### 具体功能需要/Specific features require

在设置中添加选项，启用后可以在聊天窗口粘贴图片时不经过确认，直接发送。

https://github.com/cinit/QAuxiliary/blob/da0e2bcb0321cf33b5b22a26ba42a93ba68311ea/app/src/main/java/cc/ioctl/hook/msg/AioChatPieClipPasteHook.java#L263-L269

**Comment by Cryolitia** [comment]
@univeous 防止误触
