### ISSUE TITLE
[功能请求] 电脑 QQ NT 登录时，手机自动确认

### ISSUE THREAD

**Issue by YidaozhanYa** [cinit/QAuxiliary#249]
### QQ(TIM)版本/QQ(TIM) Version

8.19.13.9280

### 为什么你认为需要此功能

QQ NT 在登录时，会像早期微信一样要求手机端确认，很烦。

![图片](https://user-images.githubusercontent.com/73830635/207013517-1a2321ae-eaa3-4fbd-a7f0-e28a32a0c9f8.png)
<img src="https://user-images.githubusercontent.com/73830635/207013795-3afce3aa-5c69-42ad-895e-8d69219d0414.jpg" width="300rem" />

QQ NT 版本: Linux 2.0.1-429

### 具体功能需要/Specific features require

在电脑端 QQ NT 点击登录时，手机端自动确认（类似 WeXposed 模块的行为）。

> 确认界面对应 Activity: com.tencent.mobileqq.activity.DevlockQuickLoginActivity

**Comment by keta1** [comment]
这个版本没有测试资格不给用捏，挂着吧

**Comment by YidaozhanYa** [comment]
在 macOS 上大家都能用，macOS 版好像也是需要手机确认的。

**Comment by keta1** [comment]
我是 linux 用户
[Screenshot_2022-12-11-12-50-31-891_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/41381927/207027480-544b4dc8-0d1b-42cf-ac7f-2371be5bc4eb.jpg)

**Comment by YidaozhanYa** [comment]
QQ NT 已经加入自动登录，此  issue 关闭，
