### ISSUE TITLE
适配底部虚拟按键[功能请求] 

### ISSUE THREAD

**Issue by luckyzyx** [cinit/QAuxiliary#25]
### QQ(TIM)版本/QQ(TIM) Version

8.8.80

### 为什么你认为需要此功能

部分页面项目过多时会被虚拟按键挡住，比如QA-聊天页面
![IMG_20220317_203653](https://user-images.githubusercontent.com/46274354/158810724-3367b242-8040-4892-a4c0-1f2831dbfe11.jpg)

### 具体功能需要/Specific features require

希望页面底部留出虚拟按键的空间

**Comment by NextAlone** [comment]
这其实算 bug, 不是 功能请求

**Comment by cinit** [comment]
Fixed in l015f687cd229c407bf8ba49c6aced5392c41acbc
