### ISSUE TITLE
[功能请求] 屏蔽群帖子

### ISSUE THREAD

**Issue by wuyou-123** [cinit/QAuxiliary#252]
### QQ(TIM)版本/QQ(TIM) Version

QQ 8.9.23(3584)

### 为什么你认为需要此功能

QQ又更新了一个用不到的功能

### 具体功能需要/Specific features require

屏蔽群聊天页面的群帖子

**Comment by ZiduSama** [comment]
其实比起直接屏蔽群帖子，还是把已有的功能“移除右滑群应用”修改成“移除右滑群帖子”并保留群名称旁的切换按钮更靠谱点。
QQ正在逐渐抛弃精华消息。

**Comment by ZiduSama** [comment]
其实比起直接屏蔽群帖子，把已有的功能“移除右滑群应用”改为“移除右滑群帖子”并保留群名称旁的切换按钮更靠谱点。
现在群应用不再需要右滑，需要在群聊设置中手动进入。
以及，QQ正在逐渐抛弃精华消息（大概）。

**Comment by teble** [comment]
Duplicate of #254
