### ISSUE TITLE
[功能请求] 请求添加自动回复

### ISSUE THREAD

**Issue by Hakuin123** [cinit/QAuxiliary#253]
### QQ(TIM)版本/QQ(TIM) Version

3.4.8

### 为什么你认为需要此功能

1. 好友续火（高中生在校拿不到手机qwq）
2. TIM自带的自动回复功能，回复信息**不会在聊天记录中显示**
3. “请勿打扰”“忙碌”等支持自带自动回复的状态，不符合实际使用情况，有时只是没看手机而不是在忙

### 具体功能需要/Specific features require

~能用就行~

**Comment by cinit** [comment]
@Hakuin123 请使用 XAutoDaily

**Comment by Hakuin123** [comment]
> @Hakuin123 请使用 XAutoDaily

续火事小，主要是TIM党功能欠缺属于是

TIM自带的自动回复功能，回复信息**不会**在自己的聊天记录中显示

对方能看到回复，但是自己这边看不到自动回复消息

导致的后果比如说自动回复忘记关、聊天记录不连贯等等

**Comment by teble** [comment]
所以自动回复有什么特别的用处吗，关掉自动回复不就解决一切问题

**Comment by Hakuin123** [comment]
本身就是在自己忙的时候回复信息啊，正常用法呀，而且可能比较常用吧

但是TIM党在首页看不到自己的状态，聊天记录里面也没有自动回复消息提醒

导致咱除非去设置里面看看状态才知道自动回复到底开了没，很麻烦的一个操作不是吗

**Comment by teble** [comment]
@Hakuin123 建议使用QTool并且自行编写消息回复脚本

**Comment by Hakuin123** [comment]
可是咱小白不会啊😂
