### ISSUE TITLE
[Bug] 精简侧滑栏功能在8.9.25失效

### ISSUE THREAD

**Issue by Duck-Deng** [cinit/QAuxiliary#255]
### Steps to reproduce/复现步骤

在精简侧滑栏里任意勾选一些项目

### Expected behaviour/预期行为

被勾选的项目应该被移除

### Actual behaviour/实际行为

没有效果
![Screenshot_2022-12-18-21-15-20-597_com tencent mobileqq](https://user-images.githubusercontent.com/64295725/208301034-64057507-a548-40fd-842c-d2ffad93c1be.jpg)

### XPosed Framework you used/你使用的XP框架

lsposed zygisk版，1.8.5(6649)

### QQ(TIM)版本/QQ(TIM) Version

qq 8.9.25

### Module Version/模块版本

1.3.6.r1200.27c9975(1200)

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.3.6.r1200.27c9975
QQ8.9.25(3640)
PID: 6977, UID: 10258
cc.ioctl.hook.sideswipe.SimplifyQQSettingMe
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by Duck-Deng** [comment]
补充，这是我设置的项目
![Screenshot_2022-12-18-21-34-22-285_com tencent mobileqq](https://user-images.githubusercontent.com/64295725/208301267-7bc32948-868d-4075-bf0c-92e3725985cc.jpg)

**Comment by keta1** [comment]
fixed in fc2367ff2e09f4b51653d67f8f010c746e91b27e
