### ISSUE TITLE
[功能请求] 聊天字数统计同步到个性签名

### ISSUE THREAD

**Issue by EaGZcY** [cinit/QAuxiliary#257]
### QQ(TIM)版本/QQ(TIM) Version

QQ8.9.23

### 为什么你认为需要此功能

聊天字数统计如果同步到个性签名会更个性

### 具体功能需要/Specific features require

原本的聊天字数统计貌似只是在侧滑栏那显示，同步到个性签名不知道可不可以实现......频繁更改签名不知道会不会有事，可以几小时同步一次

**Comment by cinit** [comment]
QQ本来就有风控，你这显然是自投罗网。
