### ISSUE TITLE
[Bug] MessageStyle 气泡异常

### ISSUE THREAD

**Issue by l0z0y** [cinit/QAuxiliary#273]
### Steps to reproduce/复现步骤

1.点击聊天气泡弹出聊天界面
2.点击+显示最近聊天气泡界面
3.拖动顶部聊天气泡退出界面

### Expected behaviour/预期行为

正常退出

### Actual behaviour/实际行为

黑屏，黑屏恢复后会显示锁屏页面但无需解锁，重新进入桌面，故障排查中无异常报错日志

### XPosed Framework you used/你使用的XP框架

lsp

### QQ(TIM)版本/QQ(TIM) Version

8.9.23

### Module Version/模块版本

1.3.6r1216

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

功能异常列表无异常

**Comment by keta1** [comment]
听你的 描述像是 System UI 崩溃了。
请使用 其他 支持气泡的软件，测试他们的气泡是否会造成 相同的现象。
比如使用 telegram 进行测试

**Comment by keta1** [comment]
> 听你的 描述像是 System UI 崩溃了。 请使用 其他 支持气泡的软件，测试他们的气泡是否会造成 相同的现象。 比如使用 telegram 进行测试

如果其他软件的气泡也会导致 System UI 崩溃，建议尝试升级系统来解决问题
