### ISSUE TITLE
[功能请求] 发送自定义语音消息(发送自定义音频文件)

### ISSUE THREAD

**Issue by RedDragon0293** [cinit/QAuxiliary#274]
### QQ(TIM)版本/QQ(TIM) Version

8.9.2.8685

### 为什么你认为需要此功能

用于聊天，可以用语音发歌给大伙乐呵乐呵

### 联系到哪些已经存在的bug或者功能

 文本转语音发送

### 具体功能需要/Specific features require

可以选择音频文件，指定语音长度

**Comment by klxiaoniu** [comment]
现在已有其他模块支持这个功能了，可以关注下。

**Comment by RedDragon0293** [comment]
我已收到邮件。谢谢！I have received the email. Thank you!

**Comment by Cryolitia** [comment]
@RedDragon0293 你已收到邮件。不用客气！

**Comment by keta1** [comment]
@Cryolitia 他已收到邮件。不用客气！
