### ISSUE TITLE
[Bug] 文本转语音异常

### ISSUE THREAD

**Issue by RedDragon0293** [cinit/QAuxiliary#275]
### Steps to reproduce/复现步骤

1.聊天栏输入
#tts zh_CN
一段很长的话（也不用很长，大概6个汉字以上）
2.发送
3.失败

经过测试，系统tts能正常生成MP3文件，但是发送时语音时长设置错误(时长大约为汉字数*12,汉字越多时长越长)，当汉字数过多时提示发送失败

### Expected behaviour/预期行为

正常发送

### Actual behaviour/实际行为

无限发送失败

### XPosed Framework you used/你使用的XP框架

太极阴

### QQ(TIM)版本/QQ(TIM) Version

8.9.2.8685

### Module Version/模块版本

1.3.6.r1202.f6928c0

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

故障排查界面无异常

**Comment by duzhaokun123** [comment]
tts 发送大改 1202 已过时
