### ISSUE TITLE
[Bug] 聊天字数统计异常

### ISSUE THREAD

**Issue by RedDragon0293** [cinit/QAuxiliary#277]
### Steps to reproduce/复现步骤

开启后个性签名未被替换

### Expected behaviour/预期行为

替换

### Actual behaviour/实际行为

不替换

### XPosed Framework you used/你使用的XP框架

LSPatch

### QQ(TIM)版本/QQ(TIM) Version

8.9.25.10005

### Module Version/模块版本

1.3.6.r1220.5898d6d

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

故障排查无报错

**Comment by keta1** [comment]
fixed in ce48373370305120bcdaa963037eb889bb3f3739
