### ISSUE TITLE
模块作用以后 MIUI的平行窗口无法调用[Bug] 

### ISSUE THREAD

**Issue by ZenvHe** [cinit/QAuxiliary#279]
### Steps to reproduce/复现步骤

在MIUI fold系统中使用模块
系统设置中QQ界面选择平行窗口
打开QQ空间/设置等

### Expected behaviour/预期行为

QQ以平行窗口显示，如图
![IMG_20230101_201054](https://user-images.githubusercontent.com/98077240/210170196-ca8ac313-5f07-47af-a87f-3f1b9ae0f675.jpg)
![IMG_20230101_201114](https://user-images.githubusercontent.com/98077240/210170198-c2ef52fd-7997-4df1-bbf0-d0ac5329f737.jpg)

### Actual behaviour/实际行为

空间/设置等全屏打开
![IMG_20230101_201145](https://user-images.githubusercontent.com/98077240/210170201-f9fcf84d-f3ac-425e-95a9-a93ecc7c813e.jpg)
![IMG_20230101_201201](https://user-images.githubusercontent.com/98077240/210170202-8acc73e6-e030-4cff-bd06-fbc4155207ff.jpg)

### XPosed Framework you used/你使用的XP框架

LSPosed

### QQ(TIM)版本/QQ(TIM) Version

8.9.23

### Module Version/模块版本

1.3.6.r1220

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

模块正常激活，无功能异常，各类功能皆可实现。
问题就是不管啥版本的模块，啥版本的QQ，只要作用域勾选了QQ，哪怕启用安全模式都不能调用平行窗口。

**Comment by keta1** [comment]
开发者没有 MIUI fold，你先寄个设备过来）

**Comment by keta1** [comment]
在故障排查中 启用 安全模式， 再测试 是否影响平行窗口
我猜可能是你开了什么修改设备信息的功能，比如 改型号啥的冲突了

**Comment by ZenvHe** [comment]
安全模式开了以后 空间依然不能平行窗口，设置倒是可以了🤡

**Comment by keta1** [comment]
@ZenvHe 你确定在 LSPosed 里禁用模块后空间能用吗

**Comment by ZenvHe** [comment]
是的

**Comment by keta1** [comment]
反正没设置也修不了，你自己研究下那个功能影响了设置，把他关掉就好，安全模式会关掉所有功能

**Comment by ZenvHe** [comment]
彳亍（悲
