### ISSUE TITLE
[功能请求] 屏蔽刷一刷抢红包

### ISSUE THREAD

**Issue by Sanheiii** [cinit/QAuxiliary#280]
### QQ(TIM)版本/QQ(TIM) Version

8.9.20.9725

### 为什么你认为需要此功能

每到特定时间QQ会反复骚扰用户去刷红包，除了开刷然后再退出以外没有任何关闭提示的方法

### 具体功能需要/Specific features require

屏蔽在特定时刻出现的刷一刷抢红包

**Comment by ayanami-desu** [comment]
我也看到那玩意了

**Comment by cinit** [comment]
附议, I have the same problem.

**Comment by Huaxidesu** [comment]
确实，看的好恶心，下拉刷红包和左上角的红包图标

**Comment by Sanheiii** [comment]
> 我也看到那玩意了



> 附议, I have the same problem.



> 确实，看的好恶心，下拉刷红包和左上角的红包图标

今天发现官方有关闭入口，只是比较隐蔽
侧边栏->设置->关于QQ与帮助->反馈->如何关闭春节红包活动?->此处进行关闭
