### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by 56662017** [cinit/QAuxiliary#281]
### Steps to reproduce/复现步骤

杂项里的自定义机型无法生效

### Expected behaviour/预期行为

生效

### Actual behaviour/实际行为

没有生效

### XPosed Framework you used/你使用的XP框架

1.8.5-6649

### QQ(TIM)版本/QQ(TIM) Version

qq

### Module Version/模块版本

8.9.28

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

里面没有自定义机型

**Comment by keta1** [comment]
重复 #174
