### ISSUE TITLE
[bug] 文字转语音功能报错

### ISSUE THREAD

**Issue by Pew2018** [cinit/QAuxiliary#286]
### Steps to reproduce/复现步骤

按照格式输入文字
长按发送键

### Expected behaviour/预期行为

正常情况下应该输出语音并发送

### Actual behaviour/实际行为

在输入正确格式的文字后 长按发送键报错
![Screenshot_20230108-003119-01](https://user-images.githubusercontent.com/94493866/211161252-5d726956-e436-49f4-bd1b-839a060ff325.jpeg)

### XPosed Framework you used/你使用的XP框架

Lsposed 1.8.5（6649）

### QQ(TIM)版本/QQ(TIM) Version

QQ 8.9.15

### Module Version/模块版本

1.3.7.r1258.873fd07

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.3.7.r1258.873fd07
QQ8.9.15(3408)
PID: 32272, UID: 10311
io.github.duzhaokun123.hook.SendTTSHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by duzhaokun123** [comment]
@Pew2018 用的什么 TTS 引起

**Comment by Pew2018** [comment]
系统自带的 Google语音服务

**Comment by duzhaokun123** [comment]
@Pew2018 看错了 和引擎无关 看成找不到输入文件了
