### ISSUE TITLE
[功能请求] 戳一戳解除时间限制

### ISSUE THREAD

**Issue by 6DDUU6** [cinit/QAuxiliary#288]
### QQ(TIM)版本/QQ(TIM) Version

8.9.28

### 为什么你认为需要此功能

我想猛猛戳别人

### 联系到哪些已经存在的bug或者功能

类名：com.tencent.mobileqq.u1.a
方法名：L4
返回值：boolean
返回值修改为true即可猛猛戳。

### 具体功能需要/Specific features require

连续戳别人头像时，会有弹窗限制戳戳。

**Comment by cinit** [comment]
Added in 6de1dd193ddb01af010e224e3a5c8f943dad2b6d

**Comment by 6DDUU6** [comment]
> Added in [6de1dd1](https://github.com/cinit/QAuxiliary/commit/6de1dd193ddb01af010e224e3a5c8f943dad2b6d)

想问一下原始方法名 类名怎么得到呀，我这里全是混淆的QAQ

**Comment by keta1** [comment]
> > Added in [6de1dd1](https://github.com/cinit/QAuxiliary/commit/6de1dd193ddb01af010e224e3a5c8f943dad2b6d)
> 
> 想问一下原始方法名 类名怎么得到呀，我这里全是混淆的QAQ

可能某一个版本没混淆，大多数时候是猜的，这个原始名字只是用来看的
