### ISSUE TITLE
[Bug] qq新版本防撤回功能部分失效

### ISSUE THREAD

**Issue by xq20190308** [cinit/QAuxiliary#289]
### Steps to reproduce/复现步骤

当qq未清理后台时，qq防撤回功能正常。
当qq清理后台时，qq防撤回功能失效。
怀疑是mipush的原因，因为qq8.8.50旧版本正常。
无论是否开启justpush，问题仍然存在

### Expected behaviour/预期行为

提示防撤回信息

### Actual behaviour/实际行为

当qq完全清理后天时对方撤回消息，本人qq没有任何提示，既没有防撤回通知，也没有已撤回通知，就好像对方从未发送过消息。

### XPosed Framework you used/你使用的XP框架

LSPosed

### QQ(TIM)版本/QQ(TIM) Version

QQ8.9.25

### Module Version/模块版本

1.3.7.r1263

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.3.7.r1263.6de1dd1
QQ8.9.25(3640)
PID: 17706, UID: 10381
cc.ioctl.hook.msg.RevokeMsgHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by keta1** [comment]
@xq20190308 防撤回 必须保证 qq 在 后台存活
