### ISSUE TITLE
[Bug] QQ8.9.8(3238)自定义骰子猜拳无效

### ISSUE THREAD

**Issue by QianJue-CN** [cinit/QAuxiliary#292]
### Steps to reproduce/复现步骤

点击后直接发生骰子或猜拳

### Expected behaviour/预期行为

可以选择点数

### Actual behaviour/实际行为

直接发送了骰子

### XPosed Framework you used/你使用的XP框架

太极:青钢影·10.1.0.10141326-8861

### QQ(TIM)版本/QQ(TIM) Version

8.9.8(3238)

### Module Version/模块版本

1.3.7.r1247.db93733(1247)

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.3.7.r1247.db93733
QQ8.9.8(3238)
PID: 13562, UID: 99910359
cc.ioctl.hook.chat.CheatHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by keta1** [comment]
测试没问题
