### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by jack-pmy** [cinit/QAuxiliary#297]
### Steps to reproduce/复现步骤

打开qa
打开通知设置的message通知和老版本的什么什么通知
再关闭

### Expected behaviour/预期行为

QQ正常通知，能够通知时震动

### Actual behaviour/实际行为

没有通知震动

### XPosed Framework you used/你使用的XP框架

新版本

### QQ(TIM)版本/QQ(TIM) Version

8.9.25(3640)

### Module Version/模块版本

1.3.8.r1274.a41443f(1274)

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

没

**Comment by huajijam** [comment]
请详细描述功能名称与复现步骤 提供详细的xposed框架信息

**Comment by Cryolitia** [comment]
![IMG_20230119_201955_576.jpg](https://user-images.githubusercontent.com/23723294/213441554-89793beb-14d4-403a-87c1-6e914e6baed2.jpg)

自己去系统的通知设置里面设
