### ISSUE TITLE
[Bug] 频道防撤回无效

### ISSUE THREAD

**Issue by YiRanlol** [cinit/QAuxiliary#300]
### Steps to reproduce/复现步骤

1.进入频道
2.查看被撤回的消息

### Expected behaviour/预期行为

依旧能看到被撤回的消息

### Actual behaviour/实际行为

消息成功被撤回

### XPosed Framework you used/你使用的XP框架

太极

### QQ(TIM)版本/QQ(TIM) Version

8.9.25(3640)

### Module Version/模块版本

1.3.6

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

无报错

**Comment by lliioollcn** [comment]
已经存在相同反馈 #223
