### ISSUE TITLE
[功能请求] 合并转发支持隐藏群号/QQ

### ISSUE THREAD

**Issue by klxiaoniu** [cinit/QAuxiliary#303]
### QQ(TIM)版本/QQ(TIM) Version

8.9.28

### 为什么你认为需要此功能

QQ 转发合并消息会附带群号和 QQ号等信息，可能导致信息泄露，而截图打码又相当于没打码。因合并消息为客户端生成，因此也许有可能实现隐藏群号/QQ 的功能。

### 联系到哪些已经存在的bug或者功能

查看合并转发消息

### 具体功能需要/Specific features require

当多选后点合并转发时，弹出选项可勾选隐藏群号/QQ号，选择则将指定数据替换为 0 等无关信息（QQ号替换或许会影响展示，替换群号可能更加有用）

**Comment by CrepaRB** [comment]
显示别人的群号/QQ号，隐藏自己的群号/QQ号😂
说实话我是不太希望加入，真这么整的话…嗯，纯纯的自寻死路
