### ISSUE TITLE
[功能请求] 请求加入复读二次确认

### ISSUE THREAD

**Issue by IsaacWangTT** [cinit/QAuxiliary#305]
### QQ(TIM)版本/QQ(TIM) Version

8.9.28

### 为什么你认为需要此功能

向上或向下滑动聊天窗口，或者执行某些操作时，容易误触到复读按钮（或许是我屏幕太小）

### 具体功能需要/Specific features require

点击复读按钮后弹窗以确认与取消操作

**Comment by frg2089** [comment]
我觉得你可以试试看`消息+1 Plus`里的双击复读功能
