### ISSUE TITLE
[功能请求]频道与q群的下载路径 重定向 分开

### ISSUE THREAD

**Issue by bzmshang** [cinit/QAuxiliary#310]
### QQ(TIM)版本/QQ(TIM) Version

8.9.28(3700)

### 为什么你认为需要此功能

目前QA的更改文件下载路径是直接更改/storage/emulated/0/Android/data/com.tencent.mobileqq/Tencent/QQfile_recv/，一般更改路径都喜欢更改到download里面去，但是，qq频道这个下载文件也在这个路径里面，里面包括了一些无用缓存图片，这就导致，有时候翻qq的相册，就会翻到频道里面的一些无用缓存图片，所以，是不是可以将q群文件的下载与频道的下载区分开来，这样图片就不会干扰了

### 具体功能需要/Specific features require

下载文件重定向

**Comment by Hicores** [comment]
> > 测试一下最新的ci版看看有没有分开了
> 
> 是分开了 但是这个分开是 频道文件留在了qq自己的下载目录里面 /storage/emulated/0/Android/data/com.tencent.mobileqq/Tencent/QQfile_recv/nt_qq_23169f31ee5d7b7e1aa5537d1ef2d/File/Ori/ 重定向的目录里面只有群下载的文件
> 
> 不知道是不是就这样设计的

是改成这样了,频道的文件丢回默认的位置,然后重定向的就是群下载的文件,频道下载的文件由于QQ的设计问题和缓存混在一起难以分开也一并丢回去了
