### ISSUE TITLE
[功能请求] 自定义语音合成，可以选择音频文件，指定语音长度

### ISSUE THREAD

**Issue by baiqilingnai** [cinit/QAuxiliary#314]
### QQ(TIM)版本/QQ(TIM) Version

8.88

### 为什么你认为需要此功能

用于聊天，可以用语音发歌给大伙乐呵乐呵

### 具体功能需要/Specific features require

可以选择音频文件，指定语音长度

**Comment by Hakuin123** [comment]
https://github.com/cinit/QAuxiliary#不会支持的功能

> - 修改聊天记录等可能被恶意利用的功能

🤔

**Comment by Hakuin123** [comment]
#274

**Comment by qwq233** [comment]
@Hakuin123 我已收到邮件。谢谢！I have received the email. Thank you!

**Comment by klxiaoniu** [comment]
现在已有其他模块支持这个功能了，可以关注下。
