### ISSUE TITLE
功能请求：可以加一个去掉启动图的功能吗

### ISSUE THREAD

**Issue by k650dg4d2** [cinit/QAuxiliary#32]
### QQ(TIM)版本/QQ(TIM) Version

8.8.83

### 为什么你认为需要此功能

因为QQ的启动图在夜晚打开的时候有几秒会亮瞎眼

### 具体功能需要/Specific features require

在首次打开的时候不加载启动图

**Comment by NextAlone** [comment]
加启动图是为了掩饰消息加载, 你确定要去掉他的遮羞布吗?

**Comment by NextAlone** [comment]
抱歉, 点成关闭了

**Comment by k650dg4d2** [comment]
> 加启动图是为了掩饰消息加载, 你确定要去掉他的遮羞布吗?

那就把他的白色底板换成透明的吧，夜间模式让他自己是黑色的，白天模式让他是白色的背景

**Comment by keta1** [comment]
已经支持为白天 夜间设置不同启动图
