### ISSUE TITLE
[功能请求] 根据QQ普通模式/体验模式/XX模式适配qa设置项

### ISSUE THREAD

**Issue by haogena** [cinit/QAuxiliary#321]
### QQ(TIM)版本/QQ(TIM) Version

8.9.28

### 为什么你认为需要此功能

qq日益复杂，不少用户选择使用简约风的设置-通用-体验模式或更换tim。

### 联系到哪些已经存在的bug或者功能

qq体验模式界面较普通模式会少很多元素，qa设置项基于普通模式开发，虽然不缺功能但并不相匹配

### 具体功能需要/Specific features require

建议增加进入qa自动识别/用户选择普通/体验模式，根据选择匹配不同设置菜单

**Comment by cinit** [comment]
设计不同设置菜单太过麻烦，请按需使用功能搜索。
