### ISSUE TITLE
[功能请求] QQ8.6.0 小程序去开屏广告

### ISSUE THREAD

**Issue by OnlyNaya** [cinit/QAuxiliary#333]
### QQ(TIM)版本/QQ(TIM) Version

QQ 8.6.0

### 为什么你认为需要此功能

看到广告就烦，有时候还会误点
小程序还加广告，本来就花里胡哨的，让人发火
![Screenshot_20230224_115131_com huawei android launcher](https://user-images.githubusercontent.com/119770909/221128895-8fdb3cb9-efa5-466e-8e26-a85c97df6dd7.jpg)

### 具体功能需要/Specific features require

可以先尝试滞空此方法实现去广告
以下为广告控件方法签名
Lcom/tencent/mobileqq/mini/widget/MiniLoadingAdLayout;->initUI()V
广告图片组件id：ncm 可能因版本而造成差异
![Screenshot_20230224_161914_bin mt plus](https://user-images.githubusercontent.com/119770909/221129274-5da75154-deaa-4041-81c2-b5a0b826a8ed.jpg)
若上述做法无效，请作者大大研究屏蔽方法，谢谢

**Comment by cinit** [comment]
8a988b0d6f75f9e77a783c9fcef82285c6df1da7
