### ISSUE TITLE
[功能请求] 划后台进入关闭qq

### ISSUE THREAD

**Issue by jiushu9** [cinit/QAuxiliary#337]
### QQ(TIM)版本/QQ(TIM) Version

8.8.98

### 为什么你认为需要此功能

qq在后台的耗电很恐怖，但是从账号管理那里关闭qq，耗电会好很多倍
![Screenshot_2023_0301_103648](https://user-images.githubusercontent.com/104915458/222031064-f3bbb2fe-b7d7-40bf-9651-5fd048eb7d97.png)

### 具体功能需要/Specific features require

希望划后台能直接进入那个状态，或者将那个移动到首页

**Comment by keta1** [comment]
你应该使用 qq 省电模块
