### ISSUE TITLE
[功能请求] 搜索文件时在全部群文件检索

### ISSUE THREAD

**Issue by whx9986** [cinit/QAuxiliary#34]
### QQ(TIM)版本/QQ(TIM) Version

8.8.50.6735

### 为什么你认为需要此功能

一个实例：加了一些电子书群，有时候要找一本书的txt，但是不知道哪个群里会有，而qq有时候会展示别的群是否有，有时候不显示，要一个一个群的去找，特别麻烦，最后还可能全都没有。而且不止是txt，找其他word，PDF，apk各种文件也是，要一个群一个群的挨个检索。

### 联系到哪些已经存在的bug或者功能

QQ自身是有一定这个功能的，A群搜索一个文件，如果没有，而B群有，就会在下方展示  其他群文件  ，但是这个功能时常失效

### 具体功能需要/Specific features require

希望大佬们能做出来这样一个功能：搜群文件时，会在加入的所有群检索，显示出所有结果，不用一个一个群的去寻找。

**Comment by molanp** [comment]
新版QQ搜索顶栏好像一直都有“”查看其他结果“”的选项
