### ISSUE TITLE
[功能请求] 请支持Android10，我Mix2SMiui最后一个稳定版，新版不生效，旧版能用，谢谢

### ISSUE THREAD

**Issue by OneMiOne** [cinit/QAuxiliary#342]
### QQ(TIM)版本/QQ(TIM) Version

QQV8.9.15

### 为什么你认为需要此功能

我不知道是不是BUG，但我之前V1.3.8的时候就不生效了，我看了更新日志，没看到这个修复的说明，所以想问问是不是不在支持Android10了，主要我现在用旧版QQ被强制退出了，想来问问，我LSPosed没问题，更新过了，V1.3.8还是用不了，如果可以的话希望可以支持Android10，谢谢

### 具体功能需要/Specific features require

支持Android10，谢谢

**Comment by duzhaokun123** [comment]
@OneMiOne 虽然但是 理论支持 请按 bug 反馈
