### ISSUE TITLE
[功能请求] TTS语音合成的改善建议

### ISSUE THREAD

**Issue by Sorrow-Scarlet** [cinit/QAuxiliary#346]
### QQ(TIM)版本/QQ(TIM) Version

TIM 3.4.6

### 为什么你认为需要此功能

**娱乐**  

TTS在QQ上的功能娱乐性大于实用性

### 联系到哪些已经存在的bug或者功能

已存在功能：TTS

### 具体功能需要/Specific features require

设置等待  

我有注意到TTS一直提示的错误是trycounts，建议设置等待时长

具体实现可以试着获取tts生成的mp3，等文件大小不变的情况下发送

在此期间还请加个语音生成中的对话框2333

**Comment by duzhaokun123** [comment]
@Sorrow-Scarlet 我先研究一下 trycount 到底是在干什么

**Comment by duzhaokun123** [comment]
@Sorrow-Scarlet 就说哪来的 trycount
原来你没更新
