### ISSUE TITLE
[Bug] 使用MessageStyle气泡通知后会出现无法删除的通知管理项目

### ISSUE THREAD

**Issue by BuRanYY** [cinit/QAuxiliary#351]
### Steps to reproduce/复现步骤

复现步骤如下
1.打开MessageStyle通知功能
2.接收消息后使用气泡模式
3.这时已经在通知管理内出现QQ PLUS进化通知内新增通知项
4.点击管理-QQ设置-进入对话泡界面-删除对话泡内对应对话
5.通知管理内新增的通知项无法被删除（如果一直重复操作会越来越多新增的通知项，并且都是重复的）

### Expected behaviour/预期行为

正常情况下应该不出现重复通知项，希望能够删除多余的通知项

### Actual behaviour/实际行为

![Screenshot_2023-03-18-00-39-08-746_com android settings-edit](https://user-images.githubusercontent.com/128172286/225965896-9f51629d-0fbf-4ea2-8ffe-6115c7c5898d.jpg)
![Screenshot_2023-03-18-00-39-33-489_com android settings-edit](https://user-images.githubusercontent.com/128172286/225965909-2f7dce04-598c-4add-9402-02abd5a121ad.jpg)

### XPosed Framework you used/你使用的XP框架

LSPosed 1.8.6.6712

### QQ(TIM)版本/QQ(TIM) Version

QQ 8.9.28

### Module Version/模块版本

1347

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

复现步骤如下
1.打开MessageStyle通知功能
2.接收消息后使用气泡模式
3.这时已经在通知管理内出现QQ PLUS进化通知内新增通知项
4.点击管理-QQ设置-进入对话泡界面-删除对话泡内对应对话
5.通知管理内新增的通知项无法被删除（如果一直重复操作会越来越多新增的通知项，并且都是重复的）

**Comment by Cryolitia** [comment]
@BuRanYY 管理-QQ设置是个什么东西

**Comment by BuRanYY** [comment]
> @BuRanYY 管理-QQ设置是个什么东西
管理-QQ设置是进入对话泡的方式
![0B192EEE88F0C649415225EAF4D48658](https://user-images.githubusercontent.com/128172286/226083399-d0ad840c-0820-43c5-94e6-dd13609fca95.jpg)
![1A9B3D76A5F45413A2226763533035A5](https://user-images.githubusercontent.com/128172286/226083402-71e9115c-f760-415a-9c9f-4e8b7a5259a9.jpg)
但这并不重要，重点是我希望能够有一个合理的方式删除通知管理内创建的那些通知管理项目
如下图这些
![225965909-2f7dce04-598c-4add-9402-02abd5a121ad](https://user-images.githubusercontent.com/128172286/226083449-e7350928-accf-4186-9a2b-931164b40424.jpg)

![image](https://user-images.githubusercontent.com/128172286/226083515-082e7c9c-9af9-4ae9-b337-7a814857fdfa.png)
图上这些内容都是使用对话泡后创建的，对话泡内可以通过这里删除，但是删除后重新创建就会增加一个，而删除却不会删除通知管理内的项目
希望能够在删除对话泡内的选项后，也能对应删除通知管理内的项目

**Comment by Cryolitia** [comment]
这是你的手机系统的问题，不在我们的解决范围之内，而且你闲的没事删他干什么

**Comment by Cryolitia** [comment]
![Screenshot_20230318-115632](https://user-images.githubusercontent.com/23723294/226083757-51d7007c-fb6b-47b9-8cc0-4f36c5756721.png)
我这边的通知渠道是正常的，所有功能都已经开启

**Comment by BuRanYY** [comment]
> 这是你的手机系统的问题，不在我们的解决范围之内，而且你闲的没事删他干什么

系统来自MIUI，删除他是因为暂时不想使用对话泡了
