### ISSUE TITLE
[Bug] QQ更新了侧滑栏导致QA侧滑栏精简失效，似乎是灰测中

### ISSUE THREAD

**Issue by lvzhenbo** [cinit/QAuxiliary#366]
### Steps to reproduce/复现步骤

1. 使用收到侧滑栏更新的账号
2. 打开侧滑栏

### Expected behaviour/预期行为

QA侧滑栏精简正常

### Actual behaviour/实际行为

QA侧滑栏精简失效

### XPosed Framework you used/你使用的XP框架

LSPosed

### QQ(TIM)版本/QQ(TIM) Version

8.9.35

### Module Version/模块版本

1.4.1.r1395.eccb8bb(1395)

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.4.1.r1395.eccb8bb
QQ8.9.35(3814)
PID: 23165, UID: 10293
cc.ioctl.hook.sideswipe.SimplifyQQSettingMe
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by lvzhenbo** [comment]
https://user-images.githubusercontent.com/32427677/228417952-15518047-e098-4096-b4e5-5de578459c95.mp4

**Comment by klxiaoniu** [comment]
已添加临时性功能：侧滑栏-禁止新样式侧滑栏
