### ISSUE TITLE
[语言录制超过1分钟] 

### ISSUE THREAD

**Issue by fgr178707** [cinit/QAuxiliary#368]
### QQ(TIM)版本/QQ(TIM) Version

8.9.35.10440

### 为什么你认为需要此功能

语言消息超过1分钟

### 具体功能需要/Specific features require

语言消息超过1分钟

**Comment by keta1** [comment]
@fgr178707 你需要开一个会员

**Comment by cinit** [comment]
目前开发者没有这样的需求，暂不考虑开发此功能，您也可以尝试自行编写代码后 PR。
