### ISSUE TITLE
[Bug] 精简聊天消息菜单存表情失效

### ISSUE THREAD

**Issue by Rudfio** [cinit/QAuxiliary#376]
### Steps to reproduce/复现步骤

精简聊天气泡长按菜单，选择精简存表情，然而并没有精简存表情
![Screenshot_20230402_212931_com tencent mobileqq](https://user-images.githubusercontent.com/125795701/229356254-aceaa741-50d0-4ec8-a54b-fc7517f7934c.jpg)
![Screenshot_20230402_212913_com tencent mobileqq_edit_151630820566966](https://user-images.githubusercontent.com/125795701/229356257-4491e49d-e677-4d3a-aa16-ce8d9345d58a.jpg)

### Expected behaviour/预期行为

精简存表情

### Actual behaviour/实际行为

没有精简存表情

### XPosed Framework you used/你使用的XP框架

太极

### QQ(TIM)版本/QQ(TIM) Version

QQ8.6.0

### Module Version/模块版本

1.4.1.r1395.eccb8bb

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.4.1.r1395.eccb8bb
QQ8.6.0(1672)
PID: 17483, UID: 10290
xyz.nextalone.hook.SimplifyChatLongItem
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by klxiaoniu** [comment]
已尝试修复，请更新CI版再试
