### ISSUE TITLE
[功能请求] 高版本中的“体验模式”主题需要在群聊成员详情页显示加入该群时间的具体日月

### ISSUE THREAD

**Issue by KiWinger** [cinit/QAuxiliary#383]
### QQ(TIM)版本/QQ(TIM) Version

v8.9.35.10440 （更新体验模式后的所有版本）

### 为什么你认为需要此功能

普通模式可以看见日月；
但体验模式看不见，算作功能的补充。

### 具体功能需要/Specific features require

![IMG_20230405_140202](https://user-images.githubusercontent.com/49084827/229994405-e0b29baf-9b83-4057-adda-bb3d773d2d26.jpg)

红框处“2022年加入该群”
改成：2022年xx月xx日加入该群

**Comment by klxiaoniu** [comment]
已添加"显示完整群成员入群时间"，位于辅助功能-好友和资料卡
