### ISSUE TITLE
[功能请求] 解除QQ最多登录10账号限制

### ISSUE THREAD

**Issue by bili-22** [cinit/QAuxiliary#389]
### QQ(TIM)版本/QQ(TIM) Version

8.9.38

### 为什么你认为需要此功能

号多的时候方便切换账号，不用重新登录

### 联系到哪些已经存在的bug或者功能

娱乐功能-添加账号

添加账号功能可以添加超过十个账号，但是在登录时依然会提示账号已满

### 具体功能需要/Specific features require

登录10个以上的账号

**Comment by cinit** [comment]
@bili-22 和官方作对是没有好下场的
