### ISSUE TITLE
[功能请求] 以语音形式发送音频文件

### ISSUE THREAD

**Issue by sovzzz** [cinit/QAuxiliary#395]
### QQ(TIM)版本/QQ(TIM) Version

8.9.33.10335

### 为什么你认为需要此功能

发送一些搞怪的语音包。
如果通过语音包app来发送，需要上传、审核、每次发送还需要打开app十分麻烦。由于这类app都是通过外放加麦克风实现的，在嘈杂的环境中效果很差劲。

### 联系到哪些已经存在的bug或者功能

语音消息转发
文字转语音发送
xposed模块彩豆有此功能，但已经停更不支持现有qq版本

### 具体功能需要/Specific features require

通过内部存储空间管理选择音频文件进行处理，发送。

**Comment by dix8** [comment]
支持！

**Comment by klxiaoniu** [comment]
现在已有其他模块支持这个功能了，可以关注下。

**Comment by sovzzz** [comment]
> 现在已有其他模块支持这个功能了，可以关注下。

好的，是哪个模块，能指个路吗？
