### ISSUE TITLE
[功能请求] 屏蔽头像挂件

### ISSUE THREAD

**Issue by woxihuanmaogong** [cinit/QAuxiliary#407]
### QQ(TIM)版本/QQ(TIM) Version

8.9.38

### 为什么你认为需要此功能

资料卡屏蔽头像挂件失效 聊天界面无法屏蔽

### 具体功能需要/Specific features require

想要屏蔽头像挂件 拜托了

**Comment by klxiaoniu** [comment]
@woxihuanmaogong 最新CI版已修复，资料卡-屏蔽头像挂件
