### ISSUE TITLE
[功能请求] 拍一拍所有人

### ISSUE THREAD

**Issue by Andy-Chuck** [cinit/QAuxiliary#411]
### QQ(TIM)版本/QQ(TIM) Version

QQ8.9.5

### 为什么你认为需要此功能

增加趣味性

### 具体功能需要/Specific features require

可以拍一拍群列表里的任意一个人，不论他最近是否发言

**Comment by WsureDev** [comment]
批量操作有可能直接冻结号，参考批量修改群名片

**Comment by klxiaoniu** [comment]
似乎暂时无计划开发此功能。

**Comment by xiao-k233** [comment]
> 似乎暂时无计划开发此功能。

这不是wxb插件作者吗
doge

**Comment by klxiaoniu** [comment]
@xiao-k233 一个时代过去了

**Comment by xiao-k233** [comment]
> @xiao-k233 一个时代过去了

是啊疫情结束了

**Comment by wujie-eng** [comment]
何必缅怀过去，直面生活




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cinit/QAuxiliary"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月22日(星期一) 晚上9:47
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [cinit/QAuxiliary] [功能请求] 拍一拍所有人 (Issue #411)





  
@xiao-k233 一个时代过去了
  
是啊疫情结束了
