### ISSUE TITLE
底栏tab侧边栏显示添加频道和消息小红点

### ISSUE THREAD

**Issue by xiuciy** [cinit/QAuxiliary#412]
### QQ(TIM)版本/QQ(TIM) Version

QQ

### 为什么你认为需要此功能

1.tab底栏自动到侧边栏之后不能打开频道了，虽然很少看频道但是还是希望能有这个入口
2.没有消息数量小红点不能快捷查看确认是否消息，最好能重复点消息栏目后能像原版QQ那样直接自动滑到消息列表
3.一样点侧边栏的消息/频道/动态/联系人后能自动左滑侧边栏
不知道我讲清楚没有，感谢作者

### 具体功能需要/Specific features require

1.底栏tab侧边栏显示添加频道入口
2.侧边栏显示消息数量小红点
3.点击消息/频道/联系人/动态后自动左滑侧边栏

**Comment by klxiaoniu** [comment]
1. 此为娱乐功能，维护几率低；
2. 因频道界面无法通过侧滑动作打开侧滑栏，导致卡在频道界面，因此没有加上此项。
