### ISSUE TITLE
[功能请求] 添加 Ctrl+Enter 发送消息的快捷键

### ISSUE THREAD

**Issue by SlimeNull** [cinit/QAuxiliary#419]
我知道这很离谱， 但是我确实在使用物理键盘操作手机。希望有一个能够为发送消息添加快捷键的选项

（虽然默认 QQ 可以设置回车发送消息， 但是我发送消息的内容时常包含换行， 所以这个东西对我来讲并不友好）

如果能弄 Ctrl+Enter 发送消息， 那就太感谢了

**Comment by cinit** [comment]
@SlimeNull 很抱歉，但是我最近确实没时间。

**Comment by teble** [comment]
虽然但是，shift + enter不是就能换行吗（不知道手机上是什么样的表现，至少电脑上是如此）

**Comment by superen7527** [comment]
不是不做了吗？还能提issue？还是会复活？

**Comment by Cryolitia** [comment]
@superen7527 百足之虫，死而不僵

**Comment by snowingmerak** [comment]
> 不是不做了吗？还能提issue？还是会复活？

肯定会复活，尤其是基于electron的新qq普及以后，直接改一个平台就全平台可用了，即使作者大佬不打算复活也会有别人试着复活

**Comment by Cryolitia** [comment]
@snowingmerak 就你话多

**Comment by teble** [comment]
@snowingmerak 就你话多

**Comment by WsureDev** [comment]
非常赞成，这个功能对平板配键盘用户非常有用，以及通过qtscrcpy adb投屏用户来说，简直是上班摸鱼神器，再也不用打一句话点一下发送

**Comment by klxiaoniu** [comment]
已添加，试试效果
