### ISSUE TITLE
[功能请求] 希望可以去掉qq的启动图

### ISSUE THREAD

**Issue by freedomspiritJohn** [cinit/QAuxiliary#422]
### QQ(TIM)版本/QQ(TIM) Version

8.9.30

### 为什么你认为需要此功能

因为启动图影响打开的时间，而且完全没必要加启动图。直接点击打开到主界面就行了

### 联系到哪些已经存在的bug或者功能

去掉的话接受消息可能会有延迟，但是没有影响，与其一直看QQ的启动图页面，不如看看自己聊天页面更有用一些。

### 具体功能需要/Specific features require

打开QQ的时候没有启动图

**Comment by EnvyNie** [comment]
今天QQ启屏竟然是原神广告，请求作者顺便干了

**Comment by klxiaoniu** [comment]
意义不大，启动图显示时其实同时在加载内容，即时去掉了启动图也是要等的

**Comment by freedomspiritJohn** [comment]
> 意义不大，启动图显示时其实同时在加载内容，即使去掉了启动图也是要等的

意义不在于启动图本身和速度。而是不用在晚上开启深色模式后，第一次打开QQ会特别亮刺眼。

**Comment by klxiaoniu** [comment]
> > 意义不大，启动图显示时其实同时在加载内容，即使去掉了启动图也是要等的
> 
> 意义不在于启动图本身和速度。而是不用在晚上开启深色模式后，第一次打开QQ会特别亮刺眼。

你猜猜启动图有这个切换过程，里面的界面有没有

**Comment by klxiaoniu** [comment]
> > > > 意义不大，启动图显示时其实同时在加载内容，即使去掉了启动图也是要等的
> > > 
> > > 
> > > 意义不在于启动图本身和速度。而是不用在晚上开启深色模式后，第一次打开QQ会特别亮刺眼。
> > 
> > 
> > 你猜猜启动图有这个切换过程，里面的界面有没有
> 
> 我之前用修改版的qq就是没有启动图，一启动就是一个透明色的背景图。当然，是黑色的。

那你用吧
