### ISSUE TITLE
[功能请求] 添加盘古功能

### ISSUE THREAD

**Issue by MicroCBer** [cinit/QAuxiliary#423]
### QQ(TIM)版本/QQ(TIM) Version

/

### 为什么你认为需要此功能

> # 為什麼你們就是不能加個空格呢？
>   
> 如果你跟我一樣，每次看到網頁上的中文字和英文、數字、符號擠在一塊，就會坐立難安，忍不住想在它們之間加個空格。這個外掛（支援 Chrome 和 Firefox）正是你在網路世界走跳所需要的東西，它會自動替你在網頁中所有的中文字和半形的英文、數字、符號之間插入空白。
> 
> 漢學家稱這個空白字元為「盤古之白」，因為它劈開了全形字和半形字之間的混沌。另有研究顯示，打字的時候不喜歡在中文和英文之間加空格的人，感情路都走得很辛苦，有七成的比例會在 34 歲的時候跟自己不愛的人結婚，而其餘三成的人最後只能把遺產留給自己的貓。畢竟愛情跟書寫都需要適時地留白。
> 
> 與大家共勉之。

https://github.com/vinta/pangu.js

### 具体功能需要/Specific features require

在发送消息/收到消息时 自动执行盘古

**Comment by NextAlone** [comment]
@MicroCBer 是好的

**Comment by keta1** [comment]
node js runtime 太大了,感觉不合适

**Comment by MicroCBer** [comment]
> node js runtime 太大了,感觉不合适

![image](https://github.com/cinit/QAuxiliary/assets/66859419/8bddcd68-6b9c-4707-9f85-ec23720ea709)

有没有一种可能

Cpp 的也有我之前做 Pangu Everywhere 的时候转写的

这种小库啥语言都可以做的 根本不依赖 node；非要用 js 的话可以用浏览器自带的

**Comment by MicroCBer** [comment]
<video src=https://github-production-user-asset-6210df.s3.amazonaws.com/66859419/239703997-72a6bdbe-f44f-415e-bc24-5687994072f2.mp4 />

PC版效果展示

**Comment by NextAlone** [comment]
> 
> ![GIF 2023-5-21 2-40-02](https://github.com/cinit/QAuxiliary/assets/66859419/7ffdc1a6-7adf-4bf4-ba8a-e9adacbda8cc)
> 
> 
> PC版效果展示

您应该在Mobile QQ on Android 重构（Android QQ NT）期间，向官方反馈此需求，并且由官方进行实现。

**Comment by MicroCBer** [comment]
> 您应该在Mobile QQ on Android 重构（Android QQ NT）期间，向官方反馈此需求，并且由官方进行实现。
> 
> 经观察，微信 on Android已实现此功能，我认为官方接受提议的可能性还是比较大的。

之前已经反馈过，但目前 PCQQ/PCQQNT 和 手机QQ（包括新重构版和旧 QQ） 都并没有实现此功能

这个功能做起来比较简单，我觉得插件可以做一下的

**Comment by teble** [comment]
@MicroCBer 我觉得你可以来pr一下

**Comment by MicroCBer** [comment]
> @MicroCBer 我觉得你可以来pr一下

如果等我有空了还没人做就可以

**Comment by klxiaoniu** [comment]
近期可能会添加此功能
