### ISSUE TITLE
[功能请求] 语言转发多选用户

### ISSUE THREAD

**Issue by fgr178707** [cinit/QAuxiliary#434]
### QQ(TIM)版本/QQ(TIM) Version

8.9.30.1230

### 为什么你认为需要此功能

我知道有语言转发 这个功能 但是只能对一个人进行转发
如果需要多个人转发的话，需要操作好多次
如果在右上角选择多选的话，又发不出去提示  null

### 具体功能需要/Specific features require

语言文件多个群转发

**Comment by klxiaoniu** [comment]
#106
