### ISSUE TITLE
[功能请求] 分享/转发强制显示所有群和好友

### ISSUE THREAD

**Issue by HiSuzume** [cinit/QAuxiliary#438]
### QQ(TIM)版本/QQ(TIM) Version

Tim 3.5.1.3168

### 为什么你认为需要此功能

例如：你想发个文件到群里，**这个群恰好在群助手里，没有显示在列表**。恰好你又忘记了群名称，因此要回去看群名称，再用搜索去找，**麻烦了许多**。
![Screenshot_20230606_125219](https://github.com/cinit/QAuxiliary/assets/132192681/cb000f9f-ad5c-40e3-874b-112e603baf75)

在列表里，已屏蔽的群/没有消息的好友/群助手里面的群 **全被屏蔽了，还要用“搜索”才能找到**
![Screenshot_20230606_132504](https://github.com/cinit/QAuxiliary/assets/132192681/d351f0e5-5df8-46c7-b804-6f700a20159d)

![Screenshot_20230606_125329](https://github.com/cinit/QAuxiliary/assets/132192681/c936fe8e-03b8-4270-8e2e-16b29284be30)

故此请求添加此功能，麻烦各位开发者们了！

### 具体功能需要/Specific features require

方案如下
1. 在 转发消息 或者 分享文件 的时候，**显示所有好友和群聊**
2. 如果能复现“选择好友和群”这个子选项，请尝试**强制显示这个选项**
3. 如果上述无法办到，请尝试**在“搜索”页面显示所有好友和群**

**Comment by HiSuzume** [comment]
感谢完成！

**Comment by HiSuzume** [comment]
功能不对啊？强制多选和强制显示所有好友群聊？？

**Comment by HiSuzume** [comment]
麻烦 ReOpen 一下，虽然功能弄错了，但是至少多了一个实用功能（

**Comment by MicroCBer** [comment]
![image](https://github.com/cinit/QAuxiliary/assets/66859419/88fc0e65-4f92-4b5e-8801-86082bc00711)

**Comment by HiSuzume** [comment]
> ![image](https://user-images.githubusercontent.com/66859419/261930465-88fc0e65-4f92-4b5e-8801-86082bc00711.png)

我重新装到Tim试一下

**Comment by HiSuzume** [comment]
@MicroCBer 哥们，我用的Tim啊，Tim转发文件没有显示啊

**Comment by HiSuzume** [comment]
所以又要麻烦一下贡献者们了（大悲
