### ISSUE TITLE
群聊-禁用右滑切换群帖子-失败

### ISSUE THREAD

**Issue by tdleiyao** [cinit/QAuxiliary#457]
### Steps to reproduce/复现步骤

群聊界面右划

### Expected behaviour/预期行为

不响应该操作

### Actual behaviour/实际行为

正常切换到群帖子

### XPosed Framework you used/你使用的XP框架

lsp 1.8.6( 6712 )-Zygisk

### QQ(TIM)版本/QQ(TIM) Version

8.9.63(4194)

### Module Version/模块版本

1.4.1.r1544.a5c9ccc(1544)

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

  [1]AbstractQQCustomMenuItem
com.tencent.qqnt.aio.menu.ui.AbstractQQCustomMenuItem
= Lcom/tencent/qqnt/aio/menu/ui/b;->toString()Ljava/lang/String;
  [3]AIOPictureView
com.tencent.mobileqq.richmediabrowser.view.AIOPictureView
= com.tencent.mobileqq.richmediabrowser.view.AIOPictureView
  [4]AIOUtils
com.tencent.mobileqq.activity.aio.AIOUtils
= (void*)0
  [5]AbstractGalleryScene
com.tencent.common.galleryactivity.AbstractGalleryScene
= (void*)0
  [6]AppConstants
com.tencent.mobileqq.app.AppConstants
= com.tencent.mobileqq.app.AppConstants
  [7]ArkAppItemBubbleBuilder
com.tencent.mobileqq.activity.aio.item.ArkAppItemBubbleBuilder
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [8]AvatarUtil
com.tencent.mobileqq.avatar.utils.AvatarUtil
= (void*)0
  [9]BasePicDownloadProcessor
com.tencent.mobileqq.transfile.BasePicDownloadProcessor
= com.tencent.mobileqq.transfile.BasePicDownloadProcessor
  [10]DialogUtil
com.tencent.mobileqq.utils.DialogUtil
= com.tencent.mobileqq.utils.DialogUtil
  [11]ChatActivityFacade
com.tencent.mobileqq.activity.ChatActivityFacade
= com.tencent.mobileqq.activity.ChatActivityFacade
  [12]FaceManager
com.tencent.mobileqq.app.face.FaceManager
= (void*)0
  [13]FavEmoConstant
com.tencent.mobileqq.emosm.favroaming.FavEmoConstant
= com.tencent.mobileqq.emosm.favroaming.FavEmoConstant
  [14]FlashPicHelper
com.tencent.mobileqq.app.FlashPicHelper
= Lcom/tencent/mobileqq/app/ac;->e(Lcom/tencent/mobileqq/data/MessageRecord;Z)V
  [15]FrameControllerInjectImpl
com.tencent.mobileqq.activity.framebusiness.controllerinject.FrameControllerInjectImpl
= com.tencent.mobileqq.activity.framebusiness.controllerinject.FrameControllerInjectImpl
  [16]GalleryBaseScene
com.tencent.mobileqq.gallery.view.GalleryBaseScene
= (void*)0
  [17]TroopAppShortcutDrawer
com.tencent.mobileqq.activity.aio.drawer.TroopAppShortcutDrawer
= com.tencent.mobileqq.activity.aio.drawer.TroopAppShortcutDrawer
  [18]GuildArkHelper
com.tencent.mobileqq.guild.chatpie.helper.GuildArkHelper
= (void*)0
  [19]GuildHelperProvider
com.tencent.mobileqq.guild.chatpie.GuildHelperProvider
= (void*)0
  [20]HttpDownloader
com.tencent.mobileqq.transfile.HttpDownloader
= com.tencent.mobileqq.transfile.HttpDownloader
  [21]IntimateInfoChatDrawer
com.tencent.mobileqq.activity.aio.drawer.IntimateInfoChatDrawer
= (void*)0
  [22]ItemBuilderFactory
com.tencent.mobileqq.activity.aio.item.ItemBuilderFactory
= Lcom/tencent/mobileqq/activity/aio/core/msglist/a/a;->b(Lcom/tencent/mobileqq/data/ChatMessage;Landroid/widget/BaseAdapter;)Lcom/tencent/mobileqq/activity/aio/ah;
  [23]MessageCache
com.tencent.mobileqq.service.message.MessageCache
= (void*)0
  [24]MessageRecordFactory
com.tencent.mobileqq.service.message.MessageRecordFactory
= Lcom/tencent/mobileqq/service/h/r;->J(Lcom/tencent/common/app/AppInterface;Lcom/tencent/mobileqq/data/MessageRecord;Ljava/lang/String;Ljava/lang/String;I)V
  [25]MultiMsgManager
com.tencent.mobileqq.multimsg.MultiMsgManager
= com.tencent.mobileqq.multimsg.MultiMsgManager
  [26]OnlinePushPbPushTransMsg
com.tencent.mobileqq.app.handler.receivesuccess.OnlinePushPbPushTransMsg
= (void*)0
  [27]PicEmoticonInfo
com.tencent.mobileqq.emoticonview.PicEmoticonInfo
= com.tencent.mobileqq.emoticonview.PicEmoticonInfo
  [28]PngFrameUtil
com.tencent.mobileqq.magicface.drawable.PngFrameUtil
= Lcom/tencent/mobileqq/magicface/drawable/d;->a(Ljava/lang/String;)Z
  [29]PopOutEmoticonUtil
com.tencent.mobileqq.popanim.util.PopOutEmoticonUtil
= (void*)0
  [30]MsgNotification
cooperation.qzone.push.MsgNotification
= cooperation.qzone.push.MsgNotification
  [31]ReplyMsgSender
com.tencent.mobileqq.replymsg.ReplyMsgSender
= (void*)0
  [32]ReplyMsgUtils
com.tencent.mobileqq.activity.aio.reply.ReplyMsgUtils
= (void*)0
  [33]ScreenShotHelper
com.tencent.mobileqq.screendetect.ScreenShotHelper
= com.tencent.mobileqq.screendetect.ScreenShotHelper
  [34]SimpleUIUtil
com.tencent.mobileqq.theme.SimpleUIUtil
= (void*)0
  [35]SystemMessageProcessor
com.tencent.mobileqq.app.message.SystemMessageProcessor
= (void*)0
  [36]TestStructMsg
com.tencent.mobileqq.structmsg.TestStructMsg
= Lcom/tencent/mobileqq/structmsg/w;->a(Ljava/lang/String;)Lcom/tencent/mobileqq/structmsg/AbsStructMsg;
  [37]TimeFormatterUtils
com.tencent.mobileqq.utils.TimeFormatterUtils
= (void*)0
  [38]TroopGiftUtil
com.tencent.mobileqq.troop.utils.TroopGiftUtil
= (void*)0
  [39]ZipUtils
com.tencent.biz.common.util.ZipUtils
= com.tencent.biz.common.util.ZipUtils
  [42]EmotcationConstants
com.tencent.mobileqq.text.EmotcationConstants
= com.tencent.mobileqq.text.EmotcationConstants
  [43]ForwardSendPicUtil
com.tencent.mobileqq.utils.ForwardSendPicUtil
= com.tencent.mobileqq.utils.ForwardSendPicUtil
  [0]AIO_Create_QQNT
AIO_Create_QQNT
= (void*)0
  [2]BaseListenTogetherPanel
com.tencent.mobileqq.listentogether.ui.BaseListenTogetherPanel
= com.tencent.mobileqq.listentogether.ui.BaseListenTogetherPanel
  [40]ChatPanel_InitPanel_QQNT
ChatPanel_InitPanel_QQNT
= (void*)0
  [41]

= Lcom/tencent/mobileqq/aio/utils/aa;->b(Ljava/lang/String;)Z
  [44]NotifyIdManager
com.tencent.util.notification.NotifyIdManager
= (void*)0
  [45]AtPanel
com.tencent.mobileqq.troop.quickat.ui.AtPanel
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [46]AtPanel
com.tencent.mobileqq.troop.quickat.ui.AtPanel
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [47]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= com.tencent.mobileqq.activity.aio.core.BaseChatPie
  [48]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= com.tencent.mobileqq.activity.aio.core.BaseChatPie
  [49]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= Lcom/tencent/mobileqq/activity/aio/core/BaseChatPie;->z0()V
  [50]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= com.tencent.mobileqq.activity.aio.core.BaseChatPie
  [51]ChatActivityFacade
com.tencent.mobileqq.activity.ChatActivityFacade
= com.tencent.mobileqq.activity.ChatActivityFacade
  [52]ContactUtils
com.tencent.mobileqq.utils.ContactUtils
= Lcom/tencent/mobileqq/utils/ContactUtils;->f(Lmqq/app/AppRuntime;Ljava/lang/String;Z)Ljava/lang/String;
  [53]ContactUtils
com.tencent.mobileqq.utils.ContactUtils
= Lcom/tencent/mobileqq/utils/ContactUtils;->m(Lcom/tencent/common/app/business/BaseQQAppInterface;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
  [54]Conversation
com.tencent.mobileqq.activity.home.Conversation
= com.tencent.mobileqq.activity.home.Conversation
  [55]CustomWidgetUtil
com.tencent.widget.CustomWidgetUtil
= Lcom/tencent/widget/c;->b(Landroid/widget/TextView;IIIILjava/lang/String;)V
  [56]CustomWidgetUtil
com.tencent.widget.CustomWidgetUtil
= Lcom/tencent/qqnt/chats/b/i/c$a;->e(Landroid/widget/TextView;IIIILjava/lang/String;)V
  [57]FriendChatPie
com.tencent.mobileqq.activity.aio.core.FriendChatPie
= com.tencent.mobileqq.activity.aio.core.FriendChatPie
  [58]FriendsStatusUtil
com.tencent.mobileqq.app.utils.FriendsStatusUtil
= com.tencent.mobileqq.app.utils.FriendsStatusUtil
  [59]LeftSwipeReplyHelper
com.tencent.mobileqq.bubble.LeftSwipeReplyHelper
= (void*)0
  [60]PadUtil
com.tencent.common.config.PadUtil
= (void*)0
  [61]PhotoListPanel
com.tencent.mobileqq.activity.aio.photo.PhotoListPanel
= com.tencent.mobileqq.activity.aio.photo.PhotoListPanel
  [62]ProfileCardUtil
com.tencent.mobileqq.util.ProfileCardUtil
= com.tencent.mobileqq.util.ProfileCardUtil
  [63]QQSettingMe
com.tencent.mobileqq.activity.QQSettingMe
= com.tencent.mobileqq.activity.QQSettingMe
  [64]QQSettingMe
com.tencent.mobileqq.activity.QQSettingMe
= com.tencent.mobileqq.activity.QQSettingMe
  [65]Scene
com.tencent.mobileqq.troopAddFrd.Scene
= (void*)0
  [66]TroopAppShortcutBarHelper
com.tencent.mobileqq.activity.aio.helper.TroopAppShortcutBarHelper
= (void*)0
  [67]TroopChatPie
com.tencent.mobileqq.activity.aio.core.TroopChatPie
= com.tencent.mobileqq.activity.aio.core.TroopChatPie
  [68]VasProfileTemplateController
com.tencent.mobileqq.profilecard.vas.VasProfileTemplateController
= com.tencent.mobileqq.profilecard.vas.VasProfileTemplateController
  [69]VipUtils
com.tencent.mobileqq.utils.VipUtils
= Lcom/tencent/mobileqq/vip/n;->getPrivilegeFlags(Ljava/lang/String;)I
  [70]VipUtils
com.tencent.mobileqq.utils.VipUtils
= (void*)0
  [71]WebSecurityPluginV2$
com.tencent.mobileqq.webview.WebSecurityPluginV2$
= Lcom/tencent/mobileqq/webview/h$a;->callback(Landroid/os/Bundle;)V
  [72]PaiYiPaiHandler
com.tencent.mobileqq.paiyipai.PaiYiPaiHandler
= com.tencent.mobileqq.paiyipai.PaiYiPaiHandler
  [73]

= Lcom/tencent/mobileqq/aio/input/e/k;->o(Lcom/tencent/mobileqq/aio/msg/AIOMsgItem;)V
  [74]

= Lcom/tencent/mobileqq/troop/enterEffect/TroopEnterEffectController;->o()V
  [75]TroopGuildChatPie
com.tencent.mobileqq.troop.guild.TroopGuildChatPie
= Lcom/tencent/mobileqq/troop/guild/TroopGuildChatPie;->P0()V
  [76]

= Lcom/tencent/mobileqq/filemanager/uftwrapper/a$d;->l()V
  [40001]ReplyNoAtHook
com/tencent/mobileqq/activity/aio/rebuild/input/d
  [40002]ChatWordsCount
nnl
  [40003]SortAtPanel.sessionInfoTroopUin
f
  [40004]RemovePlayTogether.ClockInEntryHelper
n
  [40005]QQMessageFacade
B2
  [40006]SimplifyQQSettingMe::MidContentName
m0
  [40007]RemovePlayTogether.TogetherControlHelper
q

**Comment by klxiaoniu** [comment]
fixed
