### ISSUE TITLE
nt版本MessageStyle通知不起作用

### ISSUE THREAD

**Issue by XMWML** [cinit/QAuxiliary#459]
### Steps to reproduce/复现步骤

开启模块通知设置里的MessageStyle通知

### Expected behaviour/预期行为

收到消息时显示一个带有对话泡和回复按钮的MessageStyle通知

### Actual behaviour/实际行为

显示了一个QQ默认样式的普通通知，功能开关没有效果

### XPosed Framework you used/你使用的XP框架

LSPosed 1.8.6 (6911) - Zygisk

### QQ(TIM)版本/QQ(TIM) Version

8.9.68（11450）

### Module Version/模块版本

1.4.1.r1546.cf7cd92

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.4.1.r1546.cf7cd92
QQ8.9.68(4218)
PID: 24036, UID: 10182
me.singleneuron.hook.NewQNotifyEvolution
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by dwughjsd** [comment]
NT版本的QQ更改了自带的消息格式。在此提供参考链接，希望能够帮助开发者。
https://github.com/ichenhe/QQ-Notify-Evolution/issues/32

**Comment by XMWML** [comment]
这个调试信息不知道有没有用
PID: 21065, UID: 10182, 64 bit
Xposed API version: 100
de.robv.android.xposed.XposedBridge
  [1]AbstractQQCustomMenuItem
com.tencent.qqnt.aio.menu.ui.AbstractQQCustomMenuItem
= Lcom/tencent/qqnt/aio/menu/ui/b;->toString()Ljava/lang/String;
  [3]AIOPictureView
com.tencent.mobileqq.richmediabrowser.view.AIOPictureView
= com.tencent.mobileqq.richmediabrowser.view.AIOPictureView
  [4]AIOUtils
com.tencent.mobileqq.activity.aio.AIOUtils
= (void*)0
  [5]AbstractGalleryScene
com.tencent.common.galleryactivity.AbstractGalleryScene
= (void*)0
  [6]AppConstants
com.tencent.mobileqq.app.AppConstants
= com.tencent.mobileqq.app.AppConstants
  [7]ArkAppItemBubbleBuilder
com.tencent.mobileqq.activity.aio.item.ArkAppItemBubbleBuilder
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [8]AvatarUtil
com.tencent.mobileqq.avatar.utils.AvatarUtil
= (void*)0
  [9]BasePicDownloadProcessor
com.tencent.mobileqq.transfile.BasePicDownloadProcessor
= com.tencent.mobileqq.transfile.BasePicDownloadProcessor
  [10]CustomWidgetUtil
com.tencent.widget.CustomWidgetUtil
= (void*)0
  [11]DialogUtil
com.tencent.mobileqq.utils.DialogUtil
= com.tencent.mobileqq.utils.DialogUtil
  [12]ChatActivityFacade
com.tencent.mobileqq.activity.ChatActivityFacade
= com.tencent.mobileqq.activity.ChatActivityFacade
  [13]FaceManager
com.tencent.mobileqq.app.face.FaceManager
= (void*)0
  [14]FavEmoConstant
com.tencent.mobileqq.emosm.favroaming.FavEmoConstant
= com.tencent.mobileqq.emosm.favroaming.FavEmoConstant
  [15]FlashPicHelper
com.tencent.mobileqq.app.FlashPicHelper
= (void*)0
  [16]FrameControllerInjectImpl
com.tencent.mobileqq.activity.framebusiness.controllerinject.FrameControllerInjectImpl
= com.tencent.mobileqq.activity.framebusiness.controllerinject.FrameControllerInjectImpl
  [17]GalleryBaseScene
com.tencent.mobileqq.gallery.view.GalleryBaseScene
= (void*)0
  [18]TroopAppShortcutDrawer
com.tencent.mobileqq.activity.aio.drawer.TroopAppShortcutDrawer
= com.tencent.mobileqq.activity.aio.drawer.TroopAppShortcutDrawer
  [19]GuildArkHelper
com.tencent.mobileqq.guild.chatpie.helper.GuildArkHelper
= (void*)0
  [20]GuildHelperProvider
com.tencent.mobileqq.guild.chatpie.GuildHelperProvider
= (void*)0
  [21]HttpDownloader
com.tencent.mobileqq.transfile.HttpDownloader
= com.tencent.mobileqq.transfile.HttpDownloader
  [22]IntimateInfoChatDrawer
com.tencent.mobileqq.activity.aio.drawer.IntimateInfoChatDrawer
= (void*)0
  [23]ItemBuilderFactory
com.tencent.mobileqq.activity.aio.item.ItemBuilderFactory
= (void*)0
  [24]MessageCache
com.tencent.mobileqq.service.message.MessageCache
= (void*)0
  [25]MessageRecordFactory
com.tencent.mobileqq.service.message.MessageRecordFactory
= Lcom/tencent/mobileqq/service/h/r;->J(Lcom/tencent/common/app/AppInterface;Lcom/tencent/mobileqq/data/MessageRecord;Ljava/lang/String;Ljava/lang/String;I)V
  [26]MultiMsgManager
com.tencent.mobileqq.multimsg.MultiMsgManager
= com.tencent.mobileqq.multimsg.MultiMsgManager
  [27]OnlinePushPbPushTransMsg
com.tencent.mobileqq.app.handler.receivesuccess.OnlinePushPbPushTransMsg
= (void*)0
  [28]PicEmoticonInfo
com.tencent.mobileqq.emoticonview.PicEmoticonInfo
= com.tencent.mobileqq.emoticonview.PicEmoticonInfo
  [29]PngFrameUtil
com.tencent.mobileqq.magicface.drawable.PngFrameUtil
= (void*)0
  [30]PopOutEmoticonUtil
com.tencent.mobileqq.popanim.util.PopOutEmoticonUtil
= (void*)0
  [31]MsgNotification
cooperation.qzone.push.MsgNotification
= cooperation.qzone.push.MsgNotification
  [32]ReplyMsgSender
com.tencent.mobileqq.replymsg.ReplyMsgSender
= (void*)0
  [33]ReplyMsgUtils
com.tencent.mobileqq.activity.aio.reply.ReplyMsgUtils
= (void*)0
  [34]ScreenShotHelper
com.tencent.mobileqq.screendetect.ScreenShotHelper
= com.tencent.mobileqq.screendetect.ScreenShotHelper
  [35]SimpleUIUtil
com.tencent.mobileqq.theme.SimpleUIUtil
= (void*)0
  [36]SystemMessageProcessor
com.tencent.mobileqq.app.message.SystemMessageProcessor
= (void*)0
  [37]TestStructMsg
com.tencent.mobileqq.structmsg.TestStructMsg
= Lcom/tencent/mobileqq/structmsg/w;->a(Ljava/lang/String;)Lcom/tencent/mobileqq/structmsg/AbsStructMsg;
  [38]TimeFormatterUtils
com.tencent.mobileqq.utils.TimeFormatterUtils
= Lcom/tencent/mobileqq/utils/dm;->o(Landroid/content/Context;JLjava/lang/StringBuilder;Ljava/text/SimpleDateFormat;IZ)Ljava/lang/CharSequence;
  [39]TroopGiftUtil
com.tencent.mobileqq.troop.utils.TroopGiftUtil
= (void*)0
  [40]ZipUtils
com.tencent.biz.common.util.ZipUtils
= com.tencent.biz.common.util.ZipUtils
  [43]EmotcationConstants
com.tencent.mobileqq.text.EmotcationConstants
= com.tencent.mobileqq.text.EmotcationConstants
  [44]ForwardSendPicUtil
com.tencent.mobileqq.utils.ForwardSendPicUtil
= com.tencent.mobileqq.utils.ForwardSendPicUtil
  [0]AIO_Create_QQNT
AIO_Create_QQNT
= Lcom/tencent/aio/base/chat/ChatPie;->k(Landroid/os/Bundle;Lcom/tencent/aio/main/fragment/ChatFragment;Lkotlin/jvm/functions/Function1;)V
  [2]BaseListenTogetherPanel
com.tencent.mobileqq.listentogether.ui.BaseListenTogetherPanel
= com.tencent.mobileqq.listentogether.ui.BaseListenTogetherPanel
  [41]ChatPanel_InitPanel_QQNT
ChatPanel_InitPanel_QQNT
= Lcom/tencent/mobileqq/aio/input/f/b;->z()V
  [42]

= (void*)0
  [45]NotifyIdManager
com.tencent.util.notification.NotifyIdManager
= (void*)0
  [46]AtPanel
com.tencent.mobileqq.troop.quickat.ui.AtPanel
= (void*)0
  [47]AtPanel
com.tencent.mobileqq.troop.quickat.ui.AtPanel
= (void*)0
  [48]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= com.tencent.mobileqq.activity.aio.core.BaseChatPie
  [49]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= com.tencent.mobileqq.activity.aio.core.BaseChatPie
  [50]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= Lcom/tencent/mobileqq/activity/aio/core/BaseChatPie;->z0()V
  [51]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= com.tencent.mobileqq.activity.aio.core.BaseChatPie
  [52]ChatActivityFacade
com.tencent.mobileqq.activity.ChatActivityFacade
= com.tencent.mobileqq.activity.ChatActivityFacade
  [53]ContactUtils
com.tencent.mobileqq.utils.ContactUtils
= Lcom/tencent/mobileqq/utils/ContactUtils;->f(Lmqq/app/AppRuntime;Ljava/lang/String;Z)Ljava/lang/String;
  [54]ContactUtils
com.tencent.mobileqq.utils.ContactUtils
= Lcom/tencent/mobileqq/utils/ContactUtils;->m(Lcom/tencent/common/app/business/BaseQQAppInterface;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
  [55]Conversation
com.tencent.mobileqq.activity.home.Conversation
= com.tencent.mobileqq.activity.home.Conversation
  [56]CustomWidgetUtil
com.tencent.widget.CustomWidgetUtil
= (void*)0
  [57]FriendChatPie
com.tencent.mobileqq.activity.aio.core.FriendChatPie
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [58]FriendsStatusUtil
com.tencent.mobileqq.app.utils.FriendsStatusUtil
= com.tencent.mobileqq.app.utils.FriendsStatusUtil
  [59]LeftSwipeReplyHelper
com.tencent.mobileqq.bubble.LeftSwipeReplyHelper
= (void*)0
  [60]PadUtil
com.tencent.common.config.PadUtil
= (void*)0
  [61]PhotoListPanel
com.tencent.mobileqq.activity.aio.photo.PhotoListPanel
= com.tencent.mobileqq.activity.aio.photo.PhotoListPanel
  [62]ProfileCardUtil
com.tencent.mobileqq.util.ProfileCardUtil
= com.tencent.mobileqq.util.ProfileCardUtil
  [63]QQSettingMe
com.tencent.mobileqq.activity.QQSettingMe
= com.tencent.mobileqq.activity.QQSettingMe
  [64]QQSettingMe
com.tencent.mobileqq.activity.QQSettingMe
= com.tencent.mobileqq.activity.QQSettingMe
  [65]Scene
com.tencent.mobileqq.troopAddFrd.Scene
= (void*)0
  [66]TroopAppShortcutBarHelper
com.tencent.mobileqq.activity.aio.helper.TroopAppShortcutBarHelper
= (void*)0
  [67]TroopChatPie
com.tencent.mobileqq.activity.aio.core.TroopChatPie
= com.tencent.mobileqq.activity.aio.core.TroopChatPie
  [68]VasProfileTemplateController
com.tencent.mobileqq.profilecard.vas.VasProfileTemplateController
= com.tencent.mobileqq.profilecard.vas.VasProfileTemplateController
  [69]VipUtils
com.tencent.mobileqq.utils.VipUtils
= (void*)0
  [70]VipUtils
com.tencent.mobileqq.utils.VipUtils
= Lcom/tencent/mobileqq/utils/dz;->r(Lcom/tencent/mobileqq/app/QQAppInterface;Ljava/lang/String;Z)I
  [71]WebSecurityPluginV2$
com.tencent.mobileqq.webview.WebSecurityPluginV2$
= Lcom/tencent/mobileqq/webview/h$a;->callback(Landroid/os/Bundle;)V
  [72]PaiYiPaiHandler
com.tencent.mobileqq.paiyipai.PaiYiPaiHandler
= Lcom/tencent/mobileqq/paiyipai/PaiYiPaiHandler;->r4(Ljava/lang/String;)Z
  [73]

= (void*)0
  [74]

= (void*)0
  [75]TroopGuildChatPie
com.tencent.mobileqq.troop.guild.TroopGuildChatPie
= com.tencent.mobileqq.troop.guild.TroopGuildChatPie
  [76]

= Lcom/tencent/mobileqq/filemanager/uftwrapper/a$d;->l()V
  [40001]ReplyNoAtHook
com/tencent/mobileqq/activity/aio/rebuild/input/d
  [40002]ChatWordsCount
nnl
  [40003]SortAtPanel.sessionInfoTroopUin
f
  [40004]RemovePlayTogether.ClockInEntryHelper
n
  [40005]QQMessageFacade
B2
  [40006]SimplifyQQSettingMe::MidContentName
l0
  [40007]RemovePlayTogether.TogetherControlHelper
q

**Comment by dwughjsd** [comment]
最新版本CI合入了新的通知增强commit，但实测其不起作用。我手机没有root，使用LSPatch。有什么帮助处理问题的事情可做吗？诊断中未发现异常。

**Comment by klxiaoniu** [comment]
已支持
