### ISSUE TITLE
[Bug] 对方撤回信息后灰字不在所撤回的消息位置提示

### ISSUE THREAD

**Issue by LionYu66** [cinit/QAuxiliary#461]
### Steps to reproduce/复现步骤

对方发来1、2、3、4条信息，并撤回了2

### Expected behaviour/预期行为

撤回提示应该在1、3之间
![IMG_8271(20230704-201338)](https://github.com/cinit/QAuxiliary/assets/51237029/35917387-21cb-4b3b-8b47-3ee0b4ca78b2)

### Actual behaviour/实际行为

但现在却显示在最下方，也就是4的后面
![qq_pic_merged_1688472749283](https://github.com/cinit/QAuxiliary/assets/51237029/71f8759f-9bca-49b1-818a-fed74ce308a1)

### XPosed Framework you used/你使用的XP框架

LSPosed 1.8.6(6712)-Zygisk

### QQ(TIM)版本/QQ(TIM) Version

V8.9.63.11390

### Module Version/模块版本

1.4.1.r1550.9b11570

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.4.1.r1550.9b11570
QQ8.9.63(4194)
PID: 30502, UID: 10237
cc.ioctl.hook.msg.RevokeMsgHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by cinit** [comment]
NT kernel 目前不支持手动指定灰字插入位置，没有提供相关 API. 如果你有兴趣，可以研究一下 QQ 的 IKernelMsgService 接口。
