### ISSUE TITLE
[Bug] 以图片方式打开闪照不显示“闪照”角标

### ISSUE THREAD

**Issue by LionYu66** [cinit/QAuxiliary#462]
### Steps to reproduce/复现步骤

对方发来闪照

### Expected behaviour/预期行为

显示为图片且右下角有闪照角标字样

### Actual behaviour/实际行为

没有闪照角标，与普通图片一致

### XPosed Framework you used/你使用的XP框架

LSPosed 1.8.6(6712)-Zygisk

### QQ(TIM)版本/QQ(TIM) Version

V8.9.63.11390

### Module Version/模块版本

1.4.1.r1550.9b11570

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.4.1.r1550.9b11570
QQ8.9.63(4194)
PID: 17919, UID: 10237
cc.ioctl.hook.msg.FlashPicHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by klxiaoniu** [comment]
Fixed in https://github.com/cinit/QAuxiliary/commit/74df690efb4354e7f3bb7490a52193fb1d3a50f9
