### ISSUE TITLE
[Bug] QQ8.9.63以上的NT无法点击转发消息查看详细信息

### ISSUE THREAD

**Issue by sxyofficial** [cinit/QAuxiliary#467]
### Steps to reproduce/复现步骤

点开转发消息，点击头像后无任何反应

### Expected behaviour/预期行为

正常情况下应该能跳出发消息的人相关信息

### Actual behaviour/实际行为

实际点开头像后无任何反应

### XPosed Framework you used/你使用的XP框架

lsposed

### QQ(TIM)版本/QQ(TIM) Version

8.9.63 8.9.68

### Module Version/模块版本

1.4.1.r1562.47d1ddd(1562)

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.4.1.r1562.47d1ddd
QQ8.9.68(4264)
PID: 25008, UID: 10371
cc.ioctl.hook.msg.MultiForwardAvatarHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by klxiaoniu** [comment]
fixed: https://github.com/cinit/QAuxiliary/commit/1ad3d42e9b1abaf96a78569b7214c8346b424fe7
