### ISSUE TITLE
[Bug] 侧滑没有找到QAuxliliary

### ISSUE THREAD

**Issue by W4J1e** [cinit/QAuxiliary#476]
### Steps to reproduce/复现步骤

1.安装模块
2.启用模块并选择QQ
3.强制重启QQ

### Expected behaviour/预期行为

侧滑之后在设置的菜单里应该有模块

### Actual behaviour/实际行为

没有找到模块菜单

### XPosed Framework you used/你使用的XP框架

LSPosed

### QQ(TIM)版本/QQ(TIM) Version

8.9.63.11345

### Module Version/模块版本

1.4.1.r1395

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

故障排查，点击QQ。如果QQ没有启动就会闪一下，如果启动了点击无反应。

**Comment by klxiaoniu** [comment]
更新 CI 版后再试

**Comment by jcdomt** [comment]
我也是这个问题，具体怎么解决啊

**Comment by W4J1e** [comment]
> 

用CI版本就解决了。

**Comment by jcdomt** [comment]
CI版本能给个链接吗/kk

**Comment by jcdomt** [comment]
> > 
> 
> 用CI版本就解决了。

CI版本能给个链接吗/kk
