### ISSUE TITLE
[Bug] “文字转语音发送”功能没有效果

### ISSUE THREAD

**Issue by Mrqqeat** [cinit/QAuxiliary#480]
### Steps to reproduce/复现步骤

开启文字转语音功能后，输入框输入

#tts
你好

长按“发送”按钮没反应

### Expected behaviour/预期行为

正常应该发送出去“你好”的语音

### Actual behaviour/实际行为

没有任何效果

### XPosed Framework you used/你使用的XP框架

Lsposed 1.8.6

### QQ(TIM)版本/QQ(TIM) Version

8.9.68.11565

### Module Version/模块版本

1.4.1.r1574.b8a3b69

### Version requirement/版本要求

- [x] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.4.1.r1574.b8a3b69
QQ8.9.68(4264)
PID: 19366, UID: 10289
io.github.duzhaokun123.hook.SendTTSHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by klxiaoniu** [comment]
Fixed in https://github.com/cinit/QAuxiliary/commit/c3b551cadbc6f107b919e2bba0ac10e165c971b6
