### ISSUE TITLE
[Bug] 输入框提示文字功能失效

### ISSUE THREAD

**Issue by anxiaoxuan-hh** [cinit/QAuxiliary#482]
### Steps to reproduce/复现步骤

设置好输入框提示文字功能后在聊天窗口不显示

### Expected behaviour/预期行为

正常应该显示设置的文字

### Actual behaviour/实际行为

实际上什么都没有

### XPosed Framework you used/你使用的XP框架

LSPatch

### QQ(TIM)版本/QQ(TIM) Version

8.9.68(4264)

### Module Version/模块版本

1.4.1.r1576.d60a528(1576)

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.4.1.r1576.d60a528
QQ8.9.68(4264)
PID: 15243, UID: 11565
xyz.nextalone.hook.ChatInputHint
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by klxiaoniu** [comment]
更新 1627 试试

**Comment by anxiaoxuan-hh** [comment]
依旧还是失效的哦 我下载的是arm64版本 是这个版本的问题吗

**Comment by klxiaoniu** [comment]
> 依旧还是失效的哦 我下载的是arm64版本 是这个版本的问题吗

1629已修复私聊没有提示的问题

**Comment by anxiaoxuan-hh** [comment]
已恢复正常使用
