### ISSUE TITLE
+1闪退[Bug] 

### ISSUE THREAD

**Issue by Kwisma** [cinit/QAuxiliary#486]
### Steps to reproduce/复现步骤

点击消息旁边的+1图标，然后闪退

### Expected behaviour/预期行为

点击+1图标发送该消息

### Actual behaviour/实际行为

立马闪退

### XPosed Framework you used/你使用的XP框架

LSPosed(v1.6.8.6712)

### QQ(TIM)版本/QQ(TIM) Version

QQNT (v8.9.68.11450)

### Module Version/模块版本

1.4.1.r1583.5a1001d

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

![错误截图](https://github.com/cinit/QAuxiliary/assets/77215384/ea4c570e-ea1d-49c0-b43f-b1fa4e7cf81f)

[LSPosed_2023-07-14T00_22_33.596517.zip](https://github.com/cinit/QAuxiliary/files/12041629/LSPosed_2023-07-14T00_22_33.596517.zip)

**Comment by keta1** [comment]
使用 +1 plus 谢谢喵

**Comment by Lycofuture** [comment]
> 使用+1 plus 谢谢喵

一直开着的，没关过

**Comment by klxiaoniu** [comment]
第一，你用的是+1 而不是+1 Plus，第二，你的 QQ 不是正式版
