### ISSUE TITLE
[Bug] QQ8.9.70 +1/表情面板发送崩溃

### ISSUE THREAD

**Issue by guozi1373124875** [cinit/QAuxiliary#489]
### Steps to reproduce/复现步骤

测试使用QQ8970，使用功能复读功能

### Expected behaviour/预期行为

正常会重复发送信息

### Actual behaviour/实际行为

实际点了加一就闪退

### XPosed Framework you used/你使用的XP框架

lsp和太极

### QQ(TIM)版本/QQ(TIM) Version

8970

### Module Version/模块版本

1586

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

无

**Comment by klxiaoniu** [comment]
@guozi1373124875 测试版QQ功能异常无需反馈，正式版发布后才会进行修复

**Comment by lliioollcn** [comment]
已修复
