### ISSUE TITLE
[Bug] 修改@界面排序和防撤回

### ISSUE THREAD

**Issue by MengNianxiaoyao** [cinit/QAuxiliary#492]
### Steps to reproduce/复现步骤

在聊天框输入@
消息被撤回

### Expected behaviour/预期行为

正常排序以及正常执行防撤回

### Actual behaviour/实际行为

未正常排序，防撤回失败

### XPosed Framework you used/你使用的XP框架

lsp

### QQ(TIM)版本/QQ(TIM) Version

8.9.50

### Module Version/模块版本

1.4.1.r1587.956a8c2(1587)

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[SortAtPanel-1689428016173.txt](https://github.com/cinit/QAuxiliary/files/12061517/SortAtPanel-1689428016173.txt)
[RevokeMsgHook-1689428001905.txt](https://github.com/cinit/QAuxiliary/files/12061518/RevokeMsgHook-1689428001905.txt)

**Comment by klxiaoniu** [comment]
更新CI1591，问题1已修复。另，确认防撤回功能失效而不是仅仅有报错吗？

**Comment by lliioollcn** [comment]
已修复

**Comment by MengNianxiaoyao** [comment]
> 更新CI1591，问题1已修复。另，确认防撤回功能失效而不是仅仅有报错吗？

经过多次测试，功能失效是偶现，大部分时候还是正常的

**Comment by klxiaoniu** [comment]
ci1597 已修复
