### ISSUE TITLE
[Bug] 粘贴图片到聊天失败

### ISSUE THREAD

**Issue by guimc233** [cinit/QAuxiliary#494]
### Steps to reproduce/复现步骤

使用Gboard粘贴图片到聊天窗口

### Expected behaviour/预期行为

应该出现粘贴界面

### Actual behaviour/实际行为

![Screenshot_20230716_164809](https://github.com/cinit/QAuxiliary/assets/65482560/6d6255c3-6717-4a1c-b118-5b70ec7aac14)

### XPosed Framework you used/你使用的XP框架

lspatch

### QQ(TIM)版本/QQ(TIM) Version

QQ 8.9.63

### Module Version/模块版本

1.4.1.r1594.c8a3a79

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.4.1.r1594.c8a3a79
QQ8.9.63(4194)
PID: 12436, UID: 10754
cc.ioctl.hook.msg.AioChatPieClipPasteHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by klxiaoniu** [comment]
Fixed in https://github.com/cinit/QAuxiliary/commit/c3b551cadbc6f107b919e2bba0ac10e165c971b6
