### ISSUE TITLE
[Bug] 移除右滑群应用 功能失效

### ISSUE THREAD

**Issue by Pil0tXia** [cinit/QAuxiliary#504]
### Steps to reproduce/复现步骤

从QQ8.9.50+qauxv r1592升级到QQ8.9.68+qauxv r1619

### Expected behaviour/预期行为

在群聊界面右滑，无任何响应

### Actual behaviour/实际行为

功能状态”未见明显异常“，但在群聊界面右滑时，会进入一个白屏。

### XPosed Framework you used/你使用的XP框架

jdk11 lspatch 0.5.1

### QQ(TIM)版本/QQ(TIM) Version

8.9.68

### Module Version/模块版本

r1619

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

https://github.com/cinit/QAuxiliary/assets/41445332/86fc0d73-42c1-4d6e-aadb-4058fb15c0c9

**Comment by ArkhalisDragon** [comment]
我8.9.73+1.4.4LSP挂载也是这个问题，还没修好...

**Comment by HdShare** [comment]
尝试使用 屏蔽聊天右滑 进行平替
