### ISSUE TITLE
[Bug] +1之后文本字体变大

### ISSUE THREAD

**Issue by hdm9527** [cinit/QAuxiliary#512]
### Steps to reproduce/复现步骤

+1之后文本样式变了，字体变大，其他正常，只开启了+1plus
![Screenshot_2023-07-21-12-55-14-116_com tencent mobileqq-edit](https://github.com/cinit/QAuxiliary/assets/39702328/421a5a0f-f293-4440-b9f4-2f73cf42d5cc)
![Screenshot_2023-07-21-12-55-23-289_com tencent mobileqq-edit](https://github.com/cinit/QAuxiliary/assets/39702328/c46f7d10-993a-4cc6-965b-abb7de94d958)

### Expected behaviour/预期行为

+1之后文本样式应该一致

### Actual behaviour/实际行为

![7613302018971bc5](https://github.com/cinit/QAuxiliary/assets/39702328/a5334575-b00c-44c8-8f0a-0c79a5c9522d)

### XPosed Framework you used/你使用的XP框架

lsposed

### QQ(TIM)版本/QQ(TIM) Version

8.9.68

### Module Version/模块版本

1.4.1.r1629.2620ada

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.4.1.r1629.2620ada
QQ8.9.68(4264)
PID: 12212, UID: 10497
cc.hicore.hook.RepeaterPlus
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by klxiaoniu** [comment]
Fixed in https://github.com/cinit/QAuxiliary/commit/b83edf5810dbb4c6b9132a598e628100dc04358e
实际上对方不会看到大字体

**Comment by hdm9527** [comment]
> Fixed in [b83edf5](https://github.com/cinit/QAuxiliary/commit/b83edf5810dbb4c6b9132a598e628100dc04358e) 实际上对方不会看到大字体

我还以为是bug
