### ISSUE TITLE
[Bug] qq 8.9.68.11656设置界面无qa模块设置

### ISSUE THREAD

**Issue by Ry4nnnnn** [cinit/QAuxiliary#514]
### Steps to reproduce/复现步骤

目前qq版本为8.9.68.11565 qa版本为1.4.1r1395.eccb8bb
模块内显示已激活 太极已经把qq导入且确定启动了模块 但是打开qq设置之后没有qa模块设置

### Expected behaviour/预期行为

在打开设置后显示qa模块设置一栏

### Actual behaviour/实际行为

并没有显示qa设置一栏

### XPosed Framework you used/你使用的XP框架

青钢影 10.3.2.03081021-9560

### QQ(TIM)版本/QQ(TIM) Version

8.9.68.11565

### Module Version/模块版本

1.4.1r1395.eccb8b

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

![Screenshot_20230722_063719](https://github.com/cinit/QAuxiliary/assets/99374344/09b958e5-6762-4a99-b631-16ebab6a8e5d)
![Screenshot_20230722_063730](https://github.com/cinit/QAuxiliary/assets/99374344/de20f678-fef8-4506-896e-deaea4d2fee5)
![Screenshot_20230722_063732](https://github.com/cinit/QAuxiliary/assets/99374344/02501e3d-7e67-4304-a9c4-8f688149e696)
![Screenshot_20230722_063743](https://github.com/cinit/QAuxiliary/assets/99374344/eb813988-05e2-4195-812f-635d7c512e75)

**Comment by klxiaoniu** [comment]
使用最新 CI 调试版本试试呢
