### ISSUE TITLE
[功能请求] 通过申请加好友界面获取QQ号

### ISSUE THREAD

**Issue by lengxi2218827014** [cinit/QAuxiliary#516]
### QQ(TIM)版本/QQ(TIM) Version

8.9.68

### 为什么你认为需要此功能

通过王者荣耀或者频道加好友不会显示QQ号会直接跳转到此界面，如果QQ加好友功能被限制，只能通过小号添加，而没有QQ号则无法添加成为好友。

### 具体功能需要/Specific features require

![IMG_20230724_004117](https://github.com/cinit/QAuxiliary/assets/41940375/a6523c7d-14d9-45e1-bd4b-021b3102a317)
在这里来源参数中添加QQ号

**Comment by lengxi2218827014** [comment]
![Screenshot_2023-08-02-02-02-38-240_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/41940375/276482a5-758f-4cae-89b8-734b55fce4d8)
在QStoryEnd模块中已支持此功能，但不支持8.9.70及以上版本
请求把此功能加入到Qa里面，并适配新版本
![Screenshot_2023-08-02-02-02-38-240_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/41940375/bdb2594b-4d26-4f54-8101-ba958eeaed5a)

**Comment by klxiaoniu** [comment]
https://github.com/cinit/QAuxiliary/commit/cc2c07e8752add1b31ec7cce933564a2e218cfe4 已添加，长按可复制

**Comment by lengxi2218827014** [comment]
> [cc2c07e](https://github.com/cinit/QAuxiliary/commit/cc2c07e8752add1b31ec7cce933564a2e218cfe4)已添加，长按可复制

![Screenshot_2023-08-03-18-49-21-627_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/41940375/10f5ba41-2cb3-4a89-b2f2-bfa4ae2ab6fe)
发现了bug，在此版本下，可能当目标游戏头像与QQ头像不一致时，出现的结果不与预期的结果一致，以下是qs模块作者写的整体逻辑
![IMG_20230803_185322](https://github.com/cinit/QAuxiliary/assets/41940375/7a4cf0b8-6db8-4b39-91d1-30cd2e031df8)
