### ISSUE TITLE
合并转发信息无法获取未加入群的群号

### ISSUE THREAD

**Issue by 233dada** [cinit/QAuxiliary#524]
### Steps to reproduce/复现步骤

打开一个未加入群的合并转发信息
点击任意头像

### Expected behaviour/预期行为

弹出提示框并显示被点击者的QQ号以及所处群群号
![Uploading IMG_20230726_231639.jpg…]()

### Actual behaviour/实际行为

只显示QQ号未显示群号，且聊天记录中不显示昵称
![Screenshot_2023-07-26-22-56-49-678_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/79577850/54a11211-b6ac-4bf8-af3b-393b174e63b5)
且未提示有明显异常

### XPosed Framework you used/你使用的XP框架

LSP：1.8.6 (6712)

### QQ(TIM)版本/QQ(TIM) Version

8.9.30(3730)

### Module Version/模块版本

1.4.2.r1659.fd171b1(1659)

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.4.2.r1659.fd171b1
QQ8.9.30(3730)
PID: 1088, UID: 10207
cc.ioctl.hook.msg.MultiForwardAvatarHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

调试信息：

PID: 1088, UID: 10207, 64 bit
Xposed API version: 93
de.robv.android.xposed.XposedBridge 
 [2]AbstractQQCustomMenuItem
com.tencent.qqnt.aio.menu.ui.AbstractQQCustomMenuItem
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [4]AIOPictureView
com.tencent.mobileqq.richmediabrowser.view.AIOPictureView
= com.tencent.mobileqq.richmediabrowser.view.AIOPictureView
  [5]AIOUtils
com.tencent.mobileqq.activity.aio.AIOUtils
= Lcom/tencent/mobileqq/activity/aio/p;->L(Lcom/tencent/mobileqq/app/QQAppInterface;Lcom/tencent/mobileqq/app/BaseActivity;Landroid/content/Intent;)I
  [6]AbstractGalleryScene
com.tencent.common.galleryactivity.AbstractGalleryScene
= (void*)0
  [7]AppConstants
com.tencent.mobileqq.app.AppConstants
= com.tencent.mobileqq.app.AppConstants
  [8]ArkAppItemBubbleBuilder
com.tencent.mobileqq.activity.aio.item.ArkAppItemBubbleBuilder
= com.tencent.mobileqq.activity.aio.item.ArkAppItemBubbleBuilder
  [9]AvatarUtil
com.tencent.mobileqq.avatar.utils.AvatarUtil
= (void*)0
  [10]BasePicDownloadProcessor
com.tencent.mobileqq.transfile.BasePicDownloadProcessor
= com.tencent.mobileqq.transfile.BasePicDownloadProcessor
  [11]CustomWidgetUtil
com.tencent.widget.CustomWidgetUtil
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [12]DialogUtil
com.tencent.mobileqq.utils.DialogUtil
= com.tencent.mobileqq.utils.DialogUtil
  [13]ChatActivityFacade
com.tencent.mobileqq.activity.ChatActivityFacade
= com.tencent.mobileqq.activity.ChatActivityFacade
  [14]FaceManager
com.tencent.mobileqq.app.face.FaceManager
= (void*)0
  [15]FavEmoConstant
com.tencent.mobileqq.emosm.favroaming.FavEmoConstant
= com.tencent.mobileqq.emosm.favroaming.FavEmoConstant
  [16]FlashPicHelper
com.tencent.mobileqq.app.FlashPicHelper
= Lcom/tencent/mobileqq/app/ap;->e(Lcom/tencent/mobileqq/data/MessageRecord;Z)V
  [17]FrameControllerInjectImpl
com.tencent.mobileqq.activity.framebusiness.controllerinject.FrameControllerInjectImpl
= (void*)0
  [18]GalleryBaseScene
com.tencent.mobileqq.gallery.view.GalleryBaseScene
= (void*)0
  [19]TroopAppShortcutDrawer
com.tencent.mobileqq.activity.aio.drawer.TroopAppShortcutDrawer
= Lcom/tencent/mobileqq/activity/aio/drawer/e;->g()V
  [20]GuildArkHelper
com.tencent.mobileqq.guild.chatpie.helper.GuildArkHelper
= (void*)0
  [21]GuildHelperProvider
com.tencent.mobileqq.guild.chatpie.GuildHelperProvider
= (void*)0
  [22]HttpDownloader
com.tencent.mobileqq.transfile.HttpDownloader
= com.tencent.mobileqq.transfile.HttpDownloader
  [23]IntimateInfoChatDrawer
com.tencent.mobileqq.activity.aio.drawer.IntimateInfoChatDrawer
= (void*)0
  [24]ItemBuilderFactory
com.tencent.mobileqq.activity.aio.item.ItemBuilderFactory
= Lcom/tencent/mobileqq/activity/aio/core/msglist/a/a;->b(Lcom/tencent/mobileqq/data/ChatMessage;Landroid/widget/BaseAdapter;)Lcom/tencent/mobileqq/activity/aio/ab;
  [25]MessageCache
com.tencent.mobileqq.service.message.MessageCache
= Lcom/tencent/mobileqq/service/h/e;-><clinit>()V
  [26]MessageRecordFactory
com.tencent.mobileqq.service.message.MessageRecordFactory
= Lcom/tencent/mobileqq/service/h/r;->J(Lcom/tencent/common/app/AppInterface;Lcom/tencent/mobileqq/data/MessageRecord;Ljava/lang/String;Ljava/lang/String;I)V
  [27]MultiMsgManager
com.tencent.mobileqq.multimsg.MultiMsgManager
= com.tencent.mobileqq.multimsg.MultiMsgManager
  [28]OnlinePushPbPushTransMsg
com.tencent.mobileqq.app.handler.receivesuccess.OnlinePushPbPushTransMsg
= (void*)0
  [29]PicEmoticonInfo
com.tencent.mobileqq.emoticonview.PicEmoticonInfo
= com.tencent.mobileqq.emoticonview.PicEmoticonInfo
  [30]PngFrameUtil
com.tencent.mobileqq.magicface.drawable.PngFrameUtil
= Lcom/tencent/mobileqq/magicface/drawable/d;->a(Ljava/lang/String;)Z
  [31]PopOutEmoticonUtil
com.tencent.mobileqq.popanim.util.PopOutEmoticonUtil
= Lcom/tencent/mobileqq/popanim/a/a;->h(ILcom/tencent/mobileqq/emoticonview/EmoticonInfo;I)Z
  [32]MsgNotification
cooperation.qzone.push.MsgNotification
= cooperation.qzone.push.MsgNotification
  [33]ReplyMsgSender
com.tencent.mobileqq.replymsg.ReplyMsgSender
= (void*)0
  [34]ReplyMsgUtils
com.tencent.mobileqq.activity.aio.reply.ReplyMsgUtils
= (void*)0
  [35]ScreenShotHelper
com.tencent.mobileqq.screendetect.ScreenShotHelper
= com.tencent.mobileqq.screendetect.ScreenShotHelper
  [36]SimpleUIUtil
com.tencent.mobileqq.theme.SimpleUIUtil
= (void*)0
  [37]SystemMessageProcessor
com.tencent.mobileqq.app.message.SystemMessageProcessor
= (void*)0
  [38]TestStructMsg
com.tencent.mobileqq.structmsg.TestStructMsg
= Lcom/tencent/mobileqq/structmsg/w;->a(Ljava/lang/String;)Lcom/tencent/mobileqq/structmsg/AbsStructMsg;
  [39]TimeFormatterUtils
com.tencent.mobileqq.utils.TimeFormatterUtils
= (void*)0
  [40]TroopGiftUtil
com.tencent.mobileqq.troop.utils.TroopGiftUtil
= Lcom/tencent/mobileqq/troop/utils/t;->n(Ljava/io/File;)Z
  [41]ZipUtils
com.tencent.biz.common.util.ZipUtils
= com.tencent.biz.common.util.ZipUtils
  [43]DefaultFileModel
com.tencent.mobileqq.filemanager.fileviewer.model.DefaultFileModel
= (void*)0
  [45]EmotcationConstants
com.tencent.mobileqq.text.EmotcationConstants
= com.tencent.mobileqq.text.EmotcationConstants
  [46]ForwardSendPicUtil
com.tencent.mobileqq.utils.ForwardSendPicUtil
= com.tencent.mobileqq.utils.ForwardSendPicUtil
  [0]AIO_Create_QQNT
AIO_Create_QQNT
= (void*)0
  [1]

= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [3]BaseListenTogetherPanel
com.tencent.mobileqq.listentogether.ui.BaseListenTogetherPanel
= Lcom/tencent/mobileqq/listentogether/ui/BaseListenTogetherPanel;->P(Lcom/tencent/mobileqq/listentogether/ListenTogetherSession;)V
  [42]ChatPanel_InitPanel_QQNT
ChatPanel_InitPanel_QQNT
= (void*)0
  [44]

= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [47]NotifyIdManager
com.tencent.util.notification.NotifyIdManager
= com.tencent.util.notification.NotifyIdManager
  [48]Guild_Emo_Btn_Create_QQNT
Guild_Emo_Btn_Create_QQNT
= (void*)0
  [49]AtPanel
com.tencent.mobileqq.troop.quickat.ui.AtPanel
= Lcom/tencent/mobileqq/troop/quickat/ui/a;->c(Lcom/tencent/mobileqq/troop/quickat/ui/i$a;)V
  [50]AtPanel
com.tencent.mobileqq.troop.quickat.ui.AtPanel
= Lcom/tencent/mobileqq/troop/quickat/ui/a;->r(Landroid/view/View;Ljava/lang/String;Z)V
  [51]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= com.tencent.mobileqq.activity.aio.core.BaseChatPie
  [52]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= Lcom/tencent/mobileqq/activity/aio/helper/aw;->v(Lcom/tencent/mobileqq/data/ChatMessage;)V
  [53]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= Lcom/tencent/mobileqq/activity/aio/core/BaseChatPie;->z0()V
  [54]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= com.tencent.mobileqq.activity.aio.core.BaseChatPie
  [55]ChatActivityFacade
com.tencent.mobileqq.activity.ChatActivityFacade
= com.tencent.mobileqq.activity.ChatActivityFacade
  [56]ContactUtils
com.tencent.mobileqq.utils.ContactUtils
= Lcom/tencent/mobileqq/utils/aj;->e(Lmqq/app/AppRuntime;Ljava/lang/String;Z)Ljava/lang/String;
  [57]ContactUtils
com.tencent.mobileqq.utils.ContactUtils
= Lcom/tencent/mobileqq/utils/aj;->l(Lcom/tencent/common/app/business/BaseQQAppInterface;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
  [58]Conversation
com.tencent.mobileqq.activity.home.Conversation
= Lcom/tencent/mobileqq/activity/home/Conversation;->z()V
  [59]CustomWidgetUtil
com.tencent.widget.CustomWidgetUtil
= Lcom/tencent/widget/e;->b(Landroid/widget/TextView;IIIILjava/lang/String;)V
  [60]FriendChatPie
com.tencent.mobileqq.activity.aio.core.FriendChatPie
= Lcom/tencent/mobileqq/activity/aio/core/FriendChatPie;->e5()V
  [61]FriendsStatusUtil
com.tencent.mobileqq.app.utils.FriendsStatusUtil
= Lcom/tencent/mobileqq/app/utils/FriendsStatusUtil;->l(Lcom/tencent/mobileqq/app/QQAppInterface;Ljava/lang/String;I)Z
  [62]LeftSwipeReplyHelper
com.tencent.mobileqq.bubble.LeftSwipeReplyHelper
= Lcom/tencent/mobileqq/bubble/i;->R()V
  [63]PadUtil
com.tencent.common.config.PadUtil
= (void*)0
  [64]PhotoListPanel
com.tencent.mobileqq.activity.aio.photo.PhotoListPanel
= com.tencent.mobileqq.activity.aio.photo.PhotoListPanel
  [65]ProfileCardUtil
com.tencent.mobileqq.util.ProfileCardUtil
= com.tencent.mobileqq.util.ProfileCardUtil
  [66]QQSettingMe
com.tencent.mobileqq.activity.QQSettingMe
= com.tencent.mobileqq.activity.QQSettingMe
  [67]QQSettingMe
com.tencent.mobileqq.activity.QQSettingMe
= Lcom/tencent/mobileqq/activity/QQSettingMeView;->S(Lcom/tencent/mobileqq/activity/qqsettingme/a/m;)V
  [68]

= (void*)0
  [69]Scene
com.tencent.mobileqq.troopAddFrd.Scene
= Lcom/tencent/mobileqq/troopAddFrd/a;->f()I
  [70]TroopAppShortcutBarHelper
com.tencent.mobileqq.activity.aio.helper.TroopAppShortcutBarHelper
= (void*)0
  [71]TroopChatPie
com.tencent.mobileqq.activity.aio.core.TroopChatPie
= com.tencent.mobileqq.activity.aio.core.TroopChatPie
  [72]VasProfileTemplateController
com.tencent.mobileqq.profilecard.vas.VasProfileTemplateController
= Lcom/tencent/mobileqq/profilecard/vas/VasProfileTemplateController;->onCardUpdate(Lcom/tencent/mobileqq/profilecard/base/framework/IComponentCenter;Lcom/tencent/mobileqq/profilecard/data/ProfileCardInfo;)Z
  [73]VipUtils
com.tencent.mobileqq.utils.VipUtils
= Lcom/tencent/mobileqq/vip/n;->getPrivilegeFlags(Ljava/lang/String;)I
  [74]VipUtils
com.tencent.mobileqq.utils.VipUtils
= Lcom/tencent/mobileqq/utils/VipUtils;->t(Lcom/tencent/mobileqq/app/QQAppInterface;Ljava/lang/String;Z)I
  [75]WebSecurityPluginV2$
com.tencent.mobileqq.webview.WebSecurityPluginV2$
= Lcom/tencent/mobileqq/webview/h$a;->callback(Landroid/os/Bundle;)V
  [76]PaiYiPaiHandler
com.tencent.mobileqq.paiyipai.PaiYiPaiHandler
= Lcom/tencent/mobileqq/u1/a;->L4(Ljava/lang/String;)Z
  [77]

= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [78]

= Lcom/tencent/mobileqq/troop/enterEffect/TroopEnterEffectController;->l()V
  [79]TroopGuildChatPie
com.tencent.mobileqq.troop.guild.TroopGuildChatPie
= Lcom/tencent/mobileqq/troop/guild/TroopGuildChatPie;->Q0()V
  [80]

= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [81]

= (void*)0
  [82]AIOPictureView
com.tencent.mobileqq.activity.aio.photo.AIOPictureView
= (void*)0
  [83]AIOPictureView
com.tencent.mobileqq.activity.aio.photo.AIOPictureView
= (void*)0
  [84]TextItemBuilder
com.tencent.mobileqq.activity.aio.item.TextItemBuilder
= com.tencent.mobileqq.activity.aio.item.TextItemBuilder
  [40001]ReplyNoAtHook
com/tencent/mobileqq/activity/aio/rebuild/input/d
  [40002]ChatWordsCount
nnl
  [40003]SortAtPanel.sessionInfoTroopUin
f
  [40004]RemovePlayTogether.ClockInEntryHelper
n
  [40005]QQMessageFacade
B2
  [40006]SimplifyQQSettingMe::MidContentName
m0
  [40007]RemovePlayTogether.TogetherControlHelper
q

**Comment by klxiaoniu** [comment]
无法获取群号为正常表现，因腾讯传回的信息已不包含群号。聊天记录中不显示昵称，是QQ自身的原因。
