### ISSUE TITLE
[Bug] qqnt无法获取合并消息群QQ号

### ISSUE THREAD

**Issue by huoyan1231** [cinit/QAuxiliary#529]
### Steps to reproduce/复现步骤

使用qqnt尝试获取任意合并转发的消息群号
在tim3.5.2测试下正常工作

### Expected behaviour/预期行为

获取到群号

### Actual behaviour/实际行为

未获取到

### XPosed Framework you used/你使用的XP框架

lsposed

### QQ(TIM)版本/QQ(TIM) Version

8.9.63（4194）

### Module Version/模块版本

1.4.2.r1661.835ffbc(1661)

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

无模块内报错

**Comment by keta1** [comment]
duplicated #524
