### ISSUE TITLE
[功能请求] 能不能让每一条消息都显示时间

### ISSUE THREAD

**Issue by CCAICD** [cinit/QAuxiliary#531]
### QQ(TIM)版本/QQ(TIM) Version

8.9.35

### 为什么你认为需要此功能

有的时候连续发消息，要好几条消息之后才显示时间。自定义时间格式已经很棒了，能不能增加一个每条消息都显示时间的选项，我觉得还挺有用的

### 具体功能需要/Specific features require

每条消息都显示时间

**Comment by cinit** [comment]
@CCAICD 使用消息先生ID和时间

**Comment by CCAICD** [comment]
原来如此，感谢大佬
