### ISSUE TITLE
[Bug]图片透明背景在NT版本的问题

### ISSUE THREAD

**Issue by QAQ3254865169** [cinit/QAuxiliary#532]
### Steps to reproduce/复现步骤

聊天界面查看图片透明背景在NT版本可以开启，而且无报错，但无效果

### Expected behaviour/预期行为

打开图片背景变为透明

### Actual behaviour/实际行为

未透明

### XPosed Framework you used/你使用的XP框架

LSPOSED 1.8.6

### QQ(TIM)版本/QQ(TIM) Version

8.9.70

### Module Version/模块版本

1.4.2.r1664.02521b8

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.4.2.r1663.81a8997
QQ8.9.70(4330)
PID: 31840, UID: 10462
cc.ioctl.hook.chat.GalleryBgHook
isInitialized: false
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by duzhaokun123** [comment]
fix https://github.com/cinit/QAuxiliary/commit/b80c33503a1bd537c35cad3230401648191db63e
