### ISSUE TITLE
转发消息点头像查看详细信息 功能异常

### ISSUE THREAD

**Issue by cicur** [cinit/QAuxiliary#533]
### Steps to reproduce/复现步骤

1. 停止运行QQ
2. 打开QQ
3. 打开任意合并转发消息并点击头像

### Expected behaviour/预期行为

显示详细信息

### Actual behaviour/实际行为

点击后未显示详细信息，功能异常列表显示依赖错误。
在QA设置中关闭此功能并重新开启后，可正常显示详细信息。

### XPosed Framework you used/你使用的XP框架

LSPosed 1.8.6 (6712)

### QQ(TIM)版本/QQ(TIM) Version

QQ 8.9.50(3898)

### Module Version/模块版本

1.4.2.r1664.02521b8(1664)

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.4.2.r1664.02521b8
QQ8.9.50(3898)
PID: 1163, UID: 10255
cc.ioctl.hook.msg.MultiForwardAvatarHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: true
errors: 0

**Comment by klxiaoniu** [comment]
对，更改后需要重新打开此开关以查找相关方法

**Comment by cicur** [comment]
> 对，更改后需要重新打开此开关以查找相关方法

那每次启动都要重新开下开关？
退到正式版1.4.2.r1659.fd171b1(1659)就没有这个问题
