### ISSUE TITLE
[Bug] 更新qq 8.9.71后两个功能失效

### ISSUE THREAD

**Issue by Fiz-Victor** [cinit/QAuxiliary#534]
### Steps to reproduce/复现步骤

问题1：
1. 在群里发送消息
2. 撤回消息
问题2：
1. 选择图片->相册，弹出的是qq相册

### Expected behaviour/预期行为

问题1：显示用户名尝试撤回了一条消息：xxxx
问题2：可以系统相册弹出界面

### Actual behaviour/实际行为

问题1：撤回用户名变为u_XXXX，显示：u_xxxx尝试撤回了一条消息：xxxx
问题2：无法使用系统相册

### XPosed Framework you used/你使用的XP框架

1.8.6.6951

### QQ(TIM)版本/QQ(TIM) Version

1665

### Module Version/模块版本

8.9.71

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

未见明显异常

**Comment by klxiaoniu** [comment]
@Fiz-Victor 问题1目前是正常表现，问题3你是用的官方app进行QQ登录吗

**Comment by Fiz-Victor** [comment]
> @Fiz-Victor 问题1目前是正常表现，问题3你是用的官方app进行QQ登录吗

我是用第三方的应用用qq授权登录，并非登录qq账号，尝试启用安全模式仍然无效

**Comment by klxiaoniu** [comment]
@Fiz-Victor 这个应用如果不是官方版，QQ登录不会通过，和模块无关

**Comment by Fiz-Victor** [comment]
> @Fiz-Victor 这个应用如果不是官方版，QQ登录不会通过，和模块无关

谢谢，找到问题了，发现是隐藏应用模块配置把qq开白名单模式了
