### ISSUE TITLE
[功能请求] 违规群聊查看历史记录

### ISSUE THREAD

**Issue by 2980077544** [cinit/QAuxiliary#535]
### QQ(TIM)版本/QQ(TIM) Version

qq v8.9.68.11565

### 为什么你认为需要此功能

违规群聊中有一些迫切需要的东西，但是没法查看，很头疼

### 具体功能需要/Specific features require

正常情况下点左边的按钮会回到好友界面，点右边的按钮群聊会从好友列表消失。

![Screenshot_2023-08-01-00-43-24-257_com.tencent.mobileqq.jpg](https://img1.imgtp.com/2023/08/01/m2eMuhLX.jpg)

需要取消这个对话框使得可以查看违规被踢出群聊的聊天历史记录。

**Comment by HdShare** [comment]
尝试最新CI-r2144版本
