### ISSUE TITLE
[Bug] 查看转发消息详细信息群号显示错误

### ISSUE THREAD

**Issue by ztb1126** [cinit/QAuxiliary#538]
### Steps to reproduce/复现步骤

1.辅助功能>聊天和消息>消息>转发消息点头像查看详细信息
2.找到一个聊天记录查看详细信息

### Expected behaviour/预期行为

在不加群的情况下会显示正确的群号

### Actual behaviour/实际行为

![Screenshot_20230801_164902_com tencent tim](https://github.com/cinit/QAuxiliary/assets/123040986/c1826e20-333f-4095-8537-dd7fc6a1a31d)
![Screenshot_20230801_164854_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/123040986/d35d2e2c-85db-4ec3-980d-6a0e4b113d2b)
![Screenshot_20230801_163304_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/123040986/05bd371f-c9ad-4255-bca3-ff8d2919dc1f)
加群查看详细信息会显示正确的群号，没加的群查看详细信息会统一显示284840486这个错误的群号

### XPosed Framework you used/你使用的XP框架

lspatch

### QQ(TIM)版本/QQ(TIM) Version

qq8.9.63

### Module Version/模块版本

1.4.2.r1666.f45306d(1666)

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.4.2.r1666.f45306d
QQ8.9.63(4194)
PID: 14692, UID: 10642
cc.ioctl.hook.msg.MultiForwardAvatarHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by klxiaoniu** [comment]
这个应该是腾讯方面的原因，有待观察

**Comment by klxiaoniu** [comment]
已在 https://github.com/cinit/QAuxiliary/commit/56d72b2d6eb51952e264f9e1dd072a10c6e4d162 中排除了这个群号。
