### ISSUE TITLE
[Bug] 合并转发消息点击头像显示为一个特殊场景群号

### ISSUE THREAD

**Issue by Sh4peshifting** [cinit/QAuxiliary#539]
### Steps to reproduce/复现步骤

1. 启用转发消息点头像查看详细信息功能
2. 打开合并转发消息
3. 点击头像查看详细信息
![Screenshot_20230801-222826](https://github.com/cinit/QAuxiliary/assets/56795584/238d3267-0f73-45ca-9f04-40b973120bab)
![Screenshot_20230801-222847](https://github.com/cinit/QAuxiliary/assets/56795584/09788b70-e4a1-4b92-8938-3202ef510f0c)

### Expected behaviour/预期行为

群号应正常显示为实际群号

### Actual behaviour/实际行为

群号被定向为一个无法被查找加入的特殊场景群号

### XPosed Framework you used/你使用的XP框架

LSPatch 0.5.1(382)

### QQ(TIM)版本/QQ(TIM) Version

TIM 3.5.0

### Module Version/模块版本

1.4.2r1659.fd171b1

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.4.2.r1659.fd171b1
TIM3.5.0(1288)
PID: 26547, UID: 10461
cc.ioctl.hook.msg.MultiForwardAvatarHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by huajijam** [comment]
#duplicated #538
