### ISSUE TITLE
[Bug] 查看合并转发的聊天记录群号时失效

### ISSUE THREAD

**Issue by Amz10969** [cinit/QAuxiliary#541]
### Steps to reproduce/复现步骤

打开合并转发的聊天记录，点击头像

### Expected behaviour/预期行为

显示群号 成员QQ号

### Actual behaviour/实际行为

群号经常显示284840486
然而功能异常列表中显示正常
![Screenshot_20230803_122605](https://github.com/cinit/QAuxiliary/assets/141299138/91e28c07-bcfd-4508-b4f6-984e1df47e43)

### XPosed Framework you used/你使用的XP框架

太极10.3.2.03081021-9736

### QQ(TIM)版本/QQ(TIM) Version

8.9.58（4108）

### Module Version/模块版本

1.4.2.r1659.fd171b1

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.4.2.r1659.fd171b1
QQ8.9.58(4108)
PID: 17465, UID: 10223
cc.ioctl.hook.msg.MultiForwardAvatarHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by Amz10969** [comment]
补充:这是那个群打开的样子
![Screenshot_20230803_125601](https://github.com/cinit/QAuxiliary/assets/141299138/bd3ec409-b7b4-45d3-9bc0-7e01e9c0abe5)

**Comment by keta1** [comment]
#duplicated https://github.com/cinit/QAuxiliary/issues/538
