### ISSUE TITLE
[Bug] 消息+1Plus后消息气泡为默认蓝色气泡

### ISSUE THREAD

**Issue by XeronOwO** [cinit/QAuxiliary#542]
### Steps to reproduce/复现步骤

1. 启用消息+1Plus功能
2. 在个性装扮中使用默认以外的气泡（我用的是3块钱付费气泡）
3. 点击他人消息右边的+1按钮
4. 发送的消息的气泡为默认蓝色气泡

### Expected behaviour/预期行为

发送的消息的气泡应为自己个性装扮使用的气泡

### Actual behaviour/实际行为

发送的消息的气泡为默认蓝色气泡

### XPosed Framework you used/你使用的XP框架

LSPosed(1.8.5) (6649) - Zygisk

### QQ(TIM)版本/QQ(TIM) Version

8.9.71(4332)

### Module Version/模块版本

1.4.2.r1667.56d72b2(1667)

### Version requirement/版本要求

- [x] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

1.4.2.r1667.56d72b2
QQ8.9.71(4332)
PID: 32738, UID: 10289
cc.hicore.hook.RepeaterPlus
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by HdShare** [comment]
尝试最新CI版本
