### ISSUE TITLE
[Bug] 去你大爷的QQ浏览器对部分链接无效

### ISSUE THREAD

**Issue by Sh4peshifting** [cinit/QAuxiliary#545]
### Steps to reproduce/复现步骤

1. 启用该功能
2. 打开微信公众号或腾讯文档分享链接(已知这两种会失效)，例如https://mp.weixin.qq.com/s/JxjHBXJVeejlsui9Ct5_Gg

### Expected behaviour/预期行为

选择使用其他浏览器打开链接

### Actual behaviour/实际行为

使用qq内置浏览器或小程序打开链接

### XPosed Framework you used/你使用的XP框架

LSPatch 版本 0.5.1 (383)  框架版本 1.8.6 (6911) 

### QQ(TIM)版本/QQ(TIM) Version

QQ8.9.58

### Module Version/模块版本

1.4.2.r1659.fd171b1

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.2.r1659.fd171b1
QQ8.9.58(4106)
PID: 32325, UID: 10463
me.singleneuron.hook.decorator.FxxkQQBrowser
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by keta1** [comment]
这是预期行为

**Comment by Sh4peshifting** [comment]
> 这是预期行为

了解了，意思是本身对这腾讯系链接不起作用对吗

**Comment by keta1** [comment]
@Sh4peshifting 因为很多腾讯系连接只能在 qq 里打开，为了不影响正常使用，故意这么设置的
