### ISSUE TITLE
[Bug] 多个功能存在异常

### ISSUE THREAD

**Issue by x-leehe** [cinit/QAuxiliary#547]
### Steps to reproduce/复现步骤

如题，多个功能存在异常。具体问题原因和问题日志，请参考日志。

### Expected behaviour/预期行为

这些功能可以正常工作

### Actual behaviour/实际行为

这些功能或并未开启，或开启了提示出现错误，或开启后无法起作用，或无法达到预期效果。

### XPosed Framework you used/你使用的XP框架

LSPosed，框架版本 1.8.6 (6712) ，管理器版本 1.8.6 (6712) 

### QQ(TIM)版本/QQ(TIM) Version

QQNT 8.9.71(4332)

### Module Version/模块版本

1.4.2.r1672.aebc6f2(1672)，构建时间2023-08-04 19:01:08

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

[见此链接。](https://leehemail-my.sharepoint.com/:u:/g/personal/x-leehe_leehemail_onmicrosoft_com/ERcaX_aQc8hGlENO0qFcu1UBZrhHIWa1ZmDj8zx0_30pig?e=PquAwh)

**Comment by x-leehe** [comment]
还有，那个热更新的功能什么时候可以使用啊（

**Comment by cinit** [comment]
@x-leehe 真的有人想上热更新吗？我自己都不敢做热更新。

**Comment by klxiaoniu** [comment]
@x-leehe 头像挂件有泄漏是QQ自身有问题；群号不显示，因已被和谐；防撤回提示部分显示u_串，为正常表现。

**Comment by x-leehe** [comment]
啊呜…原来这样…那好吧

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
