### ISSUE TITLE
There is an error with a picture when replying, 1 exception

### ISSUE THREAD

**Issue by a328929** [cinit/QAuxiliary#548]
### Steps to reproduce/复现步骤

1. Enter any text in the message box, 2. Select any image in the emoticon, and the storage path of the emoticon will appear in the message box. 3. Click Send and the emoji will appear below the text you just typed.

### Expected behaviour/预期行为

1. Enter any text in the message box, 2. Select any image in the emoticon, and the storage path of the emoticon will appear in the message box. 3. Click Send and the emoji will appear below the text you just typed.

### Actual behaviour/实际行为

1. Enter any text in the message box. 2. If you select any picture in the emoticon, the storage path of the emoticon will not appear in the message box. 3. Click Send, the image will be sent directly, but the text you just entered will remain. This function is completely disabled.

### XPosed Framework you used/你使用的XP框架

Application name: LSPatch Package name: org.lsposed.lspatch Version name: 0.5.1 Version code: 382

### QQ(TIM)版本/QQ(TIM) Version

Application name: QQ Package name: com.tencent.mobileqq Version name: 8.9.68 Version code: 4264

### Module Version/模块版本

1.4.2.r1677

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

[ReplyMsgWithImg-1691351561602.txt](https://github.com/cinit/QAuxiliary/files/12270372/ReplyMsgWithImg-1691351561602.txt)

**Comment by keta1** [comment]
can u speak Chinese ?

**Comment by a328929** [comment]
yes









若有知音见采，不辞遍唱阳春。---Original---
From: ***@***.***&gt;
Date: Mon, Aug 7, 2023 04:35 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cinit/QAuxiliary] There is an error with a picture whenreplying, 1 exception (Issue #548)




 
can u speak Chinese ?
 
&mdash;
