### ISSUE TITLE
[Bug] 显示具体消息数量无效

### ISSUE THREAD

**Issue by ztb1126** [cinit/QAuxiliary#551]
### Steps to reproduce/复现步骤

这个应该没必要吧

### Expected behaviour/预期行为

群聊显示消息数量可以突破99+，显示完整的消息数量，而不是99+

### Actual behaviour/实际行为

并没有显示完整消息数量，而是显示99+，而且功能异常列表里也没有显示存在错误和不兼容当前版本，我同时使用的tim并没有问题，经过我的测试，这个功能与模块KModule的功能冲突了

### XPosed Framework you used/你使用的XP框架

lspatch0.5.1(385)

### QQ(TIM)版本/QQ(TIM) Version

QQ8.9.68

### Module Version/模块版本

1.4.2.r1678.e2a5547(1678)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.2.r1678.e2a5547
QQ8.9.68(4264)
PID: 15177, UID: 10642
cc.ioctl.hook.msg.ShowMsgCount
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by klxiaoniu** [comment]
“经过我的测试，这个功能与模块KModule的功能冲突了”

issue 提错地方了，应该去找 kmodule 开发者
