### ISSUE TITLE
[功能请求] 禁止群聊消息自动回到底部

### ISSUE THREAD

**Issue by Bcake123** [cinit/QAuxiliary#555]
### QQ(TIM)版本/QQ(TIM) Version

8.9.70(4330)

### 为什么你认为需要此功能

更新了8.9.70版本的QQ后，有时群里消息很多，需要一直往上划从第一条未读消息开始依次阅读，可是在滑动过程中，若有人发了新的消息，则会被自动拉回到底部新消息处，这极大的影响了聊天记录的阅读，因此希望有上述功能。

### 具体功能需要/Specific features require

禁止群聊消息自动回到底部。

**Comment by cinit** [comment]
是收消息时还是发消息时？我这边 8.9.90.13250 (4938) 收消息时没有发现这个问题。

**Comment by Bcake123** [comment]
我也更新到了最新版8.9.90.13250&nbsp;(4938)
估计是tx自己把这个bug修了&nbsp;现在没问题了&nbsp;这个issue可以关掉了&nbsp;辛苦啦~


---原始邮件---
发件人: &quot;ACh ***@***.***&gt;
发送时间: 2023年11月20日(周一) 下午3:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cinit/QAuxiliary] [功能请求] 禁止群聊消息自动回到底部 (Issue #555)




 
是收消息时还是发消息时？我这边 8.9.90.13250 (4938) 收消息时没有发现这个问题。
 
&mdash;
