### ISSUE TITLE
[功能请求] 频道防撤回失效

### ISSUE THREAD

**Issue by Chenyu550** [cinit/QAuxiliary#557]
### Steps to reproduce/复现步骤

1.进入一个频道，让别人发一条消息，然后撤回
2.让对方撤回这条消息

### Expected behaviour/预期行为

能正常撤回

### Actual behaviour/实际行为

![Screenshot_2023-08-10-20-50-58-151-edit_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/114039435/cb5082b9-66db-4173-adce-d70baaa9afce)

### XPosed Framework you used/你使用的XP框架

lsposed

### QQ(TIM)版本/QQ(TIM) Version

8.9.68

### Module Version/模块版本

1.4.2.r1681.6b9ffd0(1681)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

日志没有报错，但是实际上没有用
1.4.2.r1681.6b9ffd0
QQ8.9.68(4264)
PID: 22262, UID: 10239
cc.ioctl.hook.guild.RevokeGuildMsg
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by HdShare** [comment]
重复 #223
