### ISSUE TITLE
[Bug] "可选使用系统相册“失效

### ISSUE THREAD

**Issue by RedLeaf007** [cinit/QAuxiliary#558]
### Steps to reproduce/复现步骤

开启qa“净化设置>聊天界面>可选使用系统相册”，在聊天界面，点击”相册“

### Expected behaviour/预期行为

点击”相册“后弹出”选择相册“框，可以选择系统相册、系统文档、QQ相册

https://github.com/cinit/QAuxiliary/assets/53726620/4eaf3988-c0b9-498a-b91f-8e1c6a1602ae

### Actual behaviour/实际行为

点击”相册：后直接进入QQ相册

https://github.com/cinit/QAuxiliary/assets/53726620/c5fb93d9-dfe8-40f0-b03a-047634fe58bc

### XPosed Framework you used/你使用的XP框架

LSPosed 1.8.6(6904)

### QQ(TIM)版本/QQ(TIM) Version

8.9.73(4416)

### Module Version/模块版本

1.4.2.r1681.6b9ffd0(1681)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

[ForceSystemAlbum-1691674360948.txt](https://github.com/cinit/QAuxiliary/files/12313355/ForceSystemAlbum-1691674360948.txt)
[LSPosed_2023-08-10T21_27_25.547995.zip](https://github.com/cinit/QAuxiliary/files/12313373/LSPosed_2023-08-10T21_27_25.547995.zip)

**Comment by longzho** [comment]
通过 OPatch 安装 QQ 并使用了最新版本的 QA 模块后，仍出现了此问题
1.5.0.r2001.597cbf1
QQ9.0.30(6038)
PID: 15327, UID: 10492
me.singleneuron.hook.decorator.ForceSystemAlbum
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0
![Screenshot_2024-04-15-13-56-10-01_9d26c6446fd7bb8e41d99b6262b17def](https://github.com/cinit/QAuxiliary/assets/118370548/007c44ed-3f09-485e-bd3a-f52839e5e273)

**Comment by metaltube** [comment]
在最新 CI Build 下仍然存在该问题：


1.5.4.r2517.7618607
QQ9.0.60(6478)
PID: 9619, UID: 10221
me.singleneuron.hook.decorator.ForceSystemAlbum
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0
