### ISSUE TITLE
「BUG」查看转发消息点击目标头像时无法显示QQ群号

### ISSUE THREAD

**Issue by sxyofficial** [cinit/QAuxiliary#563]
### Steps to reproduce/复现步骤

点开转发记录后，点击对应头像，无法看到群聊号，只能看到对应QQ号
![Screenshot_2023-08-11-20-58-59-804_com tencent mobileqq-edit](https://github.com/cinit/QAuxiliary/assets/138845393/c82052bb-ccbd-430d-9109-075dc2f360f1)

### Expected behaviour/预期行为

可以看到群聊号和QQ号

### Actual behaviour/实际行为

现在无法获取群聊号

### XPosed Framework you used/你使用的XP框架

lsposed

### QQ(TIM)版本/QQ(TIM) Version

8.9.71

### Module Version/模块版本

1.4.3.r1682.61b8fe6(1682)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.3.r1682.61b8fe6
QQ8.9.71(4332)
PID: 15678, UID: 10333
cc.ioctl.hook.msg.MultiForwardAvatarHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by Hicores** [comment]
和谐了

**Comment by sxyofficial** [comment]
> 和谐了

啊哦，后续会有恢复的可能性嘛？

**Comment by keta1** [comment]
你快入职腾讯去帮我们问问

**Comment by klxiaoniu** [comment]
写Issue的时候三个勾愣是不看盲勾啊

**Comment by sxyofficial** [comment]
> 写Issue的时候三个勾愣是不看盲勾啊

就最近出的问题，用的最新模块ci，用的正式版QQ

**Comment by keta1** [comment]
> > 写Issue的时候三个勾愣是不看盲勾啊
> 
> 就最近出的问题，用的最新模块ci，用的正式版QQ

### Version and Other Requirements/版本和其他要求
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue

**Comment by huajijam** [comment]
下次直接dupe#538
