### ISSUE TITLE
内置小白条沉浸

### ISSUE THREAD

**Issue by skirky3605** [cinit/QAuxiliary#565]
### QQ(TIM)版本/QQ(TIM) Version

8.9.73

### 为什么你认为需要此功能

搞外挂小白条沉浸太麻烦了，希望模块内置一个小白条沉浸的功能

### 联系到哪些已经存在的bug或者功能

无

### 具体功能需要/Specific features require

沉浸小白条功能

**Comment by RedLeaf007** [comment]
这个最好的办法只能是给QQ反馈。
我之前给QQ反馈过，半个月后得到回复“被打回去重做”。不知道什么时候能做出来。

**Comment by RedLeaf007** [comment]
QQ有一堆Dock栏不是白色的主题，且默认主题的dock栏有高斯模糊。

**Comment by lliioollcn** [comment]
QQ最新内测已支持
