### ISSUE TITLE
[Bug] 安卓7.1系统无法打开1.4.2-1.4.3 QAuxiliary

### ISSUE THREAD

**Issue by sisi0318** [cinit/QAuxiliary#566]
### Steps to reproduce/复现步骤

无

### Expected behaviour/预期行为

打开qa应用界面

### Actual behaviour/实际行为

多次闪退 然后 QAuxiliary 已停止运行

### XPosed Framework you used/你使用的XP框架

太极

### QQ(TIM)版本/QQ(TIM) Version

QQ 8.9.63

### Module Version/模块版本

QAuxiliary 1.4.3.r1682.61b8fe6

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

软件打不开，无法获取日志

**Comment by klxiaoniu** [comment]
@sisi0318 没日志，约等于无法修复
