### ISSUE TITLE
[功能请求] Qnotified拥有的语音保存功能

### ISSUE THREAD

**Issue by miangou** [cinit/QAuxiliary#57]
### QQ(TIM)版本/QQ(TIM) Version

8.6.0

### 为什么你认为需要此功能

可以保存证据方便鞭尸（不是

### 具体功能需要/Specific features require

长按语音信息保存至目录

**Comment by cinit** [comment]
@miangou 不是有保存语音文件吗？

**Comment by miangou** [comment]
> @miangou 不是有保存语音文件吗？

![Screenshot_20220424-225021_QQ.png](https://user-images.githubusercontent.com/63963655/164982243-ae21aec8-011b-4087-bae4-3f4788d88276.png)

**Comment by miangou** [comment]
> > @miangou 不是有保存语音文件吗？
> 
> ![Screenshot_20220424-225021_QQ.png](https://user-images.githubusercontent.com/63963655/164982243-ae21aec8-011b-4087-bae4-3f4788d88276.png)

@cinit

**Comment by cinit** [comment]
@miangou 语音转发功能应该是带保存的
