### ISSUE TITLE
移除右滑群应用[Bug] 

### ISSUE THREAD

**Issue by UsernameMryu** [cinit/QAuxiliary#572]
### Steps to reproduce/复现步骤

开启移除右划群应用后，在群聊界面右划是黑屏，我记得之前是直接禁止划动，现在划了以后是黑屏，有点割裂

### Expected behaviour/预期行为

群聊界面不能右划

### Actual behaviour/实际行为

黑屏或者白屏

### XPosed Framework you used/你使用的XP框架

lsposed1.8.6（8864）

### QQ(TIM)版本/QQ(TIM) Version

8.9.73.11945

### Module Version/模块版本

1.4.3.r1685.7f9b633(1685)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.3.r1685.7f9b633
QQ8.9.73(4416)
PID: 23129, UID: 10343
cc.ioctl.hook.troop.RemoveGroupApp
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by klxiaoniu** [comment]
duplicate #504
