### ISSUE TITLE
[Bug] 表情面板闪退

### ISSUE THREAD

**Issue by tony6960** [cinit/QAuxiliary#579]
### Steps to reproduce/复现步骤

1.打开表情面板功能
2.长按表情图标
3.发现闪退

### Expected behaviour/预期行为

打开表情面板

### Actual behaviour/实际行为

QQ闪退

### XPosed Framework you used/你使用的XP框架

太极青钢影·10.3.2.03081021-9806

### QQ(TIM)版本/QQ(TIM) Version

QQ V 8.9.73.11945

### Module Version/模块版本

1.4.3.r1682.61b8fe6

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.3.r1682.61b8fe6
QQ8.9.73(4416)
PID: 29510, UID: 10458
cc.hicore.hook.stickerPanel.Hooker.StickerPanelEntryHooker
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by klxiaoniu** [comment]
把框架更换成LSPatch看会不会闪退

**Comment by klxiaoniu** [comment]
长期未回复，关闭处理

**Comment by Hicores** [comment]
@klxiaoniu 太极自身类加载器问题,难以修复
