### ISSUE TITLE
[功能请求] 自动续火功能、自动回赞和定时点赞

### ISSUE THREAD

**Issue by tony6960** [cinit/QAuxiliary#580]
### QQ(TIM)版本/QQ(TIM) Version

QQ V 8.9.73.11945

### 为什么你认为需要此功能

反复的续火和回赞极为枯燥和麻烦，容易忘记，烦请加入自动续火和自动回赞功能，谢谢！

### 具体功能需要/Specific features require

自动续火：在特定时间向指定联系人或者群聊发送指定语句达到续火目的
自动回赞：在他人对我方账号进行点赞时及时回赞
定时点赞：在指定时间对指定账号的资料卡进行点赞

**Comment by klxiaoniu** [comment]
去用XAutoDaily哈
