### ISSUE TITLE
[Bug] 防撤回和以图片方式打开闪照功能异常

### ISSUE THREAD

**Issue by GanSun** [cinit/QAuxiliary#596]
### Steps to reproduce/复现步骤

1.收到闪照仍然以闪照方式展现，非图片方式。
2.群聊内有消息撤回时，如果此时未在当前界面或者qq处于后台，则有大概率提示未收到消息。

### Expected behaviour/预期行为

1.收到闪照能以图片方式展示。
2.即使qq处于后台，仍能正常保存被撤回的消息并显示出来。

### Actual behaviour/实际行为

![防撤回](https://github.com/cinit/QAuxiliary/assets/38599036/994fb50f-542a-415e-9ffa-bed3bd605902)
![闪照](https://github.com/cinit/QAuxiliary/assets/38599036/649a0130-fe99-49e8-8d58-d06976fbd97a)

### XPosed Framework you used/你使用的XP框架

taichi 10.3.2.03081021-9820

### QQ(TIM)版本/QQ(TIM) Version

8.9.70（4330）

### Module Version/模块版本

1.4.3.r1682.61b8fe6(1682)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

功能异常列表中提示未见明显异常。
防撤回：
1.4.3.r1682.61b8fe6
QQ8.9.70(4330)
PID: 18508, UID: 99910593
cc.ioctl.hook.msg.RevokeMsgHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0
闪照：
1.4.3.r1682.61b8fe6
QQ8.9.70(4330)
PID: 18508, UID: 99910593
cc.ioctl.hook.msg.FlashPicHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by klxiaoniu** [comment]
闪照问题无法复现，建议更换其他框架（如LSP）再试

**Comment by GanSun** [comment]
> 闪照问题无法复现，建议更换其他框架（如LSP）再试

已改用lspatch，闪照问题已解决，撤回消息提示没收到问题仍然存在

**Comment by klxiaoniu** [comment]
撤回未收到因QQ后台掉，目前为正常现象
