### ISSUE TITLE
[功能请求] 强开被隐藏的匿名聊天功能

### ISSUE THREAD

**Issue by yqs112358** [cinit/QAuxiliary#599]
### QQ(TIM)版本/QQ(TIM) Version

8.9.73

### 为什么你认为需要此功能

如题，最近腾讯疑似开始在某些群聊屏蔽匿名聊天，表现为群聊匿名已开启，但是➕号菜单中匿名按钮消失。

![Screenshot_2023-08-26-22-25-58-426_com tencent mobileqq-edit](https://github.com/cinit/QAuxiliary/assets/37969157/52e7a230-f569-4db6-8798-bc77a4cbe9e2)

![Screenshot_2023-08-28-09-56-36-696_com tencent mobileqq-edit](https://github.com/cinit/QAuxiliary/assets/37969157/a6d8b5de-e7e8-4e54-91a5-fe599deaa825)

已经经过多人，多设备，多个群聊的交叉验证，确认不是单个设备单个群聊的问题。自己是群主的群聊同样无法使用匿名。
除安卓外ios也有同样的问题。目前只有pc版的老qq可以正常发送匿名消息。安卓版TIM3.5.2也可以正常发送匿名，但是无法跟QQ安卓同时保持登录，会互相踢下线。

### 具体功能需要/Specific features require

希望在模块可以强开被腾讯隐藏的匿名功能（即，群聊本身允许匿名的情况下仍然不显示匿名按钮）

**Comment by yqs112358** [comment]
更新：TIM匿名功能已不再可用，疑似在服务器端屏蔽。老PCQQ暂时仍然可用

估计快凉了

**Comment by GrassGreenPi** [comment]
您好，已收到您的邮件，我会尽快回复的～Hello，I have received your mail and will reply it as soon as possible ～

**Comment by MicroCBer** [comment]
服务器端已屏蔽匿名包

**Comment by GrassGreenPi** [comment]
您好，已收到您的邮件，我会尽快回复的～Hello，I have received your mail and will reply it as soon as possible ～
