### ISSUE TITLE
[Bug] MIUI小窗的QQ上划关闭动画异常

### ISSUE THREAD

**Issue by luobr233** [cinit/QAuxiliary#608]
### Steps to reproduce/复现步骤

1.QA的设置：
聊天界面查看图片背景模糊[开]
聊天界面查看图片使用透明背景[开]
2.打开一个应用（除了QQ）
3.打开MIUI小窗的QQ
4.打开一张聊天图片
5.上划关闭

### Expected behaviour/预期行为

QQ的MIUI小窗被流畅地上划动作关闭

### Actual behaviour/实际行为

上划关闭动画抽搐

https://github.com/cinit/QAuxiliary/assets/58586966/aee8c995-62d4-4fde-be6a-c449d5a61243

### XPosed Framework you used/你使用的XP框架

LSPosed 1.9.1(6990) - Zygisk

### QQ(TIM)版本/QQ(TIM) Version

8.9.38.10545

### Module Version/模块版本

1.4.3.r1708.de44e8d

### Version and Other Requirements/版本和其他要求

- [x] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

聊天界面查看图片背景模糊的日志：
1.4.3.r1708.de44e8d
QQ8.9.38(3856)
PID: 22749, UID: 10282
io.github.duzhaokun123.hook.GalBgBlurHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0
聊天界面查看图片使用透明背景的日志：
1.4.3.r1708.de44e8d
QQ8.9.38(3856)
PID: 22749, UID: 10282
cc.ioctl.hook.chat.GalleryBgHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by luobr233** [comment]
没找到在哪里启用详细日志。

**Comment by klxiaoniu** [comment]
建议联系MIUI解决
