### ISSUE TITLE
[Bug]8.9.78版本+1plus功能失效

### ISSUE THREAD

**Issue by Daroach0** [cinit/QAuxiliary#617]
### Steps to reproduce/复现步骤

设置好+1plus后在聊天界面点了+1没反应
关闭了之后正常的+1还能用

### Expected behaviour/预期行为

虽然是8.9.78版本但+1用不了还是难受

### Actual behaviour/实际行为

8.9.78版本+1plus失效

### XPosed Framework you used/你使用的XP框架

太极

### QQ(TIM)版本/QQ(TIM) Version

8.9.78

### Module Version/模块版本

1.4.3.r1682.61b8fe6(1682)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

奇怪的是并没有显示异常

**Comment by Hicores** [comment]
I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
