### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by zzzholo** [cinit/QAuxiliary#619]
### Steps to reproduce/复现步骤

勾选功能组件后该功能无法正确运行

### Expected behaviour/预期行为

精简加号菜单
隐藏亲密抽屉
聊天自动发送原图
隐藏会员红名

### Actual behaviour/实际行为

![Screenshot_2023-09-10-02-41-44-661_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/144557862/ef41a48f-6149-40ce-aa9e-97e47f59cc80)

### XPosed Framework you used/你使用的XP框架

1.9.1（6997）

### QQ(TIM)版本/QQ(TIM) Version

8.9.78(4548)

### Module Version/模块版本

1.4.3.r1682.61b8fe6(1682)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

[AutoSendOriginalPhoto-1694284878249.txt](https://github.com/cinit/QAuxiliary/files/12566478/AutoSendOriginalPhoto-1694284878249.txt)
[DisabledRedNick-1694284885555.txt](https://github.com/cinit/QAuxiliary/files/12566479/DisabledRedNick-1694284885555.txt)
[RemoveIntimateDrawer-1694284889602.txt](https://github.com/cinit/QAuxiliary/files/12566480/RemoveIntimateDrawer-1694284889602.txt)
[SimplifyPlusPanel-1694284893794.txt](https://github.com/cinit/QAuxiliary/files/12566481/SimplifyPlusPanel-1694284893794.txt)

**Comment by klxiaoniu** [comment]
更新到最新 CI 再反馈
