### ISSUE TITLE
[Bug] 聊天字数统计无效

### ISSUE THREAD

**Issue by liu486** [cinit/QAuxiliary#622]
### Steps to reproduce/复现步骤

隐藏会员红名 自动发送原图 隐藏亲密抽屉 聊天字数统计无效

### Expected behaviour/预期行为

有效

### Actual behaviour/实际行为

无效 没有用

### XPosed Framework you used/你使用的XP框架

lsposed

### QQ(TIM)版本/QQ(TIM) Version

9.9.75_64

### Module Version/模块版本

QAuxv-v1.4.4.r1735.d9f7335-arm64

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

[bug详细.zip](https://github.com/cinit/QAuxiliary/files/12673498/bug.zip)

**Comment by klxiaoniu** [comment]
@liu486 重复的Issue不要反馈

**Comment by MicroCBer** [comment]
dup #468
