### ISSUE TITLE
QQ聊天自动添加小尾巴功能

### ISSUE THREAD

**Issue by baiqilingnai** [cinit/QAuxiliary#625]
### QQ(TIM)版本/QQ(TIM) Version

8.9.58

### 为什么你认为需要此功能

能够给聊天添加趣味

### 具体功能需要/Specific features require

聊天发出的文字后面自动添加一个你想要添加的文字

**Comment by cinit** [comment]
不打算开发此功能，请考虑使用其他模块，谢谢。
