### ISSUE TITLE
[功能请求] 增加一个可以查看QQ群中匿名消息发布者的QQ号及相关账号信息

### ISSUE THREAD

**Issue by ponysun618** [cinit/QAuxiliary#63]
### QQ(TIM)版本/QQ(TIM) Version

支持所有的QQ及TIM版本

### 为什么你认为需要此功能

因为有些时候群里面有些人特别喜欢发布一些匿名信息，出于想知道这些发布匿名消息是具体哪些人，所以我认为需要开发此功能，以查看发布匿名信息的QQ号。

### 具体功能需要/Specific features require

希望开发一个单独的设置开关，打开或关闭用来查看QQ群中发布匿名信息具体的QQ号及账号信息。

**Comment by qwq233** [comment]
办不到

**Comment by keta1** [comment]
做不出来

**Comment by cinit** [comment]
@ponysun618 建议开发个一键踢群主

**Comment by Hakuin123** [comment]
你猜为什么叫匿名消息😂
