### ISSUE TITLE
[Bug] 8.8.98 +1 Plus 功能异常

### ISSUE THREAD

**Issue by ColdLemonTea** [cinit/QAuxiliary#631]
### Steps to reproduce/复现步骤

1.更新最新CI
2.重启QQ
3.QA故障排查 +1 Plus 功能异常

### Expected behaviour/预期行为

+1 Plus 应正常使用

### Actual behaviour/实际行为

它没法工作

### XPosed Framework you used/你使用的XP框架

LSPosed

### QQ(TIM)版本/QQ(TIM) Version

8.8.9.8

### Module Version/模块版本

1.4.4.r1737.9abcf42 (1737)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

[RepeaterPlus-1695684959667.txt](https://github.com/cinit/QAuxiliary/files/12720393/RepeaterPlus-1695684959667.txt)

**Comment by ColdLemonTea** [comment]
1.4.3.r1723.377efd4 (1723) 是最后一个+1 Plus正常使用的版本

**Comment by Hicores** [comment]
尝试最新的ci版本

**Comment by ColdLemonTea** [comment]
> 尝试最新的ci版本

Done.
