### ISSUE TITLE
关闭群帖子功能 与 移除右划群应用/禁用右划切换群帖子 存在冲突[Bug] 

### ISSUE THREAD

**Issue by ArkhalisDragon** [cinit/QAuxiliary#632]
### Steps to reproduce/复现步骤

1.同时打开标题中的三个功能，会导致在群聊界面右划进入空白页。
2.关闭“关闭群帖子功能”并开启其余两个功能后恢复正常，群聊界面不能右划。

### Expected behaviour/预期行为

同时打开三个功能，群聊界面不能右划，且没有群帖子功能入口

### Actual behaviour/实际行为

同时打开三个功能会导致群聊界面右划进入空白页，且没有群帖子功能入口

### XPosed Framework you used/你使用的XP框架

LSP

### QQ(TIM)版本/QQ(TIM) Version

8.9.73

### Module Version/模块版本

1.4.4

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

这个应该不需要日志？我自己能够稳定复现（

**Comment by klxiaoniu** [comment]
这是禁止群应用失效，已有issue了
