### ISSUE TITLE
转发消息点头像查看详细信息功能异常

### ISSUE THREAD

**Issue by Tylerxz** [cinit/QAuxiliary#634]
### Steps to reproduce/复现步骤

打开合并转发消息点击头像

### Expected behaviour/预期行为

显示合并转发消息发送者

### Actual behaviour/实际行为

![Screenshot_20231001_091655_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/106852232/0204290f-f623-4751-8ceb-85f70dbd57b7)
显示发送者已被服务器端屏蔽

### XPosed Framework you used/你使用的XP框架

LSpatch

### QQ(TIM)版本/QQ(TIM) Version

8.9.80.12440(4614)

### Module Version/模块版本

1.4.4.r1739.a239a0a(1739)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.4.r1739.a239a0a
QQ8.9.80(4614)
PID: 28744, UID: 11009
cc.ioctl.hook.msg.MultiForwardAvatarHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by MicroCBer** [comment]
正常行为
