### ISSUE TITLE
[Bug] vivo在启用表情面板时闪退

### ISSUE THREAD

**Issue by jiucheng008** [cinit/QAuxiliary#635]
### Steps to reproduce/复现步骤

长按表情后崩溃

### Expected behaviour/预期行为

弹出表情面板

### Actual behaviour/实际行为

崩溃

### XPosed Framework you used/你使用的XP框架

太极·阴

### QQ(TIM)版本/QQ(TIM) Version

QQv 8.9.80

### Module Version/模块版本

1.4.4

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

没有报错

**Comment by klxiaoniu** [comment]
提供日志，模块版本写详细

**Comment by cinit** [comment]
已在 e1b4ffec95ddb2bfbca83249835d3030fb1b4348 修复，请测试 [CI build](https://github.com/cinit/QAuxiliary/actions/runs/6375616528)

**Comment by jiucheng008** [comment]
> 已在 [e1b4ffe](https://github.com/cinit/QAuxiliary/commit/e1b4ffec95ddb2bfbca83249835d3030fb1b4348) 修复，请测试 [CI build](https://github.com/cinit/QAuxiliary/actions/runs/6375616528)
已无问题，感谢
