### ISSUE TITLE
[Bug] QQ8.9.76内以照片打开闪照失效

### ISSUE THREAD

**Issue by siajia** [cinit/QAuxiliary#639]
### Steps to reproduce/复现步骤

反复打开开关以及重启重装都试过

### Expected behaviour/预期行为

闪照以图片方式出现

### Actual behaviour/实际行为

闪照仍然查看五秒后消失

### XPosed Framework you used/你使用的XP框架

taichi

### QQ(TIM)版本/QQ(TIM) Version

8.9.76

### Module Version/模块版本

1.4.5.r1748.e74a6f9

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.5.r1748.e74a6f9
QQ8.9.76(4484)
PID: 14164, UID: 10314
cc.ioctl.hook.msg.FlashPicHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by Samuel-meteor** [comment]
同版本qq与模块版本，太极版本14.0.5.10151817，同样的“以照片打开闪照失效”

**Comment by HdShare** [comment]
尝试最新CI版，QQ8.9.76+最新CI版r2109未复现
