### ISSUE TITLE
[Bug] 开启具体消息数量后新消息经常不显示

### ISSUE THREAD

**Issue by IOVEYOUMC0** [cinit/QAuxiliary#644]
### Steps to reproduce/复现步骤

开启显示具体消息数量

### Expected behaviour/预期行为

99+显示为具体消息数量
新消息正常预览内容

### Actual behaviour/实际行为

没有消息数量显示，并且消息预览卡在上次读取的消息
功能关闭后正常显示

### XPosed Framework you used/你使用的XP框架

LSPosed1.9.1(6990) - Zygisk

### QQ(TIM)版本/QQ(TIM) Version

8.9.83

### Module Version/模块版本

1.4.5.r1748.e74a6f9(1748)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.5.r1748.e74a6f9
QQ8.9.83(4680)
PID: 24666, UID: 10246
cc.ioctl.hook.msg.ShowMsgCount
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by klxiaoniu** [comment]
@IOVEYOUMC0 关闭之后恢复正常吗

**Comment by klxiaoniu** [comment]
@IOVEYOUMC0 这个理论上是无关的

**Comment by IOVEYOUMC0** [comment]
可能是QQ的问题吧，关闭后也不正常，但是开关一次开关可以让消息正常预览

**Comment by IOVEYOUMC0** [comment]
> @IOVEYOUMC0关闭之后恢复正常吗

可能是QQ的问题，关闭后仍然有这个问题，但是开关一次开关可以让消息显示恢复正常
