### ISSUE TITLE
[功能请求] “检测好友被删通知”黑名单

### ISSUE THREAD

**Issue by su226** [cinit/QAuxiliary#645]
### QQ(TIM)版本/QQ(TIM) Version

QQ 8.9.58

### 为什么你认为需要此功能

使用[XAutoDaily](https://github.com/LuckyPray/XAutoDaily)的“加好友活跃”时，会每天自动添加4个机器人并立即删除，有时会被QAuxiliary的“检测好友被删通知”误检测，如图。
![图片](https://github.com/cinit/QAuxiliary/assets/17371317/92fbe245-7ccd-49ce-9540-931cb85a529d)

### 联系到哪些已经存在的bug或者功能

检测好友被删通知

### 具体功能需要/Specific features require

允许设置“检测好友被删通知”的黑名单，检测到被指定用户删除好友时不发出通知，也不出现在历史好友列表中。

**Comment by cinit** [comment]
5baf326811742ef6653c285ac2d173d57856c49a
