### ISSUE TITLE
[功能请求] 夜间模式防撤回，消息跟踪不明显

### ISSUE THREAD

**Issue by fangyuan99** [cinit/QAuxiliary#652]
### QQ(TIM)版本/QQ(TIM) Version

8.9.80

### 为什么你认为需要此功能

防撤回成功后，点击`对方尝试撤回一条消息`，对应的消息会有灰色高亮，但是在**夜间模式的时候几乎不可见**，建议在夜间模式改成浅色或者用户自定义

### 具体功能需要/Specific features require

或者能否在`对方尝试撤回一条消息`后面直接加上撤回消息的缩写（或前几个字符）

**Comment by klxiaoniu** [comment]
定位消息时消息背景高亮是 QQ 自身提供，建议向官方反馈此问题

**Comment by fangyuan99** [comment]
> 定位消息时消息背景高亮是 QQ 自身提供，建议向官方反馈此问题

那能否在提示后面加上该撤回消息的前几个字符呢？也能辨识哪条消息撤回了
