### ISSUE TITLE
[Bug] 强制平板模式失效

### ISSUE THREAD

**Issue by aixiaoke5** [cinit/QAuxiliary#658]
### Steps to reproduce/复现步骤

rt

### Expected behaviour/预期行为

rt

### Actual behaviour/实际行为

rt

### XPosed Framework you used/你使用的XP框架

LSP1.9.2 (7032) - Zygisk

### QQ(TIM)版本/QQ(TIM) Version

8.9.85.12820

### Module Version/模块版本

1.4.5.r1779.980a37a

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.5.r1779.980a37a
QQ8.9.85(4766)
PID: 24016, UID: 10246
cc.ioctl.hook.experimental.ForcePadMode
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by klxiaoniu** [comment]
无法复现。

**Comment by tcscat** [comment]
我也遇到该问题了， 显示是平板登陆，但是会顶另外手机的qq下线

**Comment by tcscat** [comment]
我也遇到了，一样的版本

**Comment by ciskonc** [comment]
小米平板 5  pad pro 12.4 刷了GSI Arrow OS LSP版本1.9.2  尝试了 8.9.88 8.9.85版本下也无法强制平板模式

**Comment by aixiaoke5** [comment]
> 无法复现。

这个问题应该不是个例，还请进行排查

**Comment by HdShare** [comment]
试试最新CI-2321版本
