### ISSUE TITLE
[功能请求] 

### ISSUE THREAD

**Issue by xwh8965** [cinit/QAuxiliary#664]
### QQ(TIM)版本/QQ(TIM) Version

8.9.80

### 为什么你认为需要此功能

强迫症 个人比较喜欢的小功能 希望能实现 谢谢

### 具体功能需要/Specific features require

个人比较喜欢的小功能 希望能实现

就是长按转发消息的时候可以不多选 发送给单个好友跟群聊，然后取消掉发送提示 点击头像就能发送，发送了之后可以不跳回聊天窗口 这样就可以继续发送给其他好友了，不用再次长按转发了！
![IMG_20231110_201117](https://github.com/cinit/QAuxiliary/assets/150440229/ae44423d-770d-42ae-aac5-4032f7f1577a)

**Comment by MicroCBer** [comment]
@xwh8965 为什么不多选..?

**Comment by klxiaoniu** [comment]
建议使用：转发时强制开启多选用户/群组
