### ISSUE TITLE
[Bug] 复读机无法复读，带有图片和表情的文字消息 和消息回复

### ISSUE THREAD

**Issue by fgr178707** [cinit/QAuxiliary#665]
### Steps to reproduce/复现步骤

rt

### Expected behaviour/预期行为

rt

### Actual behaviour/实际行为

![1699660799018](https://github.com/cinit/QAuxiliary/assets/109357981/88c42605-13d1-4446-8f49-4bfe2f304ee9)

### XPosed Framework you used/你使用的XP框架

太极

### QQ(TIM)版本/QQ(TIM) Version

8.9.33.10335

### Module Version/模块版本

1.4.6.r1786.189196f

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

没有报错，就是点不了

**Comment by HdShare** [comment]
尝试最新CI版
