### ISSUE TITLE
[Bug] QQ的屏蔽气泡和屏蔽字体失效

### ISSUE THREAD

**Issue by bilibilixxc** [cinit/QAuxiliary#666]
### Steps to reproduce/复现步骤

有一次更新版本之前正常使用，之后失效

### Expected behaviour/预期行为

开启这两个功能之后所有人应当是默认气泡和字体

### Actual behaviour/实际行为

没有任何效果，依然是他们自己的气泡和字体

### XPosed Framework you used/你使用的XP框架

太极14.0.5.10151817-10150

### QQ(TIM)版本/QQ(TIM) Version

QQ 8.9.83.12605(4680)

### Module Version/模块版本

1.4.6.r1786.189196f(1786)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.6.r1786.189196f
QQ8.9.83(4680)
PID: 31413, UID: 10959
cc.ioctl.hook.chat.DefaultFont
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

1.4.6.r1786.189196f
QQ8.9.83(4680)
PID: 31413, UID: 10959
cc.ioctl.hook.chat.DefaultBubbleHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by HdShare** [comment]
尝试最新CI版
