### ISSUE TITLE
[功能请求] 移除屏蔽消息群的“修改消息设置”提示

### ISSUE THREAD

**Issue by MoonLeeeaf** [cinit/QAuxiliary#667]
### QQ(TIM)版本/QQ(TIM) Version

Tim 3.5.1

### 为什么你认为需要此功能

碍眼
![Screenshot_20231112_105016](https://github.com/cinit/QAuxiliary/assets/150461955/659d1ca2-5587-43fe-a367-3bd636508171)

### 具体功能需要/Specific features require

以下内容仅供开发者查看

滞空此方法，使其无法弹出Toast
请放心滞空，我已查看代码，不会返回任何值，不会回调
Lcom/tencent/mobileqq/activity/aio/rebuild/TroopChatPie$8$1;->run()V

不能保证所有 Tim 版本，但很多人也只能用3.5.1（NEWEST VER）(否则会被禁止登录)

涉及的 Resource id 为 0x7f0f02ad

![Screenshot_20231112_104408_bin mt plus](https://github.com/cinit/QAuxiliary/assets/150461955/0e1150fa-9e6d-48d0-903e-2084cd9c5990)

辛苦了

**Comment by HelloSuzume** [comment]
> 我不知道什么是最新版捏，具体版本号pls

关键字是吧 我版本号都说明了3.5.1了

**Comment by MicroCBer** [comment]
@HelloSuzume 你快发pr

**Comment by HelloSuzume** [comment]
> @HelloSuzume 你快发pr

@MicroCBer 我不会啊 (

**Comment by klxiaoniu** [comment]
推荐使用重构后的QQNT，已不存在此提示

**Comment by MoonLeeeaf** [comment]
![Screenshot_20240121_223236_mark via](https://github.com/cinit/QAuxiliary/assets/150461955/a6958479-36e2-4779-bb19-d5bd030398c3)
人麻了……

**Comment by MoonLeeeaf** [comment]
有点没想明白哪里出错了，有没有大佬愿意指教一些
https://github.com/MoonLeeeaf/QAuxiliary_TestOnly/actions/runs/7601918572/job/20701845599

**Comment by MoonLeeeaf** [comment]
考虑到我无法通过PR完成功能，还请各位帮助我完成，谢谢！

**Comment by MoonLeeeaf** [comment]
@MicroCBer @cinit 谢谢你们！功能已经在 Tim 3.5.1 上生效，没有报错，提示正常去除

**Comment by MoonLeeeaf** [comment]
很可惜tx又来恶心了一遍，辛苦了:-)
详见 #781 
![Screenshot_20240201_103235](https://github.com/cinit/QAuxiliary/assets/150461955/c2eef0a7-6382-4b81-baa7-db71fab90426)
