### ISSUE TITLE
点击通知栏通知进入频道，无法退出到主页消息界面

### ISSUE THREAD

**Issue by yuf19-2022** [cinit/QAuxiliary#669]
### Steps to reproduce/复现步骤

频道消息通知

### Expected behaviour/预期行为

点击通知栏的通知

### Actual behaviour/实际行为

进入频道，就退不出来，没法正常和好友聊天

### XPosed Framework you used/你使用的XP框架

用的别人打包好的

### QQ(TIM)版本/QQ(TIM) Version

QQ8.9.88.13035(4852)

### Module Version/模块版本

1.4.5.r1782.8aabfb0(1782)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

。。。

**Comment by klxiaoniu** [comment]
小伙子，你确定这是本模块导致的问题吗？以及你勾选三个勾的时候有仔细看这些勾选的文字吗？

**Comment by klxiaoniu** [comment]
@yuf19-2022 该功能有说明，只支持消息、联系人、动态三项移动到侧栏；且该功能为娱乐功能，基本不会维护
