### ISSUE TITLE
[功能请求] 希望添加查看群消息（历史）记录的入口

### ISSUE THREAD

**Issue by Pik-4** [cinit/QAuxiliary#670]
### QQ(TIM)版本/QQ(TIM) Version

TIM 3.5.5.3198

### 为什么你认为需要此功能

群会因为各种原因被封禁（解散或被移除群聊），需要查看群保存的消息记录，查看违禁发言或查找有用的历史信息。

### 具体功能需要/Specific features require

目前能够通过QQ号查看消息记录，想添加一个通过群号（或群名模糊匹配）查看群消息记录。

**Comment by klxiaoniu** [comment]
duplicate
