### ISSUE TITLE
[功能请求] Tim 快捷打开精华消息

### ISSUE THREAD

**Issue by MoonLeeeaf** [cinit/QAuxiliary#673]
### QQ(TIM)版本/QQ(TIM) Version

Tim 3.5.1

### 为什么你认为需要此功能

背景：截止目前，我们的 android tim 始终没有精华消息的入口，也没有此功能，但是 Windows Tim 却已经有了

需求：***在群里 我很担心某些消息被设置精华而自己不知道的问题***

### 具体功能需要/Specific features require

仅供开发人员查看

① 设置快捷入口
  * 群设置
  * 更多
  * 长按右上角三横杠
  * ……（其他，方便即可）

② 点击快捷入口进入精华消息（网页）
`
https://qun.qq.com/essence/index?gc=群号
`

感谢制作人员！

**Comment by MicroCBer** [comment]
@HelloSuzume 为什么不用新QQ

**Comment by HelloSuzume** [comment]
> @HelloSuzume 为什么不用新QQ

@MicroCBer 虽然 Tim 也流氓，但比 QQ 好多了

**Comment by klxiaoniu** [comment]
@HelloSuzume 你应当尝试新版QQ
