### ISSUE TITLE
[Bug] Pangu 功能工作不正常

### ISSUE THREAD

**Issue by EmptyDreams** [cinit/QAuxiliary#676]
### Steps to reproduce/复现步骤

打开发送消息自动 pangu 功能

### Expected behaviour/预期行为

发送消息是应该保留 at 名称后的空格

### Actual behaviour/实际行为

开启发送消息自动 pangu 功能后，at 别人时 at 后面的空格消失。
比如说 `@xxx 你好`，发送后变为`@xxx你好`，同时有时候空格能加上有时候空格加不上。

### XPosed Framework you used/你使用的XP框架

太极

### QQ(TIM)版本/QQ(TIM) Version

8.9.85.12820

### Module Version/模块版本

1.4.6.r1786.189196f(1786)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.6.r1786.189196f
QQ8.9.85(4766)
PID: 8168, UID: 10303
cc.microblock.hook.SendPangu
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by TimeRainStarSky** [comment]
@MicroCBer 我需要这个开头空格取消 Pangu 化，能否加个选项自由选择开启是否开头空格自动 Pangu 化
