### ISSUE TITLE
[Bug] 隐藏 QQ 钱包超值精选 会导致 红包 功能无法正常使用

### ISSUE THREAD

**Issue by yokinanya** [cinit/QAuxiliary#697]
### Steps to reproduce/复现步骤

1. 打开模块的 `侧滑栏` - `隐藏 QQ 钱包超值精选` 功能
2. 打开任意聊天窗口 ，打开红包发送页面

### Expected behaviour/预期行为

红包发送页面存在普通红包、语音红包等多种红包类型

### Actual behaviour/实际行为

红包发送页面只有普通红包和拼手气红包（拼手气红包只存在于群聊中），缺失了其他类型的红包

### XPosed Framework you used/你使用的XP框架

Lsposed 1.9.2(7031) - Zygisk

### QQ(TIM)版本/QQ(TIM) Version

8.9.90.13250

### Module Version/模块版本

1.4.6.r1814.54a7fe8(1814)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

功能异常列表中未见明显异常功能

**Comment by klxiaoniu** [comment]
尝试ci
