### ISSUE TITLE
[QQ8.8.68] 自定义机型无效

### ISSUE THREAD

**Issue by hechou** [cinit/QAuxiliary#7]
**QQ(TIM)版本/QQ(TIM) Version**

* 8.8.68(2538)

**模块版本/Module Version**

* 1.1.2.r182.e004158(182)

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* Xposed

**问题的具体描述/Detailed Description of the Bug**

*  自定义机型后，强制结束运行重启，更改状态，但是还是显示原来的机型

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by lliioollcn** [comment]
qq貌似做了一些限制，你需要先清除qq数据，然后在打开qq里面的模块设置修改机型，再打开更改机型的界面或许或生效
