### ISSUE TITLE
[Bug] 近期侧滑栏精简再次失效

### ISSUE THREAD

**Issue by CrepaRB** [cinit/QAuxiliary#704]
### Steps to reproduce/复现步骤

1. 设置侧滑栏精简
2. 重启QQ

### Expected behaviour/预期行为

被勾选的项目没有出现在侧滑栏

### Actual behaviour/实际行为

部分项目仍在存在于侧滑栏

### XPosed Framework you used/你使用的XP框架

太极·阴

### QQ(TIM)版本/QQ(TIM) Version

8.9.90

### Module Version/模块版本

1.4.6

### Version and Other Requirements/版本和其他要求

- [ ] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

[SimplifyQQSettingMe-1701576484690.txt](https://github.com/cinit/QAuxiliary/files/13538035/SimplifyQQSettingMe-1701576484690.txt)

**Comment by Emotion04** [comment]
新版本原因

**Comment by klxiaoniu** [comment]
更新到最新CI版本再试下
