### ISSUE TITLE
[功能请求] 增加表情保存功能

### ISSUE THREAD

**Issue by cirless** [cinit/QAuxiliary#709]
### QQ(TIM)版本/QQ(TIM) Version

8.9.88.13035

### 为什么你认为需要此功能

增加表情保存功能，也就是老版本qq的表情保存功能。表情保存和分享是qq的一个常用使用场景，在8.9.80版本之后表情不能保存给用户带来了很大的不便。

### 具体功能需要/Specific features require

对于表情消息，增加保存到相册功能

**Comment by klxiaoniu** [comment]
这个功能已经有了，你搜索一下
