### ISSUE TITLE
[功能请求] 

### ISSUE THREAD

**Issue by bty552** [cinit/QAuxiliary#71]
### QQ(TIM)版本/QQ(TIM) Version

8.8.50

### 为什么你认为需要此功能

增加趣味性，

### 联系到哪些已经存在的bug或者功能

小菜豆终极版有这个功能，感觉非常不错

### 具体功能需要/Specific features require

拍一拍连拍功能

**Comment by bty552** [comment]
大佬们可以增加拍一拍连拍功能吗

**Comment by cinit** [comment]
@bty552 QAuxv 尽量从简或实验，不考虑花里胡哨的功能
