### ISSUE TITLE
[功能请求] 希望功能【+1】增加选项

### ISSUE THREAD

**Issue by chadian20** [cinit/QAuxiliary#710]
### QQ(TIM)版本/QQ(TIM) Version

QQ8.9.50.10650

### 为什么你认为需要此功能

1、功能【+1】开启后每条消息都有+1，太多+1反而容易误触。
2、【按住气泡消息弹出菜单】选项的位置，经常来回变动，总是误触到【收藏】或者【保存】选项在下一栏，有时需要点【更多】，经过2次点击才能找到。
PS：【按住气泡消息弹出菜单】默认是：复制、转发、收藏等等
![QA-建议](https://github.com/cinit/QAuxiliary/assets/61662896/342dae46-9c01-4b86-97b3-c2683e74dd02)

### 具体功能需要/Specific features require

1、功能【+1】增加选项：按住气泡消息弹出菜单+1，增加【+1】在【按住气泡消息弹出菜单】最后一个位置。
2、自定义【按住气泡消息弹出菜单】选项，比如：自定义排序、关闭和开启选项。
3、如第1条功能实现，在第2条功能还需增加【+1】到自定义【按住气泡消息弹出菜单】选项里，比如：复制、转发、收藏、+1等等。
最后感谢各位大大，多亏大大们的技术和奉献精神，让QQ的使用更加便捷，再次非常感谢！

**Comment by chadian20** [comment]
补充：
1、找到第2条功能的位置了，名称是【精简聊天气泡长按菜单】。
2、版本：QQ8.9.50.10650，自定义菜单后没有生效。
3、【精简聊天气泡长按菜单】选项的【2X】是语音倍速X2？还是功能【+1】的效果，只是名字叫【2X】。
![QA-建议-2](https://github.com/cinit/QAuxiliary/assets/61662896/e572c710-ced9-47f4-8411-546b16a954dc)

**Comment by keta1** [comment]
![image](https://github.com/cinit/QAuxiliary/assets/41381927/c501e474-9893-4b42-9fdb-3a895befcf01)

**Comment by chadian20** [comment]
> ![image](https://private-user-images.githubusercontent.com/41381927/290213953-c501e474-9893-4b42-9fdb-3a895befcf01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NzY1NDMsIm5iZiI6MTcwMjQ3NjI0MywicGF0aCI6Ii80MTM4MTkyNy8yOTAyMTM5NTMtYzUwMWU0NzQtOTg5My00YjQyLTlmZGItM2E4OTViZWZjZjAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDE0MDQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3NWFhNmM0NGRiZmJjYjBkMzFkZjhkZGIwN2Q0YTI0MjRkYWRiODUyZmE2ODhkMjEyNjY1ZWI3YmM2OWM0MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tJmuToT3SLThzFFmn5msNS4W2DdXr53FawObcQyxiNM)

解决了！谢谢你的回复。
