### ISSUE TITLE
转发消息点击头像无法正常查看详细信息

### ISSUE THREAD

**Issue by xj233168** [cinit/QAuxiliary#712]
### Steps to reproduce/复现步骤

合并转发消息中点击头像会显示同一个账号不存在的不存在的详情

### Expected behaviour/预期行为

显示对应人的详细信息

### Actual behaviour/实际行为

实际上无论是点合并信息里的哪个头像都显示同一个无头像，无任何信息，只有一个“1094950020”（搜过了不存在）的
![Screenshot_20231213_152659_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/72736485/2af7ed55-15ce-4918-a95b-46a069f77dd3)
### 

### XPosed Framework you used/你使用的XP框架

lspatch 0.6（402）

### QQ(TIM)版本/QQ(TIM) Version

8.9.58

### Module Version/模块版本

1.4.6.r1824.90e09d4（也有退回到旧版本1.4.2～1.4.6的几个版本进行测试）

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.6.r1824.90e09d4
QQ8.9.58(4108)
PID: 1038, UID: 10326
cc.ioctl.hook.msg.MultiForwardAvatarHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0
![Screenshot_20231213_152943_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/72736485/f3353b66-2622-4443-a5f5-51386f045217)

**Comment by klxiaoniu** [comment]
请你仔细看一下点击头像弹出弹窗中的提示信息，谢谢

**Comment by xj233168** [comment]
好吧，以前确实是准确的，看来是有不可抗力因素了
