### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by mikuuuuuue** [cinit/QAuxiliary#714]
### Steps to reproduce/复现步骤

1.冷启动QQ
2.任意聊天内打开任意一张图片
3.界面卡顿图片不显示，3s左右闪退
4.大概闪退两次后恢复正常
5.打开图片卡顿3s左右之后正常打开

### Expected behaviour/预期行为

打开图片正常显示

### Actual behaviour/实际行为

同复现步骤描述

### XPosed Framework you used/你使用的XP框架

lsp1.9.1(6990)-Zygisk

### QQ(TIM)版本/QQ(TIM) Version

8.8.50.6735

### Module Version/模块版本

1.4.6.r1786.189196f(1786)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

[QrLoginAuthSecCheckMitigation-1702471765244.txt](https://github.com/cinit/QAuxiliary/files/13660833/QrLoginAuthSecCheckMitigation-1702471765244.txt)
[QrLoginAuthSecCheckMitigation-1702471765244.txt](https://github.com/cinit/QAuxiliary/files/13660843/QrLoginAuthSecCheckMitigation-1702471765244.txt)

**Comment by klxiaoniu** [comment]
你使用的QQ版本太过老旧，旧版本的QQ本身就存在打开图片卡顿的问题

**Comment by mikuuuuuue** [comment]
> 你使用的QQ版本太老了，旧版本的QQ本身就存在打开图片卡顿的问题

谢谢解答，关掉扫码风险登录五秒确认可以缓解，不会闪退了只是偶尔卡顿
