### ISSUE TITLE
[功能请求] 群文件复制支链功能

### ISSUE THREAD

**Issue by zzj2039** [cinit/QAuxiliary#721]
### QQ(TIM)版本/QQ(TIM) Version

V 8.9.93.13475

### 为什么你认为需要此功能

方便其他设备下载 例如linux

### 具体功能需要/Specific features require

复制支链

**Comment by keta1** [comment]
@zzj2039 什么是复制支链

**Comment by zzj2039** [comment]
> @zzj2039 什么是复制支链

抱歉，是直链，指可以直接下载文件的链接

**Comment by keta1** [comment]
@zzj2039

**Comment by keta1** [comment]
> > @zzj2039 什么是复制支链
> 
> 抱歉，是直链，指可以直接下载文件的链接

![IMG_20231215_123524_815.jpg](https://github.com/cinit/QAuxiliary/assets/41381927/a7abac55-2e03-421c-97c2-2e469b650fc6)
