### ISSUE TITLE
[Bug] 将群应用卡片（群文件)移动到正常位置失效

### ISSUE THREAD

**Issue by ztb1126** [cinit/QAuxiliary#730]
### Steps to reproduce/复现步骤

无

### Expected behaviour/预期行为

将群应用卡片移动到最上方

### Actual behaviour/实际行为

群应用卡片在下方，虽然这个功能失效，但是在故障排查里并没有报错
![Screenshot_2023-12-20-22-13-27-15_9d26c6446fd7bb8e41d99b6262b17def](https://github.com/cinit/QAuxiliary/assets/123040986/b37edbd2-08eb-4f16-a55f-e5bea6427092)
![Screenshot_2023-12-20-22-13-11-97_9d26c6446fd7bb8e41d99b6262b17def](https://github.com/cinit/QAuxiliary/assets/123040986/ed7ef553-1024-4229-b613-1fc78257d32e)
![Screenshot_2023-12-20-22-13-06-03_9d26c6446fd7bb8e41d99b6262b17def](https://github.com/cinit/QAuxiliary/assets/123040986/c1b66e31-ae4b-40d4-8dbb-61e4f2662a30)

### XPosed Framework you used/你使用的XP框架

lspatch

### QQ(TIM)版本/QQ(TIM) Version

9.0.0.14110(5282)

### Module Version/模块版本

1.4.6.r1838.cdd250d(1838)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.6.r1838.cdd250d
QQ9.0.0(5282)
PID: 10314, UID: 10247
top.linl.hook.SortTroopSettingAppListView
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by klxiaoniu** [comment]
Fixed
