### ISSUE TITLE
[Bug] 群帖子禁用左滑失效

### ISSUE THREAD

**Issue by 233dada** [cinit/QAuxiliary#735]
### Steps to reproduce/复现步骤

进入群聊并左滑

### Expected behaviour/预期行为

无

### Actual behaviour/实际行为

进入群帖子，实际上因为关闭了群帖子，所以会黑屏然后回到群聊界面

### XPosed Framework you used/你使用的XP框架

LSP:1.9.2 (7024)

### QQ(TIM)版本/QQ(TIM) Version

QQ9.0.0(5282)

### Module Version/模块版本

1.4.6.r1834.217ee53

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.6.r1834.217ee53
QQ9.0.0(5282)
PID: 15905, UID: 10252
cc.ioctl.hook.troop.DisableFlingToTroopGuild
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by klxiaoniu** [comment]
没看明白你的表述，能说清楚一点么？

**Comment by 233dada** [comment]
> 没看明白你的表述，能说清楚一点么？

打错字了emm。我传个视频

**Comment by 233dada** [comment]
> 没看明白你的表述，能说清楚一点么？


https://github.com/cinit/QAuxiliary/assets/79577850/5936e940-fec0-4db4-8e2c-d5a788ea8a93

**Comment by klxiaoniu** [comment]
这是禁用右滑群应用功能，尚未适配 qqnt。前面已有 issue 了

**Comment by 233dada** [comment]
> 这是禁用右滑群应用功能，尚未适配 qqnt。前面已有 issue 了

好的
