### ISSUE TITLE
[Bug] "显示历史好友入口"功能不生效

### ISSUE THREAD

**Issue by GetStart13** [cinit/QAuxiliary#738]
### Steps to reproduce/复现步骤

功能位置：好友和资料卡/显示历史好友入口

### Expected behaviour/预期行为

在"联系人"的"分组" tab的底部，应该显示"历史好友"做为入口

### Actual behaviour/实际行为

底部栏的"联系人"的"分组"tab下没有"历史好友"入口，日志显示历史好友功能未启用

### XPosed Framework you used/你使用的XP框架

太极

### QQ(TIM)版本/QQ(TIM) Version

8.9.83

### Module Version/模块版本

1.4.6.r1786

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

历史好友：
1.4.6.r1786.189196f
QQ8.9.83(4680)
PID: 17570, UID: 10461
cc.ioctl.hook.friend.FriendDeletionNotification$ExFriendListEntry

显示历史好友入口：
1.4.6.r1786.189196f
QQ8.9.83(4680)
PID: 17570, UID: 10461
cc.ioctl.hook.friend.ShowDeletedFriendListEntry

**Comment by cinit** [comment]
@GetStart13 太极的老问题了，如果你从qa的"历史好友"能点进去就可以不用去管他。
