### ISSUE TITLE
[Bug] qq9中消息显示id和时间无法生效

### ISSUE THREAD

**Issue by yyk725** [cinit/QAuxiliary#740]
### Steps to reproduce/复现步骤

打开该功能

### Expected behaviour/预期行为

按照模板在每条消息下显示id和时间

### Actual behaviour/实际行为

什么都没显示，跟没打开一样

### XPosed Framework you used/你使用的XP框架

lsposed 1.9.2 (7024)

### QQ(TIM)版本/QQ(TIM) Version

9.0.0.14110 (5282)

### Module Version/模块版本

1.4.6.r1840.76b8265

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.6.r1840.76b8265
QQ9.0.0(5282)
PID: 13866, UID: 10293
me.ketal.hook.ChatItemShowQQUin
isInitialized: false
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by duzhaokun123** [comment]
fix https://github.com/cinit/QAuxiliary/commit/e5e5e4c5c1f9a2b6a7358f34671f0fecebcdf720
