### ISSUE TITLE
[Bug] 最新版QQ，开启“隐藏下拉小程序”后，下滑刷新动画不会消失。

### ISSUE THREAD

**Issue by ayanami-desu** [cinit/QAuxiliary#741]
### Steps to reproduce/复现步骤

下拉刷新消息

### Expected behaviour/预期行为

动画应该消失

### Actual behaviour/实际行为

![image](https://github.com/cinit/QAuxiliary/assets/105108444/681fa4e6-13ec-4106-817b-c131b2fc4552)

### XPosed Framework you used/你使用的XP框架

LSposed

### QQ(TIM)版本/QQ(TIM) Version

9.0.0.14110(5258)

### Module Version/模块版本

1.4.6.r1840.76b8265(1840)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.6.r1840.76b8265
QQ9.0.0(5282)
PID: 31516, UID: 10648
cc.ioctl.hook.ui.main.HideMiniAppPullEntry
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by EmptyDreams** [comment]
同时还有一个问题是下拉到底仍然可以进到选择小程序的那个页面，不过是全白的

**Comment by klxiaoniu** [comment]
fixed
