### ISSUE TITLE
如果内置模块设置里无qa选项，qa软件本体无法拉起qq[Bug] 

### ISSUE THREAD

**Issue by yingsha233** [cinit/QAuxiliary#743]
### Steps to reproduce/复现步骤

12月30日
qa1.4.6
qq9
lsp装载

### Expected behaviour/预期行为

有qa

### Actual behaviour/实际行为

没有

### XPosed Framework you used/你使用的XP框架

1.9.2(7024)

### QQ(TIM)版本/QQ(TIM) Version

9.0.8

### Module Version/模块版本

1.4.6

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

日志选项无法打开，安全模式也没用

**Comment by klxiaoniu** [comment]
QA具体版本号呢？是最新的CI？

**Comment by klxiaoniu** [comment]
https://github.com/cinit/QAuxiliary/actions/runs/7357091698

**Comment by yingsha233** [comment]
> QA具体版本号呢？是最新的CI？

1.4.6.r1786.189196f(1786)
加个qq聊吧，github有点不方便
3496189218

**Comment by klxiaoniu** [comment]
请更新CI，该问题早已解决。https://t.me/QAuxiliary_CI
