### ISSUE TITLE
[功能请求] 好友上线提醒

### ISSUE THREAD

**Issue by Cxy-2008** [cinit/QAuxiliary#745]
### QQ(TIM)版本/QQ(TIM) Version

9.0.8

### 为什么你认为需要此功能

可以在好友上线的时候提醒（特别是女朋友上线）

### 具体功能需要/Specific features require

好友上线提醒

**Comment by cinit** [comment]
@Cxy-2008 今夕是何年

**Comment by Chenyu550** [comment]
不会有人每次都要退出登录再关QQ吧？
