### ISSUE TITLE
[功能请求] 请求加入元梦之星广告屏蔽

### ISSUE THREAD

**Issue by ActualMarmot663** [cinit/QAuxiliary#746]
### QQ(TIM)版本/QQ(TIM) Version

9.0.8.14755

### 为什么你认为需要此功能

元梦之星 启动（爬）

### 具体功能需要/Specific features require

屏蔽首页元梦之星半屏广告

**Comment by fgr178707** [comment]
> ### QQ(TIM)版本/QQ(TIM) Version
> 9.0.8.14755
> 
> ### 为什么你认为需要此功能
> 元梦之星 启动（爬）
> 
> ### 联系到哪些已经存在的bug或者功能
> _No response_
> 
> ### 具体功能需要/Specific features require
> 屏蔽首页元梦之星半屏广告

你要不要看看这个项目 https://github.com/gkd-kit/gkd

**Comment by LLKawi** [comment]
> > ### QQ(TIM)版本/QQ(TIM) Version
> > 9.0.8.14755
> > ### 为什么你认为需要此功能
> > 元梦之星 启动（爬）
> > ### 联系到哪些已经存在的bug或者功能
> > _No response_
> > ### 具体功能需要/Specific features require
> > 屏蔽首页元梦之星半屏广告
> 
> 你要不要看看这个项目 https://github.com/gkd-kit/gkd

好像广告我这里已经不再推了

**Comment by fgr178707** [comment]
> > > ### QQ(TIM)版本/QQ(TIM) Version
> > > 9.0.8.14755
> > > ### 为什么你认为需要此功能
> > > 元梦之星 启动（爬）
> > > ### 联系到哪些已经存在的bug或者功能
> > > _No response_
> > > ### 具体功能需要/Specific features require
> > > 屏蔽首页元梦之星半屏广告
> > 
> > 
> > 你要不要看看这个项目 https://github.com/gkd-kit/gkd
> 
> 好像广告我这里已经不再推了

不再推了?
