### ISSUE TITLE
[Bug] 新版 qq 中 QA 选项消失，功能失效

### ISSUE THREAD

**Issue by EmptyDreams** [cinit/QAuxiliary#748]
### Steps to reproduce/复现步骤

1. 安装新版 qq(9.0.8.14755)
2. 使用太极启用 qa

### Expected behaviour/预期行为

qa 应该正常生效

### Actual behaviour/实际行为

qq 设置页面没有 qa 选项且功能未生效，启用安全模式后也无法进入 qa 的故障排查，点击后要么弹出 qq 界面后瞬间回到 qa 界面，要么点击没有任何作用。

### XPosed Framework you used/你使用的XP框架

太极阴

### QQ(TIM)版本/QQ(TIM) Version

9.0.8.14755

### Module Version/模块版本

1.4.6.r1786.189196f

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

[bugreport-MXW-AN00-HONORMXW-AN00-2023-12-31-18-59-18.zip](https://github.com/cinit/QAuxiliary/files/13800918/bugreport-MXW-AN00-HONORMXW-AN00-2023-12-31-18-59-18.zip)

**Comment by klxiaoniu** [comment]
@EmptyDreams 更新CI版本，已修复，请勿提重复issue

**Comment by EmptyDreams** [comment]
> @EmptyDreams 更新CI版本，已修复，请勿提重复issue

好像只有 tg 里面才能下 CI 版本，不能在 gh release 也发布吗？🤔

**Comment by qwq233** [comment]
https://github.com/cinit/QAuxiliary/actions

**Comment by duzhaokun123** [comment]
@EmptyDreams 不能 因为太多了
