### ISSUE TITLE
[Bug]无法登陆问题

### ISSUE THREAD

**Issue by azuki768** [cinit/QAuxiliary#750]
### Steps to reproduce/复现步骤

使用太极重装QQ

### Expected behaviour/预期行为

可以登录

### Actual behaviour/实际行为

无法登陆
跳出 con.tencent.mobileqq.msf.service.MsfService timeout

### XPosed Framework you used/你使用的XP框架

xiaomi

### QQ(TIM)版本/QQ(TIM) Version

QQ9

### Module Version/模块版本

1.4.6

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

meiyou

**Comment by keta1** [comment]
听上去可能是太极导致的,尝试禁用模块后登陆.
