### ISSUE TITLE
[Bug] 1.4.6版本中，“以图片方式打开闪照”功能无法使用，故障排查中的“以图片方式打开闪照”功能未见明显异常

### ISSUE THREAD

**Issue by wzkbuyan** [cinit/QAuxiliary#751]
### Steps to reproduce/复现步骤

闪图无法以图片方式打开和保存，故障排查中的“以图片方式打开闪图”功能未见明显异常

### Expected behaviour/预期行为

闪图无法以图片方式打开和保存，故障排查中的“以图片方式打开闪图”功能未见明显异常

### Actual behaviour/实际行为

闪图无法以图片方式打开和保存，

### XPosed Framework you used/你使用的XP框架

太极阴

### QQ(TIM)版本/QQ(TIM) Version

QQ正式版本8.9.58.11175

### Module Version/模块版本

1.4.6

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

故障排查中的“以图片方式打开闪图”功能未见明显异常

**Comment by Groocy-X** [comment]
一样的问题 这个能修不qwq

**Comment by Talloran3999** [comment]
模块 1.4.8 QQ 9.0.15.14970
也有同样的问题

**Comment by XwumingX** [comment]
模块1.4.8r1905.3aed1c5 QQ9.0.17.15190问题依旧

**Comment by caikun233** [comment]
> 模块1.4.8r1905.3aed1c5 QQ9.0.17.15190问题依旧

同样的版本我也无法使用，我是Magisk26.1&Zygisk - LSPosed1.9.2

**Comment by klxiaoniu** [comment]
更新，已修复

**Comment by Misaka-Mikoto-Tech** [comment]
> 更新，已修复

QQ8.9.68, QA1.4.8.r1940, 太极阴14.0.6，无效
