### ISSUE TITLE
你好，我想咨询一下。是如何做到把模块的类合并入宿主里的是否可以给个示例

### ISSUE THREAD

**Issue by Xiaolangs** [cinit/QAuxiliary#752]
### QQ(TIM)版本/QQ(TIM) Version

1

### 为什么你认为需要此功能

1

### 具体功能需要/Specific features require

你好，我想咨询一下。是如何做到把模块的类合并入宿主里的是否可以给个示例

**Comment by klxiaoniu** [comment]
没明白你的意思，请详细讲讲

**Comment by keta1** [comment]
https://github.com/cinit/QAuxiliary/blob/main/app/src/main/java/io/github/qauxv/startup/StartupHook.java#L86
