### ISSUE TITLE
[功能请求]长按菜单复读+1顺序

### ISSUE THREAD

**Issue by jiuban590** [cinit/QAuxiliary#758]
### QQ(TIM)版本/QQ(TIM) Version

9.0.8

### 为什么你认为需要此功能

现在+1在长按菜单最前面容易误触，建议放到长按菜单的最后边
![Screenshot_2024_0110_004226](https://github.com/cinit/QAuxiliary/assets/98690669/58f4b008-c774-47dd-91c5-2923b52449ea)

### 具体功能需要/Specific features require

把长按菜单的+1由第一位置放到最后位置。麻烦开发者有空的时候考虑一下建议，谢谢。

**Comment by klxiaoniu** [comment]
不考虑，你适应一下
