### ISSUE TITLE
[功能请求] 能否加入像QX模块一样的自动回复功能

### ISSUE THREAD

**Issue by WuYang9** [cinit/QAuxiliary#76]
### QQ(TIM)版本/QQ(TIM) Version

TIM 3.4.6

### 为什么你认为需要此功能

之前在QQ利用QX模块的关键词回复来回复相关消息，但是介于QQ过于臃肿所以转用了TIM，但是QX模块目前还没适配TIM最新版，所以请问能否加入这个功能。

### 具体功能需要/Specific features require

1.普通自动回复
2.检测到关键词自动回复(可以文字回复也可以图片回复)

**Comment by WuYang9** [comment]
> 我不知道什么是最新版捏，具体版本号pls

TIM 3.4.6

**Comment by cinit** [comment]
建议催 QX 更新, 不想做任何有关自动发消息或者批量发消息的功能.

**Comment by WuYang9** [comment]
> 建议催 QX 更新, 不想做任何有关自动发消息或者批量发消息的功能.

妥
