### ISSUE TITLE
QQ小世界无法使用百分百闪退

### ISSUE THREAD

**Issue by m2905076048** [cinit/QAuxiliary#760]
### Steps to reproduce/复现步骤

安装QQ  qa以后两三天内QQ小世界所有功能是正常使用的。但是过了两三天之后，一打开qq小世界就闪退。

### Expected behaviour/预期行为

但是他似乎只有首页就是点开那个小世界刷视频的那个地方页面会卡掉，导致QQ重启。在他快要崩溃但没有完全崩溃之前，点到私信那边就会正常显示。可能是只有那一个页面会闪退。

### Actual behaviour/实际行为

具体表现为进入QQ小世界之后，可能会出现有画面停滞，但是没有声音。或者说只有声音，但是画面是黑屏的。然后他就会卡在那儿闪退。

### XPosed Framework you used/你使用的XP框架

LSPosed.1.9.2.(7024）zygisk  API 版本 100  Xposed API 调用保护 已启用  Dex 优化器包装 支持  框架版本 1.9.2 (7024)  管理器包名 com.android.shell  系统版本 12 (API 31)  设备 Xiaomi Redmi K20 Pro   系统架构 arm64-v8a

### QQ(TIM)版本/QQ(TIM) Version

8.9.85.12820(4766)

### Module Version/模块版本

1.4.6.r1786.189196f(1786)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

功能状态里没有显示异常的。

**Comment by klxiaoniu** [comment]
@m2905076048 崩溃日志提供一下

**Comment by m2905076048** [comment]
@klxiaoniu 日志是指这里吗
![Screenshot_2024-01-13-17-50-21-452_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/47288778/da2a2cad-f9d6-4c74-9c7f-af43d4a2a3ab)

**Comment by klxiaoniu** [comment]
@m2905076048 QQ崩溃的日志

**Comment by m2905076048** [comment]
在哪里找.

**Comment by m2905076048** [comment]
@klxiaoniu 在哪里找崩溃日志啊，我连着闪退了七八次了，手机也不弹这个应用异常

**Comment by m2905076048** [comment]
@klxiaoniu 学会了，抓到了（如果没学错的话）
[crash00.log](https://github.com/cinit/QAuxiliary/files/13927733/crash00.log)

**Comment by klxiaoniu** [comment]
确定是模块问题吗

**Comment by m2905076048** [comment]
@klxiaoniu 重新安装QQ那个版本之后，它是可以正常使用的，并且用手机自带的应用分身也是可以正常使用的。然后我再去启用模块，它也还是能正常使用的，但是过个三四天之后他就开始闪退，并且连带着系统自带的应用分身也开始闪退。这个是在主QQ闪退之后我才克隆的分身，所以分身也闪退，在主QQ没有闪退的时候，克隆分身，然后等主QQ闪退，分身是否闪退我还不知道，没有试过。分身没有启用模块

最后就只得出如果把这个QQ卸载重装之后，不启用模块儿的话，他就不会闪退。但是如果重装后启用模块，并且它开始闪退之后，哪怕把模块删了，清除数据了，不启用了，它该闪退还是闪退，

他这个闪退他不是整个闪退，就是他QQ里面有那个QQ小世界，这一个界面有，只有播放视频的那个界面闪退，带着整个QQ闪退。一加载那个播放页面就开始闪退，在它正在加载播放页面要闪退之前，我跳转到小世界的其他页面之后就不会崩，但只要一返回到那个播放页面就闪退。

我用之前的老版本的时候，点开长图和视频，空间里的，或者是那个以图片形式打开表情包那个功能开启之后群里点开表情包。点开我就闪退，更新QA之后就没有这个问题了。虽然事情不是一个事情，但是感觉和这个事情好像

**Comment by m2905076048** [comment]
@klxiaoniu 
[LSPosed_2024-01-14T10_40_19.179.zip](https://github.com/cinit/QAuxiliary/files/13930158/LSPosed_2024-01-14T10_40_19.179.zip)
复现操作后lsp的日志
