### ISSUE TITLE
[Bug] 净化-杂项-精简底栏-频道 体验模式 失效

### ISSUE THREAD

**Issue by Pil0tXia** [cinit/QAuxiliary#764]
### Steps to reproduce/复现步骤

没有特别操作，15日、16日突然这样的

### Expected behaviour/预期行为

能够净化“频道”底栏

### Actual behaviour/实际行为

![Screenshot_2024-01-16-22-27-32-115_com tencent mo](https://github.com/cinit/QAuxiliary/assets/41445332/0a9bec96-9831-43a6-9d86-a56533e80bf8)
![Screenshot_2024-01-16-22-27-47-813_com tencent mo](https://github.com/cinit/QAuxiliary/assets/41445332/8a5a35a2-8872-4f60-b871-074824b2c7d8)

### XPosed Framework you used/你使用的XP框架

jdk11 lspatch 0.5.1

### QQ(TIM)版本/QQ(TIM) Version

QQ 8.9.90-4938

### Module Version/模块版本

r1845

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

```
1.4.6.r1845.3cdbcea
QQ8.9.90(4938)
PID: 19596, UID: 10262
xyz.nextalone.hook.SimplifyBottomTab
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0
```

**Comment by klxiaoniu** [comment]
QQ自带开关，在设置-辅助功能里
