### ISSUE TITLE
[功能请求] 显示最近更新/修复的功能

### ISSUE THREAD

**Issue by ztb1126** [cinit/QAuxiliary#769]
### QQ(TIM)版本/QQ(TIM) Version

QQ9.0.0

### 为什么你认为需要此功能

在tg中推送的功能更新或者修复看不懂[挠头]

### 具体功能需要/Specific features require

在其他中增加最近更新功能，点进去后显示最近更新功能

**Comment by klxiaoniu** [comment]
commit detail里可以看到哪些代码做了修改，发布推荐的CI版本时也会大致附上和上次发布之间所做的更改
