### ISSUE TITLE
[功能请求] TIM深色模式/夜间模式

### ISSUE THREAD

**Issue by AneryCoft** [cinit/QAuxiliary#778]
### QQ(TIM)版本/QQ(TIM) Version

TIM V3.5.1

### 为什么你认为需要此功能

夜间模式可以让屏幕不再刺眼
并且几乎所有的软件都会随着系统的深色模式而改变主题，这时候突然切到TIM会凸显的更加刺眼

当使用MIUI时TIM的夜间模式将跟随系统开启，**TIM的夜间模式不是没有，而是跟随系统，没有做独立的开关**
但是当使用原生的Android14时，API似乎发生了改变，TIM不再能识别系统的深色模式

### 具体功能需要/Specific features require

TIM夜间模式深色模式

**Comment by cinit** [comment]
@AneryCoft 夜间模式是个QQ主题，用模块很难完美实现

**Comment by cinit** [comment]
你说的是你系统的第三方暗色模式吧

**Comment by MoonLeeeaf** [comment]
> 你说的是你系统的第三方暗色模式吧，那不是 TIM 的功能

很抱歉在这插句话

我也遇到了一样的问题，因为不应该再开一个功能请求，所以我在这简单描述下

TIM 的夜间模式很谜

我之前在 1. Huawei MAR-AL00 调出来了，而且会跟随系统，而剩下的， 2. Redmi Note 12 和 3. Huawei HRY-AL00 都是没有深色的。甚至我把 1 的安装包给 2、3 安装，它们都不会深色模式

测试的机子不够多，我也感觉是系统的原因，可是 1 和 3 都已经是 Homo3.0 了

总之十分奇怪，有些机型可以自动夜间模式，有些机型没有，锁定日间模式

也许可以找一个能夜间模式的手机抓log看看？如果没有精力，也没关系，我也能理解各位开发者的不易

**Comment by MoonLeeeaf** [comment]
不过要在这说明一下，我除了 QA、QQ瘦身和TSBattery 之外没有加载其它模块，而且系统均开启了深色模式

下面是两台机型的截图
1. 红米Note12：
![Screenshot_2024-02-13-18-02-47-465_com android settings-edit](https://github.com/cinit/QAuxiliary/assets/150461955/6ef65703-3757-48a5-a0ac-7c2960a0929a)

![Screenshot_2024-02-13-18-02-10-049_com tencent tim](https://github.com/cinit/QAuxiliary/assets/150461955/97dd58d4-57f4-4ba2-ac57-aabf18ab4467)

![Screenshot_2024-02-13-18-01-59-358_com tencent tim](https://github.com/cinit/QAuxiliary/assets/150461955/27bacb7a-a276-4c76-9c84-c74e31d4aca8)

2. 华为Nova4e
![Screenshot_2024-02-13-18-24-41-973_com tencent tim-edit](https://github.com/cinit/QAuxiliary/assets/150461955/c9423684-f176-4eac-99ad-cba078759a8e)
![Screenshot_2024-02-13-18-25-21-566_com tencent tim](https://github.com/cinit/QAuxiliary/assets/150461955/bd567012-d68f-4669-b0d4-e09e25aaa76a)
![Screenshot_2024-02-13-18-25-25-019_com tencent tim](https://github.com/cinit/QAuxiliary/assets/150461955/d22e1a6d-a84c-4919-ad47-1d5fd952d59a)

总之我认为这个功能有可能是 TIM 自身检测深色模式不当导致的，有兴趣可以研究下

**Comment by ZhengXieGang** [comment]
可以参考一下darQ模块 强制开启软件深色模式
