### ISSUE TITLE
9.0.15闪照失效

### ISSUE THREAD

**Issue by NatsumiXD** [cinit/QAuxiliary#779]
### Steps to reproduce/复现步骤

用9.0.15.14820闪照无法以照片打开

### Expected behaviour/预期行为

以照片形式打开

### Actual behaviour/实际行为

原版行为

### XPosed Framework you used/你使用的XP框架

lsposed

### QQ(TIM)版本/QQ(TIM) Version

9.0.15.14820

### Module Version/模块版本

版本 1.4.6.r1880.08ca302

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

no

**Comment by Groocy-X** [comment]
QQ9.0.17.15185也有同样的问题 QA版本1.4.7.r1883.b3d4b79

**Comment by CutePaper1** [comment]
最新ci版本1.4.7.r1883.b3d4b79(1883)在QQ版本9.0.15.14970(5626)下也失效了
![image](https://github.com/cinit/QAuxiliary/assets/139243174/144c70e5-4335-41a8-953e-3cdcafbb22d9)

**Comment by hongjr03** [comment]
一样的问题

**Comment by klxiaoniu** [comment]
#751
