### ISSUE TITLE
[Bug] 强制使用默认字体失效

### ISSUE THREAD

**Issue by yumaobi114514** [cinit/QAuxiliary#786]
### Steps to reproduce/复现步骤

开启功能强制使用默认字体

### Expected behaviour/预期行为

使用系统自默认字体

### Actual behaviour/实际行为

并未使用系统默认字体，使用QQ个性字体

### XPosed Framework you used/你使用的XP框架

Lsposed1.9.2（7024）

### QQ(TIM)版本/QQ(TIM) Version

QQ8.9.28

### Module Version/模块版本

1.4.7.r1883.b3d4b79 (1883)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

![IMG_20240202_092826](https://github.com/cinit/QAuxiliary/assets/129368630/8058fa16-aa2b-4013-ba6c-8529c7b28d81)
[强制使用默认字体异常.txt](https://github.com/cinit/QAuxiliary/files/14132972/default.txt)

**Comment by klxiaoniu** [comment]
https://github.com/cinit/QAuxiliary/commit/6494c23d23f331d2aa684b62ee9aa27773d39429
