### ISSUE TITLE
[Bug] 辅助功能/聊天和消息/消息/以图片方式打开闪照 无法正常使用

### ISSUE THREAD

**Issue by CutePaper1** [cinit/QAuxiliary#787]
### Steps to reproduce/复现步骤

对方或者自己发送闪照

### Expected behaviour/预期行为

预期将以图片形式展现闪照，左下角显示闪照两字

### Actual behaviour/实际行为

QQ原版闪照

### XPosed Framework you used/你使用的XP框架

LSPosed

### QQ(TIM)版本/QQ(TIM) Version

9.0.15.14970(5626)

### Module Version/模块版本

1.4.7.r1883.b3d4b79(1883)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.7.r1883.b3d4b79
QQ9.0.15(5626)
PID: 19975, UID: 10347
cc.ioctl.hook.msg.FlashPicHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by klxiaoniu** [comment]
重复issue
