### ISSUE TITLE
[Bug] 防撤回后撤回人昵称乱码

### ISSUE THREAD

**Issue by HengeZi** [cinit/QAuxiliary#790]
### Steps to reproduce/复现步骤

![图片2](https://github.com/cinit/QAuxiliary/assets/151383237/a95e6386-68b9-4cb2-8d4a-41041a98dec7)
![图片1](https://github.com/cinit/QAuxiliary/assets/151383237/4c66f2a6-7cea-46c9-b71b-3e64835b8814)

### Expected behaviour/预期行为

撤回人昵称显示正常

### Actual behaviour/实际行为

昵称乱码

### XPosed Framework you used/你使用的XP框架

1.9.2（7024）

### QQ(TIM)版本/QQ(TIM) Version

9.0.17.15185(5712)

### Module Version/模块版本

1.4.7.r1883.b3d4b79(1883)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.7.r1883.b3d4b79
QQ9.0.17(5712)
PID: 10126, UID: 10357
cc.ioctl.hook.msg.RevokeMsgHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by cinit** [comment]
@HengeZi 系正常情况
