### ISSUE TITLE
[功能请求] 强制旧版频道

### ISSUE THREAD

**Issue by Xiunii** [cinit/QAuxiliary#794]
### QQ(TIM)版本/QQ(TIM) Version

8.0.15往上

### 为什么你认为需要此功能

QQ方面更新了频道页面，不能说难用，只能说一坨大便

### 具体功能需要/Specific features require

将新版界面替换回旧版本

**Comment by klxiaoniu** [comment]
Lcom/tencent/mobileqq/guild/discover/GuildDiscoverABTestHelper;->w()I

以9.0.17_HB为例，该方法返回1即恢复为旧版。
代码懒得写，意义不大，有兴趣的可以pr

**Comment by qimlisky** [comment]
有其他模块可以代替

**Comment by HdShare** [comment]
尝试最新CI版本
