### ISSUE TITLE
[Bug] 9.0.15 以图片方式打开闪照 失效

### ISSUE THREAD

**Issue by ours1505** [cinit/QAuxiliary#795]
### Steps to reproduce/复现步骤

1.接受到闪照
2.打开

### Expected behaviour/预期行为

以图片方式打开

### Actual behaviour/实际行为

出现闪电图标，马赛克，x秒后，图片销毁

### XPosed Framework you used/你使用的XP框架

Lsposed

### QQ(TIM)版本/QQ(TIM) Version

9.0.15

### Module Version/模块版本

1.4.7.r1883.b3d4b79(1883)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

功能异常列表中无此功能

**Comment by klxiaoniu** [comment]
重复
