### ISSUE TITLE
[Bug]'聊天与消息'-"显示消息 ID 和时间"无法显示

### ISSUE THREAD

**Issue by alpha-Foll** [cinit/QAuxiliary#798]
### Steps to reproduce/复现步骤

激活 Qauxiliary
打开'显示消息 ID 和时间'

### Expected behaviour/预期行为

聊天界面消息显示详细信息

### Actual behaviour/实际行为

无报错，但不生效

### XPosed Framework you used/你使用的XP框架

LSPatch

### QQ(TIM)版本/QQ(TIM) Version

9.0.0.14110

### Module Version/模块版本

1.4.7.r1883

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

日志文件显示正常
希望适配 9.0.0

**Comment by klxiaoniu** [comment]
重复 #740
