### ISSUE TITLE
[Bug] 聊天文本框上的表情无法发出

### ISSUE THREAD

**Issue by yokinanya** [cinit/QAuxiliary#80]
### Steps to reproduce/复现步骤

1. 在聊天文本框中输入文字
2. 聊天文本框上方弹出对应的收藏表情（需开启QQ设置中的 `辅助功能-表情推荐`，并在 `聊天窗口的表情管理` 中对表情进行备注）
3. 点击对应的收藏表情

### Expected behaviour/预期行为

文本框中文本消失，并发出对应表情

### Actual behaviour/实际行为

文本框中文字消失，但表情并未发送出去

### XPosed Framework you used/你使用的XP框架

Lsposed 1.8.3(6552) Zygisk

### QQ(TIM)版本/QQ(TIM) Version

8.8.88.7830(2770)

### Module Version/模块版本

1.2.5.r551.1acbd2e(551)

### Version requirement/版本要求

- [x] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2022-05-26T19_50_22.509.zip](https://github.com/cinit/QAuxiliary/files/8778710/LSPosed_2022-05-26T19_50_22.509.zip)

**Comment by Xk1001** [comment]
我也刚想反馈这个来着

**Comment by keta1** [comment]
使用 回复带图 会导致文本框上方的表情推荐点击无效，如需使用 表情推荐 功能，请关闭回复带图
