### ISSUE TITLE
[Bug] 无法修改“下载文件重定向”设置

### ISSUE THREAD

**Issue by swim233** [cinit/QAuxiliary#800]
### Steps to reproduce/复现步骤

1、将Qauxiliary升级至版本：1.4.7.r1884.1a 4cfb1
2、将系统从MIUI12.5增强版（Android11）升级至MIUI14（Android13）

### Expected behaviour/预期行为

能够修改选项设置

### Actual behaviour/实际行为

无法修改选项设置

https://github.com/cinit/QAuxiliary/assets/97345261/525ae560-7100-43f6-9a40-2ddacc918e66
![Screenshot_2024-02-03-15-00-37-433_rikka appops](https://github.com/cinit/QAuxiliary/assets/97345261/363f8cfc-6860-4db9-bdb4-013332d18ab0)

### XPosed Framework you used/你使用的XP框架

lspatch version:v0.6

### QQ(TIM)版本/QQ(TIM) Version

8.9.93与9.0.17

### Module Version/模块版本

版本：1.4.7.r1884.1a 4cfb1

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

[FileRecvRedirect-1706956025687.txt](https://github.com/cinit/QAuxiliary/files/14183692/FileRecvRedirect-1706956025687.txt)

**Comment by swim233** [comment]
已将模块版本升级为1.4.7.r1893.efdea4e，仍无效

**Comment by swim233** [comment]
已将Qauxiliary版本升级为1.4.7.r1893.efdea4e 仍无效

**Comment by klxiaoniu** [comment]
选择公共目录

**Comment by swim233** [comment]
> 选择公共目录

设置无法被保存 一样提示目录无效

**Comment by duzhaokun123** [comment]
选择存在的路径 如果可能 使用选择器

**Comment by swim233** [comment]
> 选择存在的路径 如果可能 使用选择器

试过了，视频演示可能不完整 选择存在的目录也提示目录无效，选项也无法被关闭

**Comment by duzhaokun123** [comment]
那就只能因为选择的路径不可写了

**Comment by swim233** [comment]
> 那就只能因为选择的路径不可写了

无论选择何路径都提示无效
并且我主要是想关掉这个功能，也不行

**Comment by qwq233** [comment]
你有用什么模块
magisk/kernelsu的模块列表截图一遍

**Comment by swim233** [comment]
> 你有用什么模块
> magisk/kernelsu的模块列表截图一遍

我用的lsp打包 只有Qauxiliary和tsbattery
![IMG_20240213_211932.jpg](https://github.com/cinit/QAuxiliary/assets/97345261/9582ee13-b0ca-425e-bed2-33b7c70e6e3d)
