### ISSUE TITLE
[Bug] 自定义启动图片功能无效

### ISSUE THREAD

**Issue by EmptyDreams** [cinit/QAuxiliary#803]
### Steps to reproduce/复现步骤

1. 在设置中设置启动图并保存
2. 重启 QQ

![Screenshot_20240207_230010_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/44894906/986f3d7d-ed1a-46e5-a52f-675294719ba8)

### Expected behaviour/预期行为

启动 qq 时的图像应该被替换为自己设置的图像。

### Actual behaviour/实际行为

仍然是 qq 默认图片。

### XPosed Framework you used/你使用的XP框架

应用转生

### QQ(TIM)版本/QQ(TIM) Version

9.0.8.14755(5540)

### Module Version/模块版本

1.4.7.r1897.4102c4a(1897)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.7.r1897.4102c4a
QQ9.0.8(5540)
PID: 12009, UID: 10329
cc.ioctl.hook.misc.CustomSplash
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by ScSofts** [comment]
lsposed同

**Comment by duzhaokun123** [comment]
现在 qq 启动图拆成 企鹅 和 logo 了 不好改了
