### ISSUE TITLE
[Bug] 消息ID和时间与“群文件”标识重叠

### ISSUE THREAD

**Issue by BinTianqi** [cinit/QAuxiliary#804]
### Steps to reproduce/复现步骤

在群聊中看到别人发的群文件

### Expected behaviour/预期行为

消息ID和时间应该显示在“群文件”标识下方，或者在一行内显示

### Actual behaviour/实际行为

消息ID和时间与“群文件”标识重叠
![Screenshot_20240208-000651_TIM_1_1](https://github.com/cinit/QAuxiliary/assets/146811279/ed2c1228-53ac-4205-8039-534f6fa5026d)

自己发的群文件没有问题

### XPosed Framework you used/你使用的XP框架

LSPosed v1.9.2 (7024)

### QQ(TIM)版本/QQ(TIM) Version

TIM v3.5.1

### Module Version/模块版本

r1897

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

功能没有异常

**Comment by klxiaoniu** [comment]
此为正常表现
