### ISSUE TITLE
适配 Android7.1.1

### ISSUE THREAD

**Issue by Delta-cloudy** [cinit/QAuxiliary#805]
### QQ(TIM)版本/QQ(TIM) Version

8.9.73

### 为什么你认为需要此功能

Android7.1.1 打不开 qa1.4.1.r 及以上版本

### 联系到哪些已经存在的bug或者功能

无

### 具体功能需要/Specific features require

在 Android7.1.1 上打开 Qauxiliary

**Comment by cinit** [comment]
@alpha-Foll 请提供 crash log

**Comment by alpha-Foll** [comment]
打不开 qa 怎么找日志捏

**Comment by alpha-Foll** [comment]
打不开 qa 怎么找日志捏

**Comment by alpha-Foll** [comment]
> @alpha-Foll 请提供 crash log

打不开 qa 怎么找日志捏

**Comment by cinit** [comment]
@alpha-Foll 直接提供 LSPosed 的日志，或者 ADB 的 logcat

**Comment by alpha-Foll** [comment]
> @alpha-Foll 直接提供 LSPosed 的日志，或者 ADB 的 logcat

Android7.1.1 用不了 LSPatch
