### ISSUE TITLE
[Bug]选择隐藏QQ钱包超值精选会使红包发送选择页异常

### ISSUE THREAD

**Issue by naahi-i** [cinit/QAuxiliary#806]
### Steps to reproduce/复现步骤

1打开隐藏QQ钱包超值精选
2重启QQ
3进入聊天在底栏选择红包

### Expected behaviour/预期行为

正常显示

### Actual behaviour/实际行为

普通，拼手气红包贴图缺失，专属，口令红包选项缺失

### XPosed Framework you used/你使用的XP框架

lspatch

### QQ(TIM)版本/QQ(TIM) Version

9.0.17.15185(5712)

### Module Version/模块版本

1.4.7.r1900.b63fae6(1900)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.7.r1900.b63fae6
QQ9.0.17(5712)
PID: 18928, UID: 10580
com.alphi.qhmk.module.HookQWallet
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by klxiaoniu** [comment]
#697
