### ISSUE TITLE
[Bug] 华为荣耀8青春版安装后无法打开QAuxiliary

### ISSUE THREAD

**Issue by wms26** [cinit/QAuxiliary#807]
### Steps to reproduce/复现步骤

环境：
1.华为荣耀8青春版(17年发售的)
2.Android8(CPU支持的ABIs有arm68-v8a,armeabi-v7a,armeabi)
3.已root，用的是Magisk(官方版)
4.太极 · 阳(已确认过太极功能正常)
5.QAuxiliary1.4.7_universal(目前的最新版)
步骤：
1.从github上下载目前最新版QA并安装
2.安装完毕后直接打开QA
3.白屏一小段时间就闪退了

### Expected behaviour/预期行为

正常打开QA并进入到QA的主页面(?应该吧，现在QA更新了我也不清楚，但是理论上直接打开总得有个页面吧)

### Actual behaviour/实际行为

1.白屏一段时间就闪退了(是更新了QA之后就打不开了，之前用的啥版本也忘了，之后在github里面翻旧版本QA安装也照样闪退)
![screenshot-2024-02-08-23-23-53-1](https://github.com/cinit/QAuxiliary/assets/50258919/39e4adb5-4a30-45e7-9aba-54ed8631319c)
2.即便在太极里面勾选了启用也并没有生效

### XPosed Framework you used/你使用的XP框架

太极 · 阳(也可以叫“太极 · Magisk”)

### QQ(TIM)版本/QQ(TIM) Version

QQ v9.0.17(看情况理论上任何版本都不行，旧版也不行)

### Module Version/模块版本

QAuxiliary1.4.7.r1883.b3d4b79-universal

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

因为是打开QA直接闪退，并且太极里面勾选启用也用不了，设置里面找不到QA选项(真的到处都翻了一遍)
所以没法使用QA的错误排查，所以就拿adb的logcat抓了一下，看不懂，直接上传吧
[logcat.txt](https://github.com/cinit/QAuxiliary/files/14211501/logcat.txt)

**Comment by 2652015696** [comment]
真的炸裂，我还是重新提交一个新的吧
