### ISSUE TITLE
[功能请求] 复制图片链接

### ISSUE THREAD

**Issue by n78** [cinit/QAuxiliary#81]
### QQ(TIM)版本/QQ(TIM) Version

8.8.35

### 为什么你认为需要此功能

是个比较有用的功能吧，经常会用到（原 小菜豆 模块中含有的功能）

### 联系到哪些已经存在的bug或者功能

是小菜豆模块中含有的功能（长按图片-更多-复制图片链接）

### 具体功能需要/Specific features require

同上，就长按图片可以复制 gchat.qpic.cn 的图片链接，一个简单的小功能

**Comment by cinit** [comment]
@n78 你是不是在找: 长按图片-菜单- MD5-复制图片链接

**Comment by n78** [comment]
> 

🌿，我还以为QA没有这个功能，原来藏在MD5选项里面

**Comment by NextAlone** [comment]
> @n78 你是不是在找: 长按图片-菜单- MD5-复制图片链接

什么诡异分布, 快弄出来

**Comment by keta1** [comment]
@NextAlone 弄不出来

**Comment by NextAlone** [comment]
> @NextAlone 弄不出来

好，责任全在咕咕华
