### ISSUE TITLE
[功能请求] 转发时去除9个选择限制或发送全部好友(就微信群发那样)

### ISSUE THREAD

**Issue by wdvipa** [cinit/QAuxiliary#811]
### QQ(TIM)版本/QQ(TIM) Version

9.0.8.14755

### 为什么你认为需要此功能

过年发祝福语但是转发只能一次性9个上限，一次次按太麻烦，想像微x一样可以选择转发或直接全选

### 具体功能需要/Specific features require

转发时去除9个选择限制或发送全部好友(如微信群发但qq没群发功能)[微x的转发功能那种]后台一条一条自动发送

**Comment by HdShare** [comment]
尝试最新CI版本
