### ISSUE TITLE
[Bug]屏蔽下拉小程序还能进入空白页面

### ISSUE THREAD

**Issue by naahi-i** [cinit/QAuxiliary#815]
### Steps to reproduce/复现步骤

1打开功能
2重启QQ主界面下拉
3进入空白页面
![Screenshot_2024-02-14-18-51-45-18_9d26c6446fd7bb8e41d99b6262b17def](https://github.com/cinit/QAuxiliary/assets/69071025/4f5f06ad-d250-4d4a-a2a1-e5b5e40e7379)

### Expected behaviour/预期行为

不会进入空白页面

### Actual behaviour/实际行为

进入原小程序页面的空白页面

### XPosed Framework you used/你使用的XP框架

lspatch

### QQ(TIM)版本/QQ(TIM) Version

9.0.17.15185(5712)

### Module Version/模块版本

1.4.8.r1908.ccb306d(1908)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.8.r1908.ccb306d
QQ9.0.17(5712)
PID: 15567, UID: 10580
cc.ioctl.hook.ui.main.HideMiniAppPullEntry
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by klxiaoniu** [comment]
fixed
