### ISSUE TITLE
[Bug] 自动接收原图可能失效

### ISSUE THREAD

**Issue by phillaria** [cinit/QAuxiliary#820]
### Steps to reproduce/复现步骤

部分图片无法自动接收原图，且并未显示在功能异常列表中
![453E6DC6D532B463F3ACA0DDBCDDE0C4](https://github.com/cinit/QAuxiliary/assets/130157526/e4dd76de-551d-47bf-8a76-cf02a4a3fa3d)
![E7F4604B6753EEBBDCDB508F6B13EFF1](https://github.com/cinit/QAuxiliary/assets/130157526/0f41ecc5-a97b-4c12-bb4a-7ddb2006fe06)
![6BF1F8ED99BF1B9EAD74B65835683750](https://github.com/cinit/QAuxiliary/assets/130157526/2521ba56-2742-4b33-a194-167221746a11)

### Expected behaviour/预期行为

之前用的8.5.0版本时，点开图片就会自动加载原图

### Actual behaviour/实际行为

实际并未自动加载原图，图片左下角可见【查看原图】按钮

### XPosed Framework you used/你使用的XP框架

1.9.2

### QQ(TIM)版本/QQ(TIM) Version

9.0.17

### Module Version/模块版本

1.4.8

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.8.r1905.3aed1c5
QQ9.0.17(5714)
PID: 2689, UID: 10459
xyz.nextalone.hook.AutoReceiveOriginalPhoto
isInitialized: false
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by HdShare** [comment]
尝试CI-v1.5.2-r2352版本

**Comment by phillaria** [comment]
感谢开发者大大，那么什么时候release它呢？（
