### ISSUE TITLE
[Bug] 显示设置禁言的管理这一功能未正常生效

### ISSUE THREAD

**Issue by LazySunIsMe** [cinit/QAuxiliary#822]
### Steps to reproduce/复现步骤

1.开启此功能
2.让群管理禁言你
3.禁言栏未显示管理信息，仅显示“被群主/管理员禁言XX秒”字样

### Expected behaviour/预期行为

显示禁言的管理的昵称

### Actual behaviour/实际行为

仅显示“被群主/管理员禁言XX秒”字样

### XPosed Framework you used/你使用的XP框架

太极

### QQ(TIM)版本/QQ(TIM) Version

9.0.17.15190(5714)

### Module Version/模块版本

1.4.8.r1905.3aed1c5(1905)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.8.r1905.3aed1c5
QQ9.0.17(5714)
PID: 11670, UID: 10450
cc.ioctl.hook.chat.GagInfoDisclosure
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

（事实上，排查功能并未检测出异常）
（我推测是否是因为显示禁言精确时间和显示禁言管理这两个功能不兼容，无法同时进行显示？）

**Comment by cinit** [comment]
@LazySunIsMe 坏了很久了，一直没修

**Comment by LazySunIsMe** [comment]
好的

**Comment by tksmly** [comment]
还没修
