### ISSUE TITLE
[功能请求] 一种让 TIM 允许资料卡复制QQ号的思路

### ISSUE THREAD

**Issue by MoonLeeeaf** [cinit/QAuxiliary#824]
### QQ(TIM)版本/QQ(TIM) Version

TIM 3.5.1 本功能思路目前仅限此版本

### 为什么你认为需要此功能

允许像原本QQ一样快捷复制QQ号
有时候很有用

### 具体功能需要/Specific features require

注:如果完成此功能，请连同 #578 一起关闭，因为目前没有时间给我研究，因此还请大佬帮我完成

由于无法登录到原账号，因此我无法修改 #578 以达到不重复的目的，还请原谅

具体代码实现思路：
在 com.tencent.mobileqq.activity.PublicFragmentActivity 里面加钩子，使得 Resources ID 为 @+id/nk2 的 TextView 可以处理长按，并弹出一个 PopupMenu 可以选择复制QQ号
![Screenshot_2024-02-21-23-00-00-514_bin mt plus](https://github.com/cinit/QAuxiliary/assets/150461955/a23a4109-4855-4f7b-8fba-4363ececb35f)

由于没有分析，因此需要一些办法获取这个 Fragment 再去寻找 View，如果实在没有人制作的话我只能借用 QA 的 CI 测试了（逃）

**Comment by klxiaoniu** [comment]
这个样式的资料卡从TIM哪个版本开始的？

**Comment by klxiaoniu** [comment]
![image](https://github.com/cinit/QAuxiliary/assets/48382562/8846c777-bc7c-4882-b1c6-bf9168b20a8c)

目前设置该功能最低版本TIM3.1.1
