### ISSUE TITLE
[功能请求] 

### ISSUE THREAD

**Issue by siilm** [cinit/QAuxiliary#825]
### QQ(TIM)版本/QQ(TIM) Version

8.9.88

### 为什么你认为需要此功能

+1Plus相关，按钮直接点击容易误触且不够美观

### 具体功能需要/Specific features require

希望让+1Plus中让“显示在消息右上角”选项可用

**Comment by klxiaoniu** [comment]
@siilm 可以使用添加到长按菜单

**Comment by siilm** [comment]
对，但是添加到长按菜单又不够快捷，显示在消息框右上角可以直接双击+1，比长按菜单快捷的同时又没直接显示在右侧易误触。

> @siilm 可以使用添加到长按菜单
