### ISSUE TITLE
[Bug] 从tg同步到表情包在预览缩咯图显示过于模糊，无法辨认

### ISSUE THREAD

**Issue by by123456by** [cinit/QAuxiliary#826]
### Steps to reproduce/复现步骤

1.使用插件同步表情包
2.聊天窗口查看
3.明显文字无法辨认

### Expected behaviour/预期行为

![47e325324c20da968a1501d51e3058f](https://github.com/cinit/QAuxiliary/assets/15666692/ac3442de-d5aa-4b6f-838a-5fd77678ec90)

### Actual behaviour/实际行为

![ff2e72d70850fa3e0e0a5326486f7dd](https://github.com/cinit/QAuxiliary/assets/15666692/d71476f4-ffe2-4a2a-a457-96f21371b497)

### XPosed Framework you used/你使用的XP框架

LSPosed1.9.2

### QQ(TIM)版本/QQ(TIM) Version

QQ9.0.17.15190

### Module Version/模块版本

1.4.8

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

无

**Comment by klxiaoniu** [comment]
已添加预览质量选项
