### ISSUE TITLE
 [Bug] 华为QQ NT 9.0.6 无法启动模块

### ISSUE THREAD

**Issue by CommandPrompt-Wang** [cinit/QAuxiliary#827]
### Steps to reproduce/复现步骤

太极，qqnt（版本见下）
手机nova5 homoos 3.0.0
（太极连续优化/撤销失败，不知为何，华为通病？）

### Expected behaviour/预期行为

应该会找到qaux的设置

### Actual behaviour/实际行为

什么效果也没有
显示已激活但是没有效果
找不到qqnt菜单

### XPosed Framework you used/你使用的XP框架

太极青钢影 10.3.2.03081021-10529 阴 设备管理员 已生效

### QQ(TIM)版本/QQ(TIM) Version

QQ Nt 9.0.15

### Module Version/模块版本

QAux 版本 1.4.6.r1786.189196f

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

由于无法正常启动模块，无法查看日志（已尝试安全模式）

**Comment by klxiaoniu** [comment]
@CommandPrompt-Wang 尝试使用LSPatch
