### ISSUE TITLE
[功能请求] 在启用【聊天自动发送原图】时，为发送给电脑的图片也启用该功能

### ISSUE THREAD

**Issue by phillaria** [cinit/QAuxiliary#829]
### QQ(TIM)版本/QQ(TIM) Version

9.0.17.15190(5714)

### 为什么你认为需要此功能

目前的【聊天自动发送原图】功能唯独对【我的电脑】发送图片时，不能像和其他人的聊天界面一样自动勾选【原图】按钮，应该是功能的遗漏

### 具体功能需要/Specific features require

启用【聊天自动发送原图】时，对【我的电脑】发送图片时，也自动勾选【原图】按钮

**Comment by klxiaoniu** [comment]
@phillaria 哪有原图选项？发送我的电脑不是以文件形式发送的吗？

**Comment by phillaria** [comment]
> @phillaria哪有原图选项？发送我的电脑不是以文件形式发送的吗？

确实如此，这里虽然有原图选项但勾选与否都不影响发送图片的精度。这个issue可以关掉了😂
