### ISSUE TITLE
[Bug] 系统相册Java类错误

### ISSUE THREAD

**Issue by THERentropy** [cinit/QAuxiliary#83]
### Steps to reproduce/复现步骤

1.iqoo neo5
2.更新6.9.8版本，安卓12
3.打开QQ对好友/群发送图片，选择“系统相册”随机选取一张图片发送

### Expected behaviour/预期行为

顺利发送从系统相册中选取的图片

### Actual behaviour/实际行为

发送失败，
提示：File Not Found Exception
java.io.FileNotFoundException: access image/video reject for content://media/external/images/media/243406
at
android.database.DatabaseUtils.r eadExceptionWithFileNotFoundE xceptionFromParcel(DatabaseUtils.java:151)
at
android.content.ContentProviderP roxy.openTypedAssetFile(ContentProviderNative.java:780)
at
android.content.ContentResolver. openTypedAssetFileDescriptor(ContentResolver.java:2066)
at
android.content.ContentResolver. openAssetFileDescriptor(ContentResolver.java:1881)
at
android.content.ContentResolver. openlnputStream(ContentResolver.java:1557)
at
me.singleneuron.base.AbstractChooseActivity$convertUriToPath$2.invokeSuspend(AbstractChooseActivity.kt:68)
at
me.singleneuron.base.AbstractChooseActivity$convertUriToPath$2.invoke(Unknown Source:8)
at
me.singleneuron.base.AbstractChooseActivity$convertUriToPath$2.invoke(Unknown Source:4)
at
kotlinx.coroutines.intrinsics.Undis patchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
at
kotlinx.coroutines.BuildersKt__Bui lders_commonKt.withContext(Builders.common.kt:166)
at
kotlinx.coroutines.BuildersKt.with Context(Unknown Source:1)
at
me.singleneuron.base.AbstractCh ooseActivity.convertUriToPath(AbstractChooseActivity.kt:67)
at
me.singleneuron.activity.ChooseAgentActivity$onActivityResult$1$1.invokeSuspend(ChooseAgentActivity.kt:75)
at
kotlin.coroutines.jvm.internal.Base Continuationlmpl.resumeWith(Continuationlmpl.kt:33)
at
kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at
kotlinx.coroutines.internal.Limited Dispatcher.run(LimitedDispatcher.kt:42)
at
kotlinx.coroutines.scheduling.Tasklmpl.run(Tasks.kt:95)
at
kotlinx.coroutines.scheduling.Coro utineScheduler.runSafely(CoroutineScheduler.kt:570)
at
kotlinx.coroutines.scheduling.Coro utineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)at
kotlinx.coroutines.scheduling.Coro utineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
at
kotlinx.coroutines.scheduling.Coro utineScheduler$Worker.run(CoroutineScheduler.kt:664)

注：打开DebugActivity则提示：ClassNotFoundException java.lang.ClassNotFoundExceptio n:com.tencent.mobileqq.debug.D ebugActivity

### XPosed Framework you used/你使用的XP框架

太极 9.0.1，无root

### QQ(TIM)版本/QQ(TIM) Version

8.8.50（2324）

### Module Version/模块版本

v1.2.5.r551.1acbd2e（551）

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

 PID: 30860, UID: 10731, 64 bit
Xposed API version: 92
de.robv.android.xposed.XposedBridge

 [1]DialogUtil
com.tencent.mobileqq.utils.DialogUtil
= com.tencent.mobileqq.utils.DialogUtil
  [2]ChatActivityFacade
com.tencent.mobileqq.activity.ChatActivityFacade
= com.tencent.mobileqq.activity.ChatActivityFacade
  [3]FlashPicHelper
com.tencent.mobileqq.app.FlashPicHelper
= com.tencent.mobileqq.app.FlashPicHelper
  [4]BasePicDownloadProcessor
com.tencent.mobileqq.transfile.BasePicDownloadProcessor
= com.tencent.mobileqq.transfile.BasePicDownloadProcessor
  [5]ItemBuilderFactory
com.tencent.mobileqq.activity.aio.item.ItemBuilderFactory
= (void*)0
  [6]AIOUtils
com.tencent.mobileqq.activity.aio.AIOUtils
= com.tencent.mobileqq.activity.aio.AIOUtils
  [7]AbstractGalleryScene
com.tencent.common.galleryactivity.AbstractGalleryScene
= com.tencent.common.galleryactivity.AbstractGalleryScene
  [8]java.lang.IndexOutOfBoundsException: No class index for 8,max = 37
  [9]FavEmoConstant
com.tencent.mobileqq.emosm.favroaming.FavEmoConstant
= com.tencent.mobileqq.emosm.favroaming.FavEmoConstant
  [10]MessageRecordFactory
com.tencent.mobileqq.service.message.MessageRecordFactory
= com.tencent.mobileqq.service.message.MessageRecordFactory
  [11]ContactUtils
com.tencent.mobileqq.utils.ContactUtils
= com.tencent.mobileqq.utils.ContactUtils
  [12]java.lang.IndexOutOfBoundsException: No class index for 12,max = 37
  [13]ArkAppItemBubbleBuilder
com.tencent.mobileqq.activity.aio.item.ArkAppItemBubbleBuilder
= com.tencent.mobileqq.activity.aio.item.ArkAppItemBubbleBuilder
  [14]PngFrameUtil
com.tencent.mobileqq.magicface.drawable.PngFrameUtil
= com.tencent.mobileqq.magicface.drawable.PngFrameUtil
  [15]PicEmoticonInfo
com.tencent.mobileqq.emoticonview.PicEmoticonInfo
= com.tencent.mobileqq.emoticonview.PicEmoticonInfo
  [16]SimpleUIUtil
com.tencent.mobileqq.theme.SimpleUIUtil
= (void*)0
  [17]TroopGiftUtil
com.tencent.mobileqq.troop.utils.TroopGiftUtil
= com.tencent.mobileqq.troop.utils.TroopGiftUtil
  [18]TestStructMsg
com.tencent.mobileqq.structmsg.TestStructMsg
= com.tencent.mobileqq.structmsg.TestStructMsg
  [19]MsgNotification
cooperation.qzone.push.MsgNotification
= cooperation.qzone.push.MsgNotification
  [20]AppConstants
com.tencent.mobileqq.app.AppConstants
= com.tencent.mobileqq.app.AppConstants
  [21]CustomWidgetUtil
com.tencent.widget.CustomWidgetUtil
= com.tencent.widget.CustomWidgetUtil
  [22]MessageCache
com.tencent.mobileqq.service.message.MessageCache
= com.tencent.mobileqq.service.message.MessageCache
  [23]ScreenShotHelper
com.tencent.mobileqq.screendetect.ScreenShotHelper
= com.tencent.mobileqq.screendetect.ScreenShotHelper
  [24]TimeFormatterUtils
com.tencent.mobileqq.utils.TimeFormatterUtils
= com.tencent.mobileqq.utils.TimeFormatterUtils
  [25]TogetherControlHelper
com.tencent.mobileqq.aio.helper.TogetherControlHelper
= (void*)0
  [26]TroopAppShortcutDrawer
com.tencent.mobileqq.activity.aio.drawer.TroopAppShortcutDrawer
= com.tencent.mobileqq.activity.aio.drawer.TroopAppShortcutDrawer
  [27]IntimateInfoChatDrawer
com.tencent.mobileqq.activity.aio.drawer.IntimateInfoChatDrawer
= com.tencent.mobileqq.activity.aio.drawer.IntimateInfoChatDrawer
  [28]ZipUtils
com.tencent.biz.common.util.ZipUtils
= com.tencent.biz.common.util.ZipUtils
  [29]HttpDownloader
com.tencent.mobileqq.transfile.HttpDownloader
= com.tencent.mobileqq.transfile.HttpDownloader
  [30]MultiMsgManager
com.tencent.mobileqq.multimsg.MultiMsgManager
= com.tencent.mobileqq.multimsg.MultiMsgManager
  [31]ClockInEntryHelper
com.tencent.mobileqq.activity.aio.helper.ClockInEntryHelper
= com.tencent.mobileqq.activity.aio.helper.ClockInEntryHelper
  [32]CaptureUtil
com.tencent.mobileqq.richmedia.capture.util.CaptureUtil
= com.tencent.mobileqq.richmedia.capture.util.CaptureUtil
  [33]AvatarUtil
com.tencent.mobileqq.avatar.utils.AvatarUtil
= com.tencent.mobileqq.avatar.utils.AvatarUtil
  [34]FaceManager
com.tencent.mobileqq.app.face.FaceManager
= (void*)0
  [35]SmartDeviceProxyMgr
com.tencent.device.devicemgr.SmartDeviceProxyMgr
= com.tencent.device.devicemgr.SmartDeviceProxyMgr
  [36]AIOPictureView
com.tencent.mobileqq.richmediabrowser.view.AIOPictureView
= com.tencent.mobileqq.richmediabrowser.view.AIOPictureView
  [37]GalleryBaseScene
com.tencent.mobileqq.gallery.view.GalleryBaseScene
= (void*)0
  [20001]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= com.tencent.mobileqq.activity.aio.core.BaseChatPie
  [20002]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= com.tencent.mobileqq.activity.aio.core.BaseChatPie
  [20003]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= com.tencent.mobileqq.activity.aio.core.BaseChatPie
  [20004]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= com.tencent.mobileqq.activity.aio.core.BaseChatPie
  [20005]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= com.tencent.mobileqq.activity.aio.core.BaseChatPie
  [20006]LeftSwipeReplyHelper
com.tencent.mobileqq.bubble.LeftSwipeReplyHelper
= com.tencent.mobileqq.bubble.LeftSwipeReplyHelper
  [20007]AtPanel
com.tencent.mobileqq.troop.quickat.ui.AtPanel
= com.tencent.mobileqq.troop.quickat.ui.AtPanel
  [20008]AtPanel
com.tencent.mobileqq.troop.quickat.ui.AtPanel
= com.tencent.mobileqq.troop.quickat.ui.AtPanel
  [20009]FriendChatPie
com.tencent.mobileqq.activity.aio.core.FriendChatPie
= com.tencent.mobileqq.activity.aio.core.FriendChatPie
  [20010]ProfileCardUtil
com.tencent.mobileqq.util.ProfileCardUtil
= com.tencent.mobileqq.util.ProfileCardUtil
  [20011]VasProfileTemplateController
com.tencent.mobileqq.profilecard.vas.VasProfileTemplateController
= com.tencent.mobileqq.profilecard.vas.VasProfileTemplateController
  [20012]QQSettingMe
com.tencent.mobileqq.activity.QQSettingMe
= com.tencent.mobileqq.activity.QQSettingMe
  [20013]VipUtils
com.tencent.mobileqq.utils.VipUtils
= com.tencent.mobileqq.utils.VipUtils
  [20014]TroopChatPie
com.tencent.mobileqq.activity.aio.core.TroopChatPie
= com.tencent.mobileqq.activity.aio.core.TroopChatPie
  [20015]Conversation
com.tencent.mobileqq.activity.home.Conversation
= com.tencent.mobileqq.activity.home.Conversation
  [20016]QQSettingMe
com.tencent.mobileqq.activity.QQSettingMe
= com.tencent.mobileqq.activity.QQSettingMe
  [20017]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= com.tencent.mobileqq.activity.aio.core.BaseChatPie
  [20018]WebSecurityPluginV2$1
com.tencent.mobileqq.webview.WebSecurityPluginV2$1
= com.tencent.mobileqq.webview.WebSecurityPluginV2$1
  [40001]VasProfileAntiCrash
com.tencent.mobileqq.profilecard.vas.component.template.VasProfileTemplateComponent
  [40002]ReplyNoAtHook
__NOT_USED__
  [40003]ChatWordsCount
nf4
  [40004]SortAtPanel.sessionInfoTroopUin
b
  [40005]RemovePlayTogether.ClockInEntryHelper
f
  [40006]SimplifyQQSettingMe::MidContentName
S
  [40007]RemovePlayTogether.TogetherControlHelper
n

**Comment by THERentropy** [comment]
对的，这个bug是在我更新了次系统后出现的，影响并不是很大，我能正常从“系统文档”中选取图片来绕过这个错误

**Comment by Cryolitia** [comment]
> 对的，这个bug是在我更新了次系统后出现的，影响并不是很大，我能正常从“系统文档”中选取图片来绕过这个错误

Android10以后逐步加强了对直接访问文件的限制，出现这种问题是十分正常的。因此我们提供了多种方式来选择文件，只要有其中一种可以正常工作即可。

**Comment by THERentropy** [comment]
更新，太极在昨日8/8号更新了青钢影10.0.0，该议题下的bug已解决

**Comment by Cryolitia** [comment]
原来是太极的问题……
