### ISSUE TITLE
[Bug] QQ版本9.0.17正式版和内测版9.0.20有几项设置项失效或异常

### ISSUE THREAD

**Issue by 233YUZI** [cinit/QAuxiliary#833]
### Steps to reproduce/复现步骤

**正式版9.0.17和测试版9.0.20都有的bug**

1. **异常**  隐藏下拉小程序   _下拉过头后仍然会进入一个空白页_
2. **失效**  禁用轻互动 
3. **异常**  移除右滑群应用  _右滑仍然会进入一个纯黑页_
还有其他感知不强的直接发logs

**以下是内测版9.0.20独有bug**

1. **失效**  屏蔽主界面超级QQ秀图标
2. **失效**  侧边栏精简→超级QQ秀
3. **异常**  侧滑栏  _屏蔽某个项目后会导致侧滑栏全消失，具体是哪个项目没测_

### Expected behaviour/预期行为

如上

### Actual behaviour/实际行为

如上

### XPosed Framework you used/你使用的XP框架

lsp 1.9.2（7024）

### QQ(TIM)版本/QQ(TIM) Version

9.0.17正式版/9.0.20内测版

### Module Version/模块版本

1.4.8.r1905.3aed1c5(1905)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

[DisabledRedNick-1709030083194.txt](https://github.com/cinit/QAuxiliary/files/14418167/DisabledRedNick-1709030083194.txt)
[DisableDropSticker-1709030093651.txt](https://github.com/cinit/QAuxiliary/files/14418169/DisableDropSticker-1709030093651.txt)
[DisableLightInteraction-1709029039234.txt](https://github.com/cinit/QAuxiliary/files/14418171/DisableLightInteraction-1709029039234.txt)
[RemoveCameraButton-1709030075734.txt](https://github.com/cinit/QAuxiliary/files/14418172/RemoveCameraButton-1709030075734.txt)
[RemoveIntimateDrawer-1709030087810.txt](https://github.com/cinit/QAuxiliary/files/14418173/RemoveIntimateDrawer-1709030087810.txt)

**Comment by klxiaoniu** [comment]
前三个已知，后三个更新CI版

**Comment by HumanMus1c** [comment]
> 前三个已知，后三个更新CI版

已安装最新CL版本v1.4.8.r1928.220314a
以及清除缓存以重新计算适配数据后依然存在问题。
![Screenshot_20240228_185835_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/46023154/de458547-6f00-4a48-8186-44a3133169fb)
![Screenshot_20240228_185925_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/46023154/18bcd435-be94-4f90-ad6d-ae78a3a9c78b)
