### ISSUE TITLE
[Bug] 9.0.20在pad布局打开移除侧滑栏左上角打卡导致侧滑栏消失

### ISSUE THREAD

**Issue by HoratioShaw** [cinit/QAuxiliary#837]
### Steps to reproduce/复现步骤

1.在pad布局打开移除侧滑栏左上角打卡

### Expected behaviour/预期行为

正常显示

### Actual behaviour/实际行为

侧滑栏消失
![Screenshot_20240228_184554](https://github.com/cinit/QAuxiliary/assets/72498396/05f6d6e9-1017-4ffd-b6f9-8dcc257ac725)
并且提示未发现异常
1.4.8.r1928.220314a
QQ9.0.20(5782)
PID: 19985, UID: 10407
cc.ioctl.hook.ui.title.RemoveDailySign
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

### XPosed Framework you used/你使用的XP框架

ONPatch-9.0.20 (5782)

### QQ(TIM)版本/QQ(TIM) Version

9.0.20 (5782)

### Module Version/模块版本

1.4.8.r1928.220314a (1928)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

PID: 27666, UID: 10407, 64 bit
Xposed API version: 100
de.robv.android.xposed.XposedBridge

[0]PicElement
com.tencent.mobileqq.aio.msg.AIOMsgElementType.PicElement
= Lcom/tencent/qqnt/aio/u/a/a$d;->toString()Ljava/lang/String;
  [5]AbstractQQCustomMenuItem
com.tencent.qqnt.aio.menu.ui.AbstractQQCustomMenuItem
= Lcom/tencent/qqnt/aio/menu/ui/k;->toString()Ljava/lang/String;
  [7]AIOPictureView
com.tencent.mobileqq.richmediabrowser.view.AIOPictureView
= com.tencent.mobileqq.richmediabrowser.view.AIOPictureView
  [8]AIOUtils
com.tencent.mobileqq.activity.aio.AIOUtils
= Lcom/tencent/mobileqq/activity/aio/v;->R(Lcom/tencent/mobileqq/app/QQAppInterface;Lcom/tencent/mobileqq/app/BaseActivity;Landroid/content/Intent;)I
  [9]AbstractGalleryScene
com.tencent.common.galleryactivity.AbstractGalleryScene
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [10]AppConstants
com.tencent.mobileqq.app.AppConstants
= com.tencent.mobileqq.app.AppConstants
  [11]ArkAppItemBubbleBuilder
com.tencent.mobileqq.activity.aio.item.ArkAppItemBubbleBuilder
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [12]AvatarUtil
com.tencent.mobileqq.avatar.utils.AvatarUtil
= (void*)0
  [13]BasePicDownloadProcessor
com.tencent.mobileqq.transfile.BasePicDownloadProcessor
= com.tencent.mobileqq.transfile.BasePicDownloadProcessor
  [14]CustomWidgetUtil
com.tencent.widget.CustomWidgetUtil
= Lcom/tencent/qqnt/chats/b/h/c$a;->a(Landroid/widget/TextView;III)V
  [15]DialogUtil
com.tencent.mobileqq.utils.DialogUtil
= com.tencent.mobileqq.utils.DialogUtil
  [16]ChatActivityFacade
com.tencent.mobileqq.activity.ChatActivityFacade
= com.tencent.mobileqq.activity.ChatActivityFacade
  [17]FaceManager
com.tencent.mobileqq.app.face.FaceManager
= (void*)0
  [18]FavEmoConstant
com.tencent.mobileqq.emosm.favroaming.FavEmoConstant
= com.tencent.mobileqq.emosm.favroaming.FavEmoConstant
  [19]FlashPicHelper
com.tencent.mobileqq.app.FlashPicHelper
= Lcom/tencent/mobileqq/app/al;->e(Lcom/tencent/mobileqq/data/MessageRecord;Z)V
  [20]FrameControllerInjectImpl
com.tencent.mobileqq.activity.framebusiness.controllerinject.FrameControllerInjectImpl
= com.tencent.mobileqq.activity.framebusiness.controllerinject.FrameControllerInjectImpl
  [21]GalleryBaseScene
com.tencent.mobileqq.gallery.view.GalleryBaseScene
= Lcom/tencent/richmediabrowser/view/BrowserBaseScene;->onItemSelected(I)V
  [22]TroopAppShortcutDrawer
com.tencent.mobileqq.activity.aio.drawer.TroopAppShortcutDrawer
= com.tencent.mobileqq.activity.aio.drawer.TroopAppShortcutDrawer
  [23]GuildArkHelper
com.tencent.mobileqq.guild.chatpie.helper.GuildArkHelper
= (void*)0
  [24]GuildHelperProvider
com.tencent.mobileqq.guild.chatpie.GuildHelperProvider
= (void*)0
  [25]HttpDownloader
com.tencent.mobileqq.transfile.HttpDownloader
= com.tencent.mobileqq.transfile.HttpDownloader
  [26]IntimateInfoChatDrawer
com.tencent.mobileqq.activity.aio.drawer.IntimateInfoChatDrawer
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [27]ItemBuilderFactory
com.tencent.mobileqq.activity.aio.item.ItemBuilderFactory
= Lcom/tencent/mobileqq/activity/aio/core/msglist/a/a;->b(Lcom/tencent/mobileqq/data/ChatMessage;Landroid/widget/BaseAdapter;)Lcom/tencent/mobileqq/activity/aio/ah;
  [28]MessageCache
com.tencent.mobileqq.service.message.MessageCache
= Lcom/tencent/mobileqq/service/h/e;-><clinit>()V
  [29]MessageRecordFactory
com.tencent.mobileqq.service.message.MessageRecordFactory
= Lcom/tencent/mobileqq/service/h/r;->I(Lcom/tencent/common/app/AppInterface;Lcom/tencent/mobileqq/data/MessageRecord;Ljava/lang/String;Ljava/lang/String;I)V
  [30]MultiMsgManager
com.tencent.mobileqq.multimsg.MultiMsgManager
= com.tencent.mobileqq.multimsg.MultiMsgManager
  [31]OnlinePushPbPushTransMsg
com.tencent.mobileqq.app.handler.receivesuccess.OnlinePushPbPushTransMsg
= (void*)0
  [32]PicEmoticonInfo
com.tencent.mobileqq.emoticonview.PicEmoticonInfo
= com.tencent.mobileqq.emoticonview.PicEmoticonInfo
  [33]PngFrameUtil
com.tencent.mobileqq.magicface.drawable.PngFrameUtil
= (void*)0
  [34]PopOutEmoticonUtil
com.tencent.mobileqq.popanim.util.PopOutEmoticonUtil
= Lcom/tencent/mobileqq/popanim/a/a;->f(ILcom/tencent/mobileqq/emoticonview/EmoticonInfo;I)Z
  [35]MsgNotification
cooperation.qzone.push.MsgNotification
= cooperation.qzone.push.MsgNotification
  [36]ReplyMsgSender
com.tencent.mobileqq.replymsg.ReplyMsgSender
= (void*)0
  [37]ReplyMsgUtils
com.tencent.mobileqq.activity.aio.reply.ReplyMsgUtils
= (void*)0
  [38]ScreenShotHelper
com.tencent.mobileqq.screendetect.ScreenShotHelper
= com.tencent.mobileqq.screendetect.ScreenShotHelper
  [39]SimpleUIUtil
com.tencent.mobileqq.theme.SimpleUIUtil
= (void*)0
  [40]SystemMessageProcessor
com.tencent.mobileqq.app.message.SystemMessageProcessor
= (void*)0
  [41]TestStructMsg
com.tencent.mobileqq.structmsg.TestStructMsg
= Lcom/tencent/mobileqq/structmsg/w;->a(Ljava/lang/String;)Lcom/tencent/mobileqq/structmsg/AbsStructMsg;
  [42]TimeFormatterUtils
com.tencent.mobileqq.utils.TimeFormatterUtils
= (void*)0
  [43]TroopGiftUtil
com.tencent.mobileqq.troop.utils.TroopGiftUtil
= Lcom/tencent/mobileqq/troop/utils/ab;->n(Ljava/io/File;)Z
  [44]ZipUtils
com.tencent.biz.common.util.ZipUtils
= com.tencent.biz.common.util.ZipUtils
  [47]DefaultFileModel
com.tencent.mobileqq.filemanager.fileviewer.model.DefaultFileModel
= Lcom/tencent/mobileqq/filemanager/fileviewer/model/f;->v0(ILjava/lang/String;)V
  [49]EmotcationConstants
com.tencent.mobileqq.text.EmotcationConstants
= com.tencent.mobileqq.text.EmotcationConstants
  [50]ForwardSendPicUtil
com.tencent.mobileqq.utils.ForwardSendPicUtil
= com.tencent.mobileqq.utils.ForwardSendPicUtil
  [53]toBottomIntent
com.tencent.mobileqq.aio.input.multiselect.c.toBottomIntent
= Lcom/tencent/mobileqq/aio/input/multiselect/c$h;->toString()Ljava/lang/String;
  [87]LoadPropertiesUtils
com.tencent.smtt.utils.LoadPropertiesUtils
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [88]activity
com.tencent.qqnt.aio.activity
= Lcom/tencent/qqnt/aio/activity/AIODelegate$d;->a()V
  [91]

= (void*)0
  [92]

= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [95]

= (void*)0
  [1]sendMsg
com.tencent.mobileqq.aio.input.sendmsg.AIOSendMsgVMDelegate.sendMsg
= (void*)0
  [2]AIOTextElementCtor
com.tencent.mobileqq.aio.msg.AIOMsgElement.AIOTextElementCtor
= (void*)0
  [3]AIO_Create_QQNT
AIO_Create_QQNT
= Lcom/tencent/aio/base/chat/ChatPie;->g(Landroid/os/Bundle;Lcom/tencent/aio/main/fragment/ChatFragment;Lkotlin/jvm/functions/Function1;)V
  [4]

= Lcom/tencent/mobileqq/aio/input/i/b;->E(Lcom/tencent/mobileqq/aio/input/e/b/a;)V
  [6]BaseListenTogetherPanel
com.tencent.mobileqq.listentogether.ui.BaseListenTogetherPanel
= com.tencent.mobileqq.listentogether.ui.BaseListenTogetherPanel
  [45]ChatPanel_InitPanel_QQNT
ChatPanel_InitPanel_QQNT
= (void*)0
  [46]

= (void*)0
  [48]

= (void*)0
  [51]NotifyIdManager
com.tencent.util.notification.NotifyIdManager
= Lcom/tencent/util/notification/d;->i(Ljava/lang/String;Lcom/tencent/imcore/message/Message;)Ljava/lang/String;
  [52]Guild_Emo_Btn_Create_QQNT
Guild_Emo_Btn_Create_QQNT
= (void*)0
  [54]AtPanel
com.tencent.mobileqq.troop.quickat.ui.AtPanel
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [55]AtPanel
com.tencent.mobileqq.troop.quickat.ui.AtPanel
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [56]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= com.tencent.mobileqq.activity.aio.core.BaseChatPie
  [57]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= Lcom/tencent/mobileqq/activity/aio/helper/AIOMultiActionHelper;->w(Lcom/tencent/mobileqq/data/ChatMessage;)V
  [58]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= Lcom/tencent/mobileqq/activity/aio/core/BaseChatPie;->B0()V
  [59]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= com.tencent.mobileqq.activity.aio.core.BaseChatPie
  [60]ChatActivityFacade
com.tencent.mobileqq.activity.ChatActivityFacade
= Lcom/tencent/mobileqq/activity/ChatActivityFacade;->j1(Lcom/tencent/mobileqq/app/QQAppInterface;Landroid/content/Context;Lcom/tencent/mobileqq/activity/aio/ab;Ljava/lang/String;Ljava/util/ArrayList;Lcom/tencent/mobileqq/activity/ChatActivityFacade$d;)[J
  [61]ContactUtils
com.tencent.mobileqq.utils.ContactUtils
= Lcom/tencent/mobileqq/utils/ContactUtils;->f(Lmqq/app/AppRuntime;Ljava/lang/String;Z)Ljava/lang/String;
  [62]ContactUtils
com.tencent.mobileqq.utils.ContactUtils
= Lcom/tencent/mobileqq/utils/ContactUtils;->m(Lcom/tencent/common/app/business/BaseQQAppInterface;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
  [63]Conversation
com.tencent.mobileqq.activity.home.Conversation
= Lcom/tencent/mobileqq/activity/home/Conversation;->onCreate()V
  [64]CustomWidgetUtil
com.tencent.widget.CustomWidgetUtil
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [65]FriendChatPie
com.tencent.mobileqq.activity.aio.core.FriendChatPie
= com.tencent.mobileqq.activity.aio.core.FriendChatPie
  [66]FriendsStatusUtil
com.tencent.mobileqq.app.utils.FriendsStatusUtil
= Lcom/tencent/mobileqq/app/utils/FriendsStatusUtil;->k(Lcom/tencent/mobileqq/app/QQAppInterface;Ljava/lang/String;I)Z
  [67]LeftSwipeReplyHelper
com.tencent.mobileqq.bubble.LeftSwipeReplyHelper
= Lcom/tencent/mobileqq/bubble/i;->M()V
  [68]PadUtil
com.tencent.common.config.PadUtil
= (void*)0
  [69]PhotoListPanel
com.tencent.mobileqq.activity.aio.photo.PhotoListPanel
= com.tencent.mobileqq.activity.aio.photo.PhotoListPanel
  [70]ProfileCardUtil
com.tencent.mobileqq.util.ProfileCardUtil
= com.tencent.mobileqq.util.ProfileCardUtil
  [71]QQSettingMe
com.tencent.mobileqq.activity.QQSettingMe
= (void*)0
  [72]QQSettingMe
com.tencent.mobileqq.activity.QQSettingMe
= Lcom/tencent/mobileqq/QQSettingMeView;->M(Lcom/tencent/mobileqq/activity/qqsettingme/a/l;)V
  [73]

= Lcom/qzone/reborn/qzmoment/util/g;->d()Z
  [74]Scene
com.tencent.mobileqq.troopAddFrd.Scene
= Lcom/tencent/mobileqq/troopAddFrd/c;->f()I
  [75]TroopAppShortcutBarHelper
com.tencent.mobileqq.activity.aio.helper.TroopAppShortcutBarHelper
= Lcom/tencent/mobileqq/activity/aio/helper/df;->F()V
  [76]TroopChatPie
com.tencent.mobileqq.activity.aio.core.TroopChatPie
= com.tencent.mobileqq.activity.aio.core.TroopChatPie
  [77]VasProfileTemplateController
com.tencent.mobileqq.profilecard.vas.VasProfileTemplateController
= Lcom/tencent/mobileqq/profilecard/vas/VasProfileTemplateController;->onCardUpdate(Lcom/tencent/mobileqq/profilecard/base/framework/IComponentCenter;Lcom/tencent/mobileqq/profilecard/data/ProfileCardInfo;)Z
  [78]VipUtils
com.tencent.mobileqq.utils.VipUtils
= Lcom/tencent/mobileqq/vip/p;->getPrivilegeFlags(Ljava/lang/String;)I
  [79]VipUtils
com.tencent.mobileqq.utils.VipUtils
= (void*)0
  [80]WebSecurityPluginV2$
com.tencent.mobileqq.webview.WebSecurityPluginV2$
= Lcom/tencent/mobileqq/webview/h$a;->callback(Landroid/os/Bundle;)V
  [81]PaiYiPaiHandler
com.tencent.mobileqq.paiyipai.PaiYiPaiHandler
= Lcom/tencent/mobileqq/paiyipai/PaiYiPaiHandler;->u4(Ljava/lang/String;)Z
  [82]

= Lcom/tencent/mobileqq/aio/input/h/k;->p(Lcom/tencent/mobileqq/aio/msg/AIOMsgItem;)V
  [83]

= Lcom/tencent/mobileqq/troop/enterEffect/TroopEnterEffectController;->o()V
  [84]TroopGuildChatPie
com.tencent.mobileqq.troop.guild.TroopGuildChatPie
= Lcom/tencent/mobileqq/troop/guild/TroopGuildChatPie;->R0()V
  [85]

= Lcom/tencent/mobileqq/filemanager/uftwrapper/b$d;->l()V
  [86]p
com.tencent.mobileqq.vas.p
= Lcom/tencent/mobileqq/vas/q;->a(Ljava/util/HashMap;Lcom/tencent/qqnt/kernel/nativeinterface/Contact;I)V
  [89]

= Lcom/tencent/mobileqq/emotionintegrate/m;->c()Z
  [90]

= Lcom/tencent/mobileqq/filebrowser/FileBrowserActivity$c;->onItemClick(Lcom/tencent/mobileqq/utils/ShareActionSheetBuilder$ActionSheetItem;Lcom/tencent/mobileqq/widget/share/ShareActionSheet;)V
  [93]

= (void*)0
  [94]

= (void*)0
  [96]AIOAvatarContentComponent
com.tencent.mobileqq.aio.msglist.holder.component.avatar.AIOAvatarContentComponent
= Lcom/tencent/mobileqq/aio/msglist/holder/component/avatar/AIOAvatarContentComponent;->g1()V
  [97]AIOPictureView
com.tencent.mobileqq.activity.aio.photo.AIOPictureView
= Lcom/tencent/mobileqq/richmediabrowser/view/AIOPictureView;->T0()V
  [98]AIOPictureView
com.tencent.mobileqq.activity.aio.photo.AIOPictureView
= Lcom/tencent/mobileqq/richmediabrowser/view/AIOPictureView;->j1(Z)V
  [99]TextItemBuilder
com.tencent.mobileqq.activity.aio.item.TextItemBuilder
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [100]TextMsgItem
com.tencent.mobileqq.aio.msg.TextMsgItem
= (void*)0
  [40001]ReplyNoAtHook
com/tencent/mobileqq/activity/aio/rebuild/input/d
  [40002]ChatWordsCount
nyn
  [40003]SortAtPanel.sessionInfoTroopUin
f
  [40004]RemovePlayTogether.ClockInEntryHelper
n
  [40005]QQMessageFacade
B2
  [40006]SimplifyQQSettingMe::MidContentName
f0
  [40007]RemovePlayTogether.TogetherControlHelper
q

**Comment by klxiaoniu** [comment]
非Pad正常吗？

**Comment by HumanMus1c** [comment]
> 非Pad正常吗？

一样的问题

**Comment by HoratioShaw** [comment]
> 非Pad正常吗？

pad没有新版侧栏，我在手机上打开禁止新样式侧栏之后也能复现
