### ISSUE TITLE
[功能请求] 希望增加修改群文件名的功能

### ISSUE THREAD

**Issue by Huaxidesu** [cinit/QAuxiliary#84]
### QQ(TIM)版本/QQ(TIM) Version

8.8.38

### 为什么你认为需要此功能

使用手机管理群文件，因为无法命名导致非常麻烦。还得请求管理或者是群友使用电脑来改名。发送文件的时候，如果没有及时改名，那么还必须删掉后重新改名发送。所以我认为这个功能是非常必要的。

### 联系到哪些已经存在的bug或者功能

None

### 具体功能需要/Specific features require

在群文件页面可以左滑增添重命名功能按钮
点击后可以自定义修改对应群文件名称

**Comment by keta1** [comment]
add in #06537f
