### ISSUE TITLE
[Bug] 1.4.8, QQ8.9.68 以图片方式打开闪照 失效

### ISSUE THREAD

**Issue by Misaka-Mikoto-Tech** [cinit/QAuxiliary#851]
### Steps to reproduce/复现步骤

打开 `以图片方式打开闪照`，但是闪照依旧5秒后被销毁

### Expected behaviour/预期行为

以图片打开

### Actual behaviour/实际行为

5秒后销毁

### XPosed Framework you used/你使用的XP框架

太极阴14.0.6

### QQ(TIM)版本/QQ(TIM) Version

QQ8.9.68

### Module Version/模块版本

QA1.4.8.r1940

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

[qa.log.txt](https://github.com/cinit/QAuxiliary/files/14626107/qa.log.txt)

看这个地址 https://github.com/cinit/QAuxiliary/issues/751#issuecomment-1953289783 提示已修复，但经过测试问题依旧

我在 /sdcard/Android/data/com.tencent.mobileqq/Tencent/MobileQQ/chatpic/chatimg 目录找到了这个文件，但是无法复制，adb pull 提示没有权限
```
adb pull /sdcard/Android/data/com.tencent.mobileqq/Tencent/MobileQQ/chatpic/chatimg/041/Cache_14c17e53fbe40041 1.jpg
adb: error: failed to copy '/sdcard/Android/data/com.tencent.mobileqq/Tencent/MobileQQ/chatpic/chatimg/041/Cache_14c17e53fbe40041' to '1.jpg': remote open failed: Permission denied
```

chmod失败
```
chmod: chmod 'Cache_14c17e53fbe40041' to 0777: Operation not permitted
```

所以QA能否增加一个修改文件权限，或者复制文件的功能？

**Comment by klxiaoniu** [comment]
没有日志？

**Comment by Misaka-Mikoto-Tech** [comment]
> 没有日志？

已添加

**Comment by N0v1ceccy** [comment]
> 没有日志？

如何解决呢

**Comment by Misaka-Mikoto-Tech** [comment]
我觉得在 `消息显示 ID 和时间` -> `点击显示消息详细信息` 这里把图片或者闪照的 url 给显示出来也行，用户点击自动打开浏览器显示，也可以接受，反正就是想要看或者下载这张图嘛

**Comment by HdShare** [comment]
QQ8.9.70+最新CI版r2109未复现
