### ISSUE TITLE
[BUG] 模块在某个build完全失效

### ISSUE THREAD

**Issue by ZoruaFox** [cinit/QAuxiliary#854]
### Steps to reproduce/复现步骤

1. Download newest CI😅
2. 安装并启用
3. 无法加载模块

### Expected behaviour/预期行为

模块正常加载

### Actual behaviour/实际行为

模块完全失效，设置菜单未出现模块设置项

### XPosed Framework you used/你使用的XP框架

太极·无极14.0.6.01302314-10609

### QQ(TIM)版本/QQ(TIM) Version

9.0.25.15655

### Module Version/模块版本

1.4.8.r1944.43d400a

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

无日志。

为什么是测试版，依然勾选第三个复选框：在QA1.4.8.r1943.1c330eb就无法加载模块，那时QQ版本是9.0.20正式版，再尝试了最近的Build和测试版QQ版本后均以失败告终，因此提出issue。

**Comment by cinit** [comment]
![image](https://github.com/cinit/QAuxiliary/assets/40174090/b235fc4f-7a69-4208-8a1c-6733a3e0402d)
如图，我这版可以正常生效，apk 来源于 CI, 请核对 QQ 版本和模块版本与你的是否一致。

**Comment by klxiaoniu** [comment]
@ZoruaFox 换框架试试？

**Comment by ZoruaFox** [comment]
![Collage_20240311_190254.jpg](https://github.com/cinit/QAuxiliary/assets/96456728/8767bd9c-2628-4cc6-80f2-96b2fd574c66)

一图流

已确认 QQ 版本和模块版本一致，因 QQ 内未出现菜单所以无法获取 QA 显示的 QQ 版本。太极“取消优化”、重装 QA 与太极、单独开启 QA 不加载其他模块等方法均未生效。

**Comment by ZoruaFox** [comment]
> @ZoruaFox 换框架试试？

华为除了还有什么可选框架吗（）

**Comment by cinit** [comment]
> > @ZoruaFox 换框架试试？
> 
> 华为除了太极还有什么可选框架吗（）

LSPatch

**Comment by cinit** [comment]
另外麻烦试一下 1942

**Comment by cinit** [comment]
另外问一下你用的安卓几？

**Comment by ZoruaFox** [comment]
> 另外问一下你用的安卓几？

设备信息里显示是**Android 12 Snow Cone (API31)**

**Comment by ZoruaFox** [comment]
> 另外麻烦试一下 1942

我之后拿另一个设备试试

<s>主力机不想试的原因是现在进不去，配置备份不出来（x）</s>

**Comment by ZoruaFox** [comment]
@cinit 证实在上述环境下1942可用，看来是从1943开始不能用的

**Comment by klxiaoniu** [comment]
昨日应已修复，如有疑问，可在此回复。此issue关闭。
