### ISSUE TITLE
[功能请求]  表情包下载功能

### ISSUE THREAD

**Issue by ie9ei** [cinit/QAuxiliary#862]
### QQ(TIM)版本/QQ(TIM) Version

9.0.25

### 为什么你认为需要此功能

qq移除了表情包下载功能，需要自行查找对应的文件进行下载

### 具体功能需要/Specific features require

长按表情包后显示下载选项/
点击表情包后以图片形式打开

**Comment by klxiaoniu** [comment]
已经有的功能
