### ISSUE TITLE
[Bug] 9.0大版本下，勾选强制平板模式后，没法成功生效，设备三星Fold5

### ISSUE THREAD

**Issue by lokiyao** [cinit/QAuxiliary#868]
### Steps to reproduce/复现步骤

1 现在强制平板模式是关闭的
![Screenshot_20240320_131852_QQ](https://github.com/cinit/QAuxiliary/assets/36297271/d62f8270-6688-4a51-a554-e552746f1930)
2 勾选平板模式 并重启QQ
![Screenshot_20240320_132022_QQ](https://github.com/cinit/QAuxiliary/assets/36297271/d79a7350-3707-4404-a24c-0330cbe809df)
3 尝试在iPhone上登陆QQ 被顶掉 不能双端一起登陆
![Screenshot_20240320_132126_QQ](https://github.com/cinit/QAuxiliary/assets/36297271/05cb1308-7cb6-4550-a22f-478b53f80def)

### Expected behaviour/预期行为

8.9大版本下，我一直都能双端登录，即iPhone和折叠屏一起登陆，信息同步，最近我账号都被云控了，被迫更新到9.0大版本，结果折叠屏那一端没法被认为是平板，会互相被顶掉

### Actual behaviour/实际行为

实际上，折叠屏Android那端不被认为是Android平板，Android和iPhone会被互相顶掉。
尝试过用QA内置的更改dpi和设备名，依旧无效
也尝试过用QStory打开平板模式，在共同开启和各自打开时也无效

### Xposed Framework you used/你使用的Xposed框架

我使用的是内置版本，无root

### Your Android version/你使用的安卓系统版本

Android15 Oneui6.0

### QQ(TIM)版本/QQ(TIM) Version

9.0.25

### Module Version/模块版本

1.4.9.r1955.ce0d86a(1955)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.9.r1955.ce0d86a
QQ9.0.25(5932)
PID: 27408, UID: 10639
cc.ioctl.hook.experimental.ForcePadMode
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by MicroCBer** [comment]
@lokiyao 无法复现

**Comment by hexadecimal233** [comment]
听说平板模式的逻辑给移到native代码里了，要hook native代码

**Comment by MicroCBer** [comment]
@hexadecimal233 我在 9.0.8 android&android 测试依然有效

**Comment by cinit** [comment]
这边测试了 QQ 9.0.25.15760 (5942) 和 QQ 9.0.30.15945 (6016) 该功能均有效 (Android 14, LSPosed, arm64-v8a)

**Comment by MeditaterC** [comment]
Vivo x fold 3 pro 成功复现，多qa和qq版本组合均无法激活平板模式，且同组合在s23u可正常激活平板模式

**Comment by lzy4ever** [comment]
我是iOS端QQ9.0.60，安卓QQ9.0.60注入1.51版qa插件，按照以下步骤实现iOS和安卓双端登录qq。

**Comment by HdShare** [comment]
试试最新CI-2321版本
