### ISSUE TITLE
开启Pangu.kt功能会导致机器人指令无法使用

### ISSUE THREAD

**Issue by bocchi810** [cinit/QAuxiliary#869]
### Steps to reproduce/复现步骤

输入带有 / + 中文 的机器人指令

### Expected behaviour/预期行为

/ 与中文之间不应该有空格

### Actual behaviour/实际行为

/ 与中文出现了空格

### Xposed Framework you used/你使用的Xposed框架

LSPosed

### Your Android version/你使用的安卓系统版本

13

### QQ(TIM)版本/QQ(TIM) Version

9.0.20

### Module Version/模块版本

1.4.9

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.9.r1950.d539521
QQ9.0.20(5844)
PID: 31034, UID: 10349
cc.microblock.hook.SendPangu
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by lliioollcn** [comment]
@bocchi810 6，今天nonebot群的
