### ISSUE TITLE
[功能请求] qq9移除频道首页小视频

### ISSUE THREAD

**Issue by sunforwork** [cinit/QAuxiliary#871]
### QQ(TIM)版本/QQ(TIM) Version

9.0.25(QQ)

### 为什么你认为需要此功能

想移除这些小视频。
![Uploading Screenshot_20240321-083303_QQ.png…]()
他们真的是太烦人了。
而且基本上都是软涩情

### 具体功能需要/Specific features require

移除这些小视频，最好能够还原为qq8.x频道内测时的界面

**Comment by sunforwork** [comment]
[![pFfAcBq.png](https://s21.ax1x.com/2024/03/21/pFfAcBq.png)](https://imgse.com/i/pFfAcBq)
[![pFfALE6.png](https://s21.ax1x.com/2024/03/21/pFfALE6.png)](https://imgse.com/i/pFfALE6)

全是软色情小视频

**Comment by HdShare** [comment]
可以使用最新CI版本，支持9.0.15~9.0.73还原频道旧版样式
