### ISSUE TITLE
[功能请求] 禁用QQ非官方应用分享验证

### ISSUE THREAD

**Issue by zzqsld** [cinit/QAuxiliary#873]
### QQ(TIM)版本/QQ(TIM) Version

8.9.35

### 为什么你认为需要此功能

我使用内置哔哩漫游模块的第三方客户端每次想分享视频给好友发现总是报错非官方应用错误码25201，复制链接只能显示标题不能显示封面，分享视频为图片也不行所以，有些修改过的软件也不能分享到QQ，我就想能不能禁用这个验证

### 具体功能需要/Specific features require

禁用QQ非官方应用验证

**Comment by klxiaoniu** [comment]
https://github.com/xihan123/SignHook

**Comment by hexadecimal233** [comment]
你是不是装了应用隐藏模块？
之前也遇到过把b站白名单就行
