### ISSUE TITLE
[Bug] 下载文件重定向失效

### ISSUE THREAD

**Issue by MoYuanCN** [cinit/QAuxiliary#876]
### Steps to reproduce/复现步骤

1.打开下载文件重定向
2.选择路径/storage/emulated/0/QQFiles/
3.重启QQ
4.下载文件

### Expected behaviour/预期行为

文件出现在/storage/emulated/0/QQFiles/

### Actual behaviour/实际行为

文件出现在/storage/emulated/0/Android/data/com.tencent.mobileqq/tencent/QQfile_recv/

### Xposed Framework you used/你使用的Xposed框架

Lspatch 0.6(403)

### Your Android version/你使用的安卓系统版本

13

### QQ(TIM)版本/QQ(TIM) Version

9.0.15.14970(56269)

### Module Version/模块版本

1.4.9.r1967.921ac1d(1967)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

无日志

**Comment by klxiaoniu** [comment]
https://github.com/cinit/QAuxiliary/issues/855#issuecomment-1999836936
