### ISSUE TITLE
[功能请求] tg表情同步至表情面板

### ISSUE THREAD

**Issue by by123456by** [cinit/QAuxiliary#877]
### QQ(TIM)版本/QQ(TIM) Version

9.0.25.15760

### 为什么你认为需要此功能

可以与原来表情包区分，可以更方便

### 联系到哪些已经存在的bug或者功能

tg表情包同步

### 具体功能需要/Specific features require

tg表情同步至表情面板而不是自带的表情包

**Comment by klxiaoniu** [comment]
@by123456by https://t.me/QToolCI

**Comment by by123456by** [comment]
> @by123456by https://t.me/QToolCI

不能用了

**Comment by klxiaoniu** [comment]
@by123456by ？

**Comment by by123456by** [comment]
> @by123456by ？

![image](https://github.com/cinit/QAuxiliary/assets/15666692/135237b7-a22e-4eb7-adb8-ad686ab96bd5)

**Comment by klxiaoniu** [comment]
已重新开放

**Comment by by123456by** [comment]
> 已重新开放

还是不能用啊，QA不是有同步表情吗，不能再同步到表情面板吗
