### ISSUE TITLE
[功能请求] 屏蔽QQ新功能消息表态

### ISSUE THREAD

**Issue by 233YUZI** [cinit/QAuxiliary#878]
### QQ(TIM)版本/QQ(TIM) Version

9.0.25.15760

### 为什么你认为需要此功能

![Screenshot_2024-03-27-09-18-42-060_com tencent mobileqq-edit](https://github.com/cinit/QAuxiliary/assets/69708373/89e9e8dd-1597-4e6d-aa6f-2ab776c5970b)
如图所示，菜单中的推荐表情常出现在群聊中，长按气泡弹出，但并不是所有群聊都会有，目前来看似乎和用户在群聊中活跃度有关

### 具体功能需要/Specific features require

添加一个净化开关或者在长按气泡菜单净化中加一个新选项

**Comment by lgc2333** [comment]
这是QQ的新功能消息表态

**Comment by HdShare** [comment]
尝试CI-2214版本
