### ISSUE TITLE
无法在MIUI的QQ多开上使用

### ISSUE THREAD

**Issue by HL-hollow** [cinit/QAuxiliary#879]
### Steps to reproduce/复现步骤

https://github.com/cinit/QAuxiliary/assets/106107869/6fdf9c77-ac90-433a-8525-19921d1efcb9

### Expected behaviour/预期行为

多开的QQ会被打开

### Actual behaviour/实际行为

点击多开的QQ后无事发生
主QQ可以正常打开并显示模块

### Xposed Framework you used/你使用的Xposed框架

1.9.3_mod(7244)

### Your Android version/你使用的安卓系统版本

12

### QQ(TIM)版本/QQ(TIM) Version

QQ9.0.0

### Module Version/模块版本

1.4.9.r1967.921ac1d(1967)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

没有日志，打都打不开
顺便一说，miui分身包名就是在包名原后加999
com.tencent.mobileqq:999

**Comment by klxiaoniu** [comment]
LSPosed中将QA添加到分身账户了吗？

**Comment by HL-hollow** [comment]
> LSPosed中将QA添加到分身账户了吗？

![Screenshot_2024-03-29-15-55-57-654_com.android.shell.jpg](https://github.com/cinit/QAuxiliary/assets/106107869/c88e5717-98a4-4de4-a837-313de769ebd9)

lsp没有显示QQ分身，不清楚MIUIQQ分身的原理

**Comment by klxiaoniu** [comment]
> > LSPosed中将QA添加到分身账户了吗？
> 
> ![Screenshot_2024-03-29-15-55-57-654_com.android.shell.jpg](https://private-user-images.githubusercontent.com/106107869/317989718-c88e5717-98a4-4de4-a837-313de769ebd9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2OTk5MzksIm5iZiI6MTcxMTY5OTYzOSwicGF0aCI6Ii8xMDYxMDc4NjkvMzE3OTg5NzE4LWM4OGU1NzE3LTk4YTQtNGRlNC1hODM3LTMxM2RlNzY5ZWJkOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOVQwODA3MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOWFhM2YyNjQwNjJjZWNlZDNkNjU4ZTA1MzAxMDkzODVlZDhlNzEyOTlhMzA4NzBkYWIyNzJlNzcyZDM5OGFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jJGSlOEBuUd4H6araBZCnDYRrkxUUuCZUGO2sMQyMII)
> 
> lsp没有显示QQ分身，不清楚MIUIQQ分身的原理

上一页顶部没有分身用户？MIUI分身基于多用户

**Comment by HL-hollow** [comment]
> > > LSPosed中将QA添加到分身账户了吗？
> > 
> > ![Screenshot_2024-03-29-15-55-57-654_com.android.shell.jpg](https://private-user-images.githubusercontent.com/106107869/317989718-c88e5717-98a4-4de4-a837-313de769ebd9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2OTk5MzksIm5iZiI6MTcxMTY5OTYzOSwicGF0aCI6Ii8xMDYxMDc4NjkvMzE3OTg5NzE4LWM4OGU1NzE3LTk4YTQtNGRlNC1hODM3LTMxM2RlNzY5ZWJkOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOVQwODA3MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOWFhM2YyNjQwNjJjZWNlZDNkNjU4ZTA1MzAxMDkzODVlZDhlNzEyOTlhMzA4NzBkYWIyNzJlNzcyZDM5OGFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jJGSlOEBuUd4H6araBZCnDYRrkxUUuCZUGO2sMQyMII)
> > 
> > lsp没有显示QQ分身，不清楚MIUIQQ分身的原理
> 
> 上一页顶部没有分身用户？MIUI分身基于多用户

问题解决了，要将模块安装到Lsp的XSpace![Screenshot_2024-03-29-20-04-35-704_com.android.shell.jpg](https://github.com/cinit/QAuxiliary/assets/106107869/954c643d-b769-4d1a-bc2f-560142351c57)
