### ISSUE TITLE
[功能请求] 给好友和群聊的通知分到不同的通知渠道

### ISSUE THREAD

**Issue by lgc2333** [cinit/QAuxiliary#880]
### QQ(TIM)版本/QQ(TIM) Version

9.0.30

### 为什么你认为需要此功能

<img height="720px" src="https://github.com/cinit/QAuxiliary/assets/59048777/23d83ccd-570d-4cc6-ba9e-d096acbdfea1" />

### 具体功能需要/Specific features require

RT

**Comment by klxiaoniu** [comment]
MessagingStyle消息通知功能

**Comment by Cryolitia** [comment]
![Screenshot_20240329-220408](https://github.com/cinit/QAuxiliary/assets/23723294/1701dff9-3b1c-4ea4-89b6-84c0e17350d7)
不是有吗

**Comment by lgc2333** [comment]
感谢（
因为之前没太用过MessagingStyle通知，觉得太挡了
