### ISSUE TITLE
QA设置打开白屏

### ISSUE THREAD

**Issue by maoyixuan** [cinit/QAuxiliary#882]
### Steps to reproduce/复现步骤

1.打开qa设置
2.白屏,未显示设置项

### Expected behaviour/预期行为

显示设置项

### Actual behaviour/实际行为

未显示设置项

### Xposed Framework you used/你使用的Xposed框架

OPatch

### Your Android version/你使用的安卓系统版本

9

### QQ(TIM)版本/QQ(TIM) Version

8.9.90

### Module Version/模块版本

1.4.9r1976

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

无法打开qa设置,提供不了日志。

**Comment by maoyixuan** [comment]
![Screenshot_2024-03-30-14-01-25-49.png](https://github.com/cinit/QAuxiliary/assets/110008296/45e0a373-3a1a-476a-9165-7f26e9565cc3)

**Comment by cinit** [comment]
你好，请回退到先前的 1.4.9.r1967.921ac1d 版本测试一下是否存在相同的白屏问题，你可以从 https://github.com/cinit/QAuxiliary/actions/runs/8421451738 或者 https://t.me/QAuxiliary_CI/5224 下载 1.4.9.r1967.921ac1d 版本。

**Comment by maoyixuan** [comment]
你好，替换到1.4.9.r1967.921ac1d版本未出现白屏问题。

**Comment by cinit** [comment]
@maoyixuan 麻烦再试一下 1.4.9.r1980.589b488 版本（可以从 https://github.com/cinit/QAuxiliary/actions/runs/8498746643 或者 https://t.me/QAuxiliary_CI/5259 下载）

**Comment by maoyixuan** [comment]
你好，1.4.9.r1980.589b488版本未出现白屏问题，谢谢大佬
