### ISSUE TITLE
保存不了自己发送的图片/表情

### ISSUE THREAD

**Issue by METEOR137** [cinit/QAuxiliary#884]
### Steps to reproduce/复现步骤

1.随便发个图片
2.长按使用表情面板保存功能

### Expected behaviour/预期行为

![S40331-16572092_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/127982712/d72cab3d-4ee3-49ae-b31d-af56df394677)
正常会出现表情预览并可以保存

### Actual behaviour/实际行为

一片空白，点击保存也是空白
![S40331-16571272_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/127982712/ca614d87-6fa7-49ed-bc77-4af03abcbc89)

### Xposed Framework you used/你使用的Xposed框架

lsposed1.9.2

### Your Android version/你使用的安卓系统版本

14

### QQ(TIM)版本/QQ(TIM) Version

9.0.25

### Module Version/模块版本

1.4.9.r1978.1c2e724-arm64

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.9.r1973.f2e2ec0
QQ9.0.25(5942)
PID: 28025, UID: 10201
cc.hicore.hook.stickerPanel.Hooker.StickerPanelEntryHooker
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by Seidko** [comment]
QQ 9.0.8.14755
QA 1.4.9.r1983.d0a34d3
遇到相同问题

**Comment by klxiaoniu** [comment]
fixed

**Comment by Seidko** [comment]
![Screenshot_2024-04-15-11-15-39-918_com tencent mobileqq-edit](https://github.com/cinit/QAuxiliary/assets/64234553/1c68d7eb-e489-41ef-9f62-61f32ab18d4f)
commit `8cd949`
QQ 9.0.8
问题依然存在

**Comment by Hicores** [comment]
是所有表情都无法显示还是仅有少数表情无法显示 @@ @Seidko

**Comment by Seidko** [comment]
@klxiaoniu 是大概一半的图片无法显示，别人的自己的都有，暂时没找到什么规律。并且图片完全没有在加载（打开面板期间网速没有变化）

**Comment by Hicores** [comment]
@Seidko tx好像突然加上rkey过期，现在早的晚的rkey全过期了，迟点再看看用其他方式下载

**Comment by Seidko** [comment]
那这个issue要不要reopen？

**Comment by molanp** [comment]
gocq对于每条消息均能获取rkey，能否参考相关代码？
```
[2024-04-26 22:15:43] [INFO]: 收到群 xxx 内 xxx 的消息: [CQ:image,file=446230008a86afd5bbd62d8b4b1a2b9b.image,subType=1,url=https://gchat.qpic.cn/download?xxxxxx;rkey=CAMSKMa3OFokB_Tlwk_cQPnG6SnFED9ERhySUC4Lx9BAGu_sgIwBm_EH60I&amp;spec=0] (973965207)
```
