### ISSUE TITLE
[Bug] ＋！plus无效

### ISSUE THREAD

**Issue by hgg566** [cinit/QAuxiliary#887]
### Steps to reproduce/复现步骤

1.打开此功能
2.日志未见异常
3.聊天界面没有出现＋1

### Expected behaviour/预期行为

正常情况应该会显示＋1

### Actual behaviour/实际行为

并没有显示＋1此功能没有运行

### Xposed Framework you used/你使用的Xposed框架

太极.阴内核129

### Your Android version/你使用的安卓系统版本

13

### QQ(TIM)版本/QQ(TIM) Version

9.0.30.15995(6038)

### Module Version/模块版本

1.4.9.r1949.d308dcf(1949)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.4.9.r1949.d308dcf
QQ9.0.30(6038)
PID: 15904, UID: 11356
cc.hicore.hook.RepeaterPlus
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by klxiaoniu** [comment]
无法复现

**Comment by pangXiongYuan** [comment]
你解决了吗，我也遇到这个问题了，点+1的时候QQ闪退了，再进来+1就没了

**Comment by hgg566** [comment]
> 你解决了吗，我也遇到这个问题了，点+1的时候QQ闪退了，再进来+1就没了

没有解决，还是用回老版本吧😭

**Comment by klxiaoniu** [comment]
更新CI版本

**Comment by hgg566** [comment]
> 更新CI版本
用的就是最新版本。
