### ISSUE TITLE
[功能请求] 一种移除TIM群/好友消息灰字提示“打开消息推送设置”的实现思路

### ISSUE THREAD

**Issue by MoonLeeeaf** [cinit/QAuxiliary#889]
### QQ(TIM)版本/QQ(TIM) Version

TIM 3.5.1

### 为什么你认为需要此功能

碍眼，影响心情
而且因为是“系统”消息，所以无法删除
本现象已经不止在群聊里复现，在2024.4.5 00：54的时候打开好友消息列表之后又冒出一个
如下
![Screenshot_2024-04-04-17-13-04-943_com tencent tim-edit](https://github.com/cinit/QAuxiliary/assets/150461955/ab1e6418-ba02-40e9-8d8a-084e3ffc8ca3)

### 具体功能需要/Specific features require

严重可疑方法 Laiyc;->g(Lcom/tencent/mobileqq/activity/aio/SessionInfo;)Z
查找到文本关键字 "PushNotificationManager" 
"pushSwitchGrayTipsInfo"

另外一个可疑方法 Laiyc;->b(Lcom/tencent/mobileqq/activity/aio/SessionInfo;I)V
查找到字符串关键字 "PushNotificationMan" "gray tip"
该方法不确定是否造成影响，但是灰字提示全都是没用的东西，因此也无所谓

理论上直接滞空这些方法即可，或者进一步分析后进行 DexKit

字符串搜索结果如下图，上述两个方法均在此进行方法调用追溯
![Screenshot_2024-04-04-17-23-00-756_bin mt plus-edit](https://github.com/cinit/QAuxiliary/assets/150461955/d15b6477-87df-404b-93c4-8475c20e9ac9)

**Comment by MicroCBer** [comment]
@MoonLeeeaf 你是真和消息推送杠上了

**Comment by MoonLeeeaf** [comment]
> @MoonLeeeaf 你是真和消息推送杠上了

@MicroCBer 没办法 天天骚扰我开这B玩意 又没有什么重要的消息我也不会去屏蔽群消息（

**Comment by MoonLeeeaf** [comment]
补充：这个问题也出现在好友消息中，但是上述的思路也许可以对此生效
![Screenshot_2024-04-05-00-35-46-646_com tencent tim-edit](https://github.com/cinit/QAuxiliary/assets/150461955/a7f9fba1-0d64-474d-b33c-4aeca0cb56d2)
