### ISSUE TITLE
创建群聊分组时QQ崩溃

### ISSUE THREAD

**Issue by JerryHan3** [cinit/QAuxiliary#891]
### Steps to reproduce/复现步骤

1. 激活QAuxiliary的“群聊分组”
2. 在首页加号菜单打开群聊分组管理面板
3. 添加分组，输入任意名称后确定

### Expected behaviour/预期行为

分组成功创建并可以正常管理群聊

### Actual behaviour/实际行为

QQ立刻崩溃退出

### Xposed Framework you used/你使用的Xposed框架

LSPosed

### Your Android version/你使用的安卓系统版本

13 安全更新2023年1月5日

### QQ(TIM)版本/QQ(TIM) Version

9.0.25.15760(5942)

### Module Version/模块版本

1.4.9.r1949.d308dcf(1949)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

功能日志未见异常：
1.4.9.r1949.d308dcf
QQ9.0.25(5942)
PID: 12945, UID: 10505
com.xiaoniu.hook.TroopGroupHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

QAuxiliary的完整调试日志见附加文件
[qauxiliary_debug.txt](https://github.com/cinit/QAuxiliary/files/14865582/qauxiliary_debug.txt)

**Comment by klxiaoniu** [comment]
更新CI版
