### ISSUE TITLE
[QQ8.8.80] 无法发送卡片消息

### ISSUE THREAD

**Issue by ObcbO** [cinit/QAuxiliary#9]
**QQ版本/QQ Version**

* QQ 8.8.80(2598)

**模块版本/Module Version**

* v1.1.2.r203.9f2e756

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* Lsposed 1.7.2 (6379) - Zygisk

**问题的具体描述/Detailed Description of the bug**

* 发送卡片时报错
* 有两种报错
![Screenshot_20220305-200558_QQ](https://user-images.githubusercontent.com/49872497/156882703-4bb36856-53fd-4908-9d6d-0dca7f8e0964.png)
![Screenshot_20220305-202127_QQ](https://user-images.githubusercontent.com/49872497/156882735-8e58c5b2-a655-4b79-8b93-2ff081149780.png)

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>
  [1]DialogUtil
com.tencent.mobileqq.utils.DialogUtil
= com.tencent.mobileqq.utils.DialogUtil
  [2]ChatActivityFacade
com.tencent.mobileqq.activity.ChatActivityFacade
= com.tencent.mobileqq.activity.ChatActivityFacade
  [3]FlashPicHelper
com.tencent.mobileqq.app.FlashPicHelper
= com.tencent.mobileqq.app.FlashPicHelper
  [4]BasePicDownloadProcessor
com.tencent.mobileqq.transfile.BasePicDownloadProcessor
= com.tencent.mobileqq.transfile.BasePicDownloadProcessor
  [5]ItemBuilderFactory
com.tencent.mobileqq.activity.aio.item.ItemBuilderFactory
= Lcom/tencent/mobileqq/activity/aio/core/msglist/item/ItemBuilderFactory;->a(Lcom/tencent/mobileqq/data/ChatMessage;Landroid/widget/BaseAdapter;)Lcom/tencent/mobileqq/activity/aio/ChatItemBuilder;
  [6]AIOUtils
com.tencent.mobileqq.activity.aio.AIOUtils
= com.tencent.mobileqq.activity.aio.AIOUtils
  [7]AbstractGalleryScene
com.tencent.common.galleryactivity.AbstractGalleryScene
= com.tencent.common.galleryactivity.AbstractGalleryScene
  [8]java.lang.IndexOutOfBoundsException: No class index for 8,max = 36
  [9]FavEmoConstant
com.tencent.mobileqq.emosm.favroaming.FavEmoConstant
= com.tencent.mobileqq.emosm.favroaming.FavEmoConstant
  [10]MessageRecordFactory
com.tencent.mobileqq.service.message.MessageRecordFactory
= com.tencent.mobileqq.service.message.MessageRecordFactory
  [11]ContactUtils
com.tencent.mobileqq.utils.ContactUtils
= com.tencent.mobileqq.utils.ContactUtils
  [12]java.lang.IndexOutOfBoundsException: No class index for 12,max = 36
  [13]ArkAppItemBubbleBuilder
com.tencent.mobileqq.activity.aio.item.ArkAppItemBubbleBuilder
= com.tencent.mobileqq.activity.aio.item.ArkAppItemBubbleBuilder
  [14]PngFrameUtil
com.tencent.mobileqq.magicface.drawable.PngFrameUtil
= com.tencent.mobileqq.magicface.drawable.PngFrameUtil
  [15]PicEmoticonInfo
com.tencent.mobileqq.emoticonview.PicEmoticonInfo
= com.tencent.mobileqq.emoticonview.PicEmoticonInfo
  [16]SimpleUIUtil
com.tencent.mobileqq.theme.SimpleUIUtil
= (void*)0
  [17]TroopGiftUtil
com.tencent.mobileqq.troop.utils.TroopGiftUtil
= com.tencent.mobileqq.troop.utils.TroopGiftUtil
  [18]TestStructMsg
com.tencent.mobileqq.structmsg.TestStructMsg
= com.tencent.mobileqq.structmsg.TestStructMsg
  [19]MsgNotification
cooperation.qzone.push.MsgNotification
= cooperation.qzone.push.MsgNotification
  [20]AppConstants
com.tencent.mobileqq.app.AppConstants
= com.tencent.mobileqq.app.AppConstants
  [21]CustomWidgetUtil
com.tencent.widget.CustomWidgetUtil
= com.tencent.widget.CustomWidgetUtil
  [22]MessageCache
com.tencent.mobileqq.service.message.MessageCache
= com.tencent.mobileqq.service.message.MessageCache
  [23]ScreenShotHelper
com.tencent.mobileqq.screendetect.ScreenShotHelper
= com.tencent.mobileqq.screendetect.ScreenShotHelper
  [24]TimeFormatterUtils
com.tencent.mobileqq.utils.TimeFormatterUtils
= com.tencent.mobileqq.utils.TimeFormatterUtils
  [25]TogetherControlHelper
com.tencent.mobileqq.aio.helper.TogetherControlHelper
= (void*)0
  [26]TroopAppShortcutDrawer
com.tencent.mobileqq.activity.aio.drawer.TroopAppShortcutDrawer
= com.tencent.mobileqq.activity.aio.drawer.TroopAppShortcutDrawer
  [27]IntimateInfoChatDrawer
com.tencent.mobileqq.activity.aio.drawer.IntimateInfoChatDrawer
= com.tencent.mobileqq.activity.aio.drawer.IntimateInfoChatDrawer
  [28]ZipUtils
com.tencent.biz.common.util.ZipUtils
= com.tencent.biz.common.util.ZipUtils
  [29]HttpDownloader
com.tencent.mobileqq.transfile.HttpDownloader
= com.tencent.mobileqq.transfile.HttpDownloader
  [30]MultiMsgManager
com.tencent.mobileqq.multimsg.MultiMsgManager
= com.tencent.mobileqq.multimsg.MultiMsgManager
  [31]ClockInEntryHelper
com.tencent.mobileqq.activity.aio.helper.ClockInEntryHelper
= com.tencent.mobileqq.activity.aio.helper.ClockInEntryHelper
  [32]CaptureUtil
com.tencent.mobileqq.richmedia.capture.util.CaptureUtil
= com.tencent.mobileqq.richmedia.capture.util.CaptureUtil
  [33]AvatarUtil
com.tencent.mobileqq.avatar.utils.AvatarUtil
= com.tencent.mobileqq.avatar.utils.AvatarUtil
  [34]FaceManager
com.tencent.mobileqq.app.face.FaceManager
= (void*)0
  [35]SmartDeviceProxyMgr
com.tencent.device.devicemgr.SmartDeviceProxyMgr
= com.tencent.device.devicemgr.SmartDeviceProxyMgr
  [36]AIOPictureView
com.tencent.mobileqq.richmediabrowser.view.AIOPictureView
= com.tencent.mobileqq.richmediabrowser.view.AIOPictureView
  [20001]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= Lcom/tencent/mobileqq/activity/aio/core/BaseChatPie;->m()V
  [20002]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= com.tencent.mobileqq.activity.aio.core.BaseChatPie
  [20003]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= com.tencent.mobileqq.activity.aio.core.BaseChatPie
  [20004]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= Lcom/tencent/mobileqq/activity/aio/helper/AIOMultiActionHelper;->a(Lcom/tencent/mobileqq/data/ChatMessage;)V
  [20005]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= com.tencent.mobileqq.activity.aio.core.BaseChatPie
  [20006]LeftSwipeReplyHelper
com.tencent.mobileqq.bubble.LeftSwipeReplyHelper
= com.tencent.mobileqq.bubble.LeftSwipeReplyHelper
  [20007]AtPanel
com.tencent.mobileqq.troop.quickat.ui.AtPanel
= com.tencent.mobileqq.troop.quickat.ui.AtPanel
  [20008]AtPanel
com.tencent.mobileqq.troop.quickat.ui.AtPanel
= com.tencent.mobileqq.troop.quickat.ui.AtPanel
  [20009]FriendChatPie
com.tencent.mobileqq.activity.aio.core.FriendChatPie
= Lcom/tencent/mobileqq/activity/aio/core/FriendChatPie;->bn()V
  [20010]ProfileCardUtil
com.tencent.mobileqq.util.ProfileCardUtil
= com.tencent.mobileqq.util.ProfileCardUtil
  [20011]VasProfileTemplateController
com.tencent.mobileqq.profilecard.vas.VasProfileTemplateController
= com.tencent.mobileqq.profilecard.vas.VasProfileTemplateController
  [20012]QQSettingMe
com.tencent.mobileqq.activity.QQSettingMe
= Lcom/tencent/mobileqq/activity/QQSettingMe;->a(Lcom/tencent/mobileqq/activity/qqsettingme/bean/QQSettingMeProfileBubbleBean;)V
  [20013]VipUtils
com.tencent.mobileqq.utils.VipUtils
= com.tencent.mobileqq.utils.VipUtils
  [20014]TroopChatPie
com.tencent.mobileqq.activity.aio.core.TroopChatPie
= com.tencent.mobileqq.activity.aio.core.TroopChatPie
  [20015]Conversation
com.tencent.mobileqq.activity.home.Conversation
= com.tencent.mobileqq.activity.home.Conversation
  [20016]QQSettingMe
com.tencent.mobileqq.activity.QQSettingMe
= com.tencent.mobileqq.activity.QQSettingMe
  [20017]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= com.tencent.mobileqq.activity.aio.core.BaseChatPie
  [40001]VasProfileAntiCrash
com.tencent.mobileqq.profilecard.vas.component.template.VasProfileTemplateComponent
  [40002]ReplyNoAtHook
__NOT_USED__
  [40003]ChatWordsCount
nmx
  [40004]SortAtPanel.sessionInfoTroopUin
b
  [40005]RemovePlayTogether.ClockInEntryHelper
f
  [40006]SimplifyQQSettingMe::MidContentName
S
  [40007]RemovePlayTogether.TogetherControlHelper
</code></pre></details>

**Comment by qwq233** [comment]
网络问题 无法连接到白名单服务器的问题
