### ISSUE TITLE
[功能请求] 强制QQ调用系统Emoji

### ISSUE THREAD

**Issue by Moe23333** [cinit/QAuxiliary#90]
### QQ(TIM)版本/QQ(TIM) Version

8.8.35

### 为什么你认为需要此功能

如题，QQ内置的远古版本Apple Emoji太丑了，在扁平化的UI中观感也比较割裂，于此同时QQ未内置的部分Emoji又是调用的系统样式，整体看上去十分不协调。

### 具体功能需要/Specific features require

强制调用系统Emoji

**Comment by Cryolitia** [comment]
~~我看你就是想发跨性别旗~~

**Comment by Moe23333** [comment]
> ~我看你就是想发跨性别旗~

被发现了惹（捂脸
