### ISSUE TITLE
[Bug] 老式消息菜单显示不完整

### ISSUE THREAD

**Issue by yyyyq97** [cinit/QAuxiliary#904]
### Steps to reproduce/复现步骤

打开显示不完整，关闭才能看到文字

### Expected behaviour/预期行为

隐藏表情展示文字

### Actual behaviour/实际行为

显示不全

### Xposed Framework you used/你使用的Xposed框架

LSPOSED

### Your Android version/你使用的安卓系统版本

安卓14

### QQ(TIM)版本/QQ(TIM) Version

9.0.17

### Module Version/模块版本

1.5.0.r2001.597cbf1

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

功能异常列表中没有异常

**Comment by yyyyq97** [comment]
![IMG_20240410_114608](https://github.com/cinit/QAuxiliary/assets/54359754/ab9a8187-5e02-4ef6-95b6-953f22935a54)

**Comment by yyyyq97** [comment]
![Uploading Screenshot_2024-04-10-11-51-50-313_com.tencent.mobileqq.jpg…]()

**Comment by yyyyq97** [comment]
![Screenshot_2024-04-10-11-51-50-313_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/54359754/e049e330-2aa3-4ed0-b060-50d05a5a16e0)

**Comment by HdShare** [comment]
尝试最新CI版
