### ISSUE TITLE
[功能请求] base.apk重命名遵守用户设定的大小写

### ISSUE THREAD

**Issue by LTHPKBTE** [cinit/QAuxiliary#906]
### QQ(TIM)版本/QQ(TIM) Version

QQ 8.9.85.12820(4766)

### 为什么你认为需要此功能

在大写apk后缀结尾的情况下QQ并不会将其重命名为.apk.1
![Screenshot_2024-04-12-08-55-44-261_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/53574505/1b34d51c-a092-489d-8d0a-6ee128fb3355)
![Screenshot_2024-04-12-08-55-57-287_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/53574505/e71f4a74-23a5-40f2-b289-5bce01bf6232)

### 具体功能需要/Specific features require

重命名base.apk功能遵守用户设定的大小写。
希望不要默认设定此功能以免腾讯封堵，给予用户提示即可

**Comment by klxiaoniu** [comment]
现在不能遵循设置的大写吗？

**Comment by LTHPKBTE** [comment]
> 现在不能遵循设置的大写吗？

目前，使用系统文件分享上传时 后缀是不遵守的 (可能和QQ处理文件的方式有关?)
![Screenshot_2024-04-12-10-05-28-790_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/53574505/1377714e-bb27-4413-842b-42dc1817d6af)
![Screenshot_2024-04-12-10-06-23-536_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/53574505/f0283d5d-9fa2-4cda-9a3c-3ecaa5204d25)

**Comment by klxiaoniu** [comment]
> > 现在不能遵循设置的大写吗？
> 
> 目前，使用系统文件分享上传时 后缀是不遵守的 (可能和QQ处理文件的方式有关?) ![Screenshot_2024-04-12-10-05-28-790_com tencent mobileqq](https://private-user-images.githubusercontent.com/53574505/321832969-1377714e-bb27-4413-842b-42dc1817d6af.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4ODgwMTEsIm5iZiI6MTcxMjg4NzcxMSwicGF0aCI6Ii81MzU3NDUwNS8zMjE4MzI5NjktMTM3NzcxNGUtYmIyNy00NDEzLTg0MmItNDJkYzE4MTdkNmFmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDAyMDgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyNjZjNzU5ZDZhZjFlMTE0YWQ4NjE2NTdhODYxODVmOTJjMWU3NDJkYzFiODQyYzA0OWVlM2NkYTViNzExZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uo6TtJtDmCaYZyoT5_e-oT0aKKLSXQfvAnCRUxBbajI) ![Screenshot_2024-04-12-10-06-23-536_com tencent mobileqq](https://private-user-images.githubusercontent.com/53574505/321832999-f0283d5d-9fa2-4cda-9a3c-3ecaa5204d25.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4ODgwMTEsIm5iZiI6MTcxMjg4NzcxMSwicGF0aCI6Ii81MzU3NDUwNS8zMjE4MzI5OTktZjAyODNkNWQtOWZhMi00Y2RhLTlhM2MtM2VjYWE1MjA0ZDI1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDAyMDgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjZGJkZjAwZWM2OTgxYTc2ZGE0ZjczZjI3MTI3ZDU0ZTVkOWQ1OTY0MTgwZjBjYzAzYjdhMjYxZTk3ZWYzMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e_p0KUY9QkCf4G1DKIz5HKC-SAk12ZB_PjaIznELQws)

系统分享当然不遵守，base.apk这功能就是处理从QQ的加号里选择App分享的

**Comment by LTHPKBTE** [comment]
唔，确实分享不行
因为我的桌面也是第三方的，从那边分享会自带重命名 我以为是QA的来着
