### ISSUE TITLE
[功能请求] 为消息 +1 Plus 显示在长按菜单时添加一个图标

### ISSUE THREAD

**Issue by Dian-Jiao** [cinit/QAuxiliary#908]
### QQ(TIM)版本/QQ(TIM) Version

9.0.15.14970（5626）

### 为什么你认为需要此功能

QQ 自带的表情 +1 都有图标了，模块可以直接去用 QQ 自带的 +1 图标
![表情自带的+1](https://github.com/cinit/QAuxiliary/assets/59251784/93b130bd-9e04-40aa-8b13-205e2b8270fb)
![没有+1图标](https://github.com/cinit/QAuxiliary/assets/59251784/8b37d080-53c3-4668-85bf-a1a290b39085)

没有 +1 图标真的好丑，看着真的好难看好难看，呜，强迫症受不了了

### 具体功能需要/Specific features require

`\app\src\main\java\io\github\qauxv\util\CustomMenu.kt` 中，尝试为 NT QQ 的长按菜单整一下图标？
然后给 `\app\src\main\java\cc\hicore\hook\RepeaterPlus.java` 添加一下 +1 时的图标w

感谢感谢ww

**Comment by HdShare** [comment]
使用最新CI-r2150版
