### ISSUE TITLE
防撤回失效

### ISSUE THREAD

**Issue by xyzjbr** [cinit/QAuxiliary#910]
### Steps to reproduce/复现步骤

打开防撤回

### Expected behaviour/预期行为

防止信息撤回

### Actual behaviour/实际行为

大部分消息都会显示没收到

### Xposed Framework you used/你使用的Xposed框架

太极

### Your Android version/你使用的安卓系统版本

安卓11

### QQ(TIM)版本/QQ(TIM) Version

8.9.78

### Module Version/模块版本

1.5.0

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [x] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.5.0.r2001.597cbf1
QQ8.9.78(4548)
PID: 6686, UID: 10585
cc.ioctl.hook.msg.RevokeMsgHook
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by klxiaoniu** [comment]
这是正常的，个人推断和QQ的消息机制有关，在后台不会拉取每一条消息，因此导致一些撤回的消息并没有被收到。
