### ISSUE TITLE
卡片消息失效

### ISSUE THREAD

**Issue by xyzjbr** [cinit/QAuxiliary#912]
### Steps to reproduce/复现步骤

1.打开发送卡片消息
2.长按发送卡片消息

### Expected behaviour/预期行为

成功发送卡片消息

### Actual behaviour/实际行为

输入框中的卡片代码消失，没有发出任何消息，没有任何提示

### Xposed Framework you used/你使用的Xposed框架

太极

### Your Android version/你使用的安卓系统版本

11

### QQ(TIM)版本/QQ(TIM) Version

9.0.30

### Module Version/模块版本

1.5.0

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.5.0.r2001.597cbf1
QQ9.0.30(6038)
PID: 3271, UID: 10615
cc.ioctl.hook.experimental.CardMsgSender
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by klxiaoniu** [comment]
此非QA问题，跟相关验证机制有关，不在我们的讨论范围。
