### ISSUE TITLE
[功能请求] 能不能支持lspatch

### ISSUE THREAD

**Issue by umq34p99a3v8uqrpq984t** [cinit/QAuxiliary#913]
### QQ(TIM)版本/QQ(TIM) Version

9.0.30

### 为什么你认为需要此功能

手机没办法root😅

### 具体功能需要/Specific features require

支持lspatch 谢谢

**Comment by duzhaokun123** [comment]
怎么就不支持 lspatch 了

看见未激活就不支持吗
