### ISSUE TITLE
通知设置中的MessagingStyle通知无法使用,开启无效果,关机重启之后也无效果

### ISSUE THREAD

**Issue by fengguan9527** [cinit/QAuxiliary#914]
### Steps to reproduce/复现步骤

打开MessagingStyle通知
关闭qq重新打开
无效果

### Expected behaviour/预期行为

以前有效果(2022的时候)现在又不知道为什么没效果了

### Actual behaviour/实际行为

MessagingStyle通知无效果不可使用

### Xposed Framework you used/你使用的Xposed框架

zygisk 1.9.2

### Your Android version/你使用的安卓系统版本

13

### QQ(TIM)版本/QQ(TIM) Version

9.0.30

### Module Version/模块版本

1.5.0.r2004.04f78c4(2004)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.5.0.r2004.04f78c4
QQ9.0.30(6038)
PID: 14308, UID: 10243
moe.zapic.hook.MessagingStyleNotification
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by klxiaoniu** [comment]
@fengguan9527 支持展示多条消息内容的就是messagingstyle通知，只不过通知栏回复没支持
