### ISSUE TITLE
[Bug] 自定义聊天界面时间格式失效

### ISSUE THREAD

**Issue by anxiaoxuan-hh** [cinit/QAuxiliary#916]
### Steps to reproduce/复现步骤

1.开关正常打开
2.聊天界面应显示详细时间到秒

### Expected behaviour/预期行为

聊天界面按设置的格式应该显示年月日时分秒

### Actual behaviour/实际行为

只显示时分

### Xposed Framework you used/你使用的Xposed框架

lspatch

### Your Android version/你使用的安卓系统版本

12

### QQ(TIM)版本/QQ(TIM) Version

9.0.35.16270(6148)

### Module Version/模块版本

1.5.0.r2009.a91dbba(2009)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.5.0.r2009.a91dbba
QQ9.0.35(6148)
PID: 24441, UID: 11565
cc.ioctl.hook.chat.CustomMsgTimeFormat
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by anxiaoxuan-hh** [comment]
没有 我设置的格式是yyyy-MM-dd HH:mm:ss 但实际显示的是默认的HH:mm格式

**Comment by duzhaokun123** [comment]
fix https://github.com/cinit/QAuxiliary/commit/227553a4554dfca40f493bcfeed0a7b71eb2984e
