### ISSUE TITLE
[Bug] 表情面板失效

### ISSUE THREAD

**Issue by ZoruaFox** [cinit/QAuxiliary#918]
### Steps to reproduce/复现步骤

1. 在9.0.35.16270(6148)开启表情面板
2. 长按图片选择保存到面板
3. 图片获取异常，无法保存

### Expected behaviour/预期行为

WORK AS INTENDED

### Actual behaviour/实际行为

NOT TOTALLY WORKING

### Xposed Framework you used/你使用的Xposed框架

太极 14.0.6.01302314-10764（无极）

### Your Android version/你使用的安卓系统版本

Harmony OS 4.0.0.135(C00E116R7P6patch01)

### QQ(TIM)版本/QQ(TIM) Version

9.0.35.16270(6148)

### Module Version/模块版本

1.5.0.r2011.5214bb7(2011)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

![Screenshot_20240419_220203_com tencent mobileqq_edit_8849270326773](https://github.com/cinit/QAuxiliary/assets/96456728/c76cf244-7539-44ba-85d6-e117a1e84ca1)

日志无异常。

我清楚这个功能获取表情有延迟，我是在长时间等待+获取不同表情均失效后才认定为bug。

附知本功能开发者（功能字段判断）： @Hicores

**Comment by klxiaoniu** [comment]
https://github.com/cinit/QAuxiliary/issues/884#issuecomment-2060160851

**Comment by ZoruaFox** [comment]
> https://github.com/cinit/QAuxiliary/issues/884#issuecomment-2060160851

看到了。

可以保留issue到相关问题解决

**Comment by ZoruaFox** [comment]
> 尝试最新CI

一部分图片现在能被获取到了，仍有相当数量的图片无法保存
