### ISSUE TITLE
对移动端图片选择器的修正以重新支持图文混排

### ISSUE THREAD

**Issue by LittleJiu-furry** [cinit/QAuxiliary#923]
### QQ(TIM)版本/QQ(TIM) Version

9.0.35

### 为什么你认为需要此功能

旧版本的图片选择器可以不打开额外的占据全屏的图片选择器并选择图片发送，与此同时支持图文混排
新版本更新后强制使用占据全屏的图片选择器，图文混排失效（占据全屏的图片选择器只能选择图片而后单独发送，不支持图文混排）
在本就支持图文混排的情况下移动端却因为前台交互的问题而无法做到，非常影响使用

### 具体功能需要/Specific features require

两种方案
1、因为他是直接打开占据全屏的图片选择器，而不是旧版本的只占据功能区大小的图片选择器，考虑可能只是前端做了交互限制，因此可以尝试强制启用旧版本的图片选择器

2、因为选择的图片终归要到图片的本机存储路径，可以考虑再选择图片后将发送按钮修改为选择按钮，之后按照旧版本图文混排消息的发送逻辑来发送消息以支持图文混排

**Comment by klxiaoniu** [comment]
@LittleJiu-furry 1. 该功能已经有了。还原图片选择面板。
2. 全屏的图片选择器在选择图片的大图展示时上划也能够附加文字内容、

**Comment by LittleJiu-furry** [comment]
> @LittleJiu-furry 1. 该功能已经有了。还原图片选择面板。
> 2. 全屏的图片选择器在选择图片的大图展示时上划也能够附加文字内容、

你好，请问“还原图片选择面板”的功能是哪个构建版本，我目前在用是release中发布的，版本号为1.5.0.r2001.597cbf1(2001)
