### ISSUE TITLE
[功能请求] 建议加个免费使用qq装扮的功能

### ISSUE THREAD

**Issue by aaa-qwq-123** [cinit/QAuxiliary#932]
### QQ(TIM)版本/QQ(TIM) Version

9.0.30.15995(6038)

### 为什么你认为需要此功能

不想付钱

### 具体功能需要/Specific features require

解锁‘我的装扮’中的主题

**Comment by Hicores** [comment]
可刑可拷

**Comment by xici** [comment]
README不看？不想付钱这理由也太逆天了🤣
