### ISSUE TITLE
[Bug] 防撤回可能导致聊天记录损坏丢失聊天记录

### ISSUE THREAD

**Issue by ARKSAVE** [cinit/QAuxiliary#937]
### Steps to reproduce/复现步骤

无具体重现方法

### Expected behaviour/预期行为

聊天记录不会损坏

### Actual behaviour/实际行为

聊天记录损坏，QQ提示修复聊天记录并重启，重启后部分聊天记录丢失

### Xposed Framework you used/你使用的Xposed框架

lspatch

### Your Android version/你使用的安卓系统版本

安卓13

### QQ(TIM)版本/QQ(TIM) Version

QQ9.0.30

### Module Version/模块版本

1.5.0.r2025.669ce7 c(2025)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

无法尝试重现
  [0]PicElement
com.tencent.mobileqq.aio.msg.AIOMsgElementType.PicElement
= Lcom/tencent/qqnt/aio/v/a/a$e;->toString()Ljava/lang/String;
  [5]AbstractQQCustomMenuItem
com.tencent.qqnt.aio.menu.ui.AbstractQQCustomMenuItem
= Lcom/tencent/qqnt/aio/menu/ui/k;->toString()Ljava/lang/String;
  [7]AIOPictureView
com.tencent.mobileqq.richmediabrowser.view.AIOPictureView
= com.tencent.mobileqq.richmediabrowser.view.AIOPictureView
  [8]AIOUtils
com.tencent.mobileqq.activity.aio.AIOUtils
= Lcom/tencent/mobileqq/activity/aio/v;->R(Lcom/tencent/mobileqq/app/QQAppInterface;Lcom/tencent/mobileqq/app/BaseActivity;Landroid/content/Intent;)I
  [9]AbstractGalleryScene
com.tencent.common.galleryactivity.AbstractGalleryScene
= (void*)0
  [10]AppConstants
com.tencent.mobileqq.app.AppConstants
= com.tencent.mobileqq.app.AppConstants
  [11]ArkAppItemBubbleBuilder
com.tencent.mobileqq.activity.aio.item.ArkAppItemBubbleBuilder
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [12]AvatarUtil
com.tencent.mobileqq.avatar.utils.AvatarUtil
= (void*)0
  [13]BasePicDownloadProcessor
com.tencent.mobileqq.transfile.BasePicDownloadProcessor
= com.tencent.mobileqq.transfile.BasePicDownloadProcessor
  [14]CustomWidgetUtil
com.tencent.widget.CustomWidgetUtil
= (void*)0
  [15]DialogUtil
com.tencent.mobileqq.utils.DialogUtil
= com.tencent.mobileqq.utils.DialogUtil
  [16]ChatActivityFacade
com.tencent.mobileqq.activity.ChatActivityFacade
= com.tencent.mobileqq.activity.ChatActivityFacade
  [17]FaceManager
com.tencent.mobileqq.app.face.FaceManager
= (void*)0
  [18]FavEmoConstant
com.tencent.mobileqq.emosm.favroaming.FavEmoConstant
= com.tencent.mobileqq.emosm.favroaming.FavEmoConstant
  [19]FlashPicHelper
com.tencent.mobileqq.app.FlashPicHelper
= Lcom/tencent/mobileqq/app/am;->e(Lcom/tencent/mobileqq/data/MessageRecord;Z)V
  [20]FrameControllerInjectImpl
com.tencent.mobileqq.activity.framebusiness.controllerinject.FrameControllerInjectImpl
= com.tencent.mobileqq.activity.framebusiness.controllerinject.FrameControllerInjectImpl
  [21]GalleryBaseScene
com.tencent.mobileqq.gallery.view.GalleryBaseScene
= (void*)0
  [22]TroopAppShortcutDrawer
com.tencent.mobileqq.activity.aio.drawer.TroopAppShortcutDrawer
= com.tencent.mobileqq.activity.aio.drawer.TroopAppShortcutDrawer
  [23]GuildArkHelper
com.tencent.mobileqq.guild.chatpie.helper.GuildArkHelper
= (void*)0
  [24]GuildHelperProvider
com.tencent.mobileqq.guild.chatpie.GuildHelperProvider
= (void*)0
  [25]HttpDownloader
com.tencent.mobileqq.transfile.HttpDownloader
= com.tencent.mobileqq.transfile.HttpDownloader
  [26]IntimateInfoChatDrawer
com.tencent.mobileqq.activity.aio.drawer.IntimateInfoChatDrawer
= (void*)0
  [27]ItemBuilderFactory
com.tencent.mobileqq.activity.aio.item.ItemBuilderFactory
= Lcom/tencent/mobileqq/activity/aio/core/msglist/a/a;->b(Lcom/tencent/mobileqq/data/ChatMessage;Landroid/widget/BaseAdapter;)Lcom/tencent/mobileqq/activity/aio/ah;
  [28]MessageCache
com.tencent.mobileqq.service.message.MessageCache
= Lcom/tencent/mobileqq/service/h/e;-><clinit>()V
  [29]MessageRecordFactory
com.tencent.mobileqq.service.message.MessageRecordFactory
= Lcom/tencent/mobileqq/service/h/r;->I(Lcom/tencent/common/app/AppInterface;Lcom/tencent/mobileqq/data/MessageRecord;Ljava/lang/String;Ljava/lang/String;I)V
  [30]MultiMsgManager
com.tencent.mobileqq.multimsg.MultiMsgManager
= com.tencent.mobileqq.multimsg.MultiMsgManager
  [31]OnlinePushPbPushTransMsg
com.tencent.mobileqq.app.handler.receivesuccess.OnlinePushPbPushTransMsg
= (void*)0
  [32]PicEmoticonInfo
com.tencent.mobileqq.emoticonview.PicEmoticonInfo
= com.tencent.mobileqq.emoticonview.PicEmoticonInfo
  [33]PngFrameUtil
com.tencent.mobileqq.magicface.drawable.PngFrameUtil
= (void*)0
  [34]PopOutEmoticonUtil
com.tencent.mobileqq.popanim.util.PopOutEmoticonUtil
= Lcom/tencent/mobileqq/popanim/a/a;->f(ILcom/tencent/mobileqq/emoticonview/EmoticonInfo;I)Z
  [35]MsgNotification
cooperation.qzone.push.MsgNotification
= cooperation.qzone.push.MsgNotification
  [36]ReplyMsgSender
com.tencent.mobileqq.replymsg.ReplyMsgSender
= (void*)0
  [37]ReplyMsgUtils
com.tencent.mobileqq.activity.aio.reply.ReplyMsgUtils
= (void*)0
  [38]ScreenShotHelper
com.tencent.mobileqq.screendetect.ScreenShotHelper
= com.tencent.mobileqq.screendetect.ScreenShotHelper
  [39]SimpleUIUtil
com.tencent.mobileqq.theme.SimpleUIUtil
= (void*)0
  [40]SystemMessageProcessor
com.tencent.mobileqq.app.message.SystemMessageProcessor
= (void*)0
  [41]TestStructMsg
com.tencent.mobileqq.structmsg.TestStructMsg
= (void*)0
  [42]TimeFormatterUtils
com.tencent.mobileqq.utils.TimeFormatterUtils
= (void*)0
  [43]TroopGiftUtil
com.tencent.mobileqq.troop.utils.TroopGiftUtil
= (void*)0
  [44]ZipUtils
com.tencent.biz.common.util.ZipUtils
= com.tencent.biz.common.util.ZipUtils
  [48]DefaultFileModel
com.tencent.mobileqq.filemanager.fileviewer.model.DefaultFileModel
= (void*)0
  [50]EmotcationConstants
com.tencent.mobileqq.text.EmotcationConstants
= com.tencent.mobileqq.text.EmotcationConstants
  [51]ForwardSendPicUtil
com.tencent.mobileqq.utils.ForwardSendPicUtil
= com.tencent.mobileqq.utils.ForwardSendPicUtil
  [54]toBottomIntent
com.tencent.mobileqq.aio.input.multiselect.c.toBottomIntent
= Lcom/tencent/mobileqq/aio/input/multiselect/c$h;->toString()Ljava/lang/String;
  [93]LoadPropertiesUtils
com.tencent.smtt.utils.LoadPropertiesUtils
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [94]activity
com.tencent.qqnt.aio.activity
= Lcom/tencent/qqnt/aio/activity/AIODelegate$d;->a()V
  [98]

= (void*)0
  [99]

= (void*)0
  [102]

= Lcom/tencent/mobileqq/activity/qqsettingme/config/a;-><init>()V
  [1]sendMsg
com.tencent.mobileqq.aio.input.sendmsg.AIOSendMsgVMDelegate.sendMsg
= (void*)0
  [2]AIOTextElementCtor
com.tencent.mobileqq.aio.msg.AIOMsgElement.AIOTextElementCtor
= (void*)0
  [3]AIO_Create_QQNT
AIO_Create_QQNT
= Lcom/tencent/aio/base/chat/ChatPie;->g(Landroid/os/Bundle;Lcom/tencent/aio/main/fragment/ChatFragment;Lkotlin/jvm/functions/Function1;)V
  [4]

= (void*)0
  [6]BaseListenTogetherPanel
com.tencent.mobileqq.listentogether.ui.BaseListenTogetherPanel
= Lcom/tencent/mobileqq/listentogether/ui/BaseListenTogetherPanel;->Q(Lcom/tencent/mobileqq/listentogether/ListenTogetherSession;)V
  [45]ChatPanel_InitPanel_QQNT
ChatPanel_InitPanel_QQNT
= Lcom/tencent/mobileqq/aio/input/j/b;->B()V
  [46]

= (void*)0
  [47]

= (void*)0
  [49]

= (void*)0
  [52]NotifyIdManager
com.tencent.util.notification.NotifyIdManager
= Lcom/tencent/util/notification/d;->i(Ljava/lang/String;Lcom/tencent/imcore/message/Message;)Ljava/lang/String;
  [53]Guild_Emo_Btn_Create_QQNT
Guild_Emo_Btn_Create_QQNT
= Lcom/tencent/y/a/d/a/c;->onCreateView(Lcom/tencent/p0/a/c/a;)Landroid/view/View;
  [55]AtPanel
com.tencent.mobileqq.troop.quickat.ui.AtPanel
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [56]AtPanel
com.tencent.mobileqq.troop.quickat.ui.AtPanel
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [57]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= com.tencent.mobileqq.activity.aio.core.BaseChatPie
  [58]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= Lcom/tencent/mobileqq/activity/aio/helper/AIOMultiActionHelper;->w(Lcom/tencent/mobileqq/data/ChatMessage;)V
  [59]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= com.tencent.mobileqq.activity.aio.core.BaseChatPie
  [60]BaseChatPie
com.tencent.mobileqq.activity.aio.core.BaseChatPie
= com.tencent.mobileqq.activity.aio.core.BaseChatPie
  [61]ChatActivityFacade
com.tencent.mobileqq.activity.ChatActivityFacade
= Lcom/tencent/mobileqq/activity/ChatActivityFacade;->j1(Lcom/tencent/mobileqq/app/QQAppInterface;Landroid/content/Context;Lcom/tencent/mobileqq/activity/aio/ab;Ljava/lang/String;Ljava/util/ArrayList;Lcom/tencent/mobileqq/activity/ChatActivityFacade$d;)[J
  [62]ContactUtils
com.tencent.mobileqq.utils.ContactUtils
= Lcom/tencent/mobileqq/utils/ContactUtils;->f(Lmqq/app/AppRuntime;Ljava/lang/String;Z)Ljava/lang/String;
  [63]ContactUtils
com.tencent.mobileqq.utils.ContactUtils
= Lcom/tencent/mobileqq/utils/ContactUtils;->m(Lcom/tencent/common/app/business/BaseQQAppInterface;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
  [64]Conversation
com.tencent.mobileqq.activity.home.Conversation
= Lcom/tencent/mobileqq/activity/home/Conversation;->onCreate()V
  [65]CustomWidgetUtil
com.tencent.widget.CustomWidgetUtil
= (void*)0
  [66]FriendChatPie
com.tencent.mobileqq.activity.aio.core.FriendChatPie
= com.tencent.mobileqq.activity.aio.core.FriendChatPie
  [67]FriendsStatusUtil
com.tencent.mobileqq.app.utils.FriendsStatusUtil
= Lcom/tencent/mobileqq/app/utils/FriendsStatusUtil;->k(Lcom/tencent/mobileqq/app/QQAppInterface;Ljava/lang/String;I)Z
  [68]LeftSwipeReplyHelper
com.tencent.mobileqq.bubble.LeftSwipeReplyHelper
= Lcom/tencent/mobileqq/bubble/i;->M()V
  [69]PadUtil
com.tencent.common.config.PadUtil
= (void*)0
  [70]PhotoListPanel
com.tencent.mobileqq.activity.aio.photo.PhotoListPanel
= com.tencent.mobileqq.activity.aio.photo.PhotoListPanel
  [71]ProfileCardUtil
com.tencent.mobileqq.util.ProfileCardUtil
= com.tencent.mobileqq.util.ProfileCardUtil
  [72]QQSettingMe
com.tencent.mobileqq.activity.QQSettingMe
= (void*)0
  [73]QQSettingMe
com.tencent.mobileqq.activity.QQSettingMe
= (void*)0
  [74]

= (void*)0
  [75]Scene
com.tencent.mobileqq.troopAddFrd.Scene
= Lcom/tencent/mobileqq/troopAddFrd/e;->f()I
  [76]TroopAppShortcutBarHelper
com.tencent.mobileqq.activity.aio.helper.TroopAppShortcutBarHelper
= Lcom/tencent/mobileqq/activity/aio/helper/cu;->F()V
  [77]TroopChatPie
com.tencent.mobileqq.activity.aio.core.TroopChatPie
= com.tencent.mobileqq.activity.aio.core.TroopChatPie
  [78]VasProfileTemplateController
com.tencent.mobileqq.profilecard.vas.VasProfileTemplateController
= com.tencent.mobileqq.profilecard.vas.VasProfileTemplateController
  [79]VipUtils
com.tencent.mobileqq.utils.VipUtils
= (void*)0
  [80]VipUtils
com.tencent.mobileqq.utils.VipUtils
= (void*)0
  [81]WebSecurityPluginV2$
com.tencent.mobileqq.webview.WebSecurityPluginV2$
= Lcom/tencent/mobileqq/webview/h$a;->callback(Landroid/os/Bundle;)V
  [82]PaiYiPaiHandler
com.tencent.mobileqq.paiyipai.PaiYiPaiHandler
= Lcom/tencent/mobileqq/paiyipai/PaiYiPaiHandler;->h4(Ljava/lang/String;)Z
  [83]PushNotificationManager
com.tencent.mobileqq.managers.PushNotificationManager
= com.tencent.mobileqq.managers.PushNotificationManager
  [84]QQValuePagView
com.tencent.mobileqq.vas.qqvaluecard.view.QQValuePagView
= com.tencent.mobileqq.vas.qqvaluecard.view.QQValuePagView
  [85]QZoneFeedxTopEntranceManagerView
com.qzone.reborn.feedx.widget.entrance.QZoneFeedxTopEntranceManagerView
= com.qzone.reborn.feedx.widget.entrance.QZoneFeedxTopEntranceManagerView
  [86]

= (void*)0
  [87]

= Lcom/tencent/mobileqq/aio/input/i/k;->p(Lcom/tencent/mobileqq/aio/msg/AIOMsgItem;)V
  [88]

= Lcom/tencent/mobileqq/troop/enterEffect/TroopEnterEffectController;->r()V
  [89]TroopGuildChatPie
com.tencent.mobileqq.troop.guild.TroopGuildChatPie
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [90]

= Lcom/tencent/mobileqq/troop/troopcard/api/impl/b;->a()Z
  [91]

= Lcom/tencent/mobileqq/filemanager/uftwrapper/b$d;->l()V
  [92]p
com.tencent.mobileqq.vas.p
= Lcom/tencent/mobileqq/vas/q;->a(Ljava/util/HashMap;Lcom/tencent/qqnt/kernel/nativeinterface/Contact;I)V
  [95]AIO_Create_QQNT
AIO_Create_QQNT
= Lcom/tencent/aio/base/chat/ChatPie;->h()V
  [96]

= (void*)0
  [97]

= (void*)0
  [100]

= Lcom/tencent/mobileqq/utils/cs;->f()Z
  [101]

= Lcom/tencent/mobileqq/utils/cs;->g()Z
  [103]AIOAvatarContentComponent
com.tencent.mobileqq.aio.msglist.holder.component.avatar.AIOAvatarContentComponent
= Lcom/tencent/mobileqq/aio/msglist/holder/component/avatar/AIOAvatarContentComponent;->h1()V
  [104]AIOPictureView
com.tencent.mobileqq.activity.aio.photo.AIOPictureView
= (void*)0
  [105]AIOPictureView
com.tencent.mobileqq.activity.aio.photo.AIOPictureView
= (void*)0
  [106]TextItemBuilder
com.tencent.mobileqq.activity.aio.item.TextItemBuilder
= Lio/github/qauxv/util/DexKit$NoSuchClass;->a()V
  [107]TextMsgItem
com.tencent.mobileqq.aio.msg.TextMsgItem
= Lcom/tencent/mobileqq/aio/msg/af;->Y1()Ljava/lang/CharSequence;
  [40001]ReplyNoAtHook
com/tencent/mobileqq/activity/aio/rebuild/input/d
  [40002]ChatWordsCount
nyn
  [40003]SortAtPanel.sessionInfoTroopUin
f
  [40004]RemovePlayTogether.ClockInEntryHelper
n
  [40005]QQMessageFacade
B2
  [40006]SimplifyQQSettingMe::MidContentName
e0
  [40007]RemovePlayTogether.TogetherControlHelper
q

**Comment by klxiaoniu** [comment]
能确定是防撤回导致的？

**Comment by ARKSAVE** [comment]
> 能确定是防撤回导致的？

应该是的，因为我没开其他和聊天记录有关的功能
现在如果在某个好友的查找聊天记录里搜索关键字，会查找出所有好友关于该关键字的聊天记录

**Comment by klxiaoniu** [comment]
> > 能确定是防撤回导致的？
> 
> 应该是的，因为我没开其他和聊天记录有关的功能 现在如果在某个好友的查找聊天记录里搜索关键字，会查找出所有好友关于该关键字的聊天记录

QQ自己有时候也会这样呢 你这个情况根本无法推定是我们的问题

**Comment by ARKSAVE** [comment]
> > > 能确定是防撤回导致的？
> > 
> > 
> > 应该是的，因为我没开其他和聊天记录有关的功能 现在如果在某个好友的查找聊天记录里搜索关键字，会查找出所有好友关于该关键字的聊天记录
> 
> QQ自己有时候也会这样呢 你这个情况根本无法推定是我们的问题

是这样吗，打扰了
