### ISSUE TITLE
[Bug] 侧滑栏异常，屏蔽主界面相机/小世界图标错误

### ISSUE THREAD

**Issue by SolitaryEgo** [cinit/QAuxiliary#938]
### Steps to reproduce/复现步骤

打开就这样了

### Expected behaviour/预期行为

.

### Actual behaviour/实际行为

![Screenshot_2024-04-29-05-50-37-897_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/115763944/108b45ed-5b87-49b6-9b69-60f3d6bdd8da)
![Screenshot_2024-04-29-05-51-10-319_com tencent mobileqq](https://github.com/cinit/QAuxiliary/assets/115763944/29e31c59-ee5e-4111-8a98-fe60b39b37d7)
侧滑栏就这3个没勾选，其他全勾了

### Xposed Framework you used/你使用的Xposed框架

1.9.2(7058)

### Your Android version/你使用的安卓系统版本

14

### QQ(TIM)版本/QQ(TIM) Version

qq9.0.30

### Module Version/模块版本

1.5.0.r2001.597cbf1(2001)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

[SimplifyQQSettingMe-1714341030461.txt](https://github.com/cinit/QAuxiliary/files/15143998/SimplifyQQSettingMe-1714341030461.txt)
[RemoveCameraButton-1714341016165.txt](https://github.com/cinit/QAuxiliary/files/15143996/RemoveCameraButton-1714341016165.txt)

**Comment by klxiaoniu** [comment]
9.0.30了还用这个，用屏蔽超级QQ秀啊

**Comment by HdShare** [comment]
尝试最新Ci版
