### ISSUE TITLE
[Bug] 以图片方式打开闪照异常

### ISSUE THREAD

**Issue by LionYu66** [cinit/QAuxiliary#94]
### Steps to reproduce/复现步骤

打开功能
进入大于100人的人数较多的群
点击别人发送的闪照

### Expected behaviour/预期行为

正常快速加载并显示图片

### Actual behaviour/实际行为

卡在0%加载很久，加载时长明显大于关闭此功能时的加载速度

### XPosed Framework you used/你使用的XP框架

lsposed

### QQ(TIM)版本/QQ(TIM) Version

QQ 8.8.93(8120)

### Module Version/模块版本

1.2.6.r664.b2b511e(664)

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2022-06-15T10_20_04.454.zip](https://github.com/cinit/QAuxiliary/files/8905151/LSPosed_2022-06-15T10_20_04.454.zip)

**Comment by keta1** [comment]
目前 群聊已经无法发送闪照，无法进行测试
