### ISSUE TITLE
[功能请求] 恢复相册预览功能

### ISSUE THREAD

**Issue by jimranora** [cinit/QAuxiliary#941]
### QQ(TIM)版本/QQ(TIM) Version

V9.0.35.16270

### 为什么你认为需要此功能

新版手机QQ点击相册会向上弹出整个屏幕的缩略图预览，然而给“我的电脑”发送图片的时候，依然是半个屏幕的预览。使用下来还是感觉半个屏幕的用上去更加舒服。

### 具体功能需要/Specific features require

希望能将私聊和群聊的相册，更改为给“我的电脑”发送图片时的预览界面。

感谢。

**Comment by duzhaokun123** [comment]
这和 聊天和消息 -> 还原图片选择面板 的区别是什么

**Comment by jimranora** [comment]
你好，我安装的是armALL的1.5.0，再三检查后，并没有在聊天和消息下面找到还原图片选择面板。请问我是需要更新什么测试版吗？

**Comment by duzhaokun123** [comment]
> 请问我是需要更新什么测试版吗？

需要
