### ISSUE TITLE
[功能请求] 发送Markdown消息

### ISSUE THREAD

**Issue by Touch-Night** [cinit/QAuxiliary#944]
### QQ(TIM)版本/QQ(TIM) Version

9.0.50.16545

### 为什么你认为需要此功能

QQ官方支持Markdown消息的渲染，但是只有官方机器人能够发送会被渲染的Markdown消息。虽说如此，但我也见过第三方机器人发送Markdown消息，而且Markdown消息可以被原样转发，因此实现个人发送Markdown消息应该不是不可能。

### 具体功能需要/Specific features require

发送Markdown消息

**Comment by zhongwen-4** [comment]
第三方是用tx的漏洞发的，但是tx前几天修复了第三方机器人发送makdwon这个bug

**Comment by Touch-Night** [comment]
哦那没事了

**Comment by EmberQR** [comment]
我看还一直有新的markdown消息出来啊，应该还有方法吧

**Comment by LegendEast** [comment]
腾讯马上就要给他和谐了
