### ISSUE TITLE
[功能请求]解除转发消息最多只能选择9个对象限制

### ISSUE THREAD

**Issue by DoraemonPlusPro** [cinit/QAuxiliary#948]
### QQ(TIM)版本/QQ(TIM) Version

QQ全版本

### 为什么你认为需要此功能

因为有时候需要一次性转发多个联系人或群，所以需要这个功能

### 具体功能需要/Specific features require

解除转发消息最多只能选择9个对象限制

**Comment by HdShare** [comment]
Lcom/tencent/mobileqq/activity/ForwardRecentActivity;->add2ForwardTargetList(Lcom/tencent/mobileqq/selectmember/ResultRecord;)Z

private static final int MAX_SELECTED_NUM = 9;

**Comment by HdShare** [comment]
尝试最新CI版本
