### ISSUE TITLE
[Bug] 移除群聊界面右滑群应用在某些情况下不完全生效

### ISSUE THREAD

**Issue by ArkhalisDragon** [cinit/QAuxiliary#953]
### Steps to reproduce/复现步骤

1.某些QQ群右上角没有群帖子按钮而只有一个三条横线的“更多”按钮
2.在这些QQ群右滑

### Expected behaviour/预期行为

无反应

### Actual behaviour/实际行为

进入黑屏界面

### Xposed Framework you used/你使用的Xposed框架

LSPosed 1.9.2 (7024)

### Your Android version/你使用的安卓系统版本

Android 13,MIUI 14.0.26

### QQ(TIM)版本/QQ(TIM) Version

8.9.80

### Module Version/模块版本

1.5.0.r2036.6696e01

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

故障排查界面提示“无明显异常”，几个判断键值均为true

**Comment by HdShare** [comment]
试试 最新ci版的 净化设置-聊天界面-其他-屏蔽聊天右滑，功能应该差不多

**Comment by ArkhalisDragon** [comment]
> 试试 最新ci版的 净化设置-聊天界面-其他-屏蔽聊天右滑，功能应该差不多

在8.9.80版本上显示“不支持的功能”，但是仍然有效，可以配合移除群帖子使用，感谢
