### ISSUE TITLE
[功能请求] 本地表情面板相关建议与功能请求

### ISSUE THREAD

**Issue by zhouxinghua001** [cinit/QAuxiliary#956]
### QQ(TIM)版本/QQ(TIM) Version

9.0.50

### 为什么你认为需要此功能

1. 目前模块的本地表情面板发送是使用图片发送，导致表情比在收藏/表情集中发送的表情大许多，令人感觉有点奇怪
2. 是否可以实现将本地表情hook到表情包列表之后，以实现更加无感化的操作体验
3. 目前本地表情的导入实现逻辑为扫描当前文件夹下的图片文件，但是不扫描子目录，可否循环扫描子目录的表情并且按照目录名称添加至本地表情面板
4. 本地表情面板的保存目录名是本地表情包，看着怪怪的，修改为英文是否更加合适
5. 本地表情面板在导入gif文件时无法正常导入，是否不支持动态表情

### 联系到哪些已经存在的bug或者功能

本地表情面板

### 具体功能需要/Specific features require

1. 使用[动画表情]标签发送本地表情
2. 将本地表情hook到QQ自带的表情包列表
3. 批量添加多级目录下的本地表情
4. 修改本地表情存放路径名称
5. 添加对动态表情的支持

**Comment by zhouxinghua001** [comment]
再添加一条发现的不知道算不算bug的：
本地表情面板无法添加动态表情gif图

**Comment by Hicores** [comment]
1.表情面板都是直接发送原图,具体显示方式我不清楚
2.太麻烦,而且效果不好,你喜欢的话可以提交pr
3.这个可以做,不过最近没空
4.历史遗留,直接改了会影响大多用户
5.不清楚,识别图片用的Android的Bitmap相关方法,确认图片有效后直接复制的

**Comment by zhouxinghua001** [comment]
好的谢谢您，等我再研究一下自己实现一下吧🏄‍♂️
