### ISSUE TITLE
[Bug] 复读功能文字无法复读，会导致qq闪退，图片正常

### ISSUE THREAD

**Issue by QuincyOvO** [cinit/QAuxiliary#987]
### Steps to reproduce/复现步骤

点击文字消息旁边的消息+1plus的+1按钮，qq过1-2秒会出现闪退情况，复读图片正常。

### Expected behaviour/预期行为

复读文字消息

### Actual behaviour/实际行为

过1-2秒后qq闪退

### Xposed Framework you used/你使用的Xposed框架

LPSosed 1.9.2（7024）-Zygisk

### Your Android version/你使用的安卓系统版本

安卓12

### QQ(TIM)版本/QQ(TIM) Version

V9.0.30.15945

### Module Version/模块版本

1.5.0.r2071.bff8012(2071)

### Version and Other Requirements/版本和其他要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
- [X] I have checked recent Issues (including Open and Closed) and have not found this Issue/我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue
- [X] The QQ I am using is an official release version, not a modified or beta version/我使用的 QQ 是官方发布的正式版本，而非修改版或测试版

### Logs/日志

1.5.0.r2071.bff8012
QQ9.0.30(6016)
PID: 31415, UID: 10025
cc.hicore.hook.RepeaterPlus
isInitialized: true
isInitializationSuccessful: true
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 0

**Comment by QuincyOvO** [comment]
复读图片消息正常，文字消息无反应，过1-2秒后qq闪退。以前某个qq9.0后的版本文字也正常，更新后就不行了。功能异常列表无异常，各项启用的功能均显示正常。

**Comment by HdShare** [comment]
尝试最新CI版本

**Comment by QuincyOvO** [comment]
1.5.1 r2096 问题依旧

**Comment by Hicores** [comment]
尝试最新ci版本

**Comment by QuincyOvO** [comment]
> 尝试最新ci版本

r2186问题已解决，正常复读文字消息不闪退，谢谢，辛苦了

**Comment by QuincyOvO** [comment]
昨日更新最新版插件版本：1.5.4.r2485.087cf54
QQ版本不变：V9.0.30.15945
bug复现，双击文字的+1QQ闪退

**Comment by HdShare** [comment]
> bug复现，双击文字的+1QQ闪退

lsposed闪退日志
