### ISSUE TITLE
[Bug] 强制使用默认字体无效

### ISSUE THREAD

**Issue by Moisss** [cinit/QAuxiliary#99]
### Steps to reproduce/复现步骤

打开功能
进入任意聊天界面
查看任意文字消息

### Expected behaviour/预期行为

所有字体均为默认字体

### Actual behaviour/实际行为

所有字体均为个人设置的个性字体

### XPosed Framework you used/你使用的XP框架

应用转生6.6.0

### QQ(TIM)版本/QQ(TIM) Version

QQ 8.7.0.5295

### Module Version/模块版本

1.2.7.r681.d1acc68(681)

### Version requirement/版本要求

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[BugXposed_error_20220624_210358.log](https://github.com/cinit/QAuxiliary/files/8976382/BugXposed_error_20220624_210358.log)

**Comment by teble** [comment]
最新ci已经适配
